import { randomUUID } from 'node:crypto';
import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { OrganizationScopeService } from '../../common/tenant/organization-scope.service';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class CertificationService {
 constructor(private readonly prisma:PrismaService,private readonly ctx:TenantContext,private readonly organizationScope:OrganizationScopeService){}
 private scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId)throw new BadRequestException('Tenant context is required.');if(!companyId)throw new BadRequestException('Company context is required.');return{tenantId,companyId}}
 private async branchIds(){const s=await this.organizationScope.getBranchScopedWhere();if('branchId'in s)return typeof s.branchId==='string'?[s.branchId]:s.branchId.in;return null}
 private text(v:unknown,name:string){const x=String(v??'').trim();if(!x)throw new BadRequestException(`${name} is required.`);return x}
 private day(v:unknown,name:string){if(v===undefined||v===null||v==='')return null;const d=new Date(String(v));if(Number.isNaN(d.getTime()))throw new BadRequestException(`${name} must be a valid date.`);return d.toISOString().slice(0,10)}
 private async staff(staffId:string){const{tenantId,companyId}=this.scope(),branchIds=await this.branchIds();const row=await this.prisma.staff.findFirst({where:{id:staffId,tenantId,branch:{companyId},...(branchIds===null?{}:{branchId:{in:branchIds}})},select:{id:true,branchId:true}});if(!row)throw new NotFoundException('Staff not found');return row}
 async types(activeOnly=true){const{tenantId,companyId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,code,name,description,category,requires_expiry AS "requiresExpiry",default_validity_months AS "defaultValidityMonths",warning_days AS "warningDays",service_eligibility_required AS "serviceEligibilityRequired",active FROM hr_certification_types WHERE tenant_id=$1 AND company_id=$2 AND ($3::boolean=FALSE OR active=TRUE) ORDER BY name`,tenantId,companyId,activeOnly)}
 async createType(b:any){const{tenantId,companyId}=this.scope(),code=this.text(b.code,'code').toUpperCase(),name=this.text(b.name,'name'),warning=Math.max(0,Math.min(3650,Math.trunc(Number(b.warningDays??30))));const months=b.defaultValidityMonths==null?null:Math.trunc(Number(b.defaultValidityMonths));if(months!==null&&(!Number.isFinite(months)||months<=0))throw new BadRequestException('defaultValidityMonths must be positive.');try{return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_certification_types(id,tenant_id,company_id,code,name,description,category,requires_expiry,default_validity_months,warning_days,service_eligibility_required) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,code,name,description,category,requires_expiry AS "requiresExpiry",default_validity_months AS "defaultValidityMonths",warning_days AS "warningDays",service_eligibility_required AS "serviceEligibilityRequired",active`,randomUUID(),tenantId,companyId,code,name,String(b.description??'').trim()||null,String(b.category??'').trim()||null,b.requiresExpiry!==false,months,warning,b.serviceEligibilityRequired===true))[0]}catch(e:any){if(e?.code==='23505')throw new ConflictException('Certification type code already exists.');throw e}}
 async list(staffId:string){const{tenantId,companyId}=this.scope();await this.staff(staffId);return this.prisma.$queryRawUnsafe<any[]>(`SELECT c.id,c.certification_type_id AS "certificationTypeId",t.code,t.name,t.category,c.credential_number AS "credentialNumber",c.issuing_organization AS "issuingOrganization",c.qualification,c.issued_at::text AS "issuedAt",c.expires_at::text AS "expiresAt",CASE WHEN c.status='VERIFIED' AND c.expires_at<CURRENT_DATE THEN 'EXPIRED' ELSE c.status END AS status,c.evidence_document_id AS "evidenceDocumentId",c.verified_at AS "verifiedAt",c.verified_by AS "verifiedBy",c.verification_note AS "verificationNote",c.notes,t.warning_days AS "warningDays",t.service_eligibility_required AS "serviceEligibilityRequired" FROM hr_employee_certifications c JOIN hr_certification_types t ON t.id=c.certification_type_id AND t.tenant_id=c.tenant_id AND t.company_id=c.company_id WHERE c.tenant_id=$1 AND c.company_id=$2 AND c.staff_id=$3 ORDER BY COALESCE(c.expires_at,'9999-12-31'::date),t.name`,tenantId,companyId,staffId)}
 async create(staffId:string,b:any,actor:string){const{tenantId,companyId}=this.scope(),staff=await this.staff(staffId),typeId=this.text(b.certificationTypeId,'certificationTypeId'),issued=this.day(b.issuedAt,'issuedAt'),expires=this.day(b.expiresAt,'expiresAt');if(issued&&expires&&expires<issued)throw new BadRequestException('expiresAt cannot precede issuedAt.');const types=await this.prisma.$queryRawUnsafe<Array<{requiresExpiry:boolean}>>(`SELECT requires_expiry AS "requiresExpiry" FROM hr_certification_types WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND active=TRUE`,typeId,tenantId,companyId);if(!types.length)throw new NotFoundException('Certification type not found');if(types[0].requiresExpiry&&!expires)throw new BadRequestException('expiresAt is required for this certification type.');try{return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_employee_certifications(id,tenant_id,company_id,branch_id,staff_id,certification_type_id,credential_number,issuing_organization,qualification,issued_at,expires_at,evidence_document_id,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::date,$11::date,$12,$13,$14) RETURNING id,status`,randomUUID(),tenantId,companyId,staff.branchId,staffId,typeId,String(b.credentialNumber??'').trim()||null,String(b.issuingOrganization??'').trim()||null,String(b.qualification??'').trim()||null,issued,expires,String(b.evidenceDocumentId??'').trim()||null,String(b.notes??'').trim()||null,actor))[0]}catch(e:any){if(e?.code==='23505')throw new ConflictException('Credential number already exists.');throw e}}
 async verify(staffId:string,id:string,b:any,actor:string){const{tenantId,companyId}=this.scope();await this.staff(staffId);const status=String(b.status??'VERIFIED').toUpperCase();if(!['VERIFIED','REJECTED'].includes(status))throw new BadRequestException('Status must be VERIFIED or REJECTED.');if(status==='REJECTED'&&!String(b.note??'').trim())throw new BadRequestException('A verification note is required when rejecting a certification.');return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<Array<{id:string;status:string;expiresAt:string|null}>>(`SELECT id,status,expires_at::text AS "expiresAt" FROM hr_employee_certifications WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND staff_id=$4 FOR UPDATE`,id,tenantId,companyId,staffId),row=rows[0];if(!row)throw new NotFoundException('Certification not found');if(row.status!=='PENDING')throw new ConflictException('Only pending certifications can be verified or rejected.');if(status==='VERIFIED'&&row.expiresAt&&row.expiresAt<new Date().toISOString().slice(0,10))throw new ConflictException('An expired certification cannot be verified.');return(await tx.$queryRawUnsafe<any[]>(`UPDATE hr_employee_certifications SET status=$1,verified_at=CURRENT_TIMESTAMP,verified_by=$2,verification_note=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$4 AND tenant_id=$5 AND company_id=$6 AND staff_id=$7 AND status='PENDING' RETURNING id,status,verified_at AS "verifiedAt",verified_by AS "verifiedBy",verification_note AS "verificationNote"`,status,actor,String(b.note??'').trim()||null,id,tenantId,companyId,staffId))[0]})}
 async revoke(staffId:string,id:string,note:string,actor:string){const{tenantId,companyId}=this.scope();await this.staff(staffId);const reason=this.text(note,'note');const rows=await this.prisma.$queryRawUnsafe<any[]>(`UPDATE hr_employee_certifications SET status='REVOKED',verification_note=$1,verified_at=CURRENT_TIMESTAMP,verified_by=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$3 AND tenant_id=$4 AND company_id=$5 AND staff_id=$6 AND status='VERIFIED' RETURNING id,status,verification_note AS "verificationNote"`,reason,actor,id,tenantId,companyId,staffId);if(!rows.length)throw new ConflictException('Only verified certifications can be revoked.');return rows[0]}
 async expiring(days=30){const{tenantId,companyId}=this.scope(),branchIds=await this.branchIds(),window=Math.max(1,Math.min(365,Math.trunc(Number(days)||30)));return this.prisma.$queryRawUnsafe<any[]>(`SELECT c.id,c.staff_id AS "staffId",s."firstName",s."lastName",t.name,t.code,c.credential_number AS "credentialNumber",c.expires_at::text AS "expiresAt",(c.expires_at-CURRENT_DATE) AS "daysRemaining" FROM hr_employee_certifications c JOIN hr_certification_types t ON t.id=c.certification_type_id JOIN staff s ON s.id=c.staff_id AND s.tenant_id=c.tenant_id WHERE c.tenant_id=$1 AND c.company_id=$2 AND ($3::text[] IS NULL OR c.branch_id=ANY($3::text[])) AND c.status='VERIFIED' AND c.expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+$4::integer ORDER BY c.expires_at`,tenantId,companyId,branchIds,window)}
 async serviceEligibility(staffId:string,serviceId:string){const{tenantId,companyId}=this.scope();await this.staff(staffId);const rows=await this.prisma.$queryRawUnsafe<Array<{certificationTypeId:string;name:string;certificationId:string|null;expiresAt:string|null}>>(`SELECT r.certification_type_id AS "certificationTypeId",t.name,c.id AS "certificationId",c.expires_at::text AS "expiresAt" FROM hr_certification_service_eligibility r JOIN hr_certification_types t ON t.id=r.certification_type_id LEFT JOIN LATERAL (SELECT x.id,x.expires_at FROM hr_employee_certifications x WHERE x.tenant_id=r.tenant_id AND x.company_id=r.company_id AND x.staff_id=$3 AND x.certification_type_id=r.certification_type_id AND x.status='VERIFIED' AND (x.expires_at IS NULL OR x.expires_at>=CURRENT_DATE) ORDER BY x.expires_at DESC NULLS FIRST LIMIT 1)c ON TRUE WHERE r.tenant_id=$1 AND r.company_id=$2 AND r.service_id=$4 AND r.required=TRUE`,tenantId,companyId,staffId,serviceId);const missing=rows.filter(x=>!x.certificationId);return{eligible:missing.length===0,requirements:rows,missing}}
}
