import { randomUUID } from 'node:crypto';
import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { OrganizationScopeService } from '../../common/tenant/organization-scope.service';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class CompetencyService {
 constructor(private readonly prisma:PrismaService,private readonly ctx:TenantContext,private readonly organizationScope:OrganizationScopeService){}
 private scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId)throw new BadRequestException('Tenant context is required.');if(!companyId)throw new BadRequestException('Company context is required.');return{tenantId,companyId}}
 private async branches(){const scope=await this.organizationScope.getBranchScopedWhere();if('branchId'in scope)return typeof scope.branchId==='string'?[scope.branchId]:scope.branchId.in;return null}
 private text(v:unknown,name:string){const value=String(v??'').trim();if(!value)throw new BadRequestException(`${name} is required.`);return value}
 private level(v:unknown,name:string,min=1,max=10){const n=Math.trunc(Number(v));if(!Number.isFinite(n)||n<min||n>max)throw new BadRequestException(`${name} must be between ${min} and ${max}.`);return n}
 private async staff(staffId:string){const{tenantId,companyId}=this.scope(),branchIds=await this.branches();const row=await this.prisma.staff.findFirst({where:{id:staffId,tenantId,branch:{companyId},...(branchIds===null?{}:{branchId:{in:branchIds}})},select:{id:true,branchId:true}});if(!row)throw new NotFoundException('Staff not found');return row}
 private async position(positionId:string){const{tenantId,companyId}=this.scope(),branchIds=await this.branches();const rows=await this.prisma.$queryRawUnsafe<Array<{id:string;name:string}>>(`SELECT DISTINCT p.id,p.name FROM hr_positions p LEFT JOIN hr_employee_assignments ea ON ea.position_id=p.id AND ea.tenant_id=p.tenant_id AND ea.company_id=p.company_id AND ea.effective_from<=CURRENT_DATE AND (ea.effective_to IS NULL OR ea.effective_to>=CURRENT_DATE) WHERE p.id=$1 AND p.tenant_id=$2 AND p.company_id=$3 AND ($4::text[] IS NULL OR ea.branch_id=ANY($4::text[])) LIMIT 1`,positionId,tenantId,companyId,branchIds);if(!rows.length)throw new NotFoundException('Position not found in organization scope');return rows[0]}
 async catalog(){const{tenantId,companyId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,code,name,description,category,max_level AS "maxLevel",active FROM hr_competencies WHERE tenant_id=$1 AND company_id=$2 ORDER BY active DESC,category NULLS LAST,name`,tenantId,companyId)}
 async createCompetency(body:any,actor:string){const{tenantId,companyId}=this.scope(),code=this.text(body.code,'code').toUpperCase(),name=this.text(body.name,'name'),maxLevel=this.level(body.maxLevel??5,'maxLevel');try{return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_competencies(id,tenant_id,company_id,code,name,description,category,max_level,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,code,name,description,category,max_level AS "maxLevel",active`,randomUUID(),tenantId,companyId,code,name,String(body.description??'').trim()||null,String(body.category??'').trim()||null,maxLevel,actor))[0]}catch(e:any){if(e?.code==='23505')throw new ConflictException('Competency code already exists.');throw e}}
 async positionRequirements(positionId:string){const{tenantId,companyId}=this.scope(),position=await this.position(positionId);const requirements=await this.prisma.$queryRawUnsafe<any[]>(`SELECT r.id,r.competency_id AS "competencyId",c.code,c.name,c.category,r.required_level AS "requiredLevel",r.mandatory,r.weight::text AS weight FROM hr_position_competency_requirements r JOIN hr_competencies c ON c.id=r.competency_id AND c.tenant_id=r.tenant_id AND c.company_id=r.company_id WHERE r.tenant_id=$1 AND r.company_id=$2 AND r.position_id=$3 ORDER BY r.mandatory DESC,c.name`,tenantId,companyId,positionId);return{position,requirements}}
 async setPositionRequirement(positionId:string,body:any){const{tenantId,companyId}=this.scope(),competencyId=this.text(body.competencyId,'competencyId'),requiredLevel=this.level(body.requiredLevel,'requiredLevel'),weight=Number(body.weight??1);if(!Number.isFinite(weight)||weight<=0)throw new BadRequestException('weight must be positive.');await this.position(positionId);const competency=await this.prisma.$queryRawUnsafe<Array<{maxLevel:number}>>(`SELECT max_level AS "maxLevel" FROM hr_competencies WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND active=TRUE`,competencyId,tenantId,companyId);if(!competency.length)throw new NotFoundException('Competency not found');if(requiredLevel>competency[0].maxLevel)throw new BadRequestException('requiredLevel exceeds competency maximum level.');return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_position_competency_requirements(id,tenant_id,company_id,position_id,competency_id,required_level,mandatory,weight) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (tenant_id,company_id,position_id,competency_id) DO UPDATE SET required_level=EXCLUDED.required_level,mandatory=EXCLUDED.mandatory,weight=EXCLUDED.weight,updated_at=CURRENT_TIMESTAMP RETURNING id,competency_id AS "competencyId",required_level AS "requiredLevel",mandatory,weight::text AS weight`,randomUUID(),tenantId,companyId,positionId,competencyId,requiredLevel,body.mandatory!==false,weight))[0]}
 async assess(staffId:string,body:any,actor:string){const{tenantId,companyId}=this.scope(),staff=await this.staff(staffId),competencyId=this.text(body.competencyId,'competencyId'),assessmentType=String(body.assessmentType??'MANAGER').toUpperCase();if(!['SELF','MANAGER','PEER','SYSTEM','CERTIFICATION'].includes(assessmentType))throw new BadRequestException('Invalid assessmentType.');const competency=await this.prisma.$queryRawUnsafe<Array<{maxLevel:number}>>(`SELECT max_level AS "maxLevel" FROM hr_competencies WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND active=TRUE`,competencyId,tenantId,companyId);if(!competency.length)throw new NotFoundException('Competency not found');const level=this.level(body.level,'level',0,competency[0].maxLevel),assessedAt=body.assessedAt?new Date(String(body.assessedAt)):new Date();if(Number.isNaN(assessedAt.getTime()))throw new BadRequestException('assessedAt must be a valid date.');return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_employee_competency_assessments(id,tenant_id,company_id,branch_id,staff_id,competency_id,level,assessment_type,assessed_at,assessed_by,evidence,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::date,$10,$11,$12) RETURNING id,competency_id AS "competencyId",level,assessment_type AS "assessmentType",assessed_at::text AS "assessedAt"`,randomUUID(),tenantId,companyId,staff.branchId,staffId,competencyId,level,assessmentType,assessedAt.toISOString().slice(0,10),actor,String(body.evidence??'').trim()||null,String(body.notes??'').trim()||null))[0]}
 async employeeMatrix(staffId:string){const{tenantId,companyId}=this.scope(),staff=await this.staff(staffId);const rows=await this.prisma.$queryRawUnsafe<any[]>(`WITH assignment AS (SELECT position_id FROM hr_employee_assignments WHERE tenant_id=$1 AND company_id=$2 AND staff_id=$3 AND branch_id=$4 AND effective_from<=CURRENT_DATE AND (effective_to IS NULL OR effective_to>=CURRENT_DATE) ORDER BY effective_from DESC LIMIT 1), latest AS (SELECT DISTINCT ON (a.competency_id) a.competency_id,a.level,a.assessment_type,a.assessed_at FROM hr_employee_competency_assessments a WHERE a.tenant_id=$1 AND a.company_id=$2 AND a.staff_id=$3 AND a.branch_id=$4 ORDER BY a.competency_id,a.assessed_at DESC,a.created_at DESC) SELECT r.competency_id AS "competencyId",c.code,c.name,c.category,r.required_level AS "requiredLevel",r.mandatory,r.weight::text AS weight,COALESCE(l.level,0) AS "currentLevel",l.assessment_type AS "assessmentType",l.assessed_at::text AS "assessedAt",GREATEST(r.required_level-COALESCE(l.level,0),0) AS gap FROM assignment x JOIN hr_position_competency_requirements r ON r.position_id=x.position_id AND r.tenant_id=$1 AND r.company_id=$2 JOIN hr_competencies c ON c.id=r.competency_id LEFT JOIN latest l ON l.competency_id=r.competency_id ORDER BY gap DESC,r.mandatory DESC,c.name`,tenantId,companyId,staffId,staff.branchId);const weightedRequired=rows.reduce((s,r)=>s+Number(r.requiredLevel)*Number(r.weight),0),weightedCurrent=rows.reduce((s,r)=>s+Math.min(Number(r.currentLevel),Number(r.requiredLevel))*Number(r.weight),0),score=weightedRequired?Math.round(weightedCurrent/weightedRequired*100):100;return{staffId,score,compliant:rows.every(r=>!r.mandatory||Number(r.gap)===0),gaps:rows.filter(r=>Number(r.gap)>0),requirements:rows}}
 async createDevelopmentAction(staffId:string,body:any,actor:string){const{tenantId,companyId}=this.scope(),staff=await this.staff(staffId),competencyId=this.text(body.competencyId,'competencyId'),title=this.text(body.title,'title'),targetLevel=this.level(body.targetLevel,'targetLevel'),actionType=String(body.actionType??'TRAINING').toUpperCase(),source=String(body.source??'SKILL_GAP').toUpperCase();if(!['TRAINING','COACHING','MENTORING','PRACTICE','CERTIFICATION','OTHER'].includes(actionType))throw new BadRequestException('Invalid actionType.');if(!['MANUAL','SKILL_GAP','PERFORMANCE','CERTIFICATION'].includes(source))throw new BadRequestException('Invalid source.');const competency=await this.prisma.$queryRawUnsafe<Array<{maxLevel:number}>>(`SELECT max_level AS "maxLevel" FROM hr_competencies WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND active=TRUE`,competencyId,tenantId,companyId);if(!competency.length)throw new NotFoundException('Competency not found');if(targetLevel>competency[0].maxLevel)throw new BadRequestException('targetLevel exceeds competency maximum level.');const due=body.dueDate?new Date(String(body.dueDate)):null;if(due&&Number.isNaN(due.getTime()))throw new BadRequestException('dueDate must be a valid date.');return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_competency_development_actions(id,tenant_id,company_id,branch_id,staff_id,competency_id,target_level,action_type,title,due_date,source,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::date,$11,$12,$13) RETURNING id,competency_id AS "competencyId",target_level AS "targetLevel",action_type AS "actionType",title,due_date::text AS "dueDate",status,source`,randomUUID(),tenantId,companyId,staff.branchId,staffId,competencyId,targetLevel,actionType,title,due?due.toISOString().slice(0,10):null,source,String(body.notes??'').trim()||null,actor))[0]}
}
