import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';
import { randomUUID } from 'node:crypto';

const EVENTS=new Set(['HIRED','EMPLOYMENT_TYPE_CHANGE','SALARY_CHANGE','COST_CENTER_CHANGE','SUSPENDED','REACTIVATED','TERMINATED','OTHER']);
@Injectable()
export class EmploymentHistoryService{
 constructor(private readonly prisma:PrismaService,private readonly tenantContext:TenantContext){}
 private scope(){const tenantId=this.tenantContext.getTenantId(),branchId=this.tenantContext.getBranchId(),roleScope=this.tenantContext.getRoleScope();if(!tenantId)throw new BadRequestException('Tenant context is required.');if(roleScope!=='CENTRAL'&&!branchId)throw new BadRequestException('A branch must be selected for this operation.');return{tenantId,branchId};}
 private date(v:unknown){const d=v?new Date(String(v)):new Date();if(Number.isNaN(d.getTime()))throw new BadRequestException('effectiveFrom must be a valid date.');return d.toISOString().slice(0,10)}
 async list(staffId:string){const{tenantId,branchId}=this.scope();await this.staff(staffId);return this.prisma.$queryRawUnsafe<any[]>(`SELECT h.*,b.name AS "branchName" FROM hr_employment_history h JOIN branches b ON b.id=h.branch_id WHERE h.tenant_id=$1 AND h.staff_id=$2${branchId?' AND h.branch_id=$3':''} ORDER BY h.effective_from DESC,h.created_at DESC`,...(branchId?[tenantId,staffId,branchId]:[tenantId,staffId]));}
 private async staff(id:string){const{tenantId,branchId}=this.scope();const s=await this.prisma.staff.findFirst({where:{id,tenantId,...(branchId?{branchId}:{})},select:{id:true,branchId:true,status:true,branch:{select:{companyId:true}}}});if(!s)throw new NotFoundException('Staff not found');return s;}
 async record(staffId:string,b:any,createdBy?:string){const{tenantId}=this.scope(),staff=await this.staff(staffId),event=String(b.eventType??'OTHER').toUpperCase();if(!EVENTS.has(event))throw new BadRequestException('Unsupported employment history event.');const effective=this.date(b.effectiveFrom),targetBranchId=String(b.branchId??staff.branchId);const branch=await this.prisma.branch.findFirst({where:{id:targetBranchId,company:{tenantId}},select:{id:true,companyId:true}});if(!branch)throw new BadRequestException('Branch is not available in this tenant.');const salary=b.grossSalary===undefined||b.grossSalary===null?null:Number(b.grossSalary);if(salary!==null&&(!Number.isFinite(salary)||salary<0))throw new BadRequestException('grossSalary must be a non-negative number.');
 return this.prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`UPDATE hr_employment_history SET effective_to=($1::date-INTERVAL '1 day')::date,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$2 AND staff_id=$3 AND effective_to IS NULL AND effective_from < $1::date`,effective,tenantId,staffId);await tx.$executeRawUnsafe(`DELETE FROM hr_employment_history WHERE tenant_id=$1 AND staff_id=$2 AND effective_to IS NULL AND effective_from >= $3::date`,tenantId,staffId,effective);const rows=await tx.$queryRawUnsafe<any[]>(`INSERT INTO hr_employment_history(id,tenant_id,company_id,branch_id,staff_id,event_type,effective_from,employment_type,gross_salary,salary_type,cost_center_id,reason,metadata,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::date,$8,$9,$10,$11,$12,$13::jsonb,$14) RETURNING *`,randomUUID(),tenantId,branch.companyId,targetBranchId,staffId,event,effective,b.employmentType??null,salary,b.salaryType??null,b.costCenterId??null,b.reason??null,JSON.stringify(b.metadata??{}),createdBy??null);
 if(event==='TERMINATED'){await tx.staff.update({where:{id:staffId},data:{status:'INACTIVE'}});await tx.$executeRawUnsafe(`UPDATE employee_master_records SET termination_date=$1::date,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$2 AND staff_id=$3`,effective,tenantId,staffId);}else if(event==='REACTIVATED'){await tx.staff.update({where:{id:staffId},data:{status:'ACTIVE'}});await tx.$executeRawUnsafe(`UPDATE employee_master_records SET termination_date=NULL,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$1 AND staff_id=$2`,tenantId,staffId);}if(b.employmentType!==undefined||salary!==null||b.salaryType!==undefined){await tx.$executeRawUnsafe(`UPDATE employee_master_records SET employment_type=COALESCE($1,employment_type),gross_salary=COALESCE($2,gross_salary),salary_type=COALESCE($3,salary_type),updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$4 AND staff_id=$5`,b.employmentType??null,salary,b.salaryType??null,tenantId,staffId);}return rows[0];});}
}
