import{randomUUID}from'node:crypto';import{BadRequestException,ConflictException,Injectable,NotFoundException}from'@nestjs/common';import{PrismaService}from'@beauty-erp/database';import{TenantContext}from'../../common/tenant/tenant-context';
@Injectable()export class HrOperationsControlService{constructor(private readonly prisma:PrismaService,private readonly ctx:TenantContext){}private scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId||!companyId)throw new BadRequestException('Tenant and company context are required.');return{tenantId,companyId}}
async assets(staffId?:string){const{tenantId,companyId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT a.id,a.asset_type AS "assetType",a.name,a.asset_tag AS "assetTag",a.serial_number AS "serialNumber",a.status,x.staff_id AS "staffId",x.assigned_at AS "assignedAt",x.acknowledged_at AS "acknowledgedAt",x.returned_at AS "returnedAt" FROM hr_assets a LEFT JOIN hr_asset_assignments x ON x.asset_id=a.id AND x.returned_at IS NULL WHERE a.tenant_id=$1 AND a.company_id=$2 AND($3::text IS NULL OR x.staff_id=$3) ORDER BY a.name`,tenantId,companyId,staffId??null)}
async createAsset(b:any){const{tenantId,companyId}=this.scope();if(!b.assetType||!b.name)throw new BadRequestException('assetType and name are required.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_assets(id,tenant_id,company_id,branch_id,asset_type,name,asset_tag,serial_number)VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,id,tenantId,companyId,b.branchId??null,b.assetType,b.name,b.assetTag??null,b.serialNumber??null);return{id,status:'AVAILABLE'}}
async assignAsset(assetId:string,b:any){const{tenantId,companyId}=this.scope();if(!b.staffId)throw new BadRequestException('staffId is required.');return this.prisma.$transaction(async tx=>{const a=await tx.$queryRawUnsafe<any[]>(`SELECT id,status FROM hr_assets WHERE id=$1 AND tenant_id=$2 AND company_id=$3 FOR UPDATE`,assetId,tenantId,companyId);if(!a.length)throw new NotFoundException('Asset not found.');if(a[0].status==='ASSIGNED')throw new ConflictException('Asset is already assigned.');const staff=await tx.$queryRawUnsafe<any[]>(`SELECT s.id FROM staff s JOIN branches b ON b.id=s."branchId" WHERE s.id=$1 AND s."tenantId"=$2 AND b."companyId"=$3 LIMIT 1`,b.staffId,tenantId,companyId);if(!staff.length)throw new NotFoundException('Staff not found.');const id=randomUUID();await tx.$executeRawUnsafe(`INSERT INTO hr_asset_assignments(id,tenant_id,asset_id,staff_id,condition_out,assigned_by)VALUES($1,$2,$3,$4,$5,$6)`,id,tenantId,assetId,b.staffId,b.condition??null,b.actorId??null);await tx.$executeRawUnsafe(`UPDATE hr_assets SET status='ASSIGNED' WHERE id=$1`,assetId);return{id}})}
async returnAsset(assignmentId:string,b:any){const{tenantId}=this.scope();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,asset_id FROM hr_asset_assignments WHERE id=$1 AND tenant_id=$2 AND returned_at IS NULL FOR UPDATE`,assignmentId,tenantId);if(!rows.length)throw new NotFoundException('Open assignment not found.');await tx.$executeRawUnsafe(`UPDATE hr_asset_assignments SET returned_at=CURRENT_TIMESTAMP,condition_in=$1 WHERE id=$2`,b.condition??null,assignmentId);await tx.$executeRawUnsafe(`UPDATE hr_assets SET status='AVAILABLE' WHERE id=$1`,rows[0].asset_id);return{id:assignmentId,status:'RETURNED'}})}
async unresolvedAssets(staffId:string){const{tenantId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT x.id,a.name,a.asset_type AS "assetType",a.asset_tag AS "assetTag",x.assigned_at AS "assignedAt" FROM hr_asset_assignments x JOIN hr_assets a ON a.id=x.asset_id WHERE x.tenant_id=$1 AND x.staff_id=$2 AND x.returned_at IS NULL`,tenantId,staffId)}
async publishPolicy(b:any){const{tenantId,companyId}=this.scope();if(!b.title||!b.version)throw new BadRequestException('title and version are required.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_policies(id,tenant_id,company_id,title,category,version,content_ref,mandatory,published_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,CURRENT_TIMESTAMP)`,id,tenantId,companyId,b.title,b.category??null,b.version,b.contentRef??null,b.mandatory!==false);return{id}}
private async staffForUser(userId:string){const{tenantId,companyId}=this.scope();const rows=await this.prisma.$queryRawUnsafe<Array<{staffId:string}>>(`SELECT l.staff_id AS "staffId" FROM hr_employee_user_links l JOIN staff s ON s.id=l.staff_id AND s."tenantId"=l.tenant_id JOIN branches b ON b.id=s."branchId" WHERE l.tenant_id=$1 AND l.company_id=$2 AND l.user_id=$3 AND l.active=TRUE AND b."companyId"=$2 LIMIT 1`,tenantId,companyId,userId);if(!rows.length)throw new NotFoundException('Authenticated user is not linked to an employee.');return rows[0].staffId}
async acknowledgeByUser(policyId:string,userId:string,evidence?:string){return this.acknowledge(policyId,await this.staffForUser(userId),evidence)}
private async acknowledge(policyId:string,staffId:string,evidence?:string){const{tenantId,companyId}=this.scope();const p=await this.prisma.$queryRawUnsafe<any[]>(`SELECT id FROM hr_policies WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND active=TRUE`,policyId,tenantId,companyId);if(!p.length)throw new NotFoundException('Policy not found.');await this.prisma.$executeRawUnsafe(`INSERT INTO hr_policy_acknowledgements(id,tenant_id,policy_id,staff_id,evidence)VALUES($1,$2,$3,$4,$5) ON CONFLICT(policy_id,staff_id) DO NOTHING`,randomUUID(),tenantId,policyId,staffId,evidence??null);return{policyId,staffId,acknowledged:true}}
async inbox(status='OPEN'){const{tenantId,companyId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,item_type AS "itemType",entity_type AS "entityType",entity_id AS "entityId",title,priority,due_at AS "dueAt",assignee_id AS "assigneeId",status,created_at AS "createdAt" FROM hr_action_items WHERE tenant_id=$1 AND company_id=$2 AND status=$3 ORDER BY CASE priority WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'NORMAL' THEN 3 ELSE 4 END,due_at NULLS LAST,created_at`,tenantId,companyId,status)}
async actionItem(b:any){const{tenantId,companyId}=this.scope();if(!b.itemType||!b.entityType||!b.entityId||!b.title)throw new BadRequestException('Action item fields are incomplete.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_action_items(id,tenant_id,company_id,branch_id,item_type,entity_type,entity_id,title,priority,due_at,assignee_id,dedupe_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(tenant_id,dedupe_key) WHERE dedupe_key IS NOT NULL DO NOTHING`,id,tenantId,companyId,b.branchId??null,b.itemType,b.entityType,b.entityId,b.title,b.priority??'NORMAL',b.dueAt??null,b.assigneeId??null,b.dedupeKey??null);return{id}}
async emit(b:any){const{tenantId,companyId}=this.scope();if(!b.eventType||!b.entityType||!b.entityId||!b.idempotencyKey)throw new BadRequestException('Event fields are incomplete.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_domain_events(id,tenant_id,company_id,branch_id,event_type,entity_type,entity_id,payload,idempotency_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9) ON CONFLICT(tenant_id,idempotency_key) DO NOTHING`,id,tenantId,companyId,b.branchId??null,b.eventType,b.entityType,b.entityId,JSON.stringify(b.payload??{}),b.idempotencyKey);return{id}}
}
