import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';
import { Employee360Service } from './employee-360.service';
import { LeavePolicyService } from './leave-policy.service';
import { ApprovalWorkflowService } from './approval-workflow.service';

@Injectable()
export class HrSelfServiceService {
 constructor(private readonly prisma:PrismaService,private readonly ctx:TenantContext,private readonly employee360:Employee360Service,private readonly leave:LeavePolicyService,private readonly approvals:ApprovalWorkflowService){}
 private scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId||!companyId)throw new BadRequestException('Tenant and company context are required.');return{tenantId,companyId};}
 private async employee(userId:string){const{tenantId,companyId}=this.scope();const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT s.id,s."branchId" AS "branchId",s."firstName" AS "firstName",s."lastName" AS "lastName",s.email,s.status FROM hr_employee_user_links l JOIN staff s ON s.id=l.staff_id JOIN branches b ON b.id=s."branchId" WHERE l.tenant_id=$1 AND l.company_id=$2 AND l.user_id=$3 AND l.active=TRUE AND s."tenantId"=$1 AND b."companyId"=$2 LIMIT 1`,tenantId,companyId,userId);if(!rows.length)throw new NotFoundException('Employee identity is not linked to this user.');return rows[0];}
 async link(staffId:string,userId:string,actorId:string){const{tenantId,companyId}=this.scope();const staff=await this.prisma.staff.findFirst({where:{id:staffId,tenantId,branch:{companyId}},select:{id:true}});const user=await this.prisma.user.findFirst({where:{id:userId,tenantId},select:{id:true}});if(!staff||!user)throw new NotFoundException('Staff or user not found in organization scope.');await this.prisma.$executeRawUnsafe(`INSERT INTO hr_employee_user_links(tenant_id,company_id,staff_id,user_id,linked_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant_id,staff_id) DO UPDATE SET user_id=EXCLUDED.user_id,company_id=EXCLUDED.company_id,active=TRUE,linked_at=CURRENT_TIMESTAMP,linked_by=EXCLUDED.linked_by`,tenantId,companyId,staffId,userId,actorId);return{staffId,userId,active:true};}
 async employeeHome(userId:string){const employee=await this.employee(userId),year=new Date().getFullYear(),types=await this.leave.leaveTypes(),leaveBalances:any[]=[];for(const type of types.filter((x:any)=>x.active)){try{leaveBalances.push({...await this.leave.balance(employee.id,type.id,year),code:type.code,name:type.name});}catch{}}const{tenantId}=this.scope();const shifts=await this.prisma.$queryRawUnsafe<any[]>(`SELECT sh.id,sh.start_at AS "startAt",sh.end_at AS "endAt",sh.status FROM hr_shift_assignments a JOIN hr_scheduled_shifts sh ON sh.id=a.scheduled_shift_id WHERE a.tenant_id=$1 AND a.staff_id=$2 AND sh.start_at>=CURRENT_TIMESTAMP ORDER BY sh.start_at LIMIT 20`,tenantId,employee.id);return{employee,profile:await this.employee360.get(employee.id),leaveBalances,leaveRequests:await this.leave.requests(employee.id),upcomingShifts:shifts};}
 async requestLeave(userId:string,body:any){const employee=await this.employee(userId),request=await this.leave.request(employee.id,body);try{await this.approvals.submit({entityType:'LEAVE',entityId:request.id,branchId:employee.branchId,requesterId:userId});}catch{}return request;}
 async managerHome(userId:string){const manager=await this.employee(userId),{tenantId,companyId}=this.scope();const team=await this.prisma.$queryRawUnsafe<any[]>(`SELECT s.id,s."firstName" AS "firstName",s."lastName" AS "lastName",s.email,s.status,a.position_id AS "positionId",a.department_id AS "departmentId",a.team_id AS "teamId" FROM hr_employee_assignments a JOIN staff s ON s.id=a.staff_id WHERE a.tenant_id=$1 AND a.company_id=$2 AND a.manager_staff_id=$3 AND a.effective_from<=CURRENT_DATE AND(a.effective_to IS NULL OR a.effective_to>=CURRENT_DATE) ORDER BY s."firstName",s."lastName"`,tenantId,companyId,manager.id);const ids=team.map((x:any)=>x.id);const pendingLeaves=ids.length?await this.prisma.$queryRawUnsafe<any[]>(`SELECT r.id,r.staff_id AS "staffId",r.start_date::text AS "startDate",r.end_date::text AS "endDate",r.days::text,r.status,t.name AS "leaveType" FROM leave_requests r LEFT JOIN hr_leave_types t ON t.id=r.leave_type_id WHERE r.tenant_id=$1 AND r.staff_id=ANY($2::text[]) AND r.status='PENDING' ORDER BY r.created_at`,tenantId,ids):[];return{manager,team,pendingLeaves,approvalQueue:await this.approvals.queue('PENDING')};}
}
