import { Module } from '@nestjs/common';
import { OrganizationScopeService } from '../../common/tenant/organization-scope.service';
import { HrController } from './hr.controller';
import { PersonnelDocumentController } from './personnel-document.controller';
import { CertificationController } from './certification.controller';
import { CompetencyController } from './competency.controller';
import { WorkforceSchedulingController } from './workforce-scheduling.controller';
import { HrService } from './hr.service';
import { HrOrganizationService } from './hr-organization.service';
import { Employee360Service } from './employee-360.service';
import { EmploymentHistoryService } from './employment-history.service';
import { OnboardingService } from './onboarding.service';
import { ProbationService } from './probation.service';
import { OffboardingService } from './offboarding.service';
import { PersonnelDocumentService } from './personnel-document.service';
import { PersonnelDocumentComplianceService } from './personnel-document-compliance.service';
import { CertificationService } from './certification.service';
import { CompetencyService } from './competency.service';
import { WorkforceSchedulingService } from './workforce-scheduling.service';
import { PayrollAccountingService } from './payroll-accounting.service';import { PayrollPeriodService } from './payroll-period.service';import { PayrollSettlementService } from './payroll-settlement.service';import { PayrollReportService } from './payroll-report.service';import { PayrollCostCenterAccountingService } from './payroll-cost-center-accounting.service';import { PayrollPostingOrchestratorService } from './payroll-posting-orchestrator.service';import { PayrollReversalService } from './payroll-reversal.service';import { PayrollDashboardService } from './payroll-dashboard.service';import { PayrollPaymentReversalService } from './payroll-payment-reversal.service';import { PayrollWorkInputService } from './payroll-work-input.service';import { HrAnalyticsService } from './hr-analytics.service';import { PayrollPolicyService } from './payroll-policy.service';
@Module({controllers:[HrController,PersonnelDocumentController,CertificationController,CompetencyController,WorkforceSchedulingController],providers:[OrganizationScopeService,HrService,HrOrganizationService,Employee360Service,EmploymentHistoryService,OnboardingService,ProbationService,OffboardingService,PersonnelDocumentService,PersonnelDocumentComplianceService,CertificationService,CompetencyService,WorkforceSchedulingService,PayrollAccountingService,PayrollPeriodService,PayrollSettlementService,PayrollReportService,PayrollCostCenterAccountingService,PayrollPostingOrchestratorService,PayrollReversalService,PayrollDashboardService,PayrollPaymentReversalService,PayrollWorkInputService,HrAnalyticsService,PayrollPolicyService],exports:[HrService,HrOrganizationService,Employee360Service,EmploymentHistoryService,OnboardingService,ProbationService,OffboardingService,PersonnelDocumentService,PersonnelDocumentComplianceService,CertificationService,CompetencyService,WorkforceSchedulingService,PayrollAccountingService,PayrollPeriodService,PayrollSettlementService,PayrollReportService,PayrollCostCenterAccountingService,PayrollPostingOrchestratorService,PayrollReversalService,PayrollDashboardService,PayrollPaymentReversalService,PayrollWorkInputService,HrAnalyticsService,PayrollPolicyService]})export class HrModule{}
