import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';

type StaffProfile = Record<string, unknown>;

@Injectable()
export class HrService {
  constructor(private readonly prisma: PrismaService, private readonly tenantContext: TenantContext) {}
  private scope() { const tenantId=this.tenantContext.getTenantId(); const companyId=this.tenantContext.getCompanyId(); const branchId=this.tenantContext.getBranchId(); const roleScope=this.tenantContext.getRoleScope(); if(!tenantId)throw new BadRequestException('Tenant context is required.'); if(roleScope==='CENTRAL'&&branchId===null)return{tenantId,branchId:null,companyId}; if(!branchId)throw new BadRequestException('A branch must be selected for this operation.'); return{tenantId,branchId,companyId}; }
  private profile(v:unknown):StaffProfile{return v&&typeof v==='object'&&!Array.isArray(v)?v as StaffProfile:{};}
  async employees(){const{tenantId,branchId}=this.scope();const rows=await this.prisma.staff.findMany({where:branchId?{tenantId,branchId}:{tenantId},orderBy:[{firstName:'asc'},{lastName:'asc'}],select:{id:true,firstName:true,lastName:true,phone:true,email:true,status:true,branchId:true,profile:true}});return rows.map(s=>{const p=this.profile(s.profile);return{...s,personnelNumber:p.personnelNumber??null,identityNumber:p.identityNumber??null,department:p.department??null,position:p.position??null,employmentType:p.employmentType??null,hireDate:p.hireDate??null,iban:p.iban??null,bankName:p.bankName??null,grossSalary:Number(p.salary??0)};});}
  async createEmployee(body:any){const{tenantId,branchId}=this.scope();const targetBranchId=body.branchId??branchId;if(!targetBranchId||!body.firstName||!body.lastName)throw new BadRequestException('firstName, lastName and branchId are required.');const branch=await this.prisma.branch.findFirst({where:{id:targetBranchId,company:{tenantId}},select:{id:true}});if(!branch)throw new BadRequestException('Branch is not available in this tenant.');if(body.email){const existing=await this.prisma.staff.findFirst({where:{tenantId,email:body.email}});if(existing)throw new BadRequestException('A staff member with this email already exists.');}const profile:StaffProfile={};for(const key of ['personnelNumber','identityNumber','department','position','employmentType','hireDate','iban','bankName','salary','salaryType','annualLeaveDays','usedLeaveDays','pendingLeaveDays'])if(body[key]!==undefined)profile[key]=body[key];return this.prisma.staff.create({data:{tenantId,branchId:targetBranchId,firstName:body.firstName,lastName:body.lastName,phone:body.phone??null,email:body.email??null,status:body.status??'ACTIVE',profile}});}
  async updateEmployee(id:string,body:any){const{tenantId,branchId}=this.scope();const c=await this.prisma.staff.findFirst({where:{id,tenantId,...(branchId?{branchId}:{})}});if(!c)throw new NotFoundException('Staff not found');const next={...this.profile(c.profile)};for(const k of ['personnelNumber','identityNumber','department','position','employmentType','hireDate','iban','bankName','salary','salaryType','annualLeaveDays','usedLeaveDays','pendingLeaveDays'])if(body[k]!==undefined)next[k]=body[k];return this.prisma.staff.update({where:{id},data:{firstName:body.firstName??c.firstName,lastName:body.lastName??c.lastName,phone:body.phone??c.phone,email:body.email??c.email,status:body.status??c.status,profile:next}});}
  async deleteEmployee(id:string){const{tenantId,branchId}=this.scope();const c=await this.prisma.staff.findFirst({where:{id,tenantId,...(branchId?{branchId}:{})}});if(!c)throw new NotFoundException('Staff not found');return this.prisma.staff.update({where:{id},data:{status:'ARCHIVED'}});}
  async personnelFiles(){return this.employees();}
  async attendance(year?:number,month?:number){const{tenantId,branchId}=this.scope(),y=year??new Date().getFullYear(),m=month??new Date().getMonth()+1;return this.prisma.$queryRawUnsafe<any[]>(`SELECT ar.*,s."firstName" AS "firstName",s."lastName" AS "lastName" FROM attendance_records ar JOIN staff s ON s.id=ar.staff_id WHERE ar.tenant_id=$1 AND EXTRACT(YEAR FROM ar.work_date)=$2 AND EXTRACT(MONTH FROM ar.work_date)=$3 ${branchId?'AND ar.branch_id=$4':''} ORDER BY ar.work_date,s."firstName"`,...(branchId?[tenantId,y,m,branchId]:[tenantId,y,m]));}
  async upsertAttendance(b:any){const{tenantId,branchId}=this.scope(),target=b.branchId??branchId;if(!target||!b.staffId||!b.workDate)throw new BadRequestException('staffId, branchId and workDate are required.');return this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO attendance_records(tenant_id,branch_id,staff_id,work_date,check_in,check_out,break_minutes,worked_minutes,overtime_minutes,status,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(staff_id,work_date) DO UPDATE SET check_in=EXCLUDED.check_in,check_out=EXCLUDED.check_out,break_minutes=EXCLUDED.break_minutes,worked_minutes=EXCLUDED.worked_minutes,overtime_minutes=EXCLUDED.overtime_minutes,status=EXCLUDED.status,note=EXCLUDED.note,updated_at=CURRENT_TIMESTAMP RETURNING *`,tenantId,target,b.staffId,b.workDate,b.checkIn??null,b.checkOut??null,Number(b.breakMinutes??0),Number(b.workedMinutes??0),Number(b.overtimeMinutes??0),b.status??'PRESENT',b.note??null);}
  async leaves(){const{tenantId,branchId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT lr.*,s."firstName" AS "firstName",s."lastName" AS "lastName" FROM leave_requests lr JOIN staff s ON s.id=lr.staff_id WHERE lr.tenant_id=$1 ${branchId?'AND lr.branch_id=$2':''} ORDER BY lr.start_date DESC,lr.created_at DESC`,...(branchId?[tenantId,branchId]:[tenantId]));}
  async createLeave(b:any){const{tenantId,branchId}=this.scope(),target=b.branchId??branchId;if(!target||!b.staffId||!b.type||!b.startDate||!b.endDate)throw new BadRequestException('staffId, branchId, type, startDate and endDate are required.');const days=Number(b.days??0);if(days<=0)throw new BadRequestException('days must be greater than zero.');return this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO leave_requests(tenant_id,branch_id,staff_id,type,start_date,end_date,days,status,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,tenantId,target,b.staffId,b.type,b.startDate,b.endDate,days,b.status??'PENDING',b.reason??null);}
  async updateLeave(id:string,b:any){const{tenantId,branchId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`UPDATE leave_requests SET status=COALESCE($1,status),reason=COALESCE($2,reason),updated_at=CURRENT_TIMESTAMP WHERE id=$3 AND tenant_id=$4 ${branchId?'AND branch_id=$5':''} RETURNING *`,b.status??null,b.reason??null,id,tenantId,...(branchId?[branchId]:[]));}
  async deleteLeave(id:string){const{tenantId,branchId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`DELETE FROM leave_requests WHERE id=$1 AND tenant_id=$2 ${branchId?'AND branch_id=$3':''} RETURNING *`,id,tenantId,...(branchId?[branchId]:[]));}
  async payroll(year?:number,month?:number){const{tenantId,branchId}=this.scope(),y=year??new Date().getFullYear(),m=month??new Date().getMonth()+1;return this.prisma.$queryRawUnsafe<any[]>(`SELECT pi.*,s."firstName" AS "firstName",s."lastName" AS "lastName",pp.year,pp.month,pp.status AS "periodStatus" FROM payroll_items pi JOIN payroll_periods pp ON pp.id=pi.period_id JOIN staff s ON s.id=pi.staff_id WHERE pi.tenant_id=$1 AND pp.year=$2 AND pp.month=$3 ${branchId?'AND pi.branch_id=$4':''} ORDER BY s."firstName",s."lastName"`,...(branchId?[tenantId,y,m,branchId]:[tenantId,y,m]));}
  async createPayrollPeriod(year:number,month:number){const{tenantId}=this.scope();if(month<1||month>12)throw new BadRequestException('month must be between 1 and 12.');return this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO payroll_periods(tenant_id,year,month,status) VALUES($1,$2,$3,'DRAFT') ON CONFLICT(tenant_id,year,month) DO UPDATE SET updated_at=CURRENT_TIMESTAMP RETURNING *`,tenantId,year,month);}
  async payments(year?:number,month?:number){const{tenantId,branchId}=this.scope(),y=year??new Date().getFullYear(),m=month??new Date().getMonth()+1;return this.prisma.$queryRawUnsafe<any[]>(`SELECT sp.*,s."firstName" AS "firstName",s."lastName" AS "lastName" FROM salary_payments sp JOIN payroll_periods pp ON pp.id=sp.period_id JOIN staff s ON s.id=sp.staff_id WHERE sp.tenant_id=$1 AND pp.year=$2 AND pp.month=$3 ${branchId?'AND sp.branch_id=$4':''} ORDER BY sp.paid_at DESC`,...(branchId?[tenantId,y,m,branchId]:[tenantId,y,m]));}
  async createPayment(b:any){const{tenantId,branchId}=this.scope();if(!branchId||!b.staffId||!b.amount||!b.year||!b.month)throw new BadRequestException('staffId, amount, year and month are required.');const period=await this.createPayrollPeriod(Number(b.year),Number(b.month));const p=(period as any[])[0];return this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO salary_payments(tenant_id,branch_id,period_id,staff_id,amount,method,status,paid_at,note) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,CURRENT_TIMESTAMP),$9) RETURNING *`,tenantId,branchId,p.id,b.staffId,Number(b.amount),b.method??'BANK',b.status??'PAID',b.paidAt??null,b.note??null);}
  async sgk(year?:number,month?:number){const{tenantId,branchId}=this.scope(),y=year??new Date().getFullYear(),m=month??new Date().getMonth()+1;return this.prisma.$queryRawUnsafe<any[]>(`SELECT sr.*,s."firstName" AS "firstName",s."lastName" AS "lastName" FROM sgk_records sr JOIN staff s ON s.id=sr.staff_id WHERE sr.tenant_id=$1 AND sr.period_year=$2 AND sr.period_month=$3 ${branchId?'AND sr.branch_id=$4':''} ORDER BY sr.record_date DESC`,...(branchId?[tenantId,y,m,branchId]:[tenantId,y,m]));}
  async createSgk(b:any){const{tenantId,branchId}=this.scope();if(!branchId||!b.staffId||!b.year||!b.month)throw new BadRequestException('staffId, year and month are required.');return this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO sgk_records(tenant_id,branch_id,staff_id,period_year,period_month,status,document_no,record_date,note) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,CURRENT_DATE),$9) RETURNING *`,tenantId,branchId,b.staffId,Number(b.year),Number(b.month),b.status??'DRAFT',b.documentNo??null,b.recordDate??null,b.note??null);}
}
