import { randomUUID } from 'node:crypto';
import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { OrganizationScopeService } from '../../common/tenant/organization-scope.service';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class LeavePolicyService {
  constructor(private readonly prisma: PrismaService, private readonly ctx: TenantContext, private readonly organizationScope: OrganizationScopeService) {}

  private scope() { const tenantId=this.ctx.getTenantId(), companyId=this.ctx.getCompanyId(); if(!tenantId) throw new BadRequestException('Tenant context is required.'); if(!companyId) throw new BadRequestException('Company context is required.'); return {tenantId,companyId}; }
  private async branches(){const scope=await this.organizationScope.getBranchScopedWhere();if('branchId' in scope)return typeof scope.branchId==='string'?[scope.branchId]:scope.branchId.in;return null;}
  private number(v:unknown,name:string,min=0){const n=Number(v);if(!Number.isFinite(n)||n<min)throw new BadRequestException(`${name} must be >= ${min}.`);return n;}

  async leaveTypes(){const{tenantId,companyId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,code,name,paid,requires_document AS "requiresDocument",active FROM hr_leave_types WHERE tenant_id=$1 AND company_id=$2 ORDER BY active DESC,name`,tenantId,companyId);}

  async createPolicy(body:any){const{tenantId,companyId}=this.scope(),branchIds=await this.branches();const leaveTypeId=String(body.leaveTypeId??'').trim(),name=String(body.name??'').trim();if(!leaveTypeId||!name)throw new BadRequestException('leaveTypeId and name are required.');if(body.branchId&&branchIds!==null&&!branchIds.includes(body.branchId))throw new BadRequestException('Branch is outside organization scope.');const type=await this.prisma.$queryRawUnsafe<any[]>(`SELECT id FROM hr_leave_types WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND active=TRUE`,leaveTypeId,tenantId,companyId);if(!type.length)throw new NotFoundException('Leave type not found.');const annual=this.number(body.annualEntitlement??0,'annualEntitlement'),accrual=this.number(body.accrualAmount??0,'accrualAmount'),method=String(body.accrualMethod??'ANNUAL').toUpperCase();if(!['ANNUAL','MONTHLY','NONE'].includes(method))throw new BadRequestException('Invalid accrualMethod.');return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_leave_policies(id,tenant_id,company_id,leave_type_id,name,employment_type,position_id,branch_id,annual_entitlement,accrual_method,accrual_amount,carry_over_limit,allow_negative,max_negative,effective_from,effective_to) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::date,$16::date) RETURNING id,leave_type_id AS "leaveTypeId",name,branch_id AS "branchId",annual_entitlement::text AS "annualEntitlement",accrual_method AS "accrualMethod",accrual_amount::text AS "accrualAmount",carry_over_limit::text AS "carryOverLimit",allow_negative AS "allowNegative",max_negative::text AS "maxNegative",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",active`,randomUUID(),tenantId,companyId,leaveTypeId,name,body.employmentType??null,body.positionId??null,body.branchId??null,annual,method,accrual,body.carryOverLimit==null?null:this.number(body.carryOverLimit,'carryOverLimit'),body.allowNegative===true,this.number(body.maxNegative??0,'maxNegative'),body.effectiveFrom??new Date().toISOString().slice(0,10),body.effectiveTo??null))[0];}

  async resolvePolicy(staffId:string,leaveTypeId:string,onDate:string){const{tenantId,companyId}=this.scope(),branchIds=await this.branches();const staff=await this.prisma.staff.findFirst({where:{id:staffId,tenantId,branch:{companyId},...(branchIds===null?{}:{branchId:{in:branchIds}})},select:{id:true,branchId:true}});if(!staff)throw new NotFoundException('Staff not found.');const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT p.* FROM hr_leave_policies p LEFT JOIN hr_employee_assignments a ON a.staff_id=$1 AND a.tenant_id=p.tenant_id AND a.company_id=p.company_id AND a.effective_from<=$5::date AND (a.effective_to IS NULL OR a.effective_to>=$5::date) LEFT JOIN employee_master_records em ON em.staff_id=$1 AND em.tenant_id=p.tenant_id WHERE p.tenant_id=$2 AND p.company_id=$3 AND p.leave_type_id=$4 AND p.active=TRUE AND p.effective_from<=$5::date AND (p.effective_to IS NULL OR p.effective_to>=$5::date) AND (p.branch_id IS NULL OR p.branch_id=$6) AND (p.position_id IS NULL OR p.position_id=a.position_id) AND (p.employment_type IS NULL OR p.employment_type=em.employment_type) ORDER BY (p.branch_id IS NOT NULL)::int DESC,(p.position_id IS NOT NULL)::int DESC,(p.employment_type IS NOT NULL)::int DESC,p.effective_from DESC LIMIT 1`,staffId,tenantId,companyId,leaveTypeId,onDate,staff.branchId);if(!rows.length)throw new NotFoundException('No applicable leave policy found.');return{staff,policy:rows[0]};}

  async ensureEntitlement(staffId:string,leaveTypeId:string,year:number){if(!Number.isInteger(year)||year<2000||year>2200)throw new BadRequestException('Invalid year.');const{tenantId,companyId}=this.scope(),resolved=await this.resolvePolicy(staffId,leaveTypeId,`${year}-01-01`),p=resolved.policy;return this.prisma.$transaction(async tx=>{const existing=await tx.$queryRawUnsafe<any[]>(`SELECT * FROM hr_leave_entitlements WHERE tenant_id=$1 AND staff_id=$2 AND leave_type_id=$3 AND period_year=$4 FOR UPDATE`,tenantId,staffId,leaveTypeId,year);if(existing.length)return this.balanceFrom(existing[0]);let carried=0;if(year>2000){const prev=await tx.$queryRawUnsafe<any[]>(`SELECT * FROM hr_leave_entitlements WHERE tenant_id=$1 AND staff_id=$2 AND leave_type_id=$3 AND period_year=$4`,tenantId,staffId,leaveTypeId,year-1);if(prev.length){const available=this.available(prev[0]);carried=Math.max(0,Math.min(available,p.carry_over_limit==null?available:Number(p.carry_over_limit)));}}const entitled=p.accrual_method==='ANNUAL'?Number(p.annual_entitlement):0;const id=randomUUID();await tx.$executeRawUnsafe(`INSERT INTO hr_leave_entitlements(id,tenant_id,company_id,branch_id,staff_id,leave_type_id,policy_id,period_year,entitled,carried_over) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,id,tenantId,companyId,resolved.staff.branchId,staffId,leaveTypeId,p.id,year,entitled,carried);if(entitled)await tx.$executeRawUnsafe(`INSERT INTO hr_leave_ledger(id,tenant_id,company_id,branch_id,staff_id,leave_type_id,entitlement_id,entry_type,quantity,effective_date,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,'ENTITLEMENT',$8,$9::date,$10)`,randomUUID(),tenantId,companyId,resolved.staff.branchId,staffId,leaveTypeId,id,entitled,`${year}-01-01`,`entitlement:${id}`);if(carried)await tx.$executeRawUnsafe(`INSERT INTO hr_leave_ledger(id,tenant_id,company_id,branch_id,staff_id,leave_type_id,entitlement_id,entry_type,quantity,effective_date,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,'CARRY_OVER',$8,$9::date,$10)`,randomUUID(),tenantId,companyId,resolved.staff.branchId,staffId,leaveTypeId,id,carried,`${year}-01-01`,`carry:${id}`);const row=(await tx.$queryRawUnsafe<any[]>(`SELECT * FROM hr_leave_entitlements WHERE id=$1`,id))[0];return this.balanceFrom(row);});}

  async accrue(staffId:string,leaveTypeId:string,year:number,month:number){if(!Number.isInteger(month)||month<1||month>12)throw new BadRequestException('Invalid month.');const entitlement=await this.ensureEntitlement(staffId,leaveTypeId,year);const{tenantId,companyId}=this.scope(),resolved=await this.resolvePolicy(staffId,leaveTypeId,`${year}-${String(month).padStart(2,'0')}-01`),amount=resolved.policy.accrual_method==='MONTHLY'?Number(resolved.policy.accrual_amount):0;if(!amount)return entitlement;const key=`accrual:${entitlement.id}:${year}-${String(month).padStart(2,'0')}`;return this.prisma.$transaction(async tx=>{const inserted=await tx.$executeRawUnsafe(`INSERT INTO hr_leave_ledger(id,tenant_id,company_id,branch_id,staff_id,leave_type_id,entitlement_id,entry_type,quantity,effective_date,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,'ACCRUAL',$8,$9::date,$10) ON CONFLICT DO NOTHING`,randomUUID(),tenantId,companyId,resolved.staff.branchId,staffId,leaveTypeId,entitlement.id,amount,`${year}-${String(month).padStart(2,'0')}-01`,key);if(inserted)await tx.$executeRawUnsafe(`UPDATE hr_leave_entitlements SET accrued=accrued+$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND tenant_id=$3`,amount,entitlement.id,tenantId);const row=(await tx.$queryRawUnsafe<any[]>(`SELECT * FROM hr_leave_entitlements WHERE id=$1 AND tenant_id=$2`,entitlement.id,tenantId))[0];return this.balanceFrom(row);});}

  async balance(staffId:string,leaveTypeId:string,year:number){await this.ensureEntitlement(staffId,leaveTypeId,year);const{tenantId}=this.scope();const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT * FROM hr_leave_entitlements WHERE tenant_id=$1 AND staff_id=$2 AND leave_type_id=$3 AND period_year=$4`,tenantId,staffId,leaveTypeId,year);return this.balanceFrom(rows[0]);}
  private available(r:any){return Number(r.opening_balance??0)+Number(r.entitled??0)+Number(r.accrued??0)+Number(r.carried_over??0)+Number(r.adjusted??0)-Number(r.used??0)-Number(r.pending??0);}
  private balanceFrom(r:any){if(!r)throw new ConflictException('Entitlement could not be resolved.');return{id:r.id,staffId:r.staff_id,leaveTypeId:r.leave_type_id,policyId:r.policy_id,year:Number(r.period_year),openingBalance:Number(r.opening_balance),entitled:Number(r.entitled),accrued:Number(r.accrued),carriedOver:Number(r.carried_over),adjusted:Number(r.adjusted),used:Number(r.used),pending:Number(r.pending),available:this.available(r)};}
}
