import { randomUUID } from 'node:crypto';
import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { OrganizationScopeService } from '../../common/tenant/organization-scope.service';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class OvertimeService {
  constructor(private readonly prisma: PrismaService, private readonly ctx: TenantContext, private readonly organizationScope: OrganizationScopeService) {}
  private async scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId||!companyId)throw new BadRequestException('Tenant and company context are required.');const scoped=await this.organizationScope.getBranchScopedWhere();const branchIds='branchId'in scoped?(typeof scoped.branchId==='string'?[scoped.branchId]:scoped.branchId.in):null;return{tenantId,companyId,branchIds}}
  async list(from:string,to:string,status?:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)throw new BadRequestException('Valid from/to dates are required.');const s=await this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT o.id,o.staff_id AS "staffId",st."firstName",st."lastName",o.work_date::text AS "workDate",o.source,o.requested_minutes AS "requestedMinutes",o.detected_minutes AS "detectedMinutes",o.approved_minutes AS "approvedMinutes",o.treatment,o.status,o.employee_note AS "employeeNote",o.manager_note AS "managerNote",o.hr_note AS "hrNote" FROM hr_overtime_requests o JOIN staff st ON st.id=o.staff_id WHERE o.tenant_id=$1 AND o.company_id=$2 AND ($3::text[] IS NULL OR o.branch_id=ANY($3::text[])) AND o.work_date BETWEEN $4::date AND $5::date AND ($6::text IS NULL OR o.status=$6) ORDER BY o.work_date DESC,o.created_at DESC`,s.tenantId,s.companyId,s.branchIds,from,to,status||null)}
  async request(staffId:string,body:any,actor:string){const s=await this.scope(),minutes=Math.trunc(Number(body.minutes));if(!staffId||!Number.isFinite(minutes)||minutes<=0)throw new BadRequestException('Positive overtime minutes are required.');const workDate=String(body.workDate??'');if(!/^\d{4}-\d{2}-\d{2}$/.test(workDate))throw new BadRequestException('Valid workDate is required.');const staff=await this.prisma.$queryRawUnsafe<any[]>(`SELECT st.id,st.branch_id AS "branchId" FROM staff st JOIN branches b ON b.id=st.branch_id WHERE st.id=$1 AND st.tenant_id=$2 AND b."companyId"=$3 AND st.status='ACTIVE' AND ($4::text[] IS NULL OR st.branch_id=ANY($4::text[]))`,staffId,s.tenantId,s.companyId,s.branchIds);if(!staff.length)throw new NotFoundException('Staff not found.');return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_overtime_requests(id,tenant_id,company_id,branch_id,staff_id,work_date,source,requested_minutes,treatment,employee_note,requested_by) VALUES($1,$2,$3,$4,$5,$6::date,'REQUESTED',$7,$8,$9,$10) RETURNING id,status,requested_minutes AS "requestedMinutes",work_date::text AS "workDate"`,randomUUID(),s.tenantId,s.companyId,staff[0].branchId,staffId,workDate,minutes,['PAYROLL','TIME_OFF_IN_LIEU','NONE'].includes(body.treatment)?body.treatment:'PAYROLL',String(body.note??'').trim()||null,actor))[0]}
  async detect(from:string,to:string,actor:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)throw new BadRequestException('Valid from/to dates are required.');const s=await this.scope();const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT a.id,a.branch_id AS "branchId",a.staff_id AS "staffId",a.work_date::text AS "workDate",a.overtime_minutes AS "minutes",a.scheduled_shift_id AS "shiftId" FROM attendance_records a JOIN branches b ON b.id=a.branch_id WHERE a.tenant_id=$1 AND b."companyId"=$2 AND ($3::text[] IS NULL OR a.branch_id=ANY($3::text[])) AND a.work_date BETWEEN $4::date AND $5::date AND a.overtime_minutes>0`,s.tenantId,s.companyId,s.branchIds,from,to);let created=0;for(const r of rows){const n=await this.prisma.$executeRawUnsafe(`INSERT INTO hr_overtime_requests(id,tenant_id,company_id,branch_id,staff_id,attendance_record_id,scheduled_shift_id,work_date,source,detected_minutes,treatment,requested_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8::date,'DETECTED',$9,'PAYROLL',$10) ON CONFLICT DO NOTHING`,randomUUID(),s.tenantId,s.companyId,r.branchId,r.staffId,r.id,r.shiftId,r.workDate,r.minutes,actor);created+=n}return{detected:rows.length,created}}
  async managerReview(id:string,approve:boolean,note:string,actor:string){return this.transition(id,'PENDING_MANAGER',approve?'PENDING_HR':'REJECTED',note,actor,'manager')}
  async hrReview(id:string,approve:boolean,approvedMinutes:number,treatment:string,note:string,actor:string){const minutes=Math.trunc(Number(approvedMinutes));if(approve&&(!Number.isFinite(minutes)||minutes<=0))throw new BadRequestException('Approved minutes must be positive.');if(!['PAYROLL','TIME_OFF_IN_LIEU','NONE'].includes(treatment))throw new BadRequestException('Invalid overtime treatment.');const s=await this.scope();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT * FROM hr_overtime_requests WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND ($4::text[] IS NULL OR branch_id=ANY($4::text[])) FOR UPDATE`,id,s.tenantId,s.companyId,s.branchIds);const row=rows[0];if(!row)throw new NotFoundException('Overtime request not found.');if(row.status!=='PENDING_HR')throw new ConflictException('Overtime request is not pending HR review.');const status=approve?'APPROVED':'REJECTED';const approved=approve?minutes:0;await tx.$executeRawUnsafe(`UPDATE hr_overtime_requests SET status=$1,approved_minutes=$2,treatment=$3,hr_note=$4,hr_reviewed_by=$5,hr_reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$6`,status,approved,treatment,String(note??'').trim()||null,actor,id);if(row.attendance_record_id)await tx.$executeRawUnsafe(`UPDATE attendance_records SET approved_overtime_minutes=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND tenant_id=$3`,approved,row.attendance_record_id,s.tenantId);return{id,status,approvedMinutes:approved,treatment}})}
  private async transition(id:string,expected:string,next:string,note:string,actor:string,kind:'manager'){const s=await this.scope();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,status FROM hr_overtime_requests WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND ($4::text[] IS NULL OR branch_id=ANY($4::text[])) FOR UPDATE`,id,s.tenantId,s.companyId,s.branchIds);if(!rows.length)throw new NotFoundException('Overtime request not found.');if(rows[0].status!==expected)throw new ConflictException('Overtime request is not in the expected review state.');await tx.$executeRawUnsafe(`UPDATE hr_overtime_requests SET status=$1,manager_note=$2,manager_reviewed_by=$3,manager_reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$4`,next,String(note??'').trim()||null,actor,id);return{id,status:next}})}
}
