import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { OrganizationScopeService } from '../../common/tenant/organization-scope.service';
import { TenantContext } from '../../common/tenant/tenant-context';

type ComplianceStatus = 'MISSING'|'PENDING'|'VERIFIED'|'EXPIRING'|'EXPIRED'|'REJECTED';
type ComplianceRow = {
  requirementId:string;documentType:string;title:string;description:string|null;required:boolean;restricted:boolean;requiresExpiry:boolean;warningDays:number;
  documentId:string|null;documentTitle:string|null;documentStatus:string|null;documentVersion:number|null;expiresAt:string|null;verificationNote:string|null;
};

@Injectable()
export class PersonnelDocumentComplianceService {
  constructor(private readonly prisma:PrismaService,private readonly ctx:TenantContext,private readonly organizationScope:OrganizationScopeService){}
  private scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId)throw new BadRequestException('Tenant context is required.');if(!companyId)throw new BadRequestException('Company context is required.');return{tenantId,companyId}}
  private async branchIds(){const s=await this.organizationScope.getBranchScopedWhere();if('branchId'in s)return typeof s.branchId==='string'?[s.branchId]:s.branchId.in;return null}
  private async staff(staffId:string){const{tenantId,companyId}=this.scope(),branchIds=await this.branchIds();const s=await this.prisma.staff.findFirst({where:{id:staffId,tenantId,branch:{companyId},...(branchIds===null?{}:{branchId:{in:branchIds}})},select:{id:true,branchId:true,profile:true}});if(!s)throw new NotFoundException('Staff not found');const profile=(s.profile??{}) as Record<string,unknown>;return{id:s.id,branchId:s.branchId,employmentType:String(profile.employmentType??'').trim()||null}}
  private status(row:ComplianceRow):ComplianceStatus{if(!row.documentId)return'MISSING';const raw=String(row.documentStatus??'PENDING').toUpperCase();if(raw==='REJECTED')return'REJECTED';if(raw==='PENDING')return'PENDING';if(row.expiresAt){const today=new Date();today.setHours(0,0,0,0);const expiry=new Date(`${row.expiresAt}T00:00:00`);if(expiry<today)return'EXPIRED';const warning=new Date(today);warning.setDate(warning.getDate()+Number(row.warningDays||0));if(expiry<=warning)return'EXPIRING'}return raw==='VERIFIED'?'VERIFIED':'PENDING'}
  async employee(staffId:string,includeRestricted=false){const{tenantId,companyId}=this.scope(),s=await this.staff(staffId);const rows=await this.prisma.$queryRawUnsafe<ComplianceRow[]>(`SELECT r.id AS "requirementId",r.document_type AS "documentType",r.title,r.description,r.required,r.restricted,r.requires_expiry AS "requiresExpiry",r.warning_days AS "warningDays",d.id AS "documentId",d.title AS "documentTitle",d.status AS "documentStatus",d.version AS "documentVersion",d.expires_at::text AS "expiresAt",d.verification_note AS "verificationNote" FROM hr_document_requirements r LEFT JOIN LATERAL (SELECT x.* FROM hr_personnel_documents x WHERE x.tenant_id=r.tenant_id AND x.company_id=r.company_id AND x.staff_id=$3 AND x.document_type=r.document_type AND x.status<>'ARCHIVED' ORDER BY x.version DESC,x.created_at DESC LIMIT 1) d ON TRUE WHERE r.tenant_id=$1 AND r.company_id=$2 AND r.active=TRUE AND r.required=TRUE AND (r.branch_id IS NULL OR r.branch_id=$4) AND (r.employment_type IS NULL OR r.employment_type=$5) AND ($6::boolean OR r.restricted=FALSE) ORDER BY r.title`,tenantId,companyId,staffId,s.branchId,s.employmentType,includeRestricted);const items=rows.map(row=>({...row,status:this.status(row),compliant:this.status(row)==='VERIFIED'}));const counts={total:items.length,verified:0,missing:0,pending:0,expiring:0,expired:0,rejected:0};for(const item of items){if(item.status==='VERIFIED')counts.verified++;else if(item.status==='MISSING')counts.missing++;else if(item.status==='PENDING')counts.pending++;else if(item.status==='EXPIRING')counts.expiring++;else if(item.status==='EXPIRED')counts.expired++;else if(item.status==='REJECTED')counts.rejected++}return{staffId,compliant:counts.total===counts.verified,score:counts.total?Math.round(counts.verified/counts.total*100):100,counts,items}}
  async overview(includeRestricted=false){const{tenantId,companyId}=this.scope(),branchIds=await this.branchIds();const staff=await this.prisma.staff.findMany({where:{tenantId,status:'ACTIVE',branch:{companyId},...(branchIds===null?{}:{branchId:{in:branchIds}})},select:{id:true,firstName:true,lastName:true,branchId:true,branch:{select:{name:true}}},orderBy:[{firstName:'asc'},{lastName:'asc'}]});const employees=[] as any[];for(const person of staff){const compliance=await this.employee(person.id,includeRestricted);employees.push({staffId:person.id,firstName:person.firstName,lastName:person.lastName,branchId:person.branchId,branchName:person.branch.name,score:compliance.score,compliant:compliance.compliant,counts:compliance.counts})}const nonCompliant=employees.filter(x=>!x.compliant).length;return{summary:{employees:employees.length,compliant:employees.length-nonCompliant,nonCompliant,complianceRate:employees.length?Math.round((employees.length-nonCompliant)/employees.length*100):100},employees}}
}
