import { PersonnelDocumentComplianceService } from './personnel-document-compliance.service';

describe('PersonnelDocumentComplianceService', () => {
  const ctx = { getTenantId: jest.fn(() => 'tenant-1'), getCompanyId: jest.fn(() => 'company-1') };
  const organizationScope = { getBranchScopedWhere: jest.fn().mockResolvedValue({ tenantId: 'tenant-1', branchId: { in: ['branch-1'] } }) };
  const staff = { id: 'staff-1', branchId: 'branch-1', profile: { employmentType: 'FULL_TIME' } };
  function prisma(){return{staff:{findFirst:jest.fn().mockResolvedValue(staff),findMany:jest.fn()},$queryRawUnsafe:jest.fn()}}
  beforeEach(()=>{jest.clearAllMocks();organizationScope.getBranchScopedWhere.mockResolvedValue({tenantId:'tenant-1',branchId:{in:['branch-1']}})});

  it('keeps employee lookup inside assigned branch scope',async()=>{const db=prisma();db.$queryRawUnsafe.mockResolvedValueOnce([]).mockResolvedValueOnce([]);const service=new PersonnelDocumentComplianceService(db as never,ctx as never,organizationScope as never);await service.employee('staff-1');expect(db.staff.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:'staff-1',tenantId:'tenant-1',branchId:{in:['branch-1']}})}))});

  it('keeps CENTRAL scope company-wide',async()=>{organizationScope.getBranchScopedWhere.mockResolvedValue({tenantId:'tenant-1',branch:{companyId:'company-1'}});const db=prisma();db.$queryRawUnsafe.mockResolvedValueOnce([]).mockResolvedValueOnce([]);const service=new PersonnelDocumentComplianceService(db as never,ctx as never,organizationScope as never);await service.employee('staff-1');expect(db.staff.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.not.objectContaining({branchId:expect.anything()})}))});

  it('uses normalized employment type before legacy profile',async()=>{const db=prisma();db.$queryRawUnsafe.mockResolvedValueOnce([{employmentType:'PART_TIME'}]).mockResolvedValueOnce([]);const service=new PersonnelDocumentComplianceService(db as never,ctx as never,organizationScope as never);await service.employee('staff-1');expect(db.$queryRawUnsafe.mock.calls[1]).toEqual(expect.arrayContaining(['PART_TIME']))});

  it('marks absent required documents as missing',async()=>{const db=prisma();db.$queryRawUnsafe.mockResolvedValueOnce([]).mockResolvedValueOnce([{requirementId:'r1',documentType:'IDENTITY',title:'Kimlik',description:null,required:true,restricted:false,requiresExpiry:false,warningDays:30,documentId:null,documentTitle:null,documentStatus:null,documentVersion:null,expiresAt:null,verificationNote:null}]);const service=new PersonnelDocumentComplianceService(db as never,ctx as never,organizationScope as never);const result=await service.employee('staff-1');expect(result.counts.missing).toBe(1);expect(result.score).toBe(0);expect(result.compliant).toBe(false)});

  it('does not accept verified documents without required expiry',async()=>{const db=prisma();db.$queryRawUnsafe.mockResolvedValueOnce([]).mockResolvedValueOnce([{requirementId:'r1',documentType:'OHS',title:'İSG',description:null,required:true,restricted:false,requiresExpiry:true,warningDays:30,documentId:'d1',documentTitle:'İSG',documentStatus:'VERIFIED',documentVersion:1,expiresAt:null,verificationNote:null}]);const service=new PersonnelDocumentComplianceService(db as never,ctx as never,organizationScope as never);const result=await service.employee('staff-1');expect(result.counts.pending).toBe(1);expect(result.counts.verified).toBe(0)});

  it('marks a verified document inside warning window as expiring',async()=>{jest.useFakeTimers().setSystemTime(new Date('2026-09-15T12:00:00Z'));try{const db=prisma();db.$queryRawUnsafe.mockResolvedValueOnce([]).mockResolvedValueOnce([{requirementId:'r1',documentType:'OHS',title:'İSG',description:null,required:true,restricted:false,requiresExpiry:true,warningDays:30,documentId:'d1',documentTitle:'İSG',documentStatus:'VERIFIED',documentVersion:1,expiresAt:'2026-09-30',verificationNote:null}]);const service=new PersonnelDocumentComplianceService(db as never,ctx as never,organizationScope as never);const result=await service.employee('staff-1');expect(result.counts.expiring).toBe(1);expect(result.compliant).toBe(false)}finally{jest.useRealTimers()}});

  it('reports fully verified requirements as compliant',async()=>{const db=prisma();db.$queryRawUnsafe.mockResolvedValueOnce([]).mockResolvedValueOnce([{requirementId:'r1',documentType:'CONTRACT',title:'Sözleşme',description:null,required:true,restricted:false,requiresExpiry:false,warningDays:30,documentId:'d1',documentTitle:'Sözleşme',documentStatus:'VERIFIED',documentVersion:1,expiresAt:null,verificationNote:null}]);const service=new PersonnelDocumentComplianceService(db as never,ctx as never,organizationScope as never);const result=await service.employee('staff-1');expect(result.score).toBe(100);expect(result.compliant).toBe(true);expect(result.counts.verified).toBe(1)});
});
