import { randomUUID } from 'node:crypto';
import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { OrganizationScopeService } from '../../common/tenant/organization-scope.service';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class PersonnelDocumentService {
  constructor(private readonly prisma:PrismaService,private readonly ctx:TenantContext,private readonly organizationScope:OrganizationScopeService){}
  private scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId)throw new BadRequestException('Tenant context is required.');if(!companyId)throw new BadRequestException('Company context is required.');return{tenantId,companyId}}
  private async branchIds(){const s=await this.organizationScope.getBranchScopedWhere();if('branchId'in s)return typeof s.branchId==='string'?[s.branchId]:s.branchId.in;return null}
  private text(v:unknown,n:string){const x=String(v??'').trim();if(!x)throw new BadRequestException(`${n} is required.`);return x}
  private day(v:unknown,n:string){if(v===undefined||v===null||v==='')return null;const d=new Date(String(v));if(Number.isNaN(d.getTime()))throw new BadRequestException(`${n} must be a valid date.`);return d.toISOString().slice(0,10)}
  private async staff(staffId:string){const{tenantId}=this.scope(),branchIds=await this.branchIds();const s=await this.prisma.staff.findFirst({where:{id:staffId,tenantId,branch:{companyId:this.ctx.getCompanyId()},...(branchIds===null?{}:{branchId:{in:branchIds}})},select:{id:true,branchId:true,branch:{select:{companyId:true}}}});if(!s)throw new NotFoundException('Staff not found');return s}
  private projection=`id,document_type AS "documentType",document_number AS "documentNumber",title,issued_at::text AS "issuedAt",expires_at::text AS "expiresAt",status,file_key AS "fileKey",file_name AS "fileName",mime_type AS "mimeType",file_size::text AS "fileSize",version,restricted,verified_at AS "verifiedAt",verified_by AS "verifiedBy",verification_note AS "verificationNote",notes,created_at AS "createdAt",updated_at AS "updatedAt"`;
  async list(staffId:string,includeRestricted=false){const{tenantId,companyId}=this.scope();await this.staff(staffId);return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,document_type AS "documentType",document_number AS "documentNumber",title,issued_at::text AS "issuedAt",expires_at::text AS "expiresAt",CASE WHEN expires_at<CURRENT_DATE AND status NOT IN ('ARCHIVED','REJECTED') THEN 'EXPIRED' ELSE status END AS status,file_key AS "fileKey",file_name AS "fileName",mime_type AS "mimeType",file_size::text AS "fileSize",version,restricted,verified_at AS "verifiedAt",verified_by AS "verifiedBy",verification_note AS "verificationNote",notes,created_at AS "createdAt" FROM hr_personnel_documents WHERE tenant_id=$1 AND company_id=$2 AND staff_id=$3 AND ($4::boolean OR restricted=FALSE) ORDER BY document_type,version DESC,created_at DESC`,tenantId,companyId,staffId,includeRestricted)}
  async create(staffId:string,b:any,actor:string){const{tenantId,companyId}=this.scope(),s=await this.staff(staffId),issued=this.day(b.issuedAt,'issuedAt'),expires=this.day(b.expiresAt,'expiresAt');if(issued&&expires&&expires<issued)throw new BadRequestException('expiresAt cannot precede issuedAt.');const type=this.text(b.documentType,'documentType'),number=String(b.documentNumber??'').trim()||null,title=this.text(b.title,'title'),fileSize=b.fileSize==null?null:Number(b.fileSize);if(fileSize!==null&&(!Number.isSafeInteger(fileSize)||fileSize<0))throw new BadRequestException('fileSize must be a non-negative integer.');return this.prisma.$transaction(async tx=>{const locked=await tx.$queryRawUnsafe<Array<{id:string}>>(`SELECT id FROM staff WHERE id=$1 AND tenant_id=$2 AND branch_id=$3 FOR UPDATE`,staffId,tenantId,s.branchId);if(!locked.length)throw new NotFoundException('Staff not found');const versions=await tx.$queryRawUnsafe<Array<{version:number}>>(`SELECT version FROM hr_personnel_documents WHERE tenant_id=$1 AND company_id=$2 AND staff_id=$3 AND document_type=$4 AND COALESCE(document_number,'')=COALESCE($5,'') ORDER BY version DESC LIMIT 1`,tenantId,companyId,staffId,type,number);const version=Number(versions[0]?.version??0)+1;return (await tx.$queryRawUnsafe<any[]>(`INSERT INTO hr_personnel_documents(id,tenant_id,company_id,branch_id,staff_id,document_type,document_number,title,issued_at,expires_at,file_key,file_name,mime_type,file_size,version,restricted,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::date,$10::date,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING ${this.projection}`,randomUUID(),tenantId,companyId,s.branchId,staffId,type,number,title,issued,expires,String(b.fileKey??'').trim()||null,String(b.fileName??'').trim()||null,String(b.mimeType??'').trim()||null,fileSize,version,b.restricted!==false,String(b.notes??'').trim()||null,actor))[0]})}
  async verify(staffId:string,documentId:string,b:any,actor:string){const{tenantId,companyId}=this.scope();await this.staff(staffId);const status=String(b.status??'VERIFIED').toUpperCase();if(!['VERIFIED','REJECTED'].includes(status))throw new BadRequestException('Verification status must be VERIFIED or REJECTED.');if(status==='REJECTED'&&!String(b.note??'').trim())throw new BadRequestException('A verification note is required when rejecting a document.');return this.prisma.$transaction(async tx=>{const docs=await tx.$queryRawUnsafe<Array<{id:string;status:string}>>(`SELECT id,status FROM hr_personnel_documents WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND staff_id=$4 FOR UPDATE`,documentId,tenantId,companyId,staffId);const doc=docs[0];if(!doc)throw new NotFoundException('Personnel document not found');if(doc.status!=='PENDING')throw new ConflictException('Only pending personnel documents can be verified or rejected. Create a new version to replace a decided document.');return (await tx.$queryRawUnsafe<any[]>(`UPDATE hr_personnel_documents SET status=$1,verified_at=CURRENT_TIMESTAMP,verified_by=$2,verification_note=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$4 AND tenant_id=$5 AND company_id=$6 AND staff_id=$7 AND status='PENDING' RETURNING ${this.projection}`,status,actor,String(b.note??'').trim()||null,documentId,tenantId,companyId,staffId))[0]})}
  async archive(staffId:string,documentId:string){const{tenantId,companyId}=this.scope();await this.staff(staffId);const rows=await this.prisma.$queryRawUnsafe<any[]>(`UPDATE hr_personnel_documents SET status='ARCHIVED',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND staff_id=$4 AND status<>'ARCHIVED' RETURNING ${this.projection}`,documentId,tenantId,companyId,staffId);if(rows.length)return rows[0];const existing=await this.prisma.$queryRawUnsafe<any[]>(`SELECT ${this.projection} FROM hr_personnel_documents WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND staff_id=$4 AND status='ARCHIVED'`,documentId,tenantId,companyId,staffId);if(existing.length)return existing[0];throw new NotFoundException('Personnel document not found')}
  async expiring(days=30,includeRestricted=false){const{tenantId,companyId}=this.scope(),branchIds=await this.branchIds(),window=Math.max(1,Math.min(365,Math.trunc(Number(days)||30)));return this.prisma.$queryRawUnsafe<any[]>(`SELECT d.id,d.staff_id AS "staffId",d.document_type AS "documentType",d.title,d.expires_at::text AS "expiresAt",d.restricted,s."firstName",s."lastName" FROM hr_personnel_documents d JOIN staff s ON s.id=d.staff_id AND s.tenant_id=d.tenant_id WHERE d.tenant_id=$1 AND d.company_id=$2 AND ($3::text[] IS NULL OR d.branch_id=ANY($3::text[])) AND ($4::boolean OR d.restricted=FALSE) AND d.status NOT IN ('ARCHIVED','REJECTED') AND d.expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+$5::integer ORDER BY d.expires_at`,tenantId,companyId,branchIds,includeRestricted,window)}
}
