import{randomUUID}from'node:crypto';import{BadRequestException,Injectable,NotFoundException}from'@nestjs/common';import{PrismaService}from'@beauty-erp/database';import{TenantContext}from'../../common/tenant/tenant-context';
@Injectable()export class TalentManagementService{constructor(private readonly prisma:PrismaService,private readonly ctx:TenantContext){}private scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId||!companyId)throw new BadRequestException('Tenant and company context are required.');return{tenantId,companyId}}private async staff(id:string){const{tenantId,companyId}=this.scope();const s=await this.prisma.staff.findFirst({where:{id,tenantId,branch:{companyId}},select:{id:true,branchId:true}});if(!s)throw new NotFoundException('Staff not found.');return s}
async goals(staffId?:string){const{tenantId,companyId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,staff_id AS "staffId",team_id AS "teamId",branch_id AS "branchId",name,metric_key AS "metricKey",target_value::text AS "target",actual_value::text AS "actual",unit,weight::text,stretch_target::text AS "stretchTarget",period_type AS "periodType",starts_on::text AS "startsOn",ends_on::text AS "endsOn",status FROM hr_goals WHERE tenant_id=$1 AND company_id=$2 AND($3::text IS NULL OR staff_id=$3) ORDER BY starts_on DESC`,tenantId,companyId,staffId??null)}
async createGoal(b:any){const{tenantId,companyId}=this.scope();if(!b.name||!b.metricKey||b.targetValue==null||!b.startsOn||!b.endsOn)throw new BadRequestException('Goal fields are incomplete.');let branchId=b.branchId??null;if(b.staffId)branchId=(await this.staff(b.staffId)).branchId;const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_goals(id,tenant_id,company_id,branch_id,staff_id,team_id,position_id,name,metric_key,target_value,unit,weight,stretch_target,period_type,starts_on,ends_on,status)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::date,$16::date,$17)`,id,tenantId,companyId,branchId,b.staffId??null,b.teamId??null,b.positionId??null,b.name,b.metricKey,b.targetValue,b.unit??null,b.weight??1,b.stretchTarget??null,b.periodType??'MONTHLY',b.startsOn,b.endsOn,b.status??'ACTIVE');return{id}}
async updateGoalActual(id:string,actual:number){const{tenantId,companyId}=this.scope();if(!Number.isFinite(Number(actual)))throw new BadRequestException('actual must be numeric.');const n=await this.prisma.$executeRawUnsafe(`UPDATE hr_goals SET actual_value=$1 WHERE id=$2 AND tenant_id=$3 AND company_id=$4`,Number(actual),id,tenantId,companyId);if(!n)throw new NotFoundException('Goal not found.');return{id,actual:Number(actual)}}
async reviews(staffId?:string){const{tenantId,companyId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT r.id,r.staff_id AS "staffId",r.manager_staff_id AS "managerStaffId",c.name AS "cycle",r.self_score::text AS "selfScore",r.manager_score::text AS "managerScore",r.final_score::text AS "finalScore",r.achievements,r.development_areas AS "developmentAreas",r.development_plan AS "developmentPlan",r.status FROM hr_performance_reviews r JOIN hr_performance_review_cycles c ON c.id=r.cycle_id WHERE r.tenant_id=$1 AND r.company_id=$2 AND($3::text IS NULL OR r.staff_id=$3) ORDER BY r.created_at DESC`,tenantId,companyId,staffId??null)}
async createCycle(b:any){const{tenantId,companyId}=this.scope();if(!b.name||!b.startsOn||!b.endsOn)throw new BadRequestException('Cycle fields are incomplete.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_performance_review_cycles(id,tenant_id,company_id,name,starts_on,ends_on,status)VALUES($1,$2,$3,$4,$5::date,$6::date,$7)`,id,tenantId,companyId,b.name,b.startsOn,b.endsOn,b.status??'DRAFT');return{id}}
async createReview(staffId:string,b:any){const{tenantId,companyId}=this.scope(),s=await this.staff(staffId);if(!b.cycleId)throw new BadRequestException('cycleId is required.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_performance_reviews(id,tenant_id,company_id,branch_id,cycle_id,staff_id,manager_staff_id)VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(cycle_id,staff_id) DO NOTHING`,id,tenantId,companyId,s.branchId,b.cycleId,staffId,b.managerStaffId??null);return{id}}
async cases(status?:string){const{tenantId,companyId}=this.scope();return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,staff_id AS "staffId",case_type AS "caseType",title,status,severity,owner_id AS "ownerId",restricted,created_at AS "createdAt",closed_at AS "closedAt" FROM hr_employee_cases WHERE tenant_id=$1 AND company_id=$2 AND($3::text IS NULL OR status=$3) ORDER BY created_at DESC`,tenantId,companyId,status??null)}
async createCase(b:any){const{tenantId,companyId}=this.scope();if(!b.branchId||!b.caseType||!b.title)throw new BadRequestException('branchId, caseType and title are required.');if(b.staffId)await this.staff(b.staffId);const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_employee_cases(id,tenant_id,company_id,branch_id,staff_id,case_type,title,description,severity,owner_id,restricted)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,id,tenantId,companyId,b.branchId,b.staffId??null,b.caseType,b.title,b.description??null,b.severity??'NORMAL',b.ownerId??null,b.restricted!==false);return{id,status:'OPEN'}}
async caseAction(id:string,b:any){const{tenantId,companyId}=this.scope();const found=await this.prisma.$queryRawUnsafe<any[]>(`SELECT id FROM hr_employee_cases WHERE id=$1 AND tenant_id=$2 AND company_id=$3`,id,tenantId,companyId);if(!found.length)throw new NotFoundException('Case not found.');const actionId=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_employee_relations_actions(id,tenant_id,case_id,action_type,description,effective_date,created_by)VALUES($1,$2,$3,$4,$5,$6::date,$7)`,actionId,tenantId,id,b.actionType,b.description,b.effectiveDate??null,b.createdBy??null);if(b.status)await this.prisma.$executeRawUnsafe(`UPDATE hr_employee_cases SET status=$1,updated_at=CURRENT_TIMESTAMP,closed_at=CASE WHEN $1='CLOSED' THEN CURRENT_TIMESTAMP ELSE closed_at END,resolution=COALESCE($2,resolution) WHERE id=$3`,b.status,b.resolution??null,id);return{id:actionId}}
}
