import { randomUUID } from 'node:crypto';
import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';
import { ApprovalWorkflowService } from './approval-workflow.service';
@Injectable()
export class TotalRewardsService {
 constructor(private readonly prisma:PrismaService,private readonly ctx:TenantContext,private readonly approvals:ApprovalWorkflowService){}
 private scope(){const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId();if(!tenantId||!companyId)throw new BadRequestException('Tenant and company context are required.');return{tenantId,companyId};}
 private async staff(id:string){const{tenantId,companyId}=this.scope();const s=await this.prisma.staff.findFirst({where:{id,tenantId,branch:{companyId}},select:{id:true,branchId:true}});if(!s)throw new NotFoundException('Staff not found.');return s;}
 async compensation(staffId:string){const{tenantId}=this.scope();await this.staff(staffId);return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,base_salary::text AS "baseSalary",variable_target::text AS "variableTarget",currency,salary_type AS "salaryType",pay_frequency AS "payFrequency",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",reason,approved_by AS "approvedBy" FROM hr_compensation_history WHERE tenant_id=$1 AND staff_id=$2 ORDER BY effective_from DESC`,tenantId,staffId);}
 async addCompensation(staffId:string,b:any){const{tenantId,companyId}=this.scope(),s=await this.staff(staffId),amount=Number(b.baseSalary);if(!Number.isFinite(amount)||amount<0||!b.effectiveFrom)throw new BadRequestException('Valid baseSalary and effectiveFrom are required.');return this.prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`UPDATE hr_compensation_history SET effective_to=($1::date-INTERVAL '1 day')::date WHERE tenant_id=$2 AND staff_id=$3 AND effective_to IS NULL AND effective_from<$1::date`,b.effectiveFrom,tenantId,staffId);const id=randomUUID();await tx.$executeRawUnsafe(`INSERT INTO hr_compensation_history(id,tenant_id,company_id,branch_id,staff_id,base_salary,variable_target,currency,salary_type,pay_frequency,effective_from,effective_to,reason,approved_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::date,$12::date,$13,$14)`,id,tenantId,companyId,s.branchId,staffId,amount,Number(b.variableTarget??0),b.currency??'TRY',b.salaryType??'GROSS',b.payFrequency??'MONTHLY',b.effectiveFrom,b.effectiveTo??null,b.reason??null,b.approvedBy??null);return{id};});}
 async benefits(staffId:string){const{tenantId}=this.scope();await this.staff(staffId);return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,benefit_type AS "type",name,amount::text,currency,employer_cost::text AS "employerCost",payroll_taxable AS "payrollTaxable",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",metadata FROM hr_benefit_assignments WHERE tenant_id=$1 AND staff_id=$2 ORDER BY effective_from DESC`,tenantId,staffId);}
 async addBenefit(staffId:string,b:any){const{tenantId,companyId}=this.scope(),s=await this.staff(staffId);if(!b.type||!b.name||!b.effectiveFrom)throw new BadRequestException('type, name and effectiveFrom are required.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_benefit_assignments(id,tenant_id,company_id,branch_id,staff_id,benefit_type,name,amount,currency,employer_cost,payroll_taxable,effective_from,effective_to,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::date,$13::date,$14::jsonb)`,id,tenantId,companyId,s.branchId,staffId,b.type,b.name,b.amount??null,b.currency??'TRY',b.employerCost??null,b.payrollTaxable===true,b.effectiveFrom,b.effectiveTo??null,JSON.stringify(b.metadata??{}));return{id};}
 async variableEarnings(staffId:string){const{tenantId}=this.scope();await this.staff(staffId);return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,earning_type AS "type",amount::text,currency,status,source_type AS "sourceType",source_id AS "sourceId",calculation_trace AS "calculationTrace",created_at AS "createdAt" FROM hr_variable_earnings WHERE tenant_id=$1 AND staff_id=$2 ORDER BY created_at DESC`,tenantId,staffId);}
 async addVariableEarning(staffId:string,b:any){const{tenantId,companyId}=this.scope(),s=await this.staff(staffId),type=String(b.type??'').toUpperCase(),amount=Number(b.amount);if(!['COMMISSION','BONUS','REWARD'].includes(type)||!Number.isFinite(amount))throw new BadRequestException('Valid earning type and amount are required.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_variable_earnings(id,tenant_id,company_id,branch_id,staff_id,earning_type,rule_id,source_type,source_id,amount,currency,calculation_trace) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb)`,id,tenantId,companyId,s.branchId,staffId,type,b.ruleId??null,b.sourceType??null,b.sourceId??null,amount,b.currency??'TRY',JSON.stringify(b.calculationTrace??{}));return{id,status:'PENDING'};}
 async advances(staffId:string){const{tenantId}=this.scope();await this.staff(staffId);return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,amount::text,currency,reason,status,repaid_amount::text AS "repaidAmount",payroll_deduction::text AS "payrollDeduction",requested_at AS "requestedAt",paid_at AS "paidAt",closed_at AS "closedAt" FROM hr_employee_advances WHERE tenant_id=$1 AND staff_id=$2 ORDER BY requested_at DESC`,tenantId,staffId);}
 async requestAdvance(staffId:string,b:any,requesterId?:string){const{tenantId,companyId}=this.scope(),s=await this.staff(staffId),amount=Number(b.amount);if(!Number.isFinite(amount)||amount<=0)throw new BadRequestException('amount must be positive.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_employee_advances(id,tenant_id,company_id,branch_id,staff_id,amount,currency,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,id,tenantId,companyId,s.branchId,staffId,amount,b.currency??'TRY',b.reason??null);try{await this.approvals.submit({entityType:'ADVANCE',entityId:id,branchId:s.branchId,requesterId,amount});}catch{}return{id,status:'REQUESTED'};}
 async expenses(staffId:string){const{tenantId}=this.scope();await this.staff(staffId);return this.prisma.$queryRawUnsafe<any[]>(`SELECT id,category,amount::text,currency,expense_date::text AS "expenseDate",receipt_url AS "receiptUrl",cost_center_id AS "costCenterId",project_id AS "projectId",travel_id AS "travelId",description,status,policy_result AS "policyResult",created_at AS "createdAt" FROM hr_expense_claims WHERE tenant_id=$1 AND staff_id=$2 ORDER BY created_at DESC`,tenantId,staffId);}
 async submitExpense(staffId:string,b:any,requesterId?:string){const{tenantId,companyId}=this.scope(),s=await this.staff(staffId),amount=Number(b.amount);if(!b.category||!b.expenseDate||!Number.isFinite(amount)||amount<=0)throw new BadRequestException('category, expenseDate and positive amount are required.');const id=randomUUID();await this.prisma.$executeRawUnsafe(`INSERT INTO hr_expense_claims(id,tenant_id,company_id,branch_id,staff_id,category,amount,currency,expense_date,receipt_url,cost_center_id,project_id,travel_id,description,policy_result) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::date,$10,$11,$12,$13,$14,$15::jsonb)`,id,tenantId,companyId,s.branchId,staffId,b.category,amount,b.currency??'TRY',b.expenseDate,b.receiptUrl??null,b.costCenterId??null,b.projectId??null,b.travelId??null,b.description??null,JSON.stringify(b.policyResult??{}));try{await this.approvals.submit({entityType:'EXPENSE',entityId:id,branchId:s.branchId,requesterId,amount});}catch{}return{id,status:'SUBMITTED'};}
 async totalReward(staffId:string){const comp=await this.compensation(staffId),benefits=await this.benefits(staffId),earnings=await this.variableEarnings(staffId);return{currentCompensation:comp[0]??null,compensationHistory:comp,benefits,variableEarnings:earnings};}
}
