import { randomUUID } from 'node:crypto';
import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { OrganizationScopeService } from '../../common/tenant/organization-scope.service';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class WorkforceWeeklyScheduleService {
  constructor(private readonly prisma: PrismaService, private readonly ctx: TenantContext, private readonly organizationScope: OrganizationScopeService) {}
  private scope() { const tenantId=this.ctx.getTenantId(),companyId=this.ctx.getCompanyId(); if(!tenantId||!companyId) throw new BadRequestException('Tenant and company context are required.'); return {tenantId,companyId}; }
  private async branches(){const scope=await this.organizationScope.getBranchScopedWhere();if('branchId' in scope)return typeof scope.branchId==='string'?[scope.branchId]:scope.branchId.in;return null;}
  private validWeek(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new BadRequestException('weekStart must be YYYY-MM-DD.');const d=new Date(`${value}T00:00:00Z`);if(d.getUTCDay()!==1)throw new BadRequestException('weekStart must be a Monday.');return value;}
  async list(from:string,to:string){const{tenantId,companyId}=this.scope(),branches=await this.branches();if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)throw new BadRequestException('Valid from/to range is required.');return this.prisma.$queryRawUnsafe<any[]>(`SELECT w.id,w.branch_id AS "branchId",w.week_start::text AS "weekStart",w.version,w.status,w.submitted_at AS "submittedAt",w.approved_at AS "approvedAt",w.published_at AS "publishedAt",COUNT(s.id)::int AS "shiftCount" FROM hr_workforce_schedules w LEFT JOIN hr_scheduled_shifts s ON s.workforce_schedule_id=w.id WHERE w.tenant_id=$1 AND w.company_id=$2 AND w.week_start BETWEEN $3::date AND $4::date AND ($5::text[] IS NULL OR w.branch_id=ANY($5::text[])) GROUP BY w.id ORDER BY w.week_start,w.branch_id,w.version DESC`,tenantId,companyId,from,to,branches);}
  async create(branchId:string,weekStart:string,actor:string){const{tenantId,companyId}=this.scope(),branches=await this.branches();this.validWeek(weekStart);if(branches!==null&&!branches.includes(branchId))throw new NotFoundException('Branch not found.');const branch=await this.prisma.$queryRawUnsafe<any[]>(`SELECT b.id FROM branches b WHERE b.id=$1 AND b.tenant_id=$2 AND b.company_id=$3 LIMIT 1`,branchId,tenantId,companyId);if(!branch.length)throw new NotFoundException('Branch not found.');try{return(await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO hr_workforce_schedules(id,tenant_id,company_id,branch_id,week_start,version,created_by) SELECT $1,$2,$3,$4,$5::date,COALESCE(MAX(version),0)+1,$6 FROM hr_workforce_schedules WHERE tenant_id=$2 AND company_id=$3 AND branch_id=$4 AND week_start=$5::date RETURNING id,branch_id AS "branchId",week_start::text AS "weekStart",version,status`,randomUUID(),tenantId,companyId,branchId,weekStart,actor))[0];}catch(e:any){if(e?.code==='23505')throw new ConflictException('An active weekly schedule already exists for this branch and week.');throw e;}}
  async attachDraftShifts(id:string){const{tenantId,companyId}=this.scope(),branches=await this.branches();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,branch_id AS "branchId",week_start AS "weekStart",status FROM hr_workforce_schedules WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND ($4::text[] IS NULL OR branch_id=ANY($4::text[])) FOR UPDATE`,id,tenantId,companyId,branches);if(!rows.length)throw new NotFoundException('Weekly schedule not found.');const w=rows[0];if(w.status!=='DRAFT')throw new ConflictException('Only draft schedules can collect shifts.');const updated=await tx.$executeRawUnsafe(`UPDATE hr_scheduled_shifts SET workforce_schedule_id=$1,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=$2 AND company_id=$3 AND branch_id=$4 AND shift_date BETWEEN $5::date AND ($5::date + 6) AND status='DRAFT' AND workforce_schedule_id IS NULL`,id,tenantId,companyId,w.branchId,w.weekStart);return{id,attached:updated};});}
  private async transition(id:string,from:string,to:string,actor:string){const{tenantId,companyId}=this.scope(),branches=await this.branches();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,status FROM hr_workforce_schedules WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND ($4::text[] IS NULL OR branch_id=ANY($4::text[])) FOR UPDATE`,id,tenantId,companyId,branches);if(!rows.length)throw new NotFoundException('Weekly schedule not found.');if(rows[0].status===to)return rows[0];if(rows[0].status!==from)throw new ConflictException(`Schedule must be ${from} before ${to}.`);const field=to==='SUBMITTED'?'submitted':to==='APPROVED'?'approved':'published';const result=(await tx.$queryRawUnsafe<any[]>(`UPDATE hr_workforce_schedules SET status=$2,${field}_at=CURRENT_TIMESTAMP,${field}_by=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING id,status,${field}_at AS "transitionedAt"`,id,to,actor))[0];if(to==='PUBLISHED')await tx.$executeRawUnsafe(`UPDATE hr_scheduled_shifts SET status='PUBLISHED',published_at=COALESCE(published_at,CURRENT_TIMESTAMP),published_by=COALESCE(published_by,$2),updated_at=CURRENT_TIMESTAMP WHERE workforce_schedule_id=$1 AND status='DRAFT'`,id,actor);return result;});}
  submit(id:string,actor:string){return this.transition(id,'DRAFT','SUBMITTED',actor);}
  approve(id:string,actor:string){return this.transition(id,'SUBMITTED','APPROVED',actor);}
  publish(id:string,actor:string){return this.transition(id,'APPROVED','PUBLISHED',actor);}
}
