import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';

export type InspectionTemplateInput={name:string;description?:string|null;category:string;items:Array<{code:string;title:string;description?:string|null;responseType?:'PASS_FAIL'|'SCORE'|'TEXT';required?:boolean;weight?:number;sortOrder?:number}>};
export type InspectionScheduleInput={branchId:string;templateId:string;cadence:string;nextDueAt:string;assigneeUserId?:string|null};
export type InspectionResultInput={templateItemId:string;outcome:'PASS'|'FAIL'|'NA'|'SCORE'|'TEXT';numericScore?:number|null;note?:string|null;finding?:{severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';category:string;title:string;description?:string|null}};

@Injectable()
export class QualityInspectionService{
  constructor(private readonly prisma:PrismaService,private readonly tenant:TenantContext){}
  private context(){return{tenantId:this.tenant.getTenantId(),companyId:this.tenant.getCompanyId(),branchId:this.tenant.getBranchId()};}
  private async assertBranch(branchId:string){const c=this.context();if(c.branchId&&c.branchId!==branchId)throw new BadRequestException('Branch is outside active branch scope.');const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT b.id FROM branches b JOIN companies c ON c.id=b."companyId" WHERE b.id=$1::text AND c.id=$2::text AND c."tenantId"=$3::text LIMIT 1`,branchId,c.companyId,c.tenantId);if(!rows.length)throw new BadRequestException('Branch is outside tenant/company scope.');}
  private async assertTemplate(templateId:string){const c=this.context();const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT id FROM quality_inspection_templates WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND is_active=true LIMIT 1`,templateId,c.tenantId,c.companyId);if(!rows.length)throw new BadRequestException('Inspection template is outside tenant/company scope or inactive.');}
  private async assertUserScope(userId:string|null|undefined,branchId:string){if(!userId)return;const c=this.context();const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT m.id FROM memberships m JOIN roles r ON r.id=m."roleId" AND r."tenantId"=m."tenantId" WHERE m."userId"=$1::text AND m."tenantId"=$2::text AND m.status='ACTIVE' AND (r.scope='CENTRAL' OR m."companyId"=$3::text) AND (r.scope<>'BRANCH' OR EXISTS(SELECT 1 FROM membership_branch_access mba WHERE mba."membershipId"=m.id AND mba."branchId"=$4::text)) LIMIT 1`,userId,c.tenantId,c.companyId,branchId);if(!rows.length)throw new BadRequestException('Assigned user is outside tenant/company/branch scope.');}

  async createTemplate(input:InspectionTemplateInput,userId:string){const c=this.context();const name=input.name?.trim(),category=input.category?.trim();if(!name||!category)throw new BadRequestException('Template name and category are required.');if(!input.items?.length)throw new BadRequestException('At least one checklist item is required.');return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`INSERT INTO quality_inspection_templates(tenant_id,company_id,name,description,category,created_by_user_id) VALUES($1::text,$2::text,$3,$4,$5,$6::text) RETURNING id,name,category,version,is_active AS "isActive"`,c.tenantId,c.companyId,name,input.description?.trim()||null,category,userId);const template=rows[0];for(let i=0;i<input.items.length;i++){const item=input.items[i];const code=item.code?.trim(),title=item.title?.trim();if(!code||!title)throw new BadRequestException('Checklist item code and title are required.');const weight=Number(item.weight??1);if(!Number.isFinite(weight)||weight<0)throw new BadRequestException('Checklist item weight must be zero or greater.');await tx.$executeRawUnsafe(`INSERT INTO quality_inspection_template_items(template_id,tenant_id,company_id,sort_order,code,title,description,response_type,is_required,weight) VALUES($1::text,$2::text,$3::text,$4,$5,$6,$7,$8,$9,$10)`,template.id,c.tenantId,c.companyId,item.sortOrder??i,code,title,item.description?.trim()||null,item.responseType??'PASS_FAIL',item.required??true,weight);}return template;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async listTemplates(){const c=this.context();return this.prisma.$queryRawUnsafe<any[]>(`SELECT t.id,t.name,t.description,t.category,t.version,t.is_active AS "isActive",count(i.id)::int AS "itemCount" FROM quality_inspection_templates t LEFT JOIN quality_inspection_template_items i ON i.template_id=t.id WHERE t.tenant_id=$1::text AND t.company_id=$2::text GROUP BY t.id ORDER BY t.name,t.version DESC`,c.tenantId,c.companyId);}

  async upsertSchedule(input:InspectionScheduleInput,userId:string){await this.assertBranch(input.branchId);await this.assertTemplate(input.templateId);await this.assertUserScope(input.assigneeUserId,input.branchId);const due=new Date(input.nextDueAt);if(Number.isNaN(due.getTime()))throw new BadRequestException('nextDueAt is invalid.');const cadence=input.cadence?.trim();if(!cadence)throw new BadRequestException('cadence is required.');const c=this.context();const rows=await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO quality_inspection_schedules(tenant_id,company_id,branch_id,template_id,cadence,next_due_at,assignee_user_id,created_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5,$6,$7::text,$8::text) ON CONFLICT(tenant_id,company_id,branch_id,template_id,cadence) DO UPDATE SET next_due_at=EXCLUDED.next_due_at,assignee_user_id=EXCLUDED.assignee_user_id,is_active=true,updated_at=now() RETURNING id,branch_id AS "branchId",template_id AS "templateId",cadence,next_due_at AS "nextDueAt",assignee_user_id AS "assigneeUserId"`,c.tenantId,c.companyId,input.branchId,input.templateId,cadence,due,input.assigneeUserId??null,userId);return rows[0];}

  async planInspection(input:{branchId:string;templateId:string;plannedFor:string;scheduleId?:string|null;inspectorUserId?:string|null;idempotencyKey?:string|null},userId:string){await this.assertBranch(input.branchId);await this.assertTemplate(input.templateId);await this.assertUserScope(input.inspectorUserId,input.branchId);const planned=new Date(input.plannedFor);if(Number.isNaN(planned.getTime()))throw new BadRequestException('plannedFor is invalid.');const c=this.context();const key=input.idempotencyKey?.trim()||null;if(key){const existing=await this.prisma.$queryRawUnsafe<any[]>(`SELECT id,status,planned_for AS "plannedFor" FROM quality_inspections WHERE tenant_id=$1::text AND company_id=$2::text AND idempotency_key=$3 LIMIT 1`,c.tenantId,c.companyId,key);if(existing.length)return{...existing[0],duplicate:true};}const rows=await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO quality_inspections(tenant_id,company_id,branch_id,template_id,schedule_id,idempotency_key,planned_for,inspector_user_id,created_by_user_id,updated_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5::text,$6,$7,$8::text,$9::text,$9::text) ON CONFLICT(tenant_id,company_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING id,status,planned_for AS "plannedFor"`,c.tenantId,c.companyId,input.branchId,input.templateId,input.scheduleId??null,key,planned,input.inspectorUserId??null,userId);return{...rows[0],duplicate:false};}

  async listInspections(filters:{status?:string;limit?:number}){const c=this.context();const limit=Math.min(Math.max(filters.limit??50,1),200);return this.prisma.$queryRawUnsafe<any[]>(`SELECT q.id,q.branch_id AS "branchId",b.name AS "branchName",q.template_id AS "templateId",t.name AS "templateName",q.status,q.planned_for AS "plannedFor",q.started_at AS "startedAt",q.completed_at AS "completedAt",q.score FROM quality_inspections q JOIN branches b ON b.id=q.branch_id JOIN quality_inspection_templates t ON t.id=q.template_id WHERE q.tenant_id=$1::text AND q.company_id=$2::text AND ($3::text IS NULL OR q.branch_id=$3::text) AND ($4::text IS NULL OR q.status=$4) ORDER BY q.planned_for DESC LIMIT $5`,c.tenantId,c.companyId,c.branchId,filters.status??null,limit);}

  async startInspection(id:string,userId:string){const c=this.context();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,status,branch_id AS "branchId" FROM quality_inspections WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,id,c.tenantId,c.companyId,c.branchId);if(!rows.length)throw new NotFoundException('Inspection not found.');if(rows[0].status==='IN_PROGRESS')return{...rows[0],duplicate:true};if(rows[0].status!=='PLANNED')throw new BadRequestException('Only planned inspections can be started.');const updated=await tx.$queryRawUnsafe<any[]>(`UPDATE quality_inspections SET status='IN_PROGRESS',started_at=now(),inspector_user_id=COALESCE(inspector_user_id,$2::text),updated_by_user_id=$2::text,updated_at=now() WHERE id=$1::text RETURNING id,status,started_at AS "startedAt"`,id,userId);return{...updated[0],duplicate:false};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async recordResult(id:string,input:InspectionResultInput,userId:string){const c=this.context();return this.prisma.$transaction(async tx=>{const inspections=await tx.$queryRawUnsafe<any[]>(`SELECT id,status,branch_id AS "branchId",template_id AS "templateId" FROM quality_inspections WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,id,c.tenantId,c.companyId,c.branchId);if(!inspections.length)throw new NotFoundException('Inspection not found.');if(inspections[0].status!=='IN_PROGRESS')throw new BadRequestException('Inspection must be in progress to record results.');const items=await tx.$queryRawUnsafe<any[]>(`SELECT id FROM quality_inspection_template_items WHERE id=$1::text AND template_id=$2::text AND tenant_id=$3::text AND company_id=$4::text LIMIT 1`,input.templateItemId,inspections[0].templateId,c.tenantId,c.companyId);if(!items.length)throw new BadRequestException('Checklist item is outside inspection template scope.');const result=await tx.$queryRawUnsafe<any[]>(`INSERT INTO quality_inspection_results(inspection_id,template_item_id,tenant_id,company_id,branch_id,outcome,numeric_score,note,recorded_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5::text,$6,$7,$8,$9::text) ON CONFLICT(inspection_id,template_item_id) DO UPDATE SET outcome=EXCLUDED.outcome,numeric_score=EXCLUDED.numeric_score,note=EXCLUDED.note,recorded_by_user_id=EXCLUDED.recorded_by_user_id,recorded_at=now() RETURNING id,outcome,numeric_score AS "numericScore"`,id,input.templateItemId,c.tenantId,c.companyId,inspections[0].branchId,input.outcome,input.numericScore??null,input.note?.trim()||null,userId);let finding=null;if(input.finding){const title=input.finding.title?.trim(),category=input.finding.category?.trim();if(!title||!category)throw new BadRequestException('Finding title and category are required.');const f=await tx.$queryRawUnsafe<any[]>(`INSERT INTO quality_findings(inspection_id,inspection_result_id,tenant_id,company_id,branch_id,severity,category,title,description,created_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5::text,$6,$7,$8,$9,$10::text) RETURNING id,status,severity,title`,id,result[0].id,c.tenantId,c.companyId,inspections[0].branchId,input.finding.severity,category,title,input.finding.description?.trim()||null,userId);finding=f[0];}return{result:result[0],finding};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async completeInspection(id:string,userId:string,notes?:string){const c=this.context();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,status,branch_id AS "branchId",template_id AS "templateId" FROM quality_inspections WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,id,c.tenantId,c.companyId,c.branchId);if(!rows.length)throw new NotFoundException('Inspection not found.');if(rows[0].status==='COMPLETED')return{...rows[0],duplicate:true};if(rows[0].status!=='IN_PROGRESS')throw new BadRequestException('Only in-progress inspections can be completed.');const missing=await tx.$queryRawUnsafe<any[]>(`SELECT i.id FROM quality_inspection_template_items i LEFT JOIN quality_inspection_results r ON r.template_item_id=i.id AND r.inspection_id=$1::text WHERE i.template_id=$2::text AND i.is_required=true AND r.id IS NULL LIMIT 1`,id,rows[0].templateId);if(missing.length)throw new BadRequestException('All required checklist items must be completed.');const scored=await tx.$queryRawUnsafe<any[]>(`SELECT COALESCE(SUM(CASE WHEN r.outcome='PASS' THEN i.weight WHEN r.outcome='SCORE' THEN i.weight*COALESCE(r.numeric_score,0)/100 ELSE 0 END),0)::numeric AS earned,COALESCE(SUM(CASE WHEN r.outcome='NA' THEN 0 ELSE i.weight END),0)::numeric AS possible FROM quality_inspection_template_items i JOIN quality_inspection_results r ON r.template_item_id=i.id AND r.inspection_id=$1::text WHERE i.template_id=$2::text`,id,rows[0].templateId);const possible=Number(scored[0]?.possible??0),earned=Number(scored[0]?.earned??0),score=possible>0?Math.round((earned/possible)*10000)/100:100;const updated=await tx.$queryRawUnsafe<any[]>(`UPDATE quality_inspections SET status='COMPLETED',completed_at=now(),score=$2,notes=$3,updated_by_user_id=$4::text,updated_at=now() WHERE id=$1::text RETURNING id,status,score,completed_at AS "completedAt"`,id,score,notes?.trim()||null,userId);return{...updated[0],duplicate:false};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async convertFindingToCase(findingId:string,userId:string){const c=this.context();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,branch_id AS "branchId",severity,category,title,description,quality_case_id AS "qualityCaseId" FROM quality_findings WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,findingId,c.tenantId,c.companyId,c.branchId);if(!rows.length)throw new NotFoundException('Quality finding not found.');const finding=rows[0];if(finding.qualityCaseId)return{id:finding.qualityCaseId,duplicate:true};const cases=await tx.$queryRawUnsafe<any[]>(`INSERT INTO quality_cases(tenant_id,company_id,branch_id,source_type,category,severity,status,title,description,created_by_user_id,updated_by_user_id) VALUES($1::text,$2::text,$3::text,'MANUAL',$4,$5,'OPEN',$6,$7,$8::text,$8::text) RETURNING id,status,severity,branch_id AS "branchId",created_at AS "createdAt"`,c.tenantId,c.companyId,finding.branchId,`INSPECTION:${finding.category}`,finding.severity,finding.title,finding.description,userId);const created=cases[0];await tx.$executeRawUnsafe(`INSERT INTO quality_case_events(case_id,tenant_id,company_id,branch_id,event_type,to_status,actor_user_id,note) VALUES($1::text,$2::text,$3::text,$4::text,'CREATED','OPEN',$5::text,$6)`,created.id,c.tenantId,c.companyId,finding.branchId,userId,`Created from inspection finding ${findingId}`);await tx.$executeRawUnsafe(`UPDATE quality_findings SET quality_case_id=$2::text,status='CASE_CREATED',updated_at=now() WHERE id=$1::text`,findingId,created.id);return{...created,duplicate:false};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
}
