import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class QualityCapaService {
  constructor(private readonly prisma:PrismaService,private readonly tenant:TenantContext){}
  private context(){return{tenantId:this.tenant.getTenantId(),companyId:this.tenant.getCompanyId(),branchId:this.tenant.getBranchId()};}
  private async assertUserScope(userId:string|null|undefined,branchId:string){if(!userId)return;const c=this.context();const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT m.id FROM memberships m JOIN roles r ON r.id=m."roleId" AND r."tenantId"=m."tenantId" WHERE m."userId"=$1::text AND m."tenantId"=$2::text AND m.status='ACTIVE' AND (r.scope='CENTRAL' OR m."companyId"=$3::text) AND (r.scope<>'BRANCH' OR EXISTS(SELECT 1 FROM membership_branch_access mba WHERE mba."membershipId"=m.id AND mba."branchId"=$4::text)) LIMIT 1`,userId,c.tenantId,c.companyId,branchId);if(!rows.length)throw new BadRequestException('Assigned user is outside tenant/company/branch scope.');}

  async assignFinding(id:string,input:{ownerUserId?:string|null;dueAt?:string|null},actorUserId:string){const c=this.context();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,branch_id AS "branchId",status FROM quality_findings WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,id,c.tenantId,c.companyId,c.branchId);if(!rows.length)throw new NotFoundException('Quality finding not found.');await this.assertUserScope(input.ownerUserId,rows[0].branchId);const due=input.dueAt?new Date(input.dueAt):null;if(due&&Number.isNaN(due.getTime()))throw new BadRequestException('dueAt is invalid.');const updated=await tx.$queryRawUnsafe<any[]>(`UPDATE quality_findings SET owner_user_id=$2::text,due_at=$3,updated_at=now() WHERE id=$1::text RETURNING id,status,owner_user_id AS "ownerUserId",due_at AS "dueAt"`,id,input.ownerUserId??null,due);return updated[0];},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async createFromCase(caseId:string,input:{rootCause:string;correctiveAction:string;preventiveAction?:string|null;ownerUserId?:string|null;dueAt?:string|null;verificationMethod?:string|null},actorUserId:string){const root=input.rootCause?.trim(),corrective=input.correctiveAction?.trim();if(!root||!corrective)throw new BadRequestException('rootCause and correctiveAction are required.');const c=this.context();return this.prisma.$transaction(async tx=>{const cases=await tx.$queryRawUnsafe<any[]>(`SELECT id,branch_id AS "branchId",root_cause AS "rootCause",corrective_action AS "correctiveAction" FROM quality_cases WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,caseId,c.tenantId,c.companyId,c.branchId);if(!cases.length)throw new NotFoundException('Quality case not found.');const branchId=cases[0].branchId;await this.assertUserScope(input.ownerUserId,branchId);const due=input.dueAt?new Date(input.dueAt):null;if(due&&Number.isNaN(due.getTime()))throw new BadRequestException('dueAt is invalid.');const existing=await tx.$queryRawUnsafe<any[]>(`SELECT id,status FROM quality_capa_plans WHERE quality_case_id=$1::text LIMIT 1`,caseId);if(existing.length)return{...existing[0],duplicate:true};const findings=await tx.$queryRawUnsafe<any[]>(`SELECT id FROM quality_findings WHERE quality_case_id=$1::text AND tenant_id=$2::text AND company_id=$3::text LIMIT 1`,caseId,c.tenantId,c.companyId);const created=await tx.$queryRawUnsafe<any[]>(`INSERT INTO quality_capa_plans(tenant_id,company_id,branch_id,quality_case_id,finding_id,root_cause,corrective_action,preventive_action,owner_user_id,due_at,verification_method,created_by_user_id,updated_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5::text,$6,$7,$8,$9::text,$10,$11,$12::text,$12::text) RETURNING id,status,branch_id AS "branchId",quality_case_id AS "qualityCaseId",owner_user_id AS "ownerUserId",due_at AS "dueAt"`,c.tenantId,c.companyId,branchId,caseId,findings[0]?.id??null,root,corrective,input.preventiveAction?.trim()||null,input.ownerUserId??null,due,input.verificationMethod?.trim()||null,actorUserId);await tx.$executeRawUnsafe(`INSERT INTO quality_capa_events(capa_id,tenant_id,company_id,branch_id,event_type,to_status,actor_user_id,note) VALUES($1::text,$2::text,$3::text,$4::text,'CREATED','OPEN',$5::text,$6)`,created[0].id,c.tenantId,c.companyId,branchId,actorUserId,'CAPA created from quality case');return{...created[0],duplicate:false};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async list(filters:{status?:string;limit?:number}){const c=this.context();const limit=Math.min(Math.max(filters.limit??50,1),200);return this.prisma.$queryRawUnsafe<any[]>(`SELECT p.id,p.quality_case_id AS "qualityCaseId",p.finding_id AS "findingId",p.branch_id AS "branchId",b.name AS "branchName",p.status,p.root_cause AS "rootCause",p.corrective_action AS "correctiveAction",p.preventive_action AS "preventiveAction",p.owner_user_id AS "ownerUserId",p.due_at AS "dueAt",p.verification_method AS "verificationMethod",p.verification_result AS "verificationResult",p.verified_at AS "verifiedAt",p.closed_at AS "closedAt" FROM quality_capa_plans p JOIN branches b ON b.id=p.branch_id WHERE p.tenant_id=$1::text AND p.company_id=$2::text AND ($3::text IS NULL OR p.branch_id=$3::text) AND ($4::text IS NULL OR p.status=$4) ORDER BY COALESCE(p.due_at,p.created_at) ASC LIMIT $5`,c.tenantId,c.companyId,c.branchId,filters.status??null,limit);}

  async transition(id:string,status:'IN_PROGRESS'|'VERIFICATION'|'CLOSED',actorUserId:string,note?:string){const c=this.context();const allowed:{[k:string]:string[]}={OPEN:['IN_PROGRESS'],IN_PROGRESS:['VERIFICATION'],EFFECTIVE:['CLOSED']};return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,status,branch_id AS "branchId",verification_result AS "verificationResult" FROM quality_capa_plans WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,id,c.tenantId,c.companyId,c.branchId);if(!rows.length)throw new NotFoundException('CAPA not found.');const current=rows[0];if(current.status===status)return{...current,duplicate:true};if(!(allowed[current.status]??[]).includes(status))throw new BadRequestException(`Invalid CAPA transition ${current.status} -> ${status}.`);const updated=await tx.$queryRawUnsafe<any[]>(`UPDATE quality_capa_plans SET status=$2,closed_at=CASE WHEN $2='CLOSED' THEN now() ELSE closed_at END,updated_by_user_id=$3::text,updated_at=now() WHERE id=$1::text RETURNING id,status,closed_at AS "closedAt"`,id,status,actorUserId);await tx.$executeRawUnsafe(`INSERT INTO quality_capa_events(capa_id,tenant_id,company_id,branch_id,event_type,from_status,to_status,actor_user_id,note) VALUES($1::text,$2::text,$3::text,$4::text,'STATUS_CHANGED',$5,$6,$7::text,$8)`,id,c.tenantId,c.companyId,current.branchId,current.status,status,actorUserId,note?.trim()||null);return{...updated[0],duplicate:false};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async verify(id:string,input:{effective:boolean;result:string},actorUserId:string){const result=input.result?.trim();if(!result)throw new BadRequestException('Verification result is required.');const c=this.context();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>(`SELECT id,status,branch_id AS "branchId" FROM quality_capa_plans WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,id,c.tenantId,c.companyId,c.branchId);if(!rows.length)throw new NotFoundException('CAPA not found.');if(rows[0].status!=='VERIFICATION')throw new BadRequestException('CAPA must be in VERIFICATION status.');const status=input.effective?'EFFECTIVE':'INEFFECTIVE';const updated=await tx.$queryRawUnsafe<any[]>(`UPDATE quality_capa_plans SET status=$2,verification_result=$3,verified_by_user_id=$4::text,verified_at=now(),updated_by_user_id=$4::text,updated_at=now() WHERE id=$1::text RETURNING id,status,verification_result AS "verificationResult",verified_at AS "verifiedAt"`,id,status,result,actorUserId);await tx.$executeRawUnsafe(`INSERT INTO quality_capa_events(capa_id,tenant_id,company_id,branch_id,event_type,from_status,to_status,actor_user_id,note) VALUES($1::text,$2::text,$3::text,$4::text,'VERIFIED','VERIFICATION',$5,$6::text,$7)`,id,c.tenantId,c.companyId,rows[0].branchId,status,actorUserId,result);return updated[0];},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
}
