"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

import { FinanceEmpty, FinanceMetric, FinancePanel } from "@/components/finance-view";
import { Alert, Button, Select, Spinner } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import { userErrorMessage } from "@/lib/user-language";

type CatalogItem={id:string;code:string;name?:string;title?:string;maxLevel?:number;requiresExpiry?:boolean};
type Catalogs={trainingCompetencies:CatalogItem[];hrCompetencies:CatalogItem[];courses:CatalogItem[];hrCertificationTypes:CatalogItem[]};
type CompetencyMapping={id:string;trainingCompetencyId:string;trainingCode:string;trainingName:string;hrCompetencyId:string;hrCode:string;hrName:string};
type CertificationMapping={id:string;courseId:string;courseCode:string;courseTitle:string;hrCertificationTypeId:string;hrCode:string;hrName:string};
type Mappings={competencies:CompetencyMapping[];certifications:CertificationMapping[]};
type SyncResult={claimed:number;competencySynced:number;certificationSynced:number;revokedSynced:number;skippedMissingExpiry:number};

export default function TrainingOperationsBridgePage(){
  const [catalogs,setCatalogs]=useState<Catalogs|null>(null);
  const [mappings,setMappings]=useState<Mappings>({competencies:[],certifications:[]});
  const [competencyForm,setCompetencyForm]=useState({trainingCompetencyId:"",hrCompetencyId:""});
  const [certificationForm,setCertificationForm]=useState({courseId:"",hrCertificationTypeId:""});
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [lastSync,setLastSync]=useState<SyncResult|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [c,m]=await Promise.all([api<Catalogs>("/training/operations-bridge/catalogs"),api<Mappings>("/training/operations-bridge/mappings")]);setCatalogs(c);setMappings(m);}catch(e){setError(e instanceof ApiError?userErrorMessage(e.message,"Operasyon yetki eşlemeleri yüklenemedi."):"Operasyon yetki eşlemeleri yüklenemedi.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const mappedCompetencies=useMemo(()=>new Set(mappings.competencies.map((x)=>x.trainingCompetencyId)),[mappings]);
  const mappedCourses=useMemo(()=>new Set(mappings.certifications.map((x)=>x.courseId)),[mappings]);
  async function act(job:()=>Promise<unknown>,message:string){setSaving(true);setError("");setSuccess("");try{await job();setSuccess(message);await load();}catch(e){setError(e instanceof ApiError?userErrorMessage(e.message,"İşlem tamamlanamadı."):"İşlem tamamlanamadı.");}finally{setSaving(false);}}
  async function mapCompetency(){if(!competencyForm.trainingCompetencyId||!competencyForm.hrCompetencyId)return;await act(()=>api("/training/operations-bridge/competencies",{method:"POST",body:competencyForm}),"Yetkinlik eşlemesi kaydedildi.");setCompetencyForm({trainingCompetencyId:"",hrCompetencyId:""});}
  async function mapCertification(){if(!certificationForm.courseId||!certificationForm.hrCertificationTypeId)return;await act(()=>api("/training/operations-bridge/certifications",{method:"POST",body:certificationForm}),"Sertifika eşlemesi kaydedildi.");setCertificationForm({courseId:"",hrCertificationTypeId:""});}
  async function sync(){setSaving(true);setError("");setSuccess("");try{const result=await api<SyncResult>("/training/operations-bridge/process?limit=500",{method:"POST"});setLastSync(result);setSuccess("Eğitim sonuçları operasyon yetkilendirme yapısına aktarıldı.");}catch(e){setError(e instanceof ApiError?userErrorMessage(e.message,"Yetki bilgileri güncellenemedi."):"Yetki bilgileri güncellenemedi.");}finally{setSaving(false);}}
  if(loading)return <div className="flex min-h-[420px] items-center justify-center rounded-[22px] border border-[var(--line)] bg-[var(--surface)]"><Spinner label="Operasyon yetkileri hazırlanıyor..."/></div>;
  return <div className="mx-auto max-w-[1500px] space-y-6 pb-10">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/training" className="text-[11px] font-semibold text-[var(--accent)] hover:underline">← Eğitim yönetimi</Link><p className="mt-4 text-[11px] font-semibold uppercase tracking-[0.15em] text-[var(--muted-soft)]">Eğitimden operasyon yetkisine</p><h1 className="mt-1 text-[32px] font-semibold tracking-[-0.045em] text-[var(--ink)]">Operasyon Yetkileri</h1><p className="mt-2 max-w-[900px] text-[13px] leading-6 text-[var(--muted)]">Eğitim sonuçlarını, hizmet sırasında kullanılan insan kaynakları yetkinlik ve sertifika kayıtlarıyla eşleştirin. Operasyon sistemi bu bilgilerle personelin hizmet uygunluğunu kontrol eder.</p></div><Button onClick={()=>void sync()} disabled={saving}>{saving?"Güncelleniyor...":"Yetkileri güncelle"}</Button></header>
    {error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}{success?<Alert tone="success" onClose={()=>setSuccess("")}>{success}</Alert>:null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><FinanceMetric label="Yetkinlik Eşlemesi" value={mappings.competencies.length} detail={`${catalogs?.trainingCompetencies.length??0} eğitim yetkinliği`} tone="info"/><FinanceMetric label="Sertifika Eşlemesi" value={mappings.certifications.length} detail={`${catalogs?.courses.length??0} aktif kurs`} tone="info"/><FinanceMetric label="Son yetkinlik aktarımı" value={lastSync?.competencySynced??0} detail="İnsan kaynakları yetkinlik değerlendirmesi" tone="success"/><FinanceMetric label="Son sertifika aktarımı" value={(lastSync?.certificationSynced??0)+(lastSync?.revokedSynced??0)} detail={lastSync?`${lastSync.revokedSynced} kaldırılan kayıt · ${lastSync.skippedMissingExpiry} süre bilgisi eksik`:"Henüz çalıştırılmadı"} tone="neutral"/></section>
    <div className="grid gap-6 xl:grid-cols-2">
      <FinancePanel title="Yetkinlik Eşlemesi" description="0–100 arasındaki eğitim puanını, insan kaynaklarındaki yetkinlik seviyesine karşılık gelecek şekilde eşleştirin."><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><label><span className="mb-1 block text-[10px] font-semibold uppercase text-[var(--muted-soft)]">Eğitim yetkinliği</span><Select value={competencyForm.trainingCompetencyId} onChange={(e)=>setCompetencyForm((v)=>({...v,trainingCompetencyId:e.target.value}))}><option value="">Seçin</option>{catalogs?.trainingCompetencies.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</Select></label><label><span className="mb-1 block text-[10px] font-semibold uppercase text-[var(--muted-soft)]">İnsan kaynakları yetkinliği</span><Select value={competencyForm.hrCompetencyId} onChange={(e)=>setCompetencyForm((v)=>({...v,hrCompetencyId:e.target.value}))}><option value="">Seçin</option>{catalogs?.hrCompetencies.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name} (L{x.maxLevel})</option>)}</Select></label><Button disabled={saving||!competencyForm.trainingCompetencyId||!competencyForm.hrCompetencyId} onClick={()=>void mapCompetency()}>Eşle</Button></div><div className="mt-5 space-y-2">{!mappings.competencies.length?<FinanceEmpty title="Yetkinlik eşlemesi yok" description="Operasyon yetkileri için gereken eğitim yetkinliklerini insan kaynaklarındaki karşılıklarıyla eşleştirin."/>:mappings.competencies.map((m)=><div key={m.id} className="flex items-center justify-between rounded-[14px] border border-[var(--line)] bg-[var(--surface-2)] px-3 py-2 text-[12px]"><span className="font-medium text-[var(--ink)]">{m.trainingCode} · {m.trainingName}</span><span className="text-[var(--muted)]">→ {m.hrCode} · {m.hrName}</span></div>)}</div>{catalogs?.trainingCompetencies.some((x)=>!mappedCompetencies.has(x.id))?null:<p className="mt-3 text-[11px] text-[var(--success)]">Aktif eğitim yetkinliklerinin tamamı eşleştirilmiş.</p>}</FinancePanel>
      <FinancePanel title="Sertifika Eşlemesi" description="Tamamlanan eğitimlerden kazanılan sertifikaları, operasyonlarda kullanılan personel sertifika türleriyle eşleştirin."><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><label><span className="mb-1 block text-[10px] font-semibold uppercase text-[var(--muted-soft)]">Eğitim kursu</span><Select value={certificationForm.courseId} onChange={(e)=>setCertificationForm((v)=>({...v,courseId:e.target.value}))}><option value="">Seçin</option>{catalogs?.courses.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.title}</option>)}</Select></label><label><span className="mb-1 block text-[10px] font-semibold uppercase text-[var(--muted-soft)]">İnsan kaynakları sertifika türü</span><Select value={certificationForm.hrCertificationTypeId} onChange={(e)=>setCertificationForm((v)=>({...v,hrCertificationTypeId:e.target.value}))}><option value="">Seçin</option>{catalogs?.hrCertificationTypes.map((x)=><option key={x.id} value={x.id}>{x.code} · {x.name}{x.requiresExpiry?" · süre zorunlu":""}</option>)}</Select></label><Button disabled={saving||!certificationForm.courseId||!certificationForm.hrCertificationTypeId} onClick={()=>void mapCertification()}>Eşle</Button></div><div className="mt-5 space-y-2">{!mappings.certifications.length?<FinanceEmpty title="Sertifika eşlemesi yok" description="Hizmet sunumu için gereken sertifika türlerini eğitim kurslarıyla eşleştirin."/>:mappings.certifications.map((m)=><div key={m.id} className="flex items-center justify-between rounded-[14px] border border-[var(--line)] bg-[var(--surface-2)] px-3 py-2 text-[12px]"><span className="font-medium text-[var(--ink)]">{m.courseCode} · {m.courseTitle}</span><span className="text-[var(--muted)]">→ {m.hrCode} · {m.hrName}</span></div>)}</div>{catalogs?.courses.some((x)=>!mappedCourses.has(x.id))?null:<p className="mt-3 text-[11px] text-[var(--success)]">Aktif kursların tamamı sertifika eşlemesine dahil edilmiş.</p>}</FinancePanel>
    </div>
  </div>;
}
