"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Modal } from "@/components/modal";
import { LeadContextFields,contextPayload,emptyLeadContext,type CommercialOptions } from "@/components/crm/lead-context-fields";
import { Alert,Button,EmptyState,Field,PageHeader,Select,Spinner,TextArea,TextInput } from "@/components/ui";
import { useToast } from "@/components/toast";
import { api, ApiError } from "@/lib/api";
import { hasActiveBranch, hasPermission } from "@/lib/auth";
import { leadSourceLabels,leadStatusLabels,type CrmAssignee,type CrmLead,type LeadStatus } from "@/lib/crm-types";

const emptyLead={firstName:"",lastName:"",phone:"",email:"",source:"MANUAL",interestNote:"",ownerUserId:""};
const emptyOpportunity={title:"",estimatedValue:"",probability:"25",expectedCloseDate:"",ownerUserId:""};
const statuses:Array<LeadStatus|"ALL">=["ALL","NEW","CONTACTED","QUALIFIED","CONVERTED","LOST"];
function formatDate(value:string){return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value));}
function initials(lead:CrmLead){return `${lead.firstName[0]??""}${lead.lastName[0]??""}`.toUpperCase();}

export default function CrmLeadsPage(){
 const canManage=hasPermission("crm","manage"),{showToast}=useToast();
 const [leads,setLeads]=useState<CrmLead[]>([]),[assignees,setAssignees]=useState<CrmAssignee[]>([]),[commercialOptions,setCommercialOptions]=useState<CommercialOptions>(),[search,setSearch]=useState(""),[status,setStatus]=useState<LeadStatus|"ALL">("ALL"),[ownerUserId,setOwnerUserId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[formError,setFormError]=useState(""),[createOpen,setCreateOpen]=useState(false),[qualifying,setQualifying]=useState<CrmLead|null>(null),[leadForm,setLeadForm]=useState(emptyLead),[leadContext,setLeadContext]=useState(emptyLeadContext),[opportunityForm,setOpportunityForm]=useState(emptyOpportunity);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({limit:"200"});if(status!=="ALL")params.set("status",status);if(ownerUserId)params.set("ownerUserId",ownerUserId);if(search.trim())params.set("search",search.trim());setLeads(await api<CrmLead[]>(`/crm/leads?${params}`));}catch(e){setError(e instanceof ApiError?e.message:"Potansiyel Müşteri Listesi Yüklenemedi.");}finally{setLoading(false);}},[ownerUserId,search,status]);
 useEffect(()=>{const timeout=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timeout);},[load]);
 useEffect(()=>{void Promise.all([api<CrmAssignee[]>("/crm/assignees"),api<CommercialOptions>("/crm/commercial-options")]).then(([people,options])=>{setAssignees(people);setCommercialOptions(options);}).catch(e=>setError(e instanceof ApiError?e.message:"CRM Form Seçenekleri Yüklenemedi."));},[]);
 function requireActiveBranch(message:string){if(hasActiveBranch())return true;showToast(message,"error");return false;}
 function openCreate(){if(!requireActiveBranch("Yeni Potansiyel Müşteri Oluşturmak İçin Önce Çalışma Kapsamından Bir Şube Seçin."))return;setFormError("");setCreateOpen(true);}
 useEffect(()=>{if(new URLSearchParams(window.location.search).get("new")==="1"&&canManage)openCreate();},[canManage]);
 const counts=useMemo(()=>({total:leads.length,actionable:leads.filter(l=>["NEW","CONTACTED"].includes(l.status)).length,qualified:leads.filter(l=>l.status==="QUALIFIED").length}),[leads]);
 const assigneeNames=useMemo(()=>new Map(assignees.map(p=>[p.id,`${p.firstName} ${p.lastName}`])),[assignees]);
 async function createLead(event:FormEvent){event.preventDefault();setFormError("");if(!requireActiveBranch("Potansiyel Müşteri Oluşturmak İçin Önce Çalışma Kapsamından Bir Şube Seçin."))return;if(!leadForm.firstName.trim()||!leadForm.lastName.trim()||(!leadForm.phone.trim()&&!leadForm.email.trim()&&!leadContext.alternativePhone.trim())){setFormError("Ad, Soyad Ve En Az Bir İletişim Bilgisi Gereklidir.");return;}setSaving(true);try{await api("/crm/leads",{method:"POST",body:{firstName:leadForm.firstName.trim(),lastName:leadForm.lastName.trim(),source:leadForm.source,...(leadForm.phone.trim()?{phone:leadForm.phone.trim()}:{}),...(leadForm.email.trim()?{email:leadForm.email.trim()}:{}),...(leadForm.interestNote.trim()?{interestNote:leadForm.interestNote.trim()}:{}),...(leadForm.ownerUserId?{ownerUserId:leadForm.ownerUserId}:{}),...contextPayload(leadContext)}});setCreateOpen(false);setLeadForm(emptyLead);setLeadContext(emptyLeadContext);showToast("Potansiyel Müşteri Oluşturuldu.","success");await load();}catch(e){setFormError(e instanceof ApiError?e.message:"Potansiyel Müşteri Oluşturulamadı.");}finally{setSaving(false);}}
 async function qualifyLead(event:FormEvent){event.preventDefault();if(!qualifying)return;setFormError("");if(!requireActiveBranch("Satış Fırsatı Oluşturmak İçin Önce Çalışma Kapsamından Bir Şube Seçin."))return;if(!opportunityForm.title.trim()){setFormError("Satış Fırsatı Başlığı Gereklidir.");return;}setSaving(true);try{await api(`/crm/leads/${qualifying.id}/qualify`,{method:"POST",body:{version:qualifying.version,title:opportunityForm.title.trim(),probability:Number(opportunityForm.probability),...(opportunityForm.estimatedValue?{estimatedValue:Number(opportunityForm.estimatedValue)}:{}),...(opportunityForm.expectedCloseDate?{expectedCloseDate:opportunityForm.expectedCloseDate}:{}),...(opportunityForm.ownerUserId?{ownerUserId:opportunityForm.ownerUserId}:{})}});setQualifying(null);setOpportunityForm(emptyOpportunity);showToast("Potansiyel Müşteri Satış Fırsatına Dönüştürüldü.","success");await load();}catch(e){setFormError(e instanceof ApiError?e.message:"Potansiyel Müşteri Nitelendirilemedi.");}finally{setSaving(false);}}
 return <div className="space-y-6">
  <PageHeader title="Potansiyel Müşteri Havuzu" description="Yeni Müşteri Adaylarını Kaydedin, Temas Durumunu İzleyin Ve Uygun Adayları Satış Fırsatına Dönüştürün." action={canManage?<Button onClick={openCreate}>+ Yeni Potansiyel Müşteri</Button>:undefined}/>{error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}
  <section className="grid gap-3 sm:grid-cols-3">{[["Görünen Potansiyel Müşteri",counts.total],["İşlem Bekleyen",counts.actionable],["Nitelikli",counts.qualified]].map(([label,value])=><article key={String(label)} className="rounded-[18px] border border-[var(--line)] bg-white px-4 py-3 shadow-[var(--shadow-soft)]"><span className="text-[10px] text-[var(--muted)]">{label}</span><strong className="ml-3 text-[20px]">{value}</strong></article>)}</section>
  <section className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-white shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-3 border-b border-[var(--line)] p-4 sm:flex-row"><TextInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ad, Telefon Veya E-Posta Ara" aria-label="Potansiyel Müşteri Ara" className="sm:max-w-sm"/><Select value={status} onChange={e=>setStatus(e.target.value as LeadStatus|"ALL")} aria-label="Duruma Göre Filtrele" className="sm:max-w-[210px]">{statuses.map(item=><option key={item} value={item}>{item==="ALL"?"Tüm Durumlar":leadStatusLabels[item]}</option>)}</Select><Select value={ownerUserId} onChange={e=>setOwnerUserId(e.target.value)} aria-label="Sorumluya Göre Filtrele" className="sm:max-w-[220px]"><option value="">Tüm Sorumlular</option>{assignees.map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</Select></div>
  {loading?<Spinner label="Potansiyel Müşteriler Yükleniyor..."/>:leads.length?<div className="divide-y divide-[var(--line)]">{leads.map(lead=><div key={lead.id} className="grid gap-3 px-4 py-4 transition-colors hover:bg-[#f8fcfd] md:grid-cols-[minmax(220px,1.3fr)_minmax(150px,1fr)_130px_120px_auto] md:items-center"><Link href={`/crm/leads/${lead.id}`} className="flex min-w-0 items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#EAF5FB] text-[11px] font-bold text-[#1674BD]">{initials(lead)}</span><span className="min-w-0"><strong className="block truncate text-[13px]">{lead.firstName} {lead.lastName}</strong><small className="mt-1 block truncate text-[10px] text-[var(--muted)]">{lead.phone||lead.email}</small></span></Link><span className="min-w-0 text-[11px] text-[var(--muted)]"><span className="block truncate">{leadSourceLabels[lead.source]??lead.source}</span><small className="mt-1 block truncate text-[9px] text-[var(--muted-soft)]">{lead.ownerUserId?(assigneeNames.get(lead.ownerUserId)??"Atanmış Kullanıcı"):"Sorumlu Yok"}</small></span><span className="w-fit rounded-full bg-[#EAF5FB] px-2.5 py-1 text-[10px] font-semibold text-[#1674BD]">{leadStatusLabels[lead.status]}</span><time className="text-[10px] text-[var(--muted)]">{formatDate(lead.updatedAt)}</time>{canManage&&["NEW","CONTACTED"].includes(lead.status)&&!lead.opportunityId?<Button variant="secondary" className="min-h-8 px-3 py-1.5 text-[11px]" onClick={()=>{if(!requireActiveBranch("Potansiyel Müşteriyi Nitelendirmek İçin Önce Çalışma Kapsamından Bir Şube Seçin."))return;setFormError("");setOpportunityForm({...emptyOpportunity,title:`${lead.firstName} ${lead.lastName} Satış Fırsatı`});setQualifying(lead);}}>Nitelendir</Button>:<Link href={`/crm/leads/${lead.id}`} className="text-[11px] font-semibold text-[#1674BD]">Detay →</Link>}</div>)}</div>:<EmptyState title="Potansiyel Müşteri Bulunamadı" description="Arama Ve Filtreleri Değiştirin Veya Yeni Bir Potansiyel Müşteri Oluşturun."/>}</section>
  <Modal open={createOpen} onClose={()=>setCreateOpen(false)} title="Yeni Potansiyel Müşteri" description="İletişim, edinim, ticari niyet ve satış sınıflandırmasını tek kayıtta oluşturun."><form onSubmit={createLead} className="space-y-5">{formError?<Alert>{formError}</Alert>:null}<div className="grid gap-4 sm:grid-cols-2"><Field label="Ad" required><TextInput value={leadForm.firstName} onChange={e=>setLeadForm({...leadForm,firstName:e.target.value})}/></Field><Field label="Soyad" required><TextInput value={leadForm.lastName} onChange={e=>setLeadForm({...leadForm,lastName:e.target.value})}/></Field><Field label="Telefon"><TextInput value={leadForm.phone} onChange={e=>setLeadForm({...leadForm,phone:e.target.value})}/></Field><Field label="E-Posta"><TextInput type="email" value={leadForm.email} onChange={e=>setLeadForm({...leadForm,email:e.target.value})}/></Field><Field label="Kaynak"><Select value={leadForm.source} onChange={e=>setLeadForm({...leadForm,source:e.target.value})}>{Object.entries(leadSourceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field><Field label="Sorumlu"><Select value={leadForm.ownerUserId} onChange={e=>setLeadForm({...leadForm,ownerUserId:e.target.value})}><option value="">Oluşturan Kullanıcı</option>{assignees.map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</Select></Field></div><Field label="İlgi / İhtiyaç Notu"><TextArea rows={3} value={leadForm.interestNote} onChange={e=>setLeadForm({...leadForm,interestNote:e.target.value})}/></Field><LeadContextFields value={leadContext} onChange={setLeadContext} commercialOptions={commercialOptions}/><div className="flex justify-end gap-3"><Button variant="secondary" onClick={()=>setCreateOpen(false)} disabled={saving}>Vazgeç</Button><Button type="submit" disabled={saving}>{saving?"Kaydediliyor...":"Potansiyel Müşteri Oluştur"}</Button></div></form></Modal>
  <Modal open={Boolean(qualifying)} onClose={()=>setQualifying(null)} title="Satış Fırsatı Oluştur" description="Potansiyel Müşteriyi Nitelikli Hale Getirip Satış Sürecine Ekleyin."><form onSubmit={qualifyLead} className="space-y-4">{formError?<Alert>{formError}</Alert>:null}<Field label="Satış Fırsatı Başlığı" required><TextInput value={opportunityForm.title} onChange={e=>setOpportunityForm({...opportunityForm,title:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Tahmini Değer"><TextInput type="number" min="0" value={opportunityForm.estimatedValue} onChange={e=>setOpportunityForm({...opportunityForm,estimatedValue:e.target.value})}/></Field><Field label="Olasılık (%)"><TextInput type="number" min="0" max="100" value={opportunityForm.probability} onChange={e=>setOpportunityForm({...opportunityForm,probability:e.target.value})}/></Field></div><Field label="Beklenen Kapanış"><TextInput type="date" value={opportunityForm.expectedCloseDate} onChange={e=>setOpportunityForm({...opportunityForm,expectedCloseDate:e.target.value})}/></Field><Field label="Satış Fırsatı Sorumlusu"><Select value={opportunityForm.ownerUserId} onChange={e=>setOpportunityForm({...opportunityForm,ownerUserId:e.target.value})}><option value="">Potansiyel Müşteri Sorumlusunu Kullan</option>{assignees.map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</Select></Field><div className="flex justify-end gap-3"><Button variant="secondary" onClick={()=>setQualifying(null)} disabled={saving}>Vazgeç</Button><Button type="submit" disabled={saving}>{saving?"Dönüştürülüyor...":"Satış Sürecine Ekle"}</Button></div></form></Modal>
 </div>;
}
