"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { Alert,Button,Field,PageHeader,Select,TextArea,TextInput } from "@/components/ui";
import { LeadContextFields,contextPayload,emptyLeadContext,type LeadContextForm } from "@/components/crm/lead-context-fields";
import { api,ApiError } from "@/lib/api";
import { hasActiveBranch } from "@/lib/auth";
import { leadSourceLabels,type CrmAssignee,type CrmLead } from "@/lib/crm-types";
const empty={firstName:"",lastName:"",phone:"",email:"",source:"MANUAL",interestNote:"",ownerUserId:""};
export default function NewCrmLeadPage(){const router=useRouter();const [form,setForm]=useState(empty),[context,setContext]=useState<LeadContextForm>(emptyLeadContext),[assignees,setAssignees]=useState<CrmAssignee[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState("");useEffect(()=>{void api<CrmAssignee[]>("/crm/assignees").then(setAssignees).catch(()=>{});},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(!hasActiveBranch()){setError("Yeni potansiyel müşteri oluşturmak için aktif bir şube seçin.");return;}if(!form.firstName.trim()||!form.lastName.trim()||(!form.phone.trim()&&!form.email.trim()&&!context.alternativePhone.trim())){setError("Ad, soyad ve en az bir iletişim bilgisi gereklidir.");return;}setSaving(true);try{const lead=await api<CrmLead>("/crm/leads",{method:"POST",body:{firstName:form.firstName.trim(),lastName:form.lastName.trim(),source:form.source,...(form.phone.trim()?{phone:form.phone.trim()}:{}),...(form.email.trim()?{email:form.email.trim()}:{}),...(form.interestNote.trim()?{interestNote:form.interestNote.trim()}:{}),...(form.ownerUserId?{ownerUserId:form.ownerUserId}:{}),...contextPayload(context)}});router.push(`/crm/leads/${lead.id}`);}catch(err){setError(err instanceof ApiError?err.message:"Potansiyel müşteri oluşturulamadı.");}finally{setSaving(false);}}
 return <div className="space-y-6"><Link href="/crm/leads" className="text-[11px] font-semibold text-[#1674BD]">← Potansiyel Müşteri Havuzuna Dön</Link><PageHeader title="Yeni Potansiyel Müşteri" description="İletişim, edinim, kampanya, ticari niyet ve satış sınıflandırmasını tek kayıtta oluşturun."/><form onSubmit={submit} className="space-y-6"><section className="rounded-[22px] border border-[var(--line)] bg-white p-5 shadow-[var(--shadow-soft)] space-y-4">{error?<Alert>{error}</Alert>:null}<h2 className="text-[13px] font-semibold">Temel Bilgiler</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Ad" required><TextInput value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></Field><Field label="Soyad" required><TextInput value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></Field><Field label="Telefon"><TextInput value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="E-Posta"><TextInput type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Kaynak"><Select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}>{Object.entries(leadSourceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field><Field label="Sorumlu"><Select value={form.ownerUserId} onChange={e=>setForm({...form,ownerUserId:e.target.value})}><option value="">Oluşturan Kullanıcı</option>{assignees.map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</Select></Field></div><Field label="İlgi / İhtiyaç Notu"><TextArea rows={3} value={form.interestNote} onChange={e=>setForm({...form,interestNote:e.target.value})}/></Field></section><section className="rounded-[22px] border border-[var(--line)] bg-white p-5 shadow-[var(--shadow-soft)]"><LeadContextFields value={context} onChange={setContext}/></section><div className="flex justify-end gap-3"><Link href="/crm/leads"><Button variant="secondary" type="button">Vazgeç</Button></Link><Button type="submit" disabled={saving}>{saving?"Kaydediliyor...":"Potansiyel Müşteri Oluştur"}</Button></div></form></div>}
