"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {api,ApiError} from "@/lib/api";
import {GlassCard,Button,Alert,Spinner} from "@/components/ui";
const cfg:any={employees:{title:'Çalışanlar',get:'/hr/employees',post:'/staff',fields:['firstName','lastName','phone','email','personnelNumber','position','department','employmentType','hireDate','salary','iban','bankName']},'personnel-files':{title:'Özlük Dosyaları',get:'/hr/personnel-files',fields:['firstName','lastName','identityNumber','department','position','hireDate','salary','iban','bankName']},attendance:{title:'Puantaj',get:'/hr/attendance',post:'/hr/attendance',fields:['staffId','workDate','checkIn','checkOut','breakMinutes','workedMinutes','overtimeMinutes','status','note']},leaves:{title:'İzinler',get:'/hr/leaves',post:'/hr/leaves',fields:['staffId','type','startDate','endDate','days','status','reason']},payroll:{title:'Bordro',get:'/hr/payroll',post:'/hr/payroll/periods',fields:['year','month']},payments:{title:'Maaş Ödemeleri',get:'/hr/payments',post:'/hr/payments',fields:['staffId','year','month','amount','method','status','paidAt','note']},sgk:{title:'SGK İşlemleri',get:'/hr/sgk',post:'/hr/sgk',fields:['staffId','year','month','status','documentNo','recordDate','note']}};
const label:any={firstName:'Ad',lastName:'Soyad',phone:'Telefon',email:'E-posta',personnelNumber:'Sicil No',identityNumber:'T.C. Kimlik No',position:'Pozisyon',department:'Departman',employmentType:'Çalışma Tipi',hireDate:'İşe Giriş',salary:'Brüt Maaş',iban:'IBAN',bankName:'Banka',staffId:'Personel',workDate:'Tarih',checkIn:'Giriş',checkOut:'Çıkış',breakMinutes:'Mola dk',workedMinutes:'Çalışma dk',overtimeMinutes:'Fazla mesai dk',status:'Durum',note:'Not',type:'İzin türü',startDate:'Başlangıç',endDate:'Bitiş',days:'Gün',reason:'Açıklama',year:'Yıl',month:'Ay',amount:'Tutar',method:'Yöntem',paidAt:'Ödeme tarihi',documentNo:'Belge no',recordDate:'Kayıt tarihi'};
const dateFields=new Set(['hireDate','workDate','startDate','endDate','paidAt','recordDate']);const numFields=new Set(['salary','breakMinutes','workedMinutes','overtimeMinutes','days','year','month','amount']);
function v(x:any){if(x===null||x===undefined||x==='')return'—';if(typeof x==='string'&&x.includes('T'))return new Date(x).toLocaleDateString('tr-TR');return String(x)}
export default function HRSection(){const p=useParams<{section:string}>(),section=p.section,c=cfg[section];const[rows,setRows]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[form,setForm]=useState<any>({}),[edit,setEdit]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
const load=async()=>{if(!c)return;setLoading(true);try{const r=await api<any>(c.get);setRows(Array.isArray(r)?r:r?.data??[]);if(section!=='employees'&&section!=='personnel-files'){const s=await api<any>('/hr/employees');setStaff(Array.isArray(s)?s:s?.data??[])}else setStaff(Array.isArray(r)?r:r?.data??[])}catch(e){setError(e instanceof ApiError?e.message:'Veri yüklenemedi.')}finally{setLoading(false)}};useEffect(()=>{void load()},[section]);
const save=async()=>{try{let body={...form};if(section==='employees'){const profile:any={};for(const k of ['personnelNumber','identityNumber','position','department','employmentType','hireDate','salary','iban','bankName'])if(body[k]!==undefined&&body[k]!=='')profile[k]=numFields.has(k)?Number(body[k]):body[k];body={firstName:body.firstName,lastName:body.lastName,phone:body.phone||undefined,email:body.email||undefined,profile};}else if(numFields.size)for(const k of Object.keys(body))if(numFields.has(k)&&body[k]!=='')body[k]=Number(body[k]);await api(edit?`${c.get}/${edit.id}`:c.post,{method:edit?'PATCH':'POST',body});setForm({});setEdit(null);await load()}catch(e){setError(e instanceof ApiError?e.message:'Kayıt kaydedilemedi.')}};
const remove=async(id:string)=>{if(!confirm('Kaydı sil/arşivle?'))return;try{await api(`${c.get}/${id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof ApiError?e.message:'Silme başarısız.')}};
if(!c)return <GlassCard>İK sayfası bulunamadı.</GlassCard>;return <div className="mx-auto max-w-[1280px] space-y-5 pb-10"><div><p className="text-[11px] uppercase tracking-[.15em] text-[var(--muted)]">İnsan Kaynakları</p><h1 className="text-[30px] font-semibold">{c.title}</h1><p className="text-xs text-[var(--muted)]">Veritabanına bağlı gerçek kayıt ekranı.</p></div>{error&&<Alert onClose={()=>setError('')}>{error}</Alert>}{c.post&&<GlassCard><div className="grid gap-3 md:grid-cols-4">{c.fields.map((f:string)=><div key={f}><label className="mb-1 block text-[10px] text-[var(--muted)]">{label[f]||f}</label>{f==='staffId'?<select className="w-full rounded-lg border p-2 text-xs" value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}><option value="">Personel seç</option>{staff.map(s=><option key={s.id} value={s.id}>{s.firstName} {s.lastName}</option>)}</select>:<input className="w-full rounded-lg border p-2 text-xs" type={dateFields.has(f)?'date':numFields.has(f)?'number':'text'} value={form[f]??''} onChange={e=>setForm({...form,[f]:e.target.value})}/>}</div>)}<div className="flex items-end gap-2"><Button onClick={save}>{edit?'Güncelle':'Kaydet'}</Button>{edit&&<Button variant="secondary" onClick={()=>{setEdit(null);setForm({})}}>İptal</Button>}</div></div></GlassCard>}{loading?<GlassCard className="flex h-56 items-center justify-center"><Spinner/></GlassCard>:<GlassCard className="!overflow-hidden !p-0"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b bg-[#faf9fc]">{(c.fields.slice(0,7)).map((f:string)=><th key={f} className="p-4">{label[f]||f}</th>)}<th className="p-4">İşlem</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id||JSON.stringify(r)} className="border-b last:border-0">{c.fields.slice(0,7).map((f:string)=><td key={f} className="p-4">{v(r[f])}</td>)}<td className="p-4"><div className="flex gap-3">{c.post&&(section==='employees'||section==='leaves')&&r.id&&<><button className="text-[#7657e8]" onClick={()=>{setEdit(r);setForm(r)}}>Düzenle</button><button className="text-red-500" onClick={()=>remove(r.id)}>Sil</button></>}</div></td></tr>)}</tbody></table>{rows.length===0&&<div className="p-10 text-center text-xs text-[var(--muted)]">Henüz kayıt yok.</div>}</div></GlassCard>}</div>}
