"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { DataView, DataViewMeta } from "@/components/data-view";
import { DatePicker } from "@/components/date-picker";
import { FormActions, FormGrid, FormSection, FormSubmitButton } from "@/components/form-system";
import { Alert, Button, Spinner } from "@/components/ui";
import { ValooSelect } from "@/components/valoo-controls";
import { api, ApiError, withQuery } from "@/lib/api";
import { hasPermission } from "@/lib/auth";
import { userLabel } from "@/lib/user-language";
type SectionKey="employees"|"personnel-files"|"attendance"|"leaves"|"payroll"|"payments"|"sgk"; type SectionConfig={title:string;get:string;post?:string;fields:readonly string[]}; type DataRow=Record<string,unknown>&{id?:string}; type StaffRow=DataRow&{id:string;firstName?:string;lastName?:string}; type FormState=Record<string,string|number|undefined>;
const SECTION_CONFIG:Record<SectionKey,SectionConfig>={employees:{title:"Çalışanlar",get:"/hr/employees",post:"/hr/employees",fields:["firstName","lastName","phone","email","personnelNumber","position","department","employmentType","hireDate","grossSalary","iban","bankName"]},"personnel-files":{title:"Özlük Dosyaları",get:"/hr/personnel-files",fields:["firstName","lastName","identityNumber","department","position","hireDate","salary","iban","bankName"]},attendance:{title:"Puantaj",get:"/hr/attendance",post:"/hr/attendance",fields:["staffId","workDate","checkIn","checkOut","breakMinutes","workedMinutes","overtimeMinutes","status","note"]},leaves:{title:"İzinler",get:"/hr/leaves",post:"/hr/leaves",fields:["staffId","type","startDate","endDate","days","status","reason"]},payroll:{title:"Bordro",get:"/hr/payroll",post:"/hr/payroll/periods",fields:["year","month"]},payments:{title:"Maaş Ödemeleri",get:"/hr/payments",post:"/hr/payments",fields:["staffId","year","month","amount","method","status","paidAt","note"]},sgk:{title:"SGK İşlemleri",get:"/hr/sgk",post:"/hr/sgk",fields:["staffId","year","month","status","documentNo","recordDate","note"]}};
const FIELD_LABELS:Record<string,string>={firstName:"Ad",lastName:"Soyad",phone:"Telefon",email:"E-posta",personnelNumber:"Sicil No",identityNumber:"T.C. Kimlik No",position:"Pozisyon",department:"Departman",employmentType:"Çalışma tipi",hireDate:"İşe giriş",salary:"Brüt maaş",grossSalary:"Brüt maaş",iban:"IBAN",bankName:"Banka",staffId:"Personel",workDate:"Tarih",checkIn:"Giriş",checkOut:"Çıkış",breakMinutes:"Mola süresi (dk)",workedMinutes:"Çalışma süresi (dk)",overtimeMinutes:"Fazla mesai (dk)",status:"Durum",note:"Not",type:"İzin türü",startDate:"Başlangıç",endDate:"Bitiş",days:"Gün",reason:"Açıklama",year:"Yıl",month:"Ay",amount:"Tutar",method:"Yöntem",paidAt:"Ödeme tarihi",documentNo:"Belge no",recordDate:"Kayıt tarihi"};
const DATE_FIELDS=new Set(["hireDate","workDate","startDate","endDate","paidAt","recordDate"]),NUMBER_FIELDS=new Set(["salary","grossSalary","breakMinutes","workedMinutes","overtimeMinutes","days","year","month","amount"]); const SELECT_VALUES:Record<string,readonly string[]>={status:["PENDING","APPROVED","PAID","PRESENT","ABSENT","DRAFT"],type:["ANNUAL","SICK","EXCUSE","UNPAID","OTHER"],method:["BANK","CASH"]}; const PERIOD_SECTIONS=new Set<SectionKey>(["attendance","payroll","payments","sgk"]),EDITABLE_SECTIONS=new Set<SectionKey>(["employees","attendance","leaves"]),SENSITIVE_SECTIONS=new Set<SectionKey>(["personnel-files","payroll","payments","sgk"]),SENSITIVE_EMPLOYEE_FIELDS=new Set(["grossSalary","iban","bankName"]);
export default function HRSection(){const params=useParams<{section:string}>(),section=isSectionKey(params.section)?params.section:null,config=section?SECTION_CONFIG[section]:null,now=new Date();const[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1),[rows,setRows]=useState<DataRow[]>([]),[staff,setStaff]=useState<StaffRow[]>([]),[form,setForm]=useState<FormState>({year:now.getFullYear(),month:now.getMonth()+1}),[edit,setEdit]=useState<DataRow|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[canReadSensitive,setCanReadSensitive]=useState(false);useEffect(()=>{setCanReadSensitive(hasPermission("hr_sensitive","read"))},[]);
const load=useCallback(async()=>{if(!section||!config)return;if(SENSITIVE_SECTIONS.has(section)&&!canReadSensitive){setRows([]);setStaff([]);setLoading(false);return}setLoading(true);setError("");try{const baseGet=section==="personnel-files"?"/hr/personnel-files/sensitive":config.get,response=await api<unknown>(PERIOD_SECTIONS.has(section)?withQuery(baseGet,{year,month}):baseGet),nextRows=rowsFromResponse(response);setRows(nextRows);if(section!=="employees"&&section!=="personnel-files"){const employees=await api<unknown>("/hr/employees");setStaff(rowsFromResponse(employees).filter(isStaffRow))}else setStaff(nextRows.filter(isStaffRow))}catch(e){setError(e instanceof ApiError?e.message:"İK verileri yüklenemedi.")}finally{setLoading(false)}},[section,config,canReadSensitive,year,month]); useEffect(()=>{void load()},[load]); const visibleFields=useMemo(()=>config?.fields.filter(f=>canReadSensitive||!SENSITIVE_EMPLOYEE_FIELDS.has(f)).slice(0,8)??[],[config,canReadSensitive]),formFields=useMemo(()=>config?.fields.filter(f=>canReadSensitive||!SENSITIVE_EMPLOYEE_FIELDS.has(f))??[],[config,canReadSensitive]),editable=section?EDITABLE_SECTIONS.has(section):false;
function updateField(field:string,value:string){setForm(c=>({...c,[field]:value}))} async function save(){if(!section||!config?.post)return;if(SENSITIVE_SECTIONS.has(section)&&!canReadSensitive){setError("Bu işlem hassas İK verisi yetkisi gerektirir.");return}setSaving(true);setError("");try{const patch=Boolean(edit&&section!=="attendance"),endpoint=patch&&edit?.id?`${config.get}/${edit.id}`:config.post;await api(endpoint,{method:patch?"PATCH":"POST",body:normalizeForm(section,form,canReadSensitive)});setForm({year,month});setEdit(null);await load()}catch(e){setError(e instanceof ApiError?e.message:"Kayıt kaydedilemedi.")}finally{setSaving(false)}} function startEdit(row:DataRow){setEdit(row);const n:FormState={year,month};for(const[k,v]of Object.entries(row))if(typeof v==="string"||typeof v==="number")n[k]=v;setForm(n);window.scrollTo({top:0,behavior:"smooth"})} function resetEdit(){setEdit(null);setForm({year,month})} async function remove(id:string){if(!config||!id||!window.confirm("Bu kayıt silinsin veya arşivlensin mi?"))return;try{await api(`${config.get}/${id}`,{method:"DELETE"});await load()}catch(e){setError(e instanceof ApiError?e.message:"Silme işlemi başarısız.")}}
if(!section||!config)return <div className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-8 text-[13px] text-[var(--muted)]">İK sayfası bulunamadı.</div>;
if(SENSITIVE_SECTIONS.has(section)&&!canReadSensitive)return <div className="mx-auto max-w-[900px] py-8"><section className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-8"><p className="text-[11px] font-semibold uppercase tracking-[.15em] text-[var(--muted-soft)]">İnsan Kaynakları · Korumalı Alan</p><h1 className="mt-2 text-2xl font-semibold text-[var(--ink)]">{config.title}</h1><p className="mt-3 max-w-2xl text-xs leading-6 text-[var(--muted)]">Bu bölüm kimlik, özlük, bordro, maaş, banka veya SGK gibi hassas personel verileri içerir. Görüntülemek için <strong>hassas İK verilerini görüntüleme yetkisi</strong> gerekir.</p><Link href="/hr/employees" className="mt-5 inline-block text-xs font-semibold text-[var(--accent)]">Çalışanlara dön →</Link></section></div>;
return <div className="mx-auto max-w-[1280px] space-y-5 pb-10"><header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.15em] text-[var(--muted-soft)]">İnsan kaynakları ve özlük</p><h1 className="mt-1 text-[30px] font-semibold tracking-[-.035em] text-[var(--ink)]">{config.title}</h1><p className="mt-1 text-xs text-[var(--muted)]">Personel kayıtlarını görüntüleyin ve yönetin.</p></div>{PERIOD_SECTIONS.has(section)?<div className="flex gap-2"><input className="control h-10 w-24" type="number" value={year} aria-label="Yıl" onChange={e=>setYear(Number(e.target.value))}/><ValooSelect className="min-w-[140px]" value={String(month)} ariaLabel="Ay" searchable={false} onChange={(value)=>setMonth(Number(value))} options={Array.from({length:12},(_,i)=>({value:String(i+1),label:`${i+1}. Ay`}))}/></div>:null}</header>{error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}
{config.post?<section className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><FormSection title={edit?"Kaydı güncelle":"Yeni kayıt"} description="Alanları doldurun ve kaydedin. Hassas personel ve bordro verileri yalnızca yetkili İK rolleri tarafından görüntülenebilir."><FormGrid columns={3} className="xl:grid-cols-4">{formFields.map(field=><DynamicField key={field} field={field} value={form[field]??""} staff={staff} onChange={v=>updateField(field,v)}/>)}</FormGrid></FormSection><FormActions>{edit?<Button type="button" variant="secondary" onClick={resetEdit} disabled={saving}>İptal</Button>:null}<FormSubmitButton type="button" saving={saving} idleLabel={edit?"Güncelle":"Kaydet"} savingLabel="Kaydediliyor…" onClick={()=>void save()}/></FormActions></section>:null}
{loading?<div className="flex h-56 items-center justify-center rounded-[20px] border border-[var(--line)] bg-[var(--surface)]"><Spinner/></div>:<DataView><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b border-[var(--line)] bg-[var(--surface-2)]/40 text-[10px] uppercase tracking-[.08em] text-[var(--muted-soft)]">{visibleFields.map(f=><th key={f} className="p-4 font-semibold">{FIELD_LABELS[f]??f}</th>)}<th className="p-4 font-semibold">İşlem</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id??`row-${i}`} className="border-b border-[var(--line)] last:border-0">{visibleFields.map(f=><td key={f} className="p-4 text-[var(--muted)]">{f==="staffId"?displayValue(row.firstName?`${String(row.firstName)} ${String(row.lastName??"")}`.trim():row[f]):displayValue(row[f])}</td>)}<td className="p-4"><div className="flex gap-3">{section==="employees"&&row.id?<Link className="font-medium text-[var(--accent)]" href={`/hr/employees/${row.id}`}>360° Görünüm</Link>:null}{editable&&row.id?<button type="button" className="text-[var(--accent)]" onClick={()=>startEdit(row)}>Düzenle</button>:null}{(section==="employees"||section==="leaves")&&row.id?<button type="button" className="text-[var(--danger)]" onClick={()=>void remove(row.id!)}>Sil</button>:null}</div></td></tr>)}</tbody></table></div>{!rows.length?<div className="p-10 text-center text-xs text-[var(--muted)]">Bu dönem için kayıt bulunmuyor.</div>:null}<DataViewMeta><span>{rows.length} kayıt</span><span>{PERIOD_SECTIONS.has(section)?`${year}/${String(month).padStart(2,"0")}`:config.title}</span></DataViewMeta></DataView>}</div>}
function DynamicField({field,value,staff,onChange}:{field:string;value:string|number;staff:StaffRow[];onChange:(v:string)=>void}){const label=FIELD_LABELS[field]??field;const normalized=String(value??"");return <label className="block"><span className="mb-2 block text-[13px] font-medium text-[var(--ink)]">{label}</span>{field==="staffId"?<ValooSelect value={normalized} onChange={onChange} placeholder="Personel seçin" searchPlaceholder="Personel ara…" options={staff.map(x=>({value:x.id,label:`${x.firstName??""} ${x.lastName??""}`.trim()}))}/>:SELECT_VALUES[field]?<ValooSelect value={normalized} onChange={onChange} searchable={false} placeholder="Seçin" options={SELECT_VALUES[field].map(o=>({value:o,label:userLabel(o)}))}/>:DATE_FIELDS.has(field)?<DatePicker value={normalized} onChange={onChange} ariaLabel={label}/>:<input className="control h-11 w-full" type={NUMBER_FIELDS.has(field)?"number":"text"} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function normalizeForm(section:SectionKey,raw:FormState,canReadSensitive:boolean):Record<string,unknown>{const body:Record<string,unknown>={...raw};if(section==="employees")return{firstName:body.firstName,lastName:body.lastName,phone:body.phone||undefined,email:body.email||undefined,personnelNumber:body.personnelNumber||undefined,position:body.position||undefined,department:body.department||undefined,employmentType:body.employmentType||undefined,hireDate:body.hireDate||undefined,...(canReadSensitive?{grossSalary:body.grossSalary===""?undefined:Number(body.grossSalary),iban:body.iban||undefined,bankName:body.bankName||undefined}:{})};for(const k of Object.keys(body))if(NUMBER_FIELDS.has(k)&&body[k]!=="")body[k]=Number(body[k]);return body}
function rowsFromResponse(r:unknown):DataRow[]{if(Array.isArray(r))return r.filter(isDataRow);if(isDataRow(r)&&Array.isArray(r.data))return r.data.filter(isDataRow);return[]} function isDataRow(v:unknown):v is DataRow{return typeof v==="object"&&v!==null} function isStaffRow(v:DataRow):v is StaffRow{return typeof v.id==="string"} function isSectionKey(v:string):v is SectionKey{return v in SECTION_CONFIG} function displayValue(v:unknown){if(v===null||v===undefined||v==="")return"—";if(typeof v==="string"&&v.includes("T")){const d=new Date(v);if(!Number.isNaN(d.getTime()))return d.toLocaleString("tr-TR")}if(typeof v==="string")return userLabel(v);return String(v)}