"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { DataView, DataViewMeta } from "@/components/data-view";
import { FormActions, FormGrid, FormSection, FormSubmitButton } from "@/components/form-system";
import { Alert, Button, Spinner } from "@/components/ui";
import { api, ApiError, withQuery } from "@/lib/api";
import { userLabel } from "@/lib/user-language";
type SectionKey="employees"|"personnel-files"|"attendance"|"leaves"|"payroll"|"payments"|"sgk"; type SectionConfig={title:string;get:string;post?:string;fields:readonly string[]}; type DataRow=Record<string,unknown>&{id?:string}; type StaffRow=DataRow&{id:string;firstName?:string;lastName?:string}; type FormState=Record<string,string|number|undefined>;
const SECTION_CONFIG:Record<SectionKey,SectionConfig>={employees:{title:"Çalışanlar",get:"/hr/employees",post:"/hr/employees",fields:["firstName","lastName","phone","email","personnelNumber","position","department","employmentType","hireDate","grossSalary","iban","bankName"]},"personnel-files":{title:"Özlük Dosyaları",get:"/hr/personnel-files",fields:["firstName","lastName","identityNumber","department","position","hireDate","salary","iban","bankName"]},attendance:{title:"Puantaj",get:"/hr/attendance",post:"/hr/attendance",fields:["staffId","workDate","checkIn","checkOut","breakMinutes","workedMinutes","overtimeMinutes","status","note"]},leaves:{title:"İzinler",get:"/hr/leaves",post:"/hr/leaves",fields:["staffId","type","startDate","endDate","days","status","reason"]},payroll:{title:"Bordro",get:"/hr/payroll",post:"/hr/payroll/periods",fields:["year","month"]},payments:{title:"Maaş Ödemeleri",get:"/hr/payments",post:"/hr/payments",fields:["staffId","year","month","amount","method","status","paidAt","note"]},sgk:{title:"SGK İşlemleri",get:"/hr/sgk",post:"/hr/sgk",fields:["staffId","year","month","status","documentNo","recordDate","note"]}};
const FIELD_LABELS:Record<string,string>={firstName:"Ad",lastName:"Soyad",phone:"Telefon",email:"E-Posta",personnelNumber:"Sicil No",identityNumber:"T.C. Kimlik No",position:"Pozisyon",department:"Departman",employmentType:"Çalışma Tipi",hireDate:"İşe Giriş",salary:"Brüt Maaş",grossSalary:"Brüt Maaş",iban:"IBAN",bankName:"Banka",staffId:"Personel",workDate:"Tarih",checkIn:"Giriş",checkOut:"Çıkış",breakMinutes:"Mola Süresi (Dk)",workedMinutes:"Çalışma Süresi (Dk)",overtimeMinutes:"Fazla Mesai (Dk)",status:"Durum",note:"Not",type:"İzin Türü",startDate:"Başlangıç",endDate:"Bitiş",days:"Gün",reason:"Açıklama",year:"Yıl",month:"Ay",amount:"Tutar",method:"Yöntem",paidAt:"Ödeme Tarihi",documentNo:"Belge No",recordDate:"Kayıt Tarihi"};
const DATE_FIELDS=new Set(["hireDate","workDate","startDate","endDate","paidAt","recordDate"]),NUMBER_FIELDS=new Set(["salary","grossSalary","breakMinutes","workedMinutes","overtimeMinutes","days","year","month","amount"]); const SELECT_VALUES:Record<string,readonly string[]>={status:["PENDING","APPROVED","PAID","PRESENT","ABSENT","DRAFT"],type:["ANNUAL","SICK","EXCUSE","UNPAID","OTHER"],method:["BANK","CASH"]}; const PERIOD_SECTIONS=new Set<SectionKey>(["attendance","payroll","payments","sgk"]),EDITABLE_SECTIONS=new Set<SectionKey>(["employees","attendance","leaves"]);
export default function HRSection(){const params=useParams<{section:string}>(),section=isSectionKey(params.section)?params.section:null,config=section?SECTION_CONFIG[section]:null,now=new Date();const[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1),[rows,setRows]=useState<DataRow[]>([]),[staff,setStaff]=useState<StaffRow[]>([]),[form,setForm]=useState<FormState>({year:now.getFullYear(),month:now.getMonth()+1}),[edit,setEdit]=useState<DataRow|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
async function load(){if(!section||!config)return;setLoading(true);setError("");try{const response=await api<unknown>(PERIOD_SECTIONS.has(section)?withQuery(config.get,{year,month}):config.get),nextRows=rowsFromResponse(response);setRows(nextRows);if(section!=="employees"&&section!=="personnel-files"){const employees=await api<unknown>("/hr/employees");setStaff(rowsFromResponse(employees).filter(isStaffRow))}else setStaff(nextRows.filter(isStaffRow))}catch(e){setError(e instanceof ApiError?e.message:"İK Verileri Yüklenemedi.")}finally{setLoading(false)}} useEffect(()=>{void load()},[section,year,month]); const visibleFields=useMemo(()=>config?.fields.slice(0,8)??[],[config]),editable=section?EDITABLE_SECTIONS.has(section):false;
function updateField(field:string,value:string){setForm(c=>({...c,[field]:value}))} async function save(){if(!section||!config?.post)return;setSaving(true);setError("");try{const patch=Boolean(edit&&section!=="attendance"),endpoint=patch&&edit?.id?`${config.get}/${edit.id}`:config.post;await api(endpoint,{method:patch?"PATCH":"POST",body:normalizeForm(section,form)});setForm({year,month});setEdit(null);await load()}catch(e){setError(e instanceof ApiError?e.message:"Kayıt Kaydedilemedi.")}finally{setSaving(false)}} function startEdit(row:DataRow){setEdit(row);const n:FormState={year,month};for(const[k,v]of Object.entries(row))if(typeof v==="string"||typeof v==="number")n[k]=v;setForm(n);window.scrollTo({top:0,behavior:"smooth"})} function resetEdit(){setEdit(null);setForm({year,month})} async function remove(id:string){if(!config||!id||!window.confirm("Bu Kayıt Silinsin Veya Arşivlensin Mi?"))return;try{await api(`${config.get}/${id}`,{method:"DELETE"});await load()}catch(e){setError(e instanceof ApiError?e.message:"Silme İşlemi Başarısız.")}}
if(!section||!config)return <div className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-8 text-[13px] text-[var(--muted)]">İK Sayfası Bulunamadı.</div>;
return <div className="mx-auto max-w-[1280px] space-y-5 pb-10"><header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.15em] text-[var(--muted-soft)]">İnsan Kaynakları Ve Özlük</p><h1 className="mt-1 text-[30px] font-semibold tracking-[-.035em] text-[var(--ink)]">{config.title}</h1><p className="mt-1 text-xs text-[var(--muted)]">Personel Kayıtlarını Görüntüleyin Ve Yönetin.</p></div>{PERIOD_SECTIONS.has(section)?<div className="flex gap-2"><input className="control h-10 w-24" type="number" value={year} aria-label="Yıl" onChange={e=>setYear(Number(e.target.value))}/><select className="control h-10 min-w-[110px]" value={month} aria-label="Ay" onChange={e=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{i+1}. Ay</option>)}</select></div>:null}</header>{error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}
{config.post?<section className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><FormSection title={edit?"Kaydı Güncelle":"Yeni Kayıt"} description="Alanları Doldurun Ve Kaydedin. Hassas Personel Ve Bordro Verileri Yalnız Yetkili İK Rollerince Görüntülenmelidir."><FormGrid columns={3} className="xl:grid-cols-4">{config.fields.map(field=><DynamicField key={field} field={field} value={form[field]??""} staff={staff} onChange={v=>updateField(field,v)}/>)}</FormGrid></FormSection><FormActions>{edit?<Button type="button" variant="secondary" onClick={resetEdit} disabled={saving}>İptal</Button>:null}<FormSubmitButton type="button" saving={saving} idleLabel={edit?"Güncelle":"Kaydet"} savingLabel="Kaydediliyor…" onClick={()=>void save()}/></FormActions></section>:null}
{loading?<div className="flex h-56 items-center justify-center rounded-[20px] border border-[var(--line)] bg-[var(--surface)]"><Spinner/></div>:<DataView><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b border-[var(--line)] bg-[var(--surface-2)]/40 text-[10px] uppercase tracking-[.08em] text-[var(--muted-soft)]">{visibleFields.map(f=><th key={f} className="p-4 font-semibold">{FIELD_LABELS[f]??f}</th>)}<th className="p-4 font-semibold">İşlem</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id??`row-${i}`} className="border-b border-[var(--line)] last:border-0">{visibleFields.map(f=><td key={f} className="p-4 text-[var(--muted)]">{f==="staffId"?displayValue(row.firstName?`${String(row.firstName)} ${String(row.lastName??"")}`.trim():row[f]):displayValue(row[f])}</td>)}<td className="p-4"><div className="flex gap-3">{section==="employees"&&row.id?<Link className="font-medium text-[var(--accent)]" href={`/hr/employees/${row.id}`}>360° Görünüm</Link>:null}{editable&&row.id?<button type="button" className="text-[var(--accent)]" onClick={()=>startEdit(row)}>Düzenle</button>:null}{(section==="employees"||section==="leaves")&&row.id?<button type="button" className="text-[var(--danger)]" onClick={()=>void remove(row.id!)}>Sil</button>:null}</div></td></tr>)}</tbody></table></div>{!rows.length?<div className="p-10 text-center text-xs text-[var(--muted)]">Bu Dönem İçin Kayıt Bulunmuyor.</div>:null}<DataViewMeta><span>{rows.length} Kayıt</span><span>{PERIOD_SECTIONS.has(section)?`${year}/${String(month).padStart(2,"0")}`:config.title}</span></DataViewMeta></DataView>}</div>}
function DynamicField({field,value,staff,onChange}:{field:string;value:string|number;staff:StaffRow[];onChange:(v:string)=>void}){const label=FIELD_LABELS[field]??field;return <label className="block"><span className="mb-1.5 block text-[11px] font-medium text-[var(--muted)]">{label}</span>{field==="staffId"?<select className="control h-11 w-full" value={value} onChange={e=>onChange(e.target.value)}><option value="">Personel Seçin</option>{staff.map(x=><option key={x.id} value={x.id}>{x.firstName??""} {x.lastName??""}</option>)}</select>:SELECT_VALUES[field]?<select className="control h-11 w-full" value={value} onChange={e=>onChange(e.target.value)}><option value="">Seçin</option>{SELECT_VALUES[field].map(o=><option key={o} value={o}>{userLabel(o)}</option>)}</select>:<input className="control h-11 w-full" type={DATE_FIELDS.has(field)?"date":NUMBER_FIELDS.has(field)?"number":"text"} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function normalizeForm(section:SectionKey,raw:FormState):Record<string,unknown>{const body:Record<string,unknown>={...raw};if(section==="employees")return{firstName:body.firstName,lastName:body.lastName,phone:body.phone||undefined,email:body.email||undefined,personnelNumber:body.personnelNumber||undefined,position:body.position||undefined,department:body.department||undefined,employmentType:body.employmentType||undefined,hireDate:body.hireDate||undefined,grossSalary:body.grossSalary===""?undefined:Number(body.grossSalary),iban:body.iban||undefined,bankName:body.bankName||undefined};for(const k of Object.keys(body))if(NUMBER_FIELDS.has(k)&&body[k]!=="")body[k]=Number(body[k]);return body}
function rowsFromResponse(r:unknown):DataRow[]{if(Array.isArray(r))return r.filter(isDataRow);if(isDataRow(r)&&Array.isArray(r.data))return r.data.filter(isDataRow);return[]} function isDataRow(v:unknown):v is DataRow{return typeof v==="object"&&v!==null} function isStaffRow(v:DataRow):v is StaffRow{return typeof v.id==="string"} function isSectionKey(v:string):v is SectionKey{return v in SECTION_CONFIG} function displayValue(v:unknown){if(v===null||v===undefined||v==="")return"—";if(typeof v==="string"&&v.includes("T")){const d=new Date(v);if(!Number.isNaN(d.getTime()))return d.toLocaleString("tr-TR")}if(typeof v==="string")return userLabel(v);return String(v)}