version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /apps/api
      - /apps/web
      - /packages/database
      - /packages/types
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
