"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Button, EmptyState, Field, PageHeader, Select, Spinner, TextInput } from "@/components/ui";
import { api, ApiError } from "@/lib/api";

type Session={id:string;status:"AVAILABLE"|"RESERVED"|"CONSUMED"|"CANCELLED";appointmentId:string|null;service:{id:string;name:string};customerPackage:{id:string;customer:{id:string;firstName:string;lastName:string};package:{id:string;name:string}};consumedAt?:string|null};
const labels:Record<string,string>={AVAILABLE:"Kullanılabilir",RESERVED:"Rezerve",CONSUMED:"Kullanıldı",CANCELLED:"İptal"};
export default function SessionsPage(){
 const[rows,setRows]=useState<Session[]>([]),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[appointmentId,setAppointmentId]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const q=status?`?status=${status}`:"";const r=await api<Session[]>(`/sessions${q}`);setRows(Array.isArray(r)?r:[])}catch(e){setError(e instanceof ApiError?e.message:"Seanslar yüklenemedi.")}finally{setLoading(false)}},[status]);
 useEffect(()=>{void load()},[load]);
 async function action(id:string,kind:"reserve"|"release"|"consume"|"cancel"){setWorking(true);setError("");try{await api(`/sessions/${id}/${kind}`,{method:"POST",body:kind==="reserve"?{appointmentId:appointmentId[id]}:undefined});setNotice(kind==="reserve"?"Seans randevuya rezerve edildi.":kind==="release"?"Seans rezervasyonu kaldırıldı.":kind==="consume"?"Seans kullanıldı olarak işlendi.":"Seans iptal edildi.");await load()}catch(e){setError(e instanceof ApiError?e.message:"Seans işlemi tamamlanamadı.")}finally{setWorking(false)}}
 const stats=useMemo(()=>({total:rows.length,available:rows.filter(x=>x.status==="AVAILABLE").length,reserved:rows.filter(x=>x.status==="RESERVED").length,consumed:rows.filter(x=>x.status==="CONSUMED").length}),[rows]);
 return <div className="mx-auto max-w-[1450px] space-y-6 pb-12"><PageHeader title="Seans Yönetimi" description="Satılmış paketlerdeki hizmet kullanım haklarını randevularla eşleştirin ve tüketim durumlarını yönetin."/>
 {error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}{notice?<Alert tone="success" onClose={()=>setNotice("")}>{notice}</Alert>:null}
 <section className="grid gap-3 sm:grid-cols-4"><Metric label="Toplam" value={stats.total}/><Metric label="Kullanılabilir" value={stats.available}/><Metric label="Rezerve" value={stats.reserved}/><Metric label="Kullanılmış" value={stats.consumed}/></section>
 <div className="max-w-xs"><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tüm durumlar</option><option value="AVAILABLE">Kullanılabilir</option><option value="RESERVED">Rezerve</option><option value="CONSUMED">Kullanıldı</option><option value="CANCELLED">İptal</option></Select></div>
 {loading?<Spinner label="Seanslar yükleniyor..."/>:rows.length?<section className="overflow-hidden rounded-[20px] border border-[var(--line)] bg-[var(--surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr className="border-b border-[var(--line)] bg-[var(--surface-2)]/40"><th className="px-4 py-3">Müşteri</th><th className="px-4 py-3">Paket</th><th className="px-4 py-3">Hizmet</th><th className="px-4 py-3">Durum</th><th className="px-4 py-3">Randevu</th><th className="px-4 py-3">İşlem</th></tr></thead><tbody>{rows.map(s=><tr key={s.id} className="border-b border-[var(--line)] last:border-0"><td className="px-4 py-4 font-medium">{s.customerPackage.customer.firstName} {s.customerPackage.customer.lastName}</td><td className="px-4 py-4">{s.customerPackage.package.name}</td><td className="px-4 py-4">{s.service.name}</td><td className="px-4 py-4">{labels[s.status]??s.status}</td><td className="px-4 py-4">{s.status==="AVAILABLE"?<TextInput value={appointmentId[s.id]??""} onChange={e=>setAppointmentId({...appointmentId,[s.id]:e.target.value})} placeholder="Randevu ID"/>:s.appointmentId??"—"}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{s.status==="AVAILABLE"?<><Button size="sm" disabled={working||!appointmentId[s.id]} onClick={()=>void action(s.id,"reserve")}>Randevuya Ata</Button><Button size="sm" variant="danger" disabled={working} onClick={()=>void action(s.id,"cancel")}>İptal</Button></>:null}{s.status==="RESERVED"?<><Button size="sm" variant="secondary" disabled={working} onClick={()=>void action(s.id,"release")}>Rezervasyonu Kaldır</Button><Button size="sm" disabled={working} onClick={()=>void action(s.id,"consume")}>Kullanıldı Olarak İşle</Button></>:null}</div></td></tr>)}</tbody></table></div></section>:<EmptyState title="Seans bulunamadı" description="Filtreye uyan paket seansı bulunmuyor."/>}
 </div>
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-[16px] border border-[var(--line)] bg-[var(--surface)] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[var(--muted-soft)]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
