"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Button, Spinner, Select } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import { hasPermission } from "@/lib/auth";

type Activity={id:string;activityType:string;status:string;title:string;outletName?:string|null;contactName?:string|null;startsAt?:string|null;endsAt?:string|null;location?:string|null;costAmount:string|number;currency:string;estimatedReach:string|number;actualReach:string|number;estimatedMediaValue:string|number;attributedRevenue:string|number;campaignName?:string|null};
const field="mt-2 h-11 w-full rounded-[13px] border border-[var(--line)] bg-white px-3 text-[12px] text-[var(--ink)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]";
const area="mt-2 min-h-24 w-full rounded-[13px] border border-[var(--line)] bg-white p-3 text-[12px] text-[var(--ink)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]";
const types=["PRESS_RELEASE","MEDIA_RELATION","INTERVIEW","EVENT","SPONSORSHIP","CRISIS_COMMUNICATION","AWARD","OTHER"];
const money=new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0});const num=new Intl.NumberFormat("tr-TR");

export default function PrMediaPage(){
 const canManage=hasPermission("communications","manage");const [rows,setRows]=useState<Activity[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [search,setSearch]=useState("");const [title,setTitle]=useState("");const [type,setType]=useState("MEDIA_RELATION");const [outlet,setOutlet]=useState("");const [contact,setContact]=useState("");const [location,setLocation]=useState("");const [cost,setCost]=useState("");const [reach,setReach]=useState("");const [mediaValue,setMediaValue]=useState("");const [objective,setObjective]=useState("");const [keyMessage,setKeyMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const q=new URLSearchParams({limit:"100"});if(search.trim())q.set("search",search.trim());setRows(await api<Activity[]>(`/corporate-communications/pr-media?${q.toString()}`));}catch(e){setError(e instanceof ApiError?e.message:"PR ve medya faaliyetleri yüklenemedi.");}finally{setLoading(false);}},[search]);useEffect(()=>{void load();},[load]);
 const stats=useMemo(()=>({active:rows.filter((r)=>!['COMPLETED','CANCELLED'].includes(r.status)).length,cost:rows.reduce((s,r)=>s+Number(r.costAmount||0),0),reach:rows.reduce((s,r)=>s+Number(r.actualReach||0),0),value:rows.reduce((s,r)=>s+Number(r.estimatedMediaValue||0),0)}),[rows]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{await api('/corporate-communications/pr-media',{method:'POST',body:{activityType:type,title,outletName:outlet||null,contactName:contact||null,location:location||null,costAmount:Number(cost||0),currency:'TRY',estimatedReach:Number(reach||0),actualReach:0,estimatedMediaValue:Number(mediaValue||0),objective:objective||null,keyMessage:keyMessage||null,metadata:{source:'PR_MEDIA_WORKSPACE'}}});setTitle('');setOutlet('');setContact('');setLocation('');setCost('');setReach('');setMediaValue('');setObjective('');setKeyMessage('');await load();}catch(err){setError(err instanceof ApiError?err.message:'PR faaliyeti kaydedilemedi.');}finally{setSaving(false);}}
 async function complete(row:Activity){setError('');try{await api(`/corporate-communications/pr-media/${row.id}`,{method:'PATCH',body:{status:'COMPLETED',actualReach:Number(row.actualReach||row.estimatedReach||0)}});await load();}catch(e){setError(e instanceof ApiError?e.message:'Faaliyet güncellenemedi.');}}
 if(loading&&!rows.length)return <div className="py-20"><Spinner label="PR ve medya merkezi yükleniyor..."/></div>;
 return <div className="space-y-6 pb-12"><header className="rounded-[24px] border border-[var(--line)] bg-[var(--surface)] p-6"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--accent)]">Kurumsal İletişim</p><h1 className="text-[30px] font-semibold tracking-[-.04em] text-[var(--ink)]">PR, Medya & Sponsorluk</h1><p className="mt-2 max-w-4xl text-[12px] leading-5 text-[var(--muted)]">Basın ilişkileri, röportaj, etkinlik, sponsorluk, kriz iletişimi ve medya görünürlüğünü maliyet, erişim ve medya değeriyle yönetin.</p></header>{error?<Alert>{error}</Alert>:null}
 <section className="grid gap-4 sm:grid-cols-4"><Metric label="Aktif Faaliyet" value={String(stats.active)}/><Metric label="Toplam Maliyet" value={money.format(stats.cost)}/><Metric label="Gerçekleşen Erişim" value={num.format(stats.reach)}/><Metric label="Tahmini Medya Değeri" value={money.format(stats.value)}/></section>
 <div className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-4"><input className={field.replace('mt-2 ','')} placeholder="Faaliyet veya medya kuruluşu ara" value={search} onChange={(e)=>setSearch(e.target.value)}/></div>
 <div className="grid gap-5 xl:grid-cols-[.78fr_1.22fr]">{canManage?<form onSubmit={(e)=>void create(e)} className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="text-[15px] font-semibold text-[var(--ink)]">Yeni PR Faaliyeti</h2><label className="mt-5 block text-[11px] font-semibold text-[var(--muted)]">Başlık<input required className={field} value={title} onChange={(e)=>setTitle(e.target.value)}/></label><label className="mt-4 block text-[11px] font-semibold text-[var(--muted)]">Tür<Select className={field} value={type} onChange={(e)=>setType(e.target.value)}>{types.map((t)=><option key={t}>{t}</option>)}</Select></label><div className="grid gap-3 sm:grid-cols-2"><label className="mt-4 block text-[11px] font-semibold text-[var(--muted)]">Medya / kurum<input className={field} value={outlet} onChange={(e)=>setOutlet(e.target.value)}/></label><label className="mt-4 block text-[11px] font-semibold text-[var(--muted)]">İletişim kişisi<input className={field} value={contact} onChange={(e)=>setContact(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Lokasyon<input className={field} value={location} onChange={(e)=>setLocation(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Maliyet<input type="number" min="0" className={field} value={cost} onChange={(e)=>setCost(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Tahmini erişim<input type="number" min="0" className={field} value={reach} onChange={(e)=>setReach(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Tahmini medya değeri<input type="number" min="0" className={field} value={mediaValue} onChange={(e)=>setMediaValue(e.target.value)}/></label></div><label className="mt-4 block text-[11px] font-semibold text-[var(--muted)]">Amaç<textarea className={area} value={objective} onChange={(e)=>setObjective(e.target.value)}/></label><label className="mt-4 block text-[11px] font-semibold text-[var(--muted)]">Ana mesaj<textarea className={area} value={keyMessage} onChange={(e)=>setKeyMessage(e.target.value)}/></label><Button className="mt-5" disabled={saving} type="submit">{saving?'Kaydediliyor...':'Faaliyeti Kaydet'}</Button></form>:null}
 <section className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="text-[15px] font-semibold text-[var(--ink)]">Faaliyetler</h2><div className="mt-4 space-y-3">{rows.map((row)=><article key={row.id} className="rounded-[16px] border border-[var(--line)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="text-[13px] font-semibold text-[var(--ink)]">{row.title}</p><Badge text={row.activityType}/><Badge text={row.status}/></div><p className="mt-1 text-[10px] text-[var(--muted)]">{row.outletName??'Medya kuruluşu tanımsız'}{row.location?` · ${row.location}`:''}</p></div><div className="text-right"><p className="text-[12px] font-semibold text-[var(--ink)]">{money.format(Number(row.costAmount||0))}</p><p className="mt-1 text-[10px] text-[var(--muted)]">Medya değeri {money.format(Number(row.estimatedMediaValue||0))}</p></div></div><div className="mt-3 flex flex-wrap gap-3 text-[10px] text-[var(--muted)]"><span>Tahmini {num.format(Number(row.estimatedReach||0))}</span><span>Gerçek {num.format(Number(row.actualReach||0))}</span><span>Gelir {money.format(Number(row.attributedRevenue||0))}</span></div>{canManage&&!['COMPLETED','CANCELLED'].includes(row.status)?<button type="button" className="mt-4 rounded-[10px] border border-[var(--line)] px-3 py-2 text-[10px] font-semibold text-[var(--accent)]" onClick={()=>void complete(row)}>Tamamlandı</button>:null}</article>)}</div></section></div></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-[18px] border border-[var(--line)] bg-[var(--surface)] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[var(--muted-soft)]">{label}</p><p className="mt-2 text-[22px] font-semibold text-[var(--ink)]">{value}</p></div>}
function Badge({text}:{text:string}){return <span className="rounded-full bg-[var(--accent-soft)] px-2 py-1 text-[9px] font-semibold text-[var(--accent)]">{text.replaceAll('_',' ')}</span>}
