"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { FinanceEmpty, FinanceMetric, FinancePanel } from "@/components/finance-view";
import { Alert, Button, Spinner } from "@/components/ui";
import { api, ApiError } from "@/lib/api";

type Rule={id:string;positionId:string;positionCode:string;positionName:string;programId:string;programCode:string;programTitle:string;autoAssign:boolean;isActive:boolean;eligibleStaff:number};
type Position={id:string;name:string;code:string;staffCount:number};
type Program={id:string;code:string;title:string;publishedVersionId?:string|null};
type Targets={positions:Position[]};
const selectClass="w-full rounded-[12px] border border-[var(--line)] bg-[var(--surface)] px-3 py-2.5 text-[12px] text-[var(--ink)] outline-none focus:border-[var(--accent)]";

export default function RoleAcademiesPage(){
 const [rules,setRules]=useState<Rule[]>([]),[positions,setPositions]=useState<Position[]>([]),[programs,setPrograms]=useState<Program[]>([]);
 const [positionId,setPositionId]=useState(""),[programId,setProgramId]=useState(""),[autoAssign,setAutoAssign]=useState(true);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [r,t,p]=await Promise.all([api<Rule[]>("/training/role-academies"),api<Targets>("/training/assignments/targets"),api<Program[]>("/training/learning-paths")]);setRules(r);setPositions(t.positions??[]);setPrograms((p??[]).filter(x=>x.publishedVersionId));}catch(e){setError(e instanceof ApiError?e.message:"Rol akademileri yüklenemedi.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const metrics=useMemo(()=>({active:rules.filter(r=>r.isActive).length,auto:rules.filter(r=>r.isActive&&r.autoAssign).length,staff:rules.filter(r=>r.isActive).reduce((s,r)=>s+r.eligibleStaff,0)}),[rules]);
 async function save(){if(!positionId||!programId)return;setSaving(true);setError("");try{await api("/training/role-academies",{method:"POST",body:JSON.stringify({positionId,programId,autoAssign})});setPositionId("");setProgramId("");await load();}catch(e){setError(e instanceof ApiError?e.message:"Rol akademisi kaydedilemedi.");}finally{setSaving(false);}}
 async function process(){setSaving(true);setError("");setMessage("");try{const r=await api<{matched:number;assigned:number;existing:number;failed:number}>("/training/role-academies/process",{method:"POST"});setMessage(`${r.matched} personel eşleşti · ${r.assigned} yeni atama · ${r.existing} mevcut · ${r.failed} hata`);await load();}catch(e){setError(e instanceof ApiError?e.message:"Rol akademileri işlenemedi.");}finally{setSaving(false);}}
 async function deactivate(id:string){setSaving(true);try{await api(`/training/role-academies/${id}`,{method:"DELETE"});await load();}catch(e){setError(e instanceof ApiError?e.message:"Eşleştirme kapatılamadı.");}finally{setSaving(false);}}
 return <div className="mx-auto max-w-[1400px] space-y-6 pb-10">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/training/learning-paths" className="text-[11px] font-semibold text-[var(--accent)] hover:underline">← Akademiler</Link><p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.14em] text-[var(--muted-soft)]">Role Academies</p><h1 className="mt-1 text-[32px] font-semibold tracking-[-0.045em] text-[var(--ink)]">Pozisyon Bazlı Akademiler</h1><p className="mt-2 max-w-[850px] text-[13px] leading-6 text-[var(--muted)]">HR pozisyonlarını published Learning Path’lerle eşleştirin. Otomatik atama aynı personel/path için idempotent çalışır.</p></div><Button onClick={()=>void process()} disabled={saving||!rules.some(r=>r.isActive&&r.autoAssign)}>Rol Akademilerini Senkronize Et</Button></header>
  {error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}{message?<Alert tone="success" onClose={()=>setMessage("")}>{message}</Alert>:null}
  <section className="grid gap-3 sm:grid-cols-3"><FinanceMetric label="Aktif Kural" value={metrics.active} detail="Pozisyon → Akademi" tone="info"/><FinanceMetric label="Auto Assign" value={metrics.auto} detail="Otomatik senkronizasyon" tone="success"/><FinanceMetric label="Eşleşen Personel" value={metrics.staff} detail="Aktif branch kapsamı" tone="info"/></section>
  <FinancePanel title="Rol Akademisi Tanımla" description="Yalnız aktif pozisyonlar ve published Learning Path’ler seçilebilir."><div className="grid gap-3 lg:grid-cols-[1fr_1fr_180px_auto] lg:items-end"><div><p className="mb-1 text-[10px] font-semibold uppercase text-[var(--muted-soft)]">Pozisyon</p><select className={selectClass} value={positionId} onChange={e=>setPositionId(e.target.value)}><option value="">Pozisyon seçin</option>{positions.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name} ({p.staffCount})</option>)}</select></div><div><p className="mb-1 text-[10px] font-semibold uppercase text-[var(--muted-soft)]">Akademi</p><select className={selectClass} value={programId} onChange={e=>setProgramId(e.target.value)}><option value="">Learning Path seçin</option>{programs.map(p=><option key={p.id} value={p.id}>{p.code} · {p.title}</option>)}</select></div><label className="flex h-[42px] items-center gap-2 text-[11px] text-[var(--muted)]"><input type="checkbox" checked={autoAssign} onChange={e=>setAutoAssign(e.target.checked)}/> Otomatik ata</label><Button onClick={()=>void save()} disabled={saving||!positionId||!programId}>Kaydet</Button></div></FinancePanel>
  <FinancePanel title="Eşleştirmeler" description="Bir pozisyon birden fazla akademiye bağlanabilir; aynı akademi birden fazla pozisyonda kullanılabilir.">{loading?<div className="flex min-h-[240px] items-center justify-center"><Spinner label="Rol akademileri yükleniyor..."/></div>:!rules.length?<FinanceEmpty title="Rol akademisi tanımlanmadı" description="İlk pozisyon → Learning Path eşleştirmesini oluşturun."/>:<div className="space-y-2">{rules.map(r=><div key={r.id} className="flex flex-col gap-3 rounded-[16px] border border-[var(--line)] bg-[var(--surface-2)] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-semibold uppercase text-[var(--accent)]">{r.positionCode} · {r.positionName}</p><p className="mt-1 text-[13px] font-semibold text-[var(--ink)]">{r.programCode} · {r.programTitle}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{r.eligibleStaff} aktif personel · {r.autoAssign?"Auto assign açık":"Manuel"} · {r.isActive?"Aktif":"Pasif"}</p></div>{r.isActive?<Button variant="secondary" onClick={()=>void deactivate(r.id)} disabled={saving}>Pasife Al</Button>:null}</div>)}</div>}</FinancePanel>
 </div>;
}
