import { EnterpriseDataPage } from "@/components/enterprise-data-page";
export default function HRTalentPage(){return <EnterpriseDataPage eyebrow="İnsan Kaynakları · Yetenek" title="Yetenek Yönetimi" description="Hedefleri, performans değerlendirmelerini ve yetenek süreçlerini izleyin." sections={[
{title:"Hedefler",path:"/hr/talent/goals"},
{title:"Performans Değerlendirmeleri",path:"/hr/talent/reviews"},
]} forms={[
{title:"Hedef Oluştur",path:"/hr/talent/goals",fields:[{name:"staffId",label:"Personel ID"},{name:"name",label:"Hedef Adı",required:true},{name:"metricKey",label:"Metrik Kodu",required:true},{name:"targetValue",label:"Hedef Değer",type:"number",required:true},{name:"unit",label:"Birim"},{name:"weight",label:"Ağırlık",type:"number",defaultValue:"1"},{name:"periodType",label:"Periyot",type:"select",defaultValue:"MONTHLY",options:[{value:"MONTHLY",label:"Aylık"},{value:"QUARTERLY",label:"Çeyreklik"},{value:"YEARLY",label:"Yıllık"}]},{name:"startsOn",label:"Başlangıç",type:"date",required:true},{name:"endsOn",label:"Bitiş",type:"date",required:true}]},
{title:"Performans Dönemi Oluştur",path:"/hr/talent/review-cycles",fields:[{name:"name",label:"Dönem Adı",required:true},{name:"startsOn",label:"Başlangıç",type:"date",required:true},{name:"endsOn",label:"Bitiş",type:"date",required:true},{name:"status",label:"Durum",type:"select",defaultValue:"DRAFT",options:[{value:"DRAFT",label:"Taslak"},{value:"ACTIVE",label:"Aktif"},{value:"CLOSED",label:"Kapalı"}]}]},
{title:"Personel Değerlendirmesi Aç",path:"/hr/talent/employees/{staffId}/reviews",fields:[{name:"staffId",label:"Personel ID",required:true},{name:"cycleId",label:"Performans Dönemi ID",required:true},{name:"managerStaffId",label:"Yönetici Personel ID"}]},
{title:"Hedef Gerçekleşmesini Güncelle",path:"/hr/talent/goals/{id}/actual",method:"PUT",fields:[{name:"id",label:"Hedef ID",required:true},{name:"actual",label:"Gerçekleşen Değer",type:"number",required:true}]},
{title:"Çalışan Vakası Oluştur",path:"/hr/talent/cases",fields:[{name:"branchId",label:"Şube ID",required:true},{name:"staffId",label:"Personel ID"},{name:"caseType",label:"Vaka Türü",required:true},{name:"title",label:"Başlık",required:true},{name:"description",label:"Açıklama",type:"textarea"},{name:"severity",label:"Önem",type:"select",defaultValue:"NORMAL",options:[{value:"LOW",label:"Düşük"},{value:"NORMAL",label:"Normal"},{value:"HIGH",label:"Yüksek"},{value:"CRITICAL",label:"Kritik"}]},{name:"ownerId",label:"Sorumlu Kullanıcı ID"},{name:"restricted",label:"Kısıtlı",type:"boolean",defaultValue:"true"}]},
{title:"Çalışan Vakasına Aksiyon Ekle",path:"/hr/talent/cases/{id}/actions",fields:[{name:"id",label:"Vaka ID",required:true},{name:"actionType",label:"Aksiyon Türü",required:true},{name:"description",label:"Açıklama",type:"textarea",required:true},{name:"effectiveDate",label:"Geçerlilik Tarihi",type:"date"},{name:"status",label:"Yeni Durum"},{name:"resolution",label:"Çözüm",type:"textarea"}]}
]} />;}
