"use client";
import { EnterpriseDataPage } from "@/components/enterprise-data-page";
import { getActiveBranchId } from "@/lib/auth";

export default function HRTalentPage(){
const activeBranchId=getActiveBranchId()??"";
return <EnterpriseDataPage eyebrow="İnsan Kaynakları · Yetenek" title="Yetenek ve Performans" description="Çalışan hedeflerini, değerlendirme dönemlerini, geri bildirimleri ve gelişim süreçlerini tek merkezden yönetin." sections={[
{title:"Hedefler",path:"/hr/talent/goals"},
{title:"Performans Değerlendirmeleri",path:"/hr/talent/reviews"},
]} forms={[
{title:"Hedef Oluştur",path:"/hr/talent/goals",fields:[{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"]},{name:"name",label:"Hedef Adı",required:true},{name:"metricKey",label:"Nasıl Ölçülecek?",required:true,placeholder:"Örn. Aylık satış tutarı"},{name:"targetValue",label:"Hedeflenen Sonuç",type:"number",required:true},{name:"unit",label:"Birim"},{name:"weight",label:"Öncelik Payı",type:"number",defaultValue:"1"},{name:"periodType",label:"Değerlendirme Aralığı",type:"select",defaultValue:"MONTHLY",options:[{value:"MONTHLY",label:"Aylık"},{value:"QUARTERLY",label:"Üç Aylık"},{value:"YEARLY",label:"Yıllık"}]},{name:"startsOn",label:"Başlangıç",type:"date",required:true},{name:"endsOn",label:"Bitiş",type:"date",required:true}]},
{title:"Performans Dönemi Oluştur",path:"/hr/talent/review-cycles",fields:[{name:"name",label:"Dönem Adı",required:true},{name:"startsOn",label:"Başlangıç",type:"date",required:true},{name:"endsOn",label:"Bitiş",type:"date",required:true},{name:"status",label:"Durum",type:"select",defaultValue:"DRAFT",options:[{value:"DRAFT",label:"Taslak"},{value:"ACTIVE",label:"Aktif"},{value:"CLOSED",label:"Kapalı"}]}]},
{title:"Çalışan Değerlendirmesi Başlat",path:"/hr/talent/employees/{staffId}/reviews",fields:[{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"],required:true},{name:"cycleId",label:"Değerlendirme Dönemi",type:"remote-select",optionsPath:"/hr/talent/review-cycles",optionLabelKeys:["name"],required:true},{name:"managerStaffId",label:"Değerlendirecek Yönetici",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"]}]},
{title:"Hedef Gerçekleşmesini Güncelle",path:"/hr/talent/goals/{id}/actual",method:"PUT",fields:[{name:"id",label:"Hedef",type:"remote-select",optionsPath:"/hr/talent/goals",optionLabelKeys:["name"],required:true},{name:"actual",label:"Gerçekleşen Değer",type:"number",required:true}]},
{title:"Çalışan Gelişim Kaydı Oluştur",path:"/hr/talent/cases",fields:[{name:"branchId",label:"Şube",type:"hidden",defaultValue:activeBranchId,required:true},{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"]},{name:"caseType",label:"Kayıt Türü",required:true,placeholder:"Örn. geri bildirim, gelişim planı veya resmi kayıt"},{name:"title",label:"Başlık",required:true},{name:"description",label:"Açıklama",type:"textarea"},{name:"severity",label:"Önem",type:"select",defaultValue:"NORMAL",options:[{value:"LOW",label:"Düşük"},{value:"NORMAL",label:"Normal"},{value:"HIGH",label:"Yüksek"},{value:"CRITICAL",label:"Kritik"}]},{name:"restricted",label:"Yalnızca Yetkililer Görsün",type:"boolean",defaultValue:"true"}]},
{title:"Gelişim Kaydına İşlem Ekle",path:"/hr/talent/cases/{id}/actions",fields:[{name:"id",label:"Gelişim Kaydı",type:"remote-select",optionsPath:"/hr/talent/cases",optionLabelKeys:["title"],required:true},{name:"actionType",label:"Yapılacak İşlem",required:true,placeholder:"Örn. görüşme, geri bildirim veya gelişim planı"},{name:"description",label:"Açıklama",type:"textarea",required:true},{name:"effectiveDate",label:"Geçerlilik Tarihi",type:"date"},{name:"status",label:"Yeni Durum",type:"select",options:[{value:"OPEN",label:"Açık"},{value:"IN_PROGRESS",label:"İşlemde"},{value:"CLOSED",label:"Kapalı"}]},{name:"resolution",label:"Çözüm",type:"textarea"}]}
]} />;
}