"use client";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Alert, Button, EmptyState, Field, PageHeader, Select, Spinner, TextArea, TextInput } from "@/components/ui";
import { api, ApiError } from "@/lib/api";

type Visit={id:string;customerId:string;source:string;status:string;note:string|null;version:number;appointmentIds:string[];createdAt:string;checkedInAt:string|null};
const labels:Record<string,string>={EXPECTED:"Bekleniyor",ARRIVED:"Geldi",CHECKED_IN:"Giriş Yapıldı",WAITING:"Bekliyor",IN_SERVICE:"İşlemde",SERVICE_COMPLETED:"Hizmet Tamamlandı",CHECKOUT_PENDING:"Çıkış Bekliyor",CHECKED_OUT:"Çıkış Yapıldı",CANCELLED:"İptal"};
export default function FrontDeskPage(){
 const[rows,setRows]=useState<Visit[]>([]),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const[appointmentId,setAppointmentId]=useState(""),[customerId,setCustomerId]=useState(""),[note,setNote]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await api<Visit[]>("/visits?limit=200");setRows(Array.isArray(r)?r:[])}catch(e){setError(e instanceof ApiError?e.message:"Ziyaretler yüklenemedi.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function checkIn(event:FormEvent,mode:"appointment"|"walkin"){event.preventDefault();setWorking(true);setError("");try{const body=mode==="appointment"?{appointmentId,note:note||undefined}:{customerId,idempotencyKey:`walkin-${customerId}-${Date.now()}`,note:note||undefined};await api("/visits/check-in",{method:"POST",body});setAppointmentId("");setCustomerId("");setNote("");setNotice(mode==="appointment"?"Randevu check-in yapıldı.":"Walk-in müşteri check-in yapıldı.");await load()}catch(e){setError(e instanceof ApiError?e.message:"Check-in tamamlanamadı.")}finally{setWorking(false)}}
 async function transition(v:Visit,toStatus:string){setWorking(true);setError("");try{await api(`/visits/${v.id}/transition`,{method:"POST",body:{toStatus,expectedVersion:v.version}});setNotice("Ziyaret durumu güncellendi.");await load()}catch(e){setError(e instanceof ApiError?e.message:"Ziyaret durumu güncellenemedi.")}finally{setWorking(false)}}
 async function checkout(v:Visit){setWorking(true);setError("");try{const readiness=await api<{ready?:boolean;issues?:unknown[]}>(`/visits/${v.id}/checkout-readiness`);if(readiness.ready===false){setError("Çıkış için tamamlanması gereken işlemler var.");return}await api(`/visits/${v.id}/check-out`,{method:"POST",body:{expectedVersion:v.version}});setNotice("Müşteri çıkışı tamamlandı.");await load()}catch(e){setError(e instanceof ApiError?e.message:"Çıkış tamamlanamadı.")}finally{setWorking(false)}}
 const active=useMemo(()=>rows.filter(v=>!["CHECKED_OUT","CANCELLED"].includes(v.status)).length,[rows]);
 return <div className="mx-auto max-w-[1450px] space-y-6 pb-12"><PageHeader title="Resepsiyon ve Ziyaret Yönetimi" description="Randevulu ve walk-in müşterilerin giriş, hizmet ve çıkış süreçlerini canlı olarak yönetin."/>
 {error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}{notice?<Alert tone="success" onClose={()=>setNotice("")}>{notice}</Alert>:null}
 <section className="grid gap-5 xl:grid-cols-2">
 <form onSubmit={e=>void checkIn(e,"appointment")} className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="text-sm font-semibold">Randevudan Check-in</h2><div className="mt-4 space-y-3"><Field label="Randevu ID" required><TextInput value={appointmentId} onChange={e=>setAppointmentId(e.target.value)} required/></Field><Field label="Not"><TextArea rows={2} value={note} onChange={e=>setNote(e.target.value)}/></Field><Button type="submit" disabled={working||!appointmentId}>Check-in Yap</Button></div></form>
 <form onSubmit={e=>void checkIn(e,"walkin")} className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="text-sm font-semibold">Walk-in Check-in</h2><div className="mt-4 space-y-3"><Field label="Müşteri ID" required><TextInput value={customerId} onChange={e=>setCustomerId(e.target.value)} required/></Field><Field label="Not"><TextArea rows={2} value={note} onChange={e=>setNote(e.target.value)}/></Field><Button type="submit" disabled={working||!customerId}>Walk-in Girişi Yap</Button></div></form>
 </section>
 <section className="grid gap-3 sm:grid-cols-3"><Metric label="Toplam Ziyaret" value={rows.length}/><Metric label="Aktif Ziyaret" value={active}/><Metric label="Tamamlanan Çıkış" value={rows.filter(v=>v.status==="CHECKED_OUT").length}/></section>
 {loading?<Spinner label="Ziyaretler yükleniyor..."/>:rows.length?<section className="overflow-hidden rounded-[20px] border border-[var(--line)] bg-[var(--surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr className="border-b border-[var(--line)] bg-[var(--surface-2)]/40"><th className="px-4 py-3">Zaman</th><th className="px-4 py-3">Müşteri ID</th><th className="px-4 py-3">Kaynak</th><th className="px-4 py-3">Durum</th><th className="px-4 py-3">Randevular</th><th className="px-4 py-3">İşlem</th></tr></thead><tbody>{rows.map(v=><tr key={v.id} className="border-b border-[var(--line)] last:border-0"><td className="px-4 py-4">{new Date(v.createdAt).toLocaleString("tr-TR")}</td><td className="px-4 py-4">{v.customerId}</td><td className="px-4 py-4">{v.source==="APPOINTMENT"?"Randevu":"Walk-in"}</td><td className="px-4 py-4">{labels[v.status]??v.status}</td><td className="px-4 py-4">{v.appointmentIds?.join(", ")||"—"}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{v.status==="CHECKED_IN"?<><Button size="sm" variant="secondary" onClick={()=>void transition(v,"WAITING")} disabled={working}>Beklemeye Al</Button><Button size="sm" onClick={()=>void transition(v,"IN_SERVICE")} disabled={working}>Hizmeti Başlat</Button></>:null}{v.status==="WAITING"?<Button size="sm" onClick={()=>void transition(v,"IN_SERVICE")} disabled={working}>Hizmeti Başlat</Button>:null}{v.status==="IN_SERVICE"?<Button size="sm" onClick={()=>void transition(v,"SERVICE_COMPLETED")} disabled={working}>Hizmeti Tamamla</Button>:null}{v.status==="SERVICE_COMPLETED"?<Button size="sm" onClick={()=>void transition(v,"CHECKOUT_PENDING")} disabled={working}>Çıkışa Hazırla</Button>:null}{v.status==="CHECKOUT_PENDING"?<Button size="sm" onClick={()=>void checkout(v)} disabled={working}>Check-out</Button>:null}{!["CHECKED_OUT","CANCELLED"].includes(v.status)?<Button size="sm" variant="danger" onClick={()=>void transition(v,"CANCELLED")} disabled={working}>İptal</Button>:null}</div></td></tr>)}</tbody></table></div></section>:<EmptyState title="Ziyaret bulunamadı" description="Henüz ziyaret kaydı yok."/>}
 </div>
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-[16px] border border-[var(--line)] bg-[var(--surface)] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[var(--muted-soft)]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
