
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // Prisma 6 supports multi-file schemas. Keep the existing core schema intact and
  // load bounded-domain schema files (for example prisma/finance.prisma) alongside it.
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
