export type FinancialHealthStatus =
  | "STRONG"
  | "STABLE"
  | "WEAK"
  | "CRITICAL"
  | "IMPROVING"
  | "DETERIORATING"
  | "INSUFFICIENT_HISTORY";

export type CfoActionStatus = "OPEN" | "IN_PROGRESS" | "BLOCKED" | "COMPLETED" | "CANCELLED";
export type CfoPriority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | string;
export type CfoSeverity = "INFO" | "WARNING" | "CRITICAL" | string;

export type CfoHealth = {
  score: number;
  status: FinancialHealthStatus | string;
  direction?: string;
  scoreDelta?: number | null;
  monthOverMonthDelta?: number | null;
};

export type CfoPriorityItem = {
  code: string;
  priority: CfoPriority;
  action?: string | null;
  recommendation?: string | null;
};

export type CfoExecutiveAlert = {
  code: string;
  severity: CfoSeverity;
  title?: string | null;
  actual?: string | number | boolean | null;
  threshold?: string | number | boolean | null;
};

export type CfoBranchPortfolioItem = {
  branchId?: string;
  branchName?: string;
  branchCode?: string;
  healthScore?: number | null;
  healthStatus?: string | null;
};

export type CfoSla = {
  open: number;
  overdue: number;
  critical: number;
  dueNext24Hours: number;
  maxEscalationLevel: number;
};

export type CfoCockpit = {
  asOf?: string;
  health?: CfoHealth;
  covenants?: {
    total: number;
    compliant: number;
    breached: number;
    allCompliant: boolean;
  };
  liquidity?: {
    opening: number;
    thirteenWeekClosing: number;
    thirteenWeekLowest: number;
    risk: boolean;
    runwayWeeks: number | null;
  };
  workingCapital?: {
    netWorkingCapital: number;
    dsoDays: number | null;
    dpoDays: number | null;
    overdueReceivableRatioPercent: number;
  };
  branchPortfolio?: {
    activeScoredBranches: number;
    improvingBranches: number;
    deterioratingBranches: number;
    criticalBranches: number;
    weakestBranches: CfoBranchPortfolioItem[];
  };
  priorities?: CfoPriorityItem[];
  executiveAlerts?: CfoExecutiveAlert[];
  actions?: {
    summary: {
      total: number;
      open: number;
      overdue: number;
      criticalOpen: number;
    };
    sla: CfoSla;
  };
};

export type CfoActionItem = {
  id: string;
  title: string;
  description?: string | null;
  priority: CfoPriority;
  status: CfoActionStatus | string;
  dueAt?: string | null;
  sourceCode?: string | null;
  autoGenerated?: boolean;
  escalationLevel?: number;
  lastEscalatedAt?: string | null;
};

export type CfoBenchmarkBranch = {
  branchId: string;
  branchName: string;
  branchCode: string;
  healthScore: number | null;
  healthStatus?: string | null;
  percentile: number | null;
  varianceFromAverage: number | null;
};

export type CfoBenchmark = {
  averageHealthScore: number | null;
  medianHealthScore: number | null;
  bestScore: number | null;
  worstScore: number | null;
  scoredBranchCount?: number;
  branches: CfoBenchmarkBranch[];
};

export type CfoAnomaly = {
  scope: string;
  branchName?: string | null;
  snapshotDate: string;
  healthScore: number;
  scoreDelta: number;
  zScore: number;
  severity: CfoSeverity;
};

export type CfoAnomalies = {
  anomalyCount: number;
  criticalCount: number;
  warningCount: number;
  anomalies: CfoAnomaly[];
};

export type CfoHealthHistoryItem = {
  id: string;
  snapshotDate: string;
  healthScore: number;
  healthStatus: string;
};

export type CfoCashFlowWeek = {
  week: number;
  start: string;
  end: string;
  projectedInflows: number;
  projectedOutflows: number;
  netCashFlow: number;
  closingLiquidity: number;
};

export type CfoCashFlow = {
  openingLiquidity: number;
  projectedInflows: number;
  projectedOutflows: number;
  projectedNetCashFlow: number;
  forecastClosingLiquidity: number;
  lowestLiquidity: number;
  liquidityRisk: boolean;
  weeks: CfoCashFlowWeek[];
};

export type CfoTabKey = "overview" | "trends" | "branches" | "actions" | "risk";

export const CFO_STATUS_LABEL: Record<string, string> = {
  STRONG: "Güçlü",
  STABLE: "Dengeli",
  WEAK: "Zayıf",
  CRITICAL: "Kritik",
  IMPROVING: "İyileşiyor",
  DETERIORATING: "Kötüleşiyor",
  INSUFFICIENT_HISTORY: "Yetersiz veri",
  OPEN: "Açık",
  IN_PROGRESS: "Devam ediyor",
  BLOCKED: "Bloke",
  COMPLETED: "Tamamlandı",
  CANCELLED: "İptal",
};

export function formatCfoMoney(value: unknown) {
  const numeric = Number(value ?? 0);
  return new Intl.NumberFormat("tr-TR", {
    style: "currency",
    currency: "TRY",
    maximumFractionDigits: 0,
  }).format(Number.isFinite(numeric) ? numeric : 0);
}

export function formatCfoNumber(value: unknown) {
  if (value === null || value === undefined || !Number.isFinite(Number(value))) return "—";
  return new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 1 }).format(Number(value));
}

export function formatCfoSigned(value: unknown) {
  if (value === null || value === undefined || !Number.isFinite(Number(value))) return "—";
  const numeric = Number(value);
  return `${numeric > 0 ? "+" : ""}${formatCfoNumber(numeric)}`;
}
