const USER_LABELS: Record<string, string> = {
  ACTIVE: "Aktif",
  INACTIVE: "Pasif",
  ARCHIVED: "Arşivlendi",
  PENDING: "Bekliyor",
  APPROVED: "Onaylandı",
  REJECTED: "Reddedildi",
  PAID: "Ödendi",
  PRESENT: "Geldi",
  ABSENT: "Gelmedi",
  DRAFT: "Taslak",
  PUBLISHED: "Yayında",
  CLOSED: "Kapandı",
  AWARDED: "Kazanan Seçildi",
  CANCELLED: "İptal Edildi",
  SUBMITTED: "Gönderildi",
  ACCEPTED: "Kabul Edildi",
  WITHDRAWN: "Geri Çekildi",
  CONNECTED: "Bağlı",
  CONNECTING: "Bağlanıyor",
  DISCONNECTED: "Bağlantı Kesildi",
  HEALTHY: "Sorunsuz",
  ATTENTION: "Kontrol Gerekli",
  WARNING: "Uyarı",
  CRITICAL: "Kritik",
  SUCCESS: "Başarılı",
  FAILED: "Başarısız",
  PROCESSING: "İşleniyor",
  PROCESSED: "İşlendi",
  RUNNING: "Devam Ediyor",
  COMPLETED: "Tamamlandı",
  RETRY_PENDING: "Yeniden Denenecek",
  ENRICHMENT_PENDING: "Bilgi Tamamlanıyor",
  DEAD_LETTER: "İşlem Başarısız",
  MATCHED: "Eşleştirildi",
  UNMATCHED: "Eşleştirilmedi",
  CONFIGURED: "Ayarlanmış",
  MISSING: "Eksik",
  READY: "Hazır",
  PARTIAL: "Kısmen Hazır",
  STALE: "Güncel Değil",
  OPEN: "Açık",
  ACKNOWLEDGED: "İnceleniyor",
  RESOLVED: "Çözüldü",
  IMPROVED: "İyileşti",
  STABLE: "Değişmedi",
  WORSE: "Kötüleşti",
  INSUFFICIENT_BASELINE: "Başlangıç Verisi Yetersiz",
  NORMAL: "Normal",
  HIGH: "Yüksek",
  LOW: "Düşük",
  BANK: "Banka",
  CASH: "Nakit",
  CARD: "Kart",
  TRANSFER: "Havale / EFT",
  ANNUAL: "Yıllık İzin",
  SICK: "Hastalık İzni",
  EXCUSE: "Mazeret İzni",
  UNPAID: "Ücretsiz İzin",
  OTHER: "Diğer",
  OWNER: "Yetkili",
  ADMIN: "Yönetici",
  MANAGER: "Müdür",
  STAFF: "Personel",
  VERIFIED: "Doğrulandı",
};

export function userLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return USER_LABELS[value] ?? value;
}

export function userLabelOr(value: string | null | undefined, fallback: string): string {
  if (!value) return fallback;
  return USER_LABELS[value] ?? value;
}
