import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';
@Injectable()
export class CrmLeadMergeService {
 constructor(private readonly prisma:PrismaService,private readonly tenantContext:TenantContext){}
 async merge(sourceLeadId:string,targetLeadId:string,actorUserId:string,reason:string,sourceVersion:number,targetVersion:number){
  if(sourceLeadId===targetLeadId)throw new BadRequestException('Source and target lead must be different.');
  const c=this.tenantContext.getContext();if(!c.branchId)throw new BadRequestException('Active branch is required for lead merge.');
  return this.prisma.$transaction(async tx=>{
   type LeadRow={id:string;version:number;mergedIntoLeadId:string|null;source:string;sourceDetail:string|null;campaignId:string|null;campaignName:string|null;adSetId:string|null;adSetName:string|null;adId:string|null;adName:string|null;landingPage:string|null;referrer:string|null;utmSource:string|null;utmMedium:string|null;utmCampaign:string|null;utmContent:string|null;utmTerm:string|null;clickIdentifiers:unknown;acquisitionChannelId:string|null;acquisitionSourceId:string|null;acquisitionCampaignRefId:string|null;acquisitionAdSetRefId:string|null;acquisitionAdRefId:string|null};
   const leads=await tx.$queryRawUnsafe<LeadRow[]>(`SELECT id,version,merged_into_lead_id AS "mergedIntoLeadId",source,source_detail AS "sourceDetail",campaign_id AS "campaignId",campaign_name AS "campaignName",ad_set_id AS "adSetId",ad_set_name AS "adSetName",ad_id AS "adId",ad_name AS "adName",landing_page AS "landingPage",referrer,utm_source AS "utmSource",utm_medium AS "utmMedium",utm_campaign AS "utmCampaign",utm_content AS "utmContent",utm_term AS "utmTerm",click_identifiers AS "clickIdentifiers",acquisition_channel_id AS "acquisitionChannelId",acquisition_source_id AS "acquisitionSourceId",acquisition_campaign_ref_id AS "acquisitionCampaignRefId",acquisition_ad_set_ref_id AS "acquisitionAdSetRefId",acquisition_ad_ref_id AS "acquisitionAdRefId" FROM crm_leads WHERE id IN ($1::text,$2::text) AND tenant_id=$3::text AND company_id=$4::text AND branch_id=$5::text ORDER BY id FOR UPDATE`,sourceLeadId,targetLeadId,c.tenantId,c.companyId,c.branchId);
   const source=leads.find(x=>x.id===sourceLeadId),target=leads.find(x=>x.id===targetLeadId);if(!source||!target)throw new NotFoundException('Source or target CRM lead was not found in the active organization scope.');if(source.version!==sourceVersion||target.version!==targetVersion)throw new ConflictException('Lead version changed before merge.');if(source.mergedIntoLeadId||target.mergedIntoLeadId)throw new ConflictException('A selected lead has already been merged.');
   const opportunities=await tx.$queryRawUnsafe<Array<{id:string;leadId:string}>>(`SELECT id,lead_id AS "leadId" FROM crm_opportunities WHERE lead_id IN ($1::text,$2::text) AND tenant_id=$3::text AND company_id=$4::text AND branch_id=$5::text FOR UPDATE`,sourceLeadId,targetLeadId,c.tenantId,c.companyId,c.branchId);const so=opportunities.find(x=>x.leadId===sourceLeadId),to=opportunities.find(x=>x.leadId===targetLeadId);if(so&&to)throw new ConflictException('Both leads have opportunities. Resolve the opportunity conflict before merging leads.');
   if(so)await tx.$executeRawUnsafe(`UPDATE crm_opportunities SET lead_id=$2::text,version=version+1,updated_at=NOW() WHERE id=$1::text AND tenant_id=$3::text AND company_id=$4::text AND branch_id=$5::text`,so.id,targetLeadId,c.tenantId,c.companyId,c.branchId);
   await tx.$executeRawUnsafe(`UPDATE crm_follow_ups SET lead_id=$2::text,version=version+1,updated_at=NOW() WHERE lead_id=$1::text AND tenant_id=$3::text AND company_id=$4::text AND branch_id=$5::text`,sourceLeadId,targetLeadId,c.tenantId,c.companyId,c.branchId);
   await tx.$executeRawUnsafe(`UPDATE crm_messages SET lead_id=$2::text,version=version+1,updated_at=NOW() WHERE lead_id=$1::text AND tenant_id=$3::text AND company_id=$4::text AND branch_id=$5::text`,sourceLeadId,targetLeadId,c.tenantId,c.companyId,c.branchId);
   const merged=await tx.$queryRawUnsafe<Array<{id:string;version:number}>>(`UPDATE crm_leads SET merged_into_lead_id=$2::text,merged_at=NOW(),merged_by_user_id=$3::text,version=version+1,updated_at=NOW() WHERE id=$1::text AND tenant_id=$4::text AND company_id=$5::text AND branch_id=$6::text AND merged_into_lead_id IS NULL AND version=$7::int RETURNING id,version`,sourceLeadId,targetLeadId,actorUserId,c.tenantId,c.companyId,c.branchId,sourceVersion);if(!merged[0])throw new ConflictException('Source lead changed before merge could complete.');
   const survivor=await tx.$queryRawUnsafe<Array<{id:string;version:number}>>(`UPDATE crm_leads SET version=version+1,updated_at=NOW() WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND branch_id=$4::text AND merged_into_lead_id IS NULL AND version=$5::int RETURNING id,version`,targetLeadId,c.tenantId,c.companyId,c.branchId,targetVersion);if(!survivor[0])throw new ConflictException('Target lead changed before merge could complete.');
   const snapshot=(lead:LeadRow)=>({source:lead.source,sourceDetail:lead.sourceDetail,campaignId:lead.campaignId,campaignName:lead.campaignName,adSetId:lead.adSetId,adSetName:lead.adSetName,adId:lead.adId,adName:lead.adName,landingPage:lead.landingPage,referrer:lead.referrer,utmSource:lead.utmSource,utmMedium:lead.utmMedium,utmCampaign:lead.utmCampaign,utmContent:lead.utmContent,utmTerm:lead.utmTerm,clickIdentifiers:lead.clickIdentifiers,acquisitionChannelId:lead.acquisitionChannelId,acquisitionSourceId:lead.acquisitionSourceId,acquisitionCampaignRefId:lead.acquisitionCampaignRefId,acquisitionAdSetRefId:lead.acquisitionAdSetRefId,acquisitionAdRefId:lead.acquisitionAdRefId});
   const metadata=JSON.stringify({sourceLeadId,targetLeadId,reason:reason.trim().slice(0,1000),movedOpportunityId:so?.id??null,sourceVersionBefore:sourceVersion,targetVersionBefore:targetVersion,sourceAttribution:snapshot(source),targetAttribution:snapshot(target)});
   await tx.$executeRawUnsafe(`INSERT INTO crm_events(tenant_id,company_id,branch_id,lead_id,event_type,actor_user_id,metadata) VALUES($1::text,$2::text,$3::text,$4::text,'LEAD_MERGED_SOURCE',$6::text,$7::jsonb),($1::text,$2::text,$3::text,$5::text,'LEAD_MERGED_TARGET',$6::text,$7::jsonb)`,c.tenantId,c.companyId,c.branchId,sourceLeadId,targetLeadId,actorUserId,metadata);
   return{sourceLeadId,targetLeadId,sourceVersion:merged[0].version,targetVersion:survivor[0].version,movedOpportunityId:so?.id??null};
  });
 }
}
