import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';
import { CrmLostReasonService } from './crm-lost-reason.service';
@Injectable() export class CrmLostTransitionService{
 constructor(private readonly prisma:PrismaService,private readonly tenantContext:TenantContext,private readonly reasons:CrmLostReasonService){}
 async loseLead(id:string,input:{version:number;lostReasonId:string;lostReasonNote?:string|null},actorUserId:string){await this.reasons.assertUsable(input.lostReasonId);const c=this.tenantContext.getContext();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>('UPDATE crm_leads SET status=\'LOST\',lost_reason_id=$5,lost_reason_note=$6,lost_reason=NULL,version=version+1,updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND branch_id=$4 AND version=$7 AND merged_into_lead_id IS NULL RETURNING id,status,lost_reason_id AS "lostReasonId",lost_reason_note AS "lostReasonNote",version',id,c.tenantId,c.companyId,c.branchId,input.lostReasonId,input.lostReasonNote??null,input.version);if(!rows[0]){const exists=await tx.$queryRawUnsafe<any[]>('SELECT id FROM crm_leads WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND branch_id=$4',id,c.tenantId,c.companyId,c.branchId);if(!exists[0])throw new NotFoundException('CRM lead not found.');throw new ConflictException('Lead changed before lost transition.');}void actorUserId;return rows[0];});}
 async loseOpportunity(id:string,input:{version:number;lostReasonId:string;lostReasonNote?:string|null}){await this.reasons.assertUsable(input.lostReasonId);const c=this.tenantContext.getContext();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRawUnsafe<any[]>('UPDATE crm_opportunities SET stage=\'LOST\',probability=0,lost_reason_id=$5,lost_reason_note=$6,lost_reason=NULL,version=version+1,updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND branch_id=$4 AND version=$7 RETURNING id,stage,probability,lost_reason_id AS "lostReasonId",lost_reason_note AS "lostReasonNote",version',id,c.tenantId,c.companyId,c.branchId,input.lostReasonId,input.lostReasonNote??null,input.version);if(!rows[0]){const exists=await tx.$queryRawUnsafe<any[]>('SELECT id FROM crm_opportunities WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND branch_id=$4',id,c.tenantId,c.companyId,c.branchId);if(!exists[0])throw new NotFoundException('CRM opportunity not found.');throw new ConflictException('Opportunity changed before lost transition.');}return rows[0];});}
}
