import { UnauthorizedException } from '@nestjs/common';
import { CrmMessageWebhookService } from './crm-message-webhook.service';

describe('CrmMessageWebhookService',()=>{
 const delivery={type:'DELIVERY' as const,externalEventId:'evt-1',externalMessageId:'provider-msg-1',tenantId:'tenant-1',companyId:'company-1',branchId:'branch-1',status:'DELIVERED' as const};
 function makeService(options?:{verified?:boolean;event?:unknown;queries?:unknown[][];resolved?:unknown}){
  const queryResults=[...(options?.queries??[])],query=jest.fn().mockImplementation(async()=>queryResults.shift()??[]),execute=jest.fn().mockResolvedValue(1),transaction=jest.fn().mockImplementation(async(work:(tx:unknown)=>Promise<unknown>)=>work({$queryRawUnsafe:query,$executeRawUnsafe:execute}));
  const provider={key:'provider-a',channels:['WHATSAPP'] as const,send:jest.fn(),verifyWebhook:jest.fn().mockResolvedValue(options?.verified??true),parseWebhook:jest.fn().mockResolvedValue(options?.event??delivery)};
  const registry={resolveByKey:jest.fn().mockReturnValue(provider)},optOut={apply:jest.fn().mockResolvedValue(false)},contacts={resolveIdentity:jest.fn().mockResolvedValue(options?.resolved??{matched:false,reason:'NOT_FOUND'})};
  const service=new CrmMessageWebhookService({$transaction:transaction} as never,registry as never,optOut as never,contacts as never);
  return{service,provider,optOut,contacts,query,execute,transaction};
 }
 it('rejects an invalid signature before touching the database',async()=>{const{service,transaction,provider,contacts}=makeService({verified:false});await expect(service.handle('provider-a',{headers:{},body:{}})).rejects.toBeInstanceOf(UnauthorizedException);expect(provider.parseWebhook).not.toHaveBeenCalled();expect(contacts.resolveIdentity).not.toHaveBeenCalled();expect(transaction).not.toHaveBeenCalled();});
 it('treats a repeated external event as idempotent',async()=>{const{service,query}=makeService({queries:[[]]});await expect(service.handle('provider-a',{headers:{},body:{}})).resolves.toEqual({idempotent:true,outcome:'DUPLICATE'});expect(query).toHaveBeenCalledTimes(1);});
 it('applies a delivery receipt to the scoped provider message',async()=>{const{service,query,execute,contacts}=makeService({queries:[[{id:'webhook-1'}],[{id:'message-1',status:'SENT'}],[{id:'message-1'}]]});await expect(service.handle('provider-a',{headers:{},body:{}})).resolves.toEqual({idempotent:false,outcome:'PROCESSED',messageId:'message-1'});expect(contacts.resolveIdentity).not.toHaveBeenCalled();expect(query.mock.calls[1][0]).toContain('provider_key=$4');expect(query.mock.calls[2][0]).toContain("status IN ('QUEUED','SENT')");expect(execute).toHaveBeenCalledWith(expect.stringContaining('UPDATE crm_message_webhook_events'),'webhook-1','message-1','PROCESSED',null);});
 it('resolves an unbound inbound event with the canonical provider namespace before persistence',async()=>{const inbound={type:'INBOUND' as const,externalEventId:'evt-resolved',externalMessageId:'in-resolved',tenantId:'tenant-1',companyId:'company-1',branchId:'branch-1',channel:'WHATSAPP' as const,sender:'+905551112233',recipient:'+902120000000',body:'Merhaba',providerContactId:'contact-7',whatsappIdentity:'905551112233'};const{service,contacts,query}=makeService({event:inbound,resolved:{matched:true,customerId:null,leadId:'lead-7'},queries:[[{id:'webhook-r'}],[{id:'message-r'}]]});await expect(service.handle('provider-a',{headers:{},body:{}})).resolves.toEqual({idempotent:false,outcome:'PROCESSED',messageId:'message-r'});expect(contacts.resolveIdentity).toHaveBeenCalledWith({tenantId:'tenant-1',companyId:'company-1',branchId:'branch-1'},{providerKey:'provider-a',providerContactId:'contact-7',whatsappIdentity:'905551112233',phone:'+905551112233'});expect(query.mock.calls[1]).toEqual(expect.arrayContaining(['lead-7']));});
 it('keeps unresolved inbound events in the operations inbox when identity resolution is inconclusive',async()=>{const inbound={type:'INBOUND' as const,externalEventId:'evt-unresolved-1',externalMessageId:'in-unresolved-1',tenantId:'tenant-1',companyId:'company-1',branchId:'branch-1',channel:'WHATSAPP' as const,sender:'+905551112233',recipient:'+902120000000',body:'Bilgi almak istiyorum'};const{service,contacts,query,execute}=makeService({event:inbound,queries:[[{id:'webhook-unresolved'}],[{id:'inbox-1'}]]});await expect(service.handle('provider-a',{headers:{},body:{}})).resolves.toEqual({idempotent:false,outcome:'IGNORED',unresolvedInboxId:'inbox-1'});expect(contacts.resolveIdentity).toHaveBeenCalled();expect(query.mock.calls[1][0]).toContain('crm_unresolved_inbound_messages');expect(execute).toHaveBeenCalledWith(expect.stringContaining("error_message='Inbound subject is not mapped'"),'webhook-unresolved');});
 it('does not re-resolve a provider event that already contains a mapped CRM subject',async()=>{const inbound={type:'INBOUND' as const,externalEventId:'evt-in-1',externalMessageId:'in-1',tenantId:'tenant-1',companyId:'company-1',branchId:'branch-1',channel:'WHATSAPP' as const,sender:'+905551112233',recipient:'+902120000000',body:'Merhaba',customerId:'customer-1'};const{service,contacts,query,optOut}=makeService({event:inbound,queries:[[{id:'webhook-2'}],[{id:'message-2'}]]});await expect(service.handle('provider-a',{headers:{},body:{}})).resolves.toEqual({idempotent:false,outcome:'PROCESSED',messageId:'message-2'});expect(contacts.resolveIdentity).not.toHaveBeenCalled();expect(optOut.apply).toHaveBeenCalled();expect(query.mock.calls[1][0]).toContain("'INBOUND'");});
 it('links a repeated provider message id instead of creating a second inbound message',async()=>{const inbound={type:'INBOUND' as const,externalEventId:'evt-in-2',externalMessageId:'in-1',tenantId:'tenant-1',companyId:'company-1',branchId:'branch-1',channel:'WHATSAPP' as const,sender:'+905551112233',recipient:'+902120000000',body:'Merhaba tekrar',customerId:'customer-1'};const{service,query,execute}=makeService({event:inbound,queries:[[{id:'webhook-3'}],[],[{id:'message-existing'}]]});await expect(service.handle('provider-a',{headers:{},body:{}})).resolves.toEqual({idempotent:false,outcome:'IGNORED',messageId:'message-existing'});expect(query.mock.calls[2][0]).toContain('external_message_id=$5');expect(execute).toHaveBeenCalledWith(expect.stringContaining('UPDATE crm_message_webhook_events'),'webhook-3','message-existing','IGNORED','Inbound message already exists');});
});
