import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';
export interface DuplicateSignals{phone?:string|null;alternativePhone?:string|null;email?:string|null;providerKey?:string|null;providerContactId?:string|null;whatsappIdentity?:string|null;}
export interface LeadDuplicateCandidate{id:string;firstName:string;lastName:string;status:string;branchId:string;confidence:number;matchedSignals:string[];updatedAt:Date;}
@Injectable() export class CrmLeadDuplicateService{
 constructor(private readonly prisma:PrismaService,private readonly tenantContext:TenantContext){}
 async findCandidatesForLead(leadId:string){const c=this.tenantContext.getContext();const s=await this.prisma.$queryRawUnsafe<Array<DuplicateSignals&{id:string}>>('SELECT id,phone,alternative_phone AS "alternativePhone",email,provider_contact_provider_key AS "providerKey",provider_contact_id AS "providerContactId",whatsapp_identity AS "whatsappIdentity" FROM crm_leads WHERE id=$1 AND tenant_id=$2 AND company_id=$3 AND ($4::text IS NULL OR branch_id=$4) LIMIT 1',leadId,c.tenantId,c.companyId,c.branchId??null);if(!s[0])throw new NotFoundException('CRM lead not found in the active organization scope.');return this.findCandidates(s[0],leadId);}
 async findCandidates(signals:DuplicateSignals,excludeLeadId?:string):Promise<LeadDuplicateCandidate[]>{const c=this.tenantContext.getContext();const phone=signals.phone?.replace(/\D/g,'')||null,alt=signals.alternativePhone?.replace(/\D/g,'')||null,email=signals.email?.trim().toLowerCase()||null,providerKey=signals.providerKey?.trim().toLowerCase()||null,providerId=signals.providerContactId?.trim()||null,wa=signals.whatsappIdentity?.replace(/\D/g,'')||null;if(!phone&&!alt&&!email&&!(providerKey&&providerId)&&!wa)return[];return this.prisma.$queryRawUnsafe<LeadDuplicateCandidate[]>(`SELECT id,first_name AS "firstName",last_name AS "lastName",status,branch_id AS "branchId",updated_at AS "updatedAt",GREATEST(CASE WHEN $4 IS NOT NULL AND $5 IS NOT NULL AND provider_contact_provider_key=$4 AND provider_contact_id=$5 THEN 100 ELSE 0 END,CASE WHEN $6 IS NOT NULL AND whatsapp_identity=$6 THEN 95 ELSE 0 END,CASE WHEN ($2 IS NOT NULL AND (normalized_phone=$2 OR normalized_alternative_phone=$2)) OR ($1 IS NOT NULL AND (normalized_phone=$1 OR normalized_alternative_phone=$1)) THEN 90 ELSE 0 END,CASE WHEN $3 IS NOT NULL AND normalized_email=$3 THEN 85 ELSE 0 END) AS confidence,array_remove(ARRAY[CASE WHEN $4 IS NOT NULL AND $5 IS NOT NULL AND provider_contact_provider_key=$4 AND provider_contact_id=$5 THEN 'providerContact' END,CASE WHEN $6 IS NOT NULL AND whatsapp_identity=$6 THEN 'whatsapp' END,CASE WHEN $2 IS NOT NULL AND (normalized_phone=$2 OR normalized_alternative_phone=$2) THEN 'phone' END,CASE WHEN $1 IS NOT NULL AND (normalized_phone=$1 OR normalized_alternative_phone=$1) THEN 'alternativePhone' END,CASE WHEN $3 IS NOT NULL AND normalized_email=$3 THEN 'email' END],NULL) AS "matchedSignals" FROM crm_leads WHERE tenant_id=$7 AND company_id=$8 AND merged_into_lead_id IS NULL AND ($9::text IS NULL OR id<>$9) AND (($4 IS NOT NULL AND $5 IS NOT NULL AND provider_contact_provider_key=$4 AND provider_contact_id=$5) OR ($6 IS NOT NULL AND whatsapp_identity=$6) OR ($2 IS NOT NULL AND (normalized_phone=$2 OR normalized_alternative_phone=$2)) OR ($3 IS NOT NULL AND normalized_email=$3) OR ($1 IS NOT NULL AND (normalized_phone=$1 OR normalized_alternative_phone=$1))) ORDER BY confidence DESC,updated_at DESC LIMIT 20`,alt,phone,email,providerKey,providerId,wa,c.tenantId,c.companyId,excludeLeadId??null);}
}
