import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';
import type { CreateLeadInput, UpdateLeadInput } from './crm.schemas';
type DbClient=Prisma.TransactionClient|PrismaService;
type AcquisitionInput=Pick<CreateLeadInput,'acquisitionChannelId'|'acquisitionSourceId'|'acquisitionCampaignRefId'|'acquisitionAdSetRefId'|'acquisitionAdRefId'>|Pick<UpdateLeadInput,'acquisitionChannelId'|'acquisitionSourceId'|'acquisitionCampaignRefId'|'acquisitionAdSetRefId'|'acquisitionAdRefId'>;
export interface ResolvedAcquisitionRefs{acquisitionChannelId:string|null;acquisitionSourceId:string|null;acquisitionCampaignRefId:string|null;acquisitionAdSetRefId:string|null;acquisitionAdRefId:string|null;}
@Injectable() export class CrmAcquisitionService{
 constructor(private readonly prisma:PrismaService,private readonly tenantContext:TenantContext){}
 private context(){return this.tenantContext.getContext();}
 hasRefChanges(input:AcquisitionInput){return input.acquisitionChannelId!==undefined||input.acquisitionSourceId!==undefined||input.acquisitionCampaignRefId!==undefined||input.acquisitionAdSetRefId!==undefined||input.acquisitionAdRefId!==undefined;}
 async getLeadRefs(leadId:string):Promise<ResolvedAcquisitionRefs>{const c=this.context();const rows=await this.prisma.$queryRawUnsafe<Array<ResolvedAcquisitionRefs>>(`SELECT acquisition_channel_id AS "acquisitionChannelId",acquisition_source_id AS "acquisitionSourceId",acquisition_campaign_ref_id AS "acquisitionCampaignRefId",acquisition_ad_set_ref_id AS "acquisitionAdSetRefId",acquisition_ad_ref_id AS "acquisitionAdRefId" FROM crm_leads WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) LIMIT 1`,leadId,c.tenantId,c.companyId,c.branchId);if(!rows.length)throw new NotFoundException('CRM lead not found.');return rows[0];}
 async resolveRefs(input:AcquisitionInput,tx:DbClient=this.prisma):Promise<ResolvedAcquisitionRefs>{const c=this.context();const rows=await tx.$queryRawUnsafe<Array<ResolvedAcquisitionRefs>>(`SELECT ch.id AS "acquisitionChannelId",s.id AS "acquisitionSourceId",cp.id AS "acquisitionCampaignRefId",a.id AS "acquisitionAdSetRefId",ad.id AS "acquisitionAdRefId" FROM (SELECT 1) q LEFT JOIN crm_acquisition_channels ch ON ch.id=$3::uuid AND ch.tenant_id=$1::text AND ch.company_id=$2::text LEFT JOIN crm_acquisition_sources s ON s.id=$4::uuid AND s.tenant_id=$1::text AND s.company_id=$2::text LEFT JOIN crm_acquisition_campaigns cp ON cp.id=$5::uuid AND cp.tenant_id=$1::text AND cp.company_id=$2::text LEFT JOIN crm_acquisition_ad_sets a ON a.id=$6::uuid AND a.tenant_id=$1::text AND a.company_id=$2::text LEFT JOIN crm_acquisition_ads ad ON ad.id=$7::uuid AND ad.tenant_id=$1::text AND ad.company_id=$2::text WHERE ($4::uuid IS NULL OR s.channel_id=COALESCE($3::uuid,s.channel_id)) AND ($5::uuid IS NULL OR cp.source_id=COALESCE($4::uuid,cp.source_id)) AND ($6::uuid IS NULL OR a.campaign_id=COALESCE($5::uuid,a.campaign_id)) AND ($7::uuid IS NULL OR ad.ad_set_id=COALESCE($6::uuid,ad.ad_set_id)) LIMIT 1`,c.tenantId,c.companyId,input.acquisitionChannelId??null,input.acquisitionSourceId??null,input.acquisitionCampaignRefId??null,input.acquisitionAdSetRefId??null,input.acquisitionAdRefId??null);if(!rows.length)throw new BadRequestException('Acquisition references are outside the active company or hierarchy.');return rows[0];}
 async persistLeadRefs(leadId:string,input:AcquisitionInput,expectedVersion?:number){const c=this.context();return this.prisma.$transaction(async tx=>{const current=await tx.$queryRawUnsafe<Array<ResolvedAcquisitionRefs&{version:number}>>(`SELECT acquisition_channel_id AS "acquisitionChannelId",acquisition_source_id AS "acquisitionSourceId",acquisition_campaign_ref_id AS "acquisitionCampaignRefId",acquisition_ad_set_ref_id AS "acquisitionAdSetRefId",acquisition_ad_ref_id AS "acquisitionAdRefId",version FROM crm_leads WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,leadId,c.tenantId,c.companyId,c.branchId);if(!current[0])throw new NotFoundException('CRM lead not found.');if(expectedVersion!==undefined&&current[0].version!==expectedVersion)throw new ConflictException('Lead changed before acquisition attribution update.');const merged:any={};for(const k of ['acquisitionChannelId','acquisitionSourceId','acquisitionCampaignRefId','acquisitionAdSetRefId','acquisitionAdRefId'] as const)merged[k]=(input as any)[k]===undefined?current[0][k]:(input as any)[k];const r=await this.resolveRefs(merged,tx);await tx.$executeRawUnsafe(`UPDATE crm_leads SET acquisition_channel_id=$5::uuid,acquisition_source_id=$6::uuid,acquisition_campaign_ref_id=$7::uuid,acquisition_ad_set_ref_id=$8::uuid,acquisition_ad_ref_id=$9::uuid,updated_at=NOW() WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text)`,leadId,c.tenantId,c.companyId,c.branchId,r.acquisitionChannelId,r.acquisitionSourceId,r.acquisitionCampaignRefId,r.acquisitionAdSetRefId,r.acquisitionAdRefId);return r;});}
}
