import { EnterpriseDataPage } from "@/components/enterprise-data-page";
export default function PlatformControlPlanePage(){return <EnterpriseDataPage eyebrow="VALOO Platform Yönetimi" title="Platform Operasyon Merkezi" description="İşletme kurulumu, abonelik, müşteri başarısı, destek ve kullanım haklarını merkezi olarak yönetin." sections={[
{title:"Kurulum Özeti",path:"/platform/provisioning/summary"},
{title:"Kurulum İşlemleri",path:"/platform/provisioning?limit=100"},
{title:"Paketler ve Planlar",path:"/platform/plans"},
{title:"Müşteri Başarısı",path:"/platform/customer-success?limit=100"},
{title:"İşletme Sağlığı",path:"/platform/customer-success/health?limit=100"},
{title:"Destek Özeti",path:"/platform/support/summary"},
{title:"Destek Talepleri",path:"/platform/support/tickets?limit=100"},
{title:"Destek Yanıt Süresi Politikaları",path:"/platform/support/sla/policies"},
{title:"Destek Oturumları",path:"/platform/support-sessions?limit=100"},
{title:"Kullanım Hakları Kataloğu",path:"/platform/entitlements"},
]} actions={[
{label:"Bekleyen Sahip Davetlerini Gönder",path:"/platform/provisioning/owner-invitations/dispatch-due",body:{limit:10,reason:"Platform yönetim ekranı tetikledi"},success:"Bekleyen sahip davetleri işlendi."}
]} forms={[
{title:"Yeni İşletme Kurulumu Başlat",path:"/platform/provisioning",fields:[{name:"tenantName",label:"İşletme Adı",required:true},{name:"tenantSlug",label:"İşletme Kısa Adı",required:true},{name:"planVersionId",label:"Plan Sürümü Kodu",required:true},{name:"companyName",label:"Şirket Adı",required:true},{name:"companySlug",label:"Şirket Kısa Adı",required:true},{name:"primaryBranchName",label:"İlk Şube Adı",required:true},{name:"primaryBranchCode",label:"İlk Şube Kodu",required:true},{name:"sourceType",label:"Kaynak",type:"select",defaultValue:"MANUAL",options:[{value:"MANUAL",label:"Manuel"},{value:"OPPORTUNITY",label:"Fırsat"}]},{name:"ownerEmail",label:"Şirket Sahibi E-posta"},{name:"reason",label:"Açıklama",type:"textarea"}]},
{title:"Paket / Plan Versiyonu Oluştur",path:"/platform/plans/versions",fields:[{name:"code",label:"Plan Kodu",required:true},{name:"name",label:"Plan Adı",required:true},{name:"description",label:"Açıklama",type:"textarea"},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"monthlyPrice",label:"Aylık Fiyat",type:"number"},{name:"annualPrice",label:"Yıllık Fiyat",type:"number"},{name:"branchLimit",label:"Şube Limiti",type:"number"},{name:"userLimit",label:"Kullanıcı Limiti",type:"number"}]},
{title:"İşletme Aboneliği Ata",path:"/platform/customers/{tenantId}/subscription",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"planVersionId",label:"Plan Sürümü Kodu",required:true},{name:"status",label:"Durum",type:"select",defaultValue:"TRIAL",options:[{value:"TRIAL",label:"Deneme"},{value:"ACTIVE",label:"Aktif"},{value:"PAST_DUE",label:"Gecikmiş"}]},{name:"contractedMonthlyPrice",label:"Sözleşmeli Aylık Fiyat",type:"number"},{name:"contractedAnnualPrice",label:"Sözleşmeli Yıllık Fiyat",type:"number"},{name:"discountPercent",label:"İndirim %",type:"number"},{name:"startsAt",label:"Başlangıç",type:"datetime-local"},{name:"renewsAt",label:"Yenileme",type:"datetime-local"}]},
{title:"Kurulum İşlemini Devam Ettir",path:"/platform/provisioning/{runId}/resume",fields:[{name:"runId",label:"Kurulum İşlemi Kodu",required:true},{name:"reason",label:"Açıklama",type:"textarea",required:true}]},
{title:"Şirket Sahibi Davetini Hazırla",path:"/platform/provisioning/{runId}/owner-invitation",fields:[{name:"runId",label:"Kurulum İşlemi Kodu",required:true},{name:"ownerEmail",label:"Şirket Sahibi E-posta",required:true},{name:"reason",label:"Açıklama",type:"textarea"}]},
{title:"Şirket Sahibi Davetini Gönder",path:"/platform/provisioning/{runId}/owner-invitation/dispatch",fields:[{name:"runId",label:"Kurulum İşlemi Kodu",required:true},{name:"reason",label:"Açıklama",type:"textarea",required:true}]},
{title:"İşletmeyi Canlıya Al",path:"/platform/provisioning/{runId}/go-live",fields:[{name:"runId",label:"Kurulum İşlemi Kodu",required:true},{name:"reason",label:"Açıklama",type:"textarea",required:true}]},
{title:"İşletme Başlangıç Kurulumunu Başlat",path:"/platform/onboarding/{tenantId}/bootstrap",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"provisioningRunId",label:"Kurulum İşlemi Kodu"},{name:"reason",label:"Açıklama",type:"textarea"}]},
{title:"Destek Talebi Oluştur",path:"/platform/support/tickets",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"subject",label:"Konu",required:true},{name:"description",label:"Açıklama",type:"textarea"},{name:"priority",label:"Öncelik",defaultValue:"NORMAL"},{name:"source",label:"Kaynak",defaultValue:"PLATFORM"},{name:"requesterEmail",label:"Talep Eden E-posta"},{name:"assignedPlatformUserId",label:"Atanan Platform Kullanıcısı Kodu"}]},
{title:"Destek Yanıt Süresi Politikası Oluştur",path:"/platform/support/sla/policies",fields:[{name:"priority",label:"Öncelik",required:true},{name:"name",label:"Politika Adı",required:true},{name:"initialResponseMinutes",label:"İlk Yanıt Dakika",type:"number",required:true},{name:"resolutionMinutes",label:"Çözüm Dakika",type:"number",required:true},{name:"reason",label:"Açıklama",type:"textarea"}]},
{title:"Destek Oturumu Talep Et",path:"/platform/support-sessions/request",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"supportTicketId",label:"Destek Talebi Kodu"},{name:"accessMode",label:"Erişim Modu",type:"select",defaultValue:"READ_ONLY",options:[{value:"READ_ONLY",label:"Salt Okunur"},{value:"CONTROLLED_WRITE",label:"Kontrollü Yazma"}]},{name:"durationMinutes",label:"Süre (dakika)",type:"number",defaultValue:"30"},{name:"reason",label:"Açıklama",type:"textarea",required:true}]},
{title:"Onaylı Destek Oturumunu Aç",path:"/platform/support-sessions/requests/{requestId}/open",fields:[{name:"requestId",label:"Destek Oturumu Talep Kodu",required:true}]},
{title:"Destek Oturumunu Sonlandır",path:"/platform/support-sessions/{sessionId}/revoke",fields:[{name:"sessionId",label:"Destek Oturumu Kodu",required:true},{name:"reason",label:"Açıklama",type:"textarea",required:true}]},
{title:"Müşteri Başarısı Kaydı Ekle",path:"/platform/customer-success/{tenantId}/events",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"eventType",label:"Olay Türü",required:true},{name:"severity",label:"Önem",required:true},{name:"summary",label:"Özet",required:true},{name:"happenedAt",label:"Olay Tarihi",type:"datetime-local"}]},
{title:"İşletme Sağlığını Yeniden Hesapla",path:"/platform/customer-success/{tenantId}/health/recalculate",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"reason",label:"Açıklama",type:"textarea"}]},
{title:"Müşteri Başarısı Kaydını Güncelle",path:"/platform/customer-success/{tenantId}",method:"PATCH",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"segment",label:"Segment"},{name:"successStage",label:"Başarı Aşaması"},{name:"riskStatus",label:"Risk Durumu"},{name:"riskReason",label:"Risk Açıklamai",type:"textarea"},{name:"nextReviewAt",label:"Sonraki Değerlendirme",type:"datetime-local"},{name:"reason",label:"Değişiklik Açıklamai",type:"textarea",required:true}]},
{title:"Başlangıç Kurulumu Maddesini Güncelle",path:"/platform/onboarding/{tenantId}/items/{itemKey}",method:"PATCH",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"itemKey",label:"Kurulum Maddesi",required:true},{name:"status",label:"Durum",type:"select",required:true,options:[{value:"PENDING",label:"Bekliyor"},{value:"IN_PROGRESS",label:"Devam Ediyor"},{value:"BLOCKED",label:"Bloke"},{value:"COMPLETED",label:"Tamamlandı"},{value:"SKIPPED",label:"Atlandı"}]},{name:"notes",label:"Not",type:"textarea"},{name:"reason",label:"Değişiklik Açıklamai",type:"textarea"}]},
{title:"Destek Talebini Güncelle",path:"/platform/support/tickets/{ticketId}",method:"PATCH",fields:[{name:"ticketId",label:"Destek Talebi Kodu",required:true},{name:"status",label:"Durum"},{name:"priority",label:"Öncelik"},{name:"assignedPlatformUserId",label:"Atanan Platform Kullanıcısı Kodu"},{name:"note",label:"İç Not",type:"textarea"},{name:"reason",label:"Değişiklik Açıklamai",type:"textarea",required:true}]},
{title:"Destek Talebine Yanıt Ekle",path:"/platform/support/tickets/{ticketId}/respond",fields:[{name:"ticketId",label:"Destek Talebi Kodu",required:true},{name:"note",label:"Yanıt / Not",type:"textarea",required:true}]},
{title:"Plan Kullanım Hakkını Güncelle",path:"/platform/plans/{planVersionId}/entitlements/{entitlementKey}",fields:[{name:"planVersionId",label:"Plan Sürümü Kodu",required:true},{name:"entitlementKey",label:"Kullanım Hakkı Anahtarı",required:true},{name:"value",label:"Değer",type:"json",required:true,placeholder:"Evet/Hayır, sayı, metin veya örneğe uygun yapı"}]},
{title:"İşletme Kullanım Hakkı İstisnası Oluştur",path:"/platform/customers/{tenantId}/entitlement-overrides",fields:[{name:"tenantId",label:"İşletme Kodu",required:true},{name:"entitlementKey",label:"Kullanım Hakkı",required:true},{name:"value",label:"Değer",required:true},{name:"reason",label:"Açıklama",type:"textarea",required:true},{name:"startsAt",label:"Başlangıç",type:"datetime-local"},{name:"endsAt",label:"Bitiş",type:"datetime-local"}]}
]} />;}
