import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class TrainingOperationsBridgeService {
  constructor(private readonly prisma: PrismaService, private readonly tenant: TenantContext) {}
  private c(){return{tenantId:this.tenant.getTenantId(),companyId:this.tenant.getCompanyId(),branchId:this.tenant.getBranchId()};}

  async catalogs(){const c=this.c();const [trainingCompetencies,hrCompetencies,courses,hrCertificationTypes]=await Promise.all([
    this.prisma.$queryRawUnsafe<any[]>(`SELECT id,code,name FROM competency_definitions WHERE tenant_id=$1::text AND company_id=$2::text AND is_active=true ORDER BY code`,c.tenantId,c.companyId),
    this.prisma.$queryRawUnsafe<any[]>(`SELECT id,code,name,max_level AS "maxLevel" FROM hr_competencies WHERE tenant_id=$1::text AND company_id=$2::text AND active=true ORDER BY code`,c.tenantId,c.companyId),
    this.prisma.$queryRawUnsafe<any[]>(`SELECT id,code,title FROM training_courses WHERE tenant_id=$1::text AND company_id=$2::text AND is_active=true ORDER BY code`,c.tenantId,c.companyId),
    this.prisma.$queryRawUnsafe<any[]>(`SELECT id,code,name,requires_expiry AS "requiresExpiry" FROM hr_certification_types WHERE tenant_id=$1::text AND company_id=$2::text AND active=true ORDER BY code`,c.tenantId,c.companyId),
  ]);return{trainingCompetencies,hrCompetencies,courses,hrCertificationTypes};}

  async mapCompetency(input:{trainingCompetencyId:string;hrCompetencyId:string},actor:string){const c=this.c();const [a,b]=await Promise.all([this.prisma.$queryRawUnsafe<any[]>(`SELECT id FROM competency_definitions WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND is_active=true`,input.trainingCompetencyId,c.tenantId,c.companyId),this.prisma.$queryRawUnsafe<any[]>(`SELECT id FROM hr_competencies WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND active=true`,input.hrCompetencyId,c.tenantId,c.companyId)]);if(!a.length||!b.length)throw new NotFoundException('Training or HR competency is outside active scope.');return (await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO training_hr_competency_mappings(tenant_id,company_id,training_competency_id,hr_competency_id,created_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5::text) ON CONFLICT(tenant_id,company_id,training_competency_id) DO UPDATE SET hr_competency_id=EXCLUDED.hr_competency_id RETURNING id,training_competency_id AS "trainingCompetencyId",hr_competency_id AS "hrCompetencyId"`,c.tenantId,c.companyId,input.trainingCompetencyId,input.hrCompetencyId,actor))[0];}

  async mapCertification(input:{courseId:string;hrCertificationTypeId:string},actor:string){const c=this.c();const [a,b]=await Promise.all([this.prisma.$queryRawUnsafe<any[]>(`SELECT id FROM training_courses WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND is_active=true`,input.courseId,c.tenantId,c.companyId),this.prisma.$queryRawUnsafe<any[]>(`SELECT id FROM hr_certification_types WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND active=true`,input.hrCertificationTypeId,c.tenantId,c.companyId)]);if(!a.length||!b.length)throw new NotFoundException('Training course or HR certification type is outside active scope.');return (await this.prisma.$queryRawUnsafe<any[]>(`INSERT INTO training_hr_certification_mappings(tenant_id,company_id,course_id,hr_certification_type_id,created_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5::text) ON CONFLICT(tenant_id,company_id,course_id) DO UPDATE SET hr_certification_type_id=EXCLUDED.hr_certification_type_id RETURNING id,course_id AS "courseId",hr_certification_type_id AS "hrCertificationTypeId"`,c.tenantId,c.companyId,input.courseId,input.hrCertificationTypeId,actor))[0];}

  async mappings(){const c=this.c();const [competencies,certifications]=await Promise.all([this.prisma.$queryRawUnsafe<any[]>(`SELECT m.id,m.training_competency_id AS "trainingCompetencyId",d.code AS "trainingCode",d.name AS "trainingName",m.hr_competency_id AS "hrCompetencyId",h.code AS "hrCode",h.name AS "hrName" FROM training_hr_competency_mappings m JOIN competency_definitions d ON d.id=m.training_competency_id JOIN hr_competencies h ON h.id=m.hr_competency_id WHERE m.tenant_id=$1::text AND m.company_id=$2::text ORDER BY d.code`,c.tenantId,c.companyId),this.prisma.$queryRawUnsafe<any[]>(`SELECT m.id,m.course_id AS "courseId",c.code AS "courseCode",c.title AS "courseTitle",m.hr_certification_type_id AS "hrCertificationTypeId",h.code AS "hrCode",h.name AS "hrName" FROM training_hr_certification_mappings m JOIN training_courses c ON c.id=m.course_id JOIN hr_certification_types h ON h.id=m.hr_certification_type_id WHERE m.tenant_id=$1::text AND m.company_id=$2::text ORDER BY c.code`,c.tenantId,c.companyId)]);return{competencies,certifications};}

  async process(actor:string,limit=100){const c=this.c(),safe=Math.min(Math.max(Math.trunc(Number(limit)||100),1),500);return this.prisma.$transaction(async tx=>{let competencySynced=0,certificationSynced=0,revokedSynced=0,skippedMissingExpiry=0;const assessments=await tx.$queryRawUnsafe<any[]>(`SELECT a.id AS "sourceId",a.branch_id AS "branchId",a.staff_id AS "staffId",a.score,a.assessed_at AS "assessedAt",m.hr_competency_id AS "hrCompetencyId",h.max_level AS "maxLevel" FROM staff_competency_assessments a JOIN training_hr_competency_mappings m ON m.tenant_id=a.tenant_id AND m.company_id=a.company_id AND m.training_competency_id=a.competency_id JOIN hr_competencies h ON h.id=m.hr_competency_id WHERE a.tenant_id=$1::text AND a.company_id=$2::text AND a.source_type='TRAINING' AND ($3::text IS NULL OR a.branch_id=$3::text) AND NOT EXISTS(SELECT 1 FROM training_operations_bridge_events e WHERE e.tenant_id=a.tenant_id AND e.company_id=a.company_id AND e.source_type='COMPETENCY_ASSESSMENT' AND e.source_id=a.id) ORDER BY a.assessed_at,a.id FOR UPDATE OF a SKIP LOCKED LIMIT $4`,c.tenantId,c.companyId,c.branchId,safe);for(const row of assessments){const level=Math.max(0,Math.min(Number(row.maxLevel),Math.round(Number(row.score)/100*Number(row.maxLevel))));const target=(await tx.$queryRawUnsafe<any[]>(`INSERT INTO hr_employee_competency_assessments(id,tenant_id,company_id,branch_id,staff_id,competency_id,level,assessment_type,assessed_at,assessed_by,evidence,notes) VALUES(gen_random_uuid()::text,$1::text,$2::text,$3::text,$4::text,$5::text,$6,'SYSTEM',$7::date,$8::text,$9,$10) RETURNING id`,c.tenantId,c.companyId,row.branchId,row.staffId,row.hrCompetencyId,level,new Date(row.assessedAt).toISOString().slice(0,10),actor,`training-assessment:${row.sourceId}`,'Synced from Training completion'))[0];await tx.$executeRawUnsafe(`INSERT INTO training_operations_bridge_events(tenant_id,company_id,branch_id,source_type,source_id,target_type,target_id,detail,actor_user_id) VALUES($1::text,$2::text,$3::text,'COMPETENCY_ASSESSMENT',$4::text,'HR_COMPETENCY_ASSESSMENT',$5::text,$6::jsonb,$7::text) ON CONFLICT DO NOTHING`,c.tenantId,c.companyId,row.branchId,row.sourceId,target.id,JSON.stringify({score:Number(row.score),level,maxLevel:Number(row.maxLevel)}),actor);competencySynced++;}

    const remaining=Math.max(safe-assessments.length,0);if(remaining>0){const certs=await tx.$queryRawUnsafe<any[]>(`SELECT cert.id AS "sourceId",cert.branch_id AS "branchId",cert.staff_id AS "staffId",cert.certificate_no AS "certificateNo",cert.issued_at AS "issuedAt",cert.expires_at AS "expiresAt",v.course_id AS "courseId",c.title AS "courseTitle",m.hr_certification_type_id AS "hrCertificationTypeId",ht.requires_expiry AS "requiresExpiry" FROM training_certificates cert JOIN training_course_versions v ON v.id=cert.course_version_id JOIN training_courses c ON c.id=v.course_id JOIN training_hr_certification_mappings m ON m.tenant_id=cert.tenant_id AND m.company_id=cert.company_id AND m.course_id=v.course_id JOIN hr_certification_types ht ON ht.id=m.hr_certification_type_id WHERE cert.tenant_id=$1::text AND cert.company_id=$2::text AND cert.status IN('ACTIVE','RENEWAL_ASSIGNED') AND cert.staff_id IS NOT NULL AND ($3::text IS NULL OR cert.branch_id=$3::text) AND NOT EXISTS(SELECT 1 FROM training_operations_bridge_events e WHERE e.tenant_id=cert.tenant_id AND e.company_id=cert.company_id AND e.source_type='TRAINING_CERTIFICATE' AND e.source_id=cert.id) ORDER BY cert.issued_at,cert.id FOR UPDATE OF cert SKIP LOCKED LIMIT $4`,c.tenantId,c.companyId,c.branchId,remaining);for(const row of certs){if(row.requiresExpiry&&!row.expiresAt){skippedMissingExpiry++;continue;}let target=(await tx.$queryRawUnsafe<any[]>(`SELECT id FROM hr_employee_certifications WHERE tenant_id=$1::text AND company_id=$2::text AND staff_id=$3::text AND certification_type_id=$4::text AND credential_number=$5 LIMIT 1`,c.tenantId,c.companyId,row.staffId,row.hrCertificationTypeId,row.certificateNo))[0];if(!target){target=(await tx.$queryRawUnsafe<any[]>(`INSERT INTO hr_employee_certifications(id,tenant_id,company_id,branch_id,staff_id,certification_type_id,credential_number,issuing_organization,qualification,issued_at,expires_at,status,verified_at,verified_by,verification_note,notes,created_by) VALUES(gen_random_uuid()::text,$1::text,$2::text,$3::text,$4::text,$5::text,$6,'Beauty ERP Training',$7,$8::date,$9::date,'VERIFIED',now(),$10::text,'System verified from passed Training certification',$11,$10::text) RETURNING id`,c.tenantId,c.companyId,row.branchId,row.staffId,row.hrCertificationTypeId,row.certificateNo,row.courseTitle,new Date(row.issuedAt).toISOString().slice(0,10),row.expiresAt?new Date(row.expiresAt).toISOString().slice(0,10):null,actor,`training-certificate:${row.sourceId}`))[0];}await tx.$executeRawUnsafe(`INSERT INTO training_operations_bridge_events(tenant_id,company_id,branch_id,source_type,source_id,target_type,target_id,detail,actor_user_id) VALUES($1::text,$2::text,$3::text,'TRAINING_CERTIFICATE',$4::text,'HR_EMPLOYEE_CERTIFICATION',$5::text,$6::jsonb,$7::text) ON CONFLICT DO NOTHING`,c.tenantId,c.companyId,row.branchId,row.sourceId,target.id,JSON.stringify({courseId:row.courseId,certificateNo:row.certificateNo}),actor);certificationSynced++;}}

    const revoked=await tx.$queryRawUnsafe<any[]>(`SELECT e.id AS "bridgeEventId",e.source_id AS "sourceId",e.target_id AS "targetId" FROM training_operations_bridge_events e JOIN training_certificates cert ON cert.id=e.source_id AND cert.tenant_id=e.tenant_id AND cert.company_id=e.company_id JOIN hr_employee_certifications hc ON hc.id=e.target_id AND hc.tenant_id=e.tenant_id AND hc.company_id=e.company_id WHERE e.tenant_id=$1::text AND e.company_id=$2::text AND e.source_type='TRAINING_CERTIFICATE' AND e.target_type='HR_EMPLOYEE_CERTIFICATION' AND cert.status='REVOKED' AND hc.status<>'REVOKED' AND ($3::text IS NULL OR cert.branch_id=$3::text) ORDER BY cert.revoked_at,e.id FOR UPDATE OF hc SKIP LOCKED LIMIT $4`,c.tenantId,c.companyId,c.branchId,safe);for(const row of revoked){await tx.$executeRawUnsafe(`UPDATE hr_employee_certifications SET status='REVOKED',verified_at=now(),verified_by=$2::text,verification_note='Revoked because source Training certificate was revoked',updated_at=now() WHERE id=$1::text`,row.targetId,actor);await tx.$executeRawUnsafe(`UPDATE training_operations_bridge_events SET detail=detail||jsonb_build_object('revokedSyncedAt',now()) WHERE id=$1::text`,row.bridgeEventId);revokedSynced++;}
    return{claimed:assessments.length+certificationSynced,competencySynced,certificationSynced,revokedSynced,skippedMissingExpiry};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
}
