import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, PrismaService } from '@beauty-erp/database';
import { TenantContext } from '../../common/tenant/tenant-context';

@Injectable()
export class TrainingPlanningService {
  constructor(private readonly prisma:PrismaService,private readonly tenant:TenantContext){}
  private c(){return{tenantId:this.tenant.getTenantId(),companyId:this.tenant.getCompanyId(),branchId:this.tenant.getBranchId()};}
  private async staff(tx:any,staffId:string,branchId:string){const c=this.c();if(c.branchId&&c.branchId!==branchId)throw new BadRequestException('Branch outside active scope.');const rows:any[]=await tx.$queryRawUnsafe(`SELECT id FROM staff WHERE id=$1::text AND "tenantId"=$2::text AND "branchId"=$3::text LIMIT 1`,staffId,c.tenantId,branchId);if(!rows.length)throw new BadRequestException('Staff outside tenant/branch scope.');}

  async createSession(input:{branchId:string;courseId:string;title?:string;startsAt:string;endsAt:string;capacity?:number|null;location?:string|null;instructorUserId?:string|null},actor:string){const c=this.c();if(c.branchId&&c.branchId!==input.branchId)throw new BadRequestException('Branch outside active scope.');const start=new Date(input.startsAt),end=new Date(input.endsAt);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start)throw new BadRequestException('Invalid session time range.');const cap=input.capacity==null?null:Math.trunc(Number(input.capacity));if(cap!=null&&cap<1)throw new BadRequestException('capacity must be positive.');return this.prisma.$transaction(async tx=>{const course=await tx.$queryRawUnsafe<any[]>(`SELECT c.id,c.title,v.id AS "courseVersionId" FROM training_courses c LEFT JOIN training_course_versions v ON v.tenant_id=c.tenant_id AND v.company_id=c.company_id AND v.course_id=c.id AND v.status='PUBLISHED' WHERE c.id=$1::text AND c.tenant_id=$2::text AND c.company_id=$3::text AND c.is_active=true LIMIT 1`,input.courseId,c.tenantId,c.companyId);if(!course.length)throw new NotFoundException('Training course not found.');const rows=await tx.$queryRawUnsafe<any[]>(`INSERT INTO training_sessions(tenant_id,company_id,branch_id,course_id,course_version_id,title,starts_at,ends_at,capacity,location,instructor_user_id,created_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5::text,$6,$7,$8,$9,$10,$11::text,$12::text) RETURNING id,title,starts_at AS "startsAt",ends_at AS "endsAt",status,course_version_id AS "courseVersionId"`,c.tenantId,c.companyId,input.branchId,input.courseId,course[0].courseVersionId??null,input.title?.trim()||course[0].title,start,end,cap,input.location?.trim()||null,input.instructorUserId??null,actor);return rows[0];},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async enroll(sessionId:string,input:{staffId:string;assignmentId?:string|null},actor:string){const c=this.c();return this.prisma.$transaction(async tx=>{const sessions=await tx.$queryRawUnsafe<any[]>(`SELECT id,branch_id AS "branchId",capacity,status FROM training_sessions WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND ($4::text IS NULL OR branch_id=$4::text) FOR UPDATE`,sessionId,c.tenantId,c.companyId,c.branchId);if(!sessions.length)throw new NotFoundException('Training session not found.');const s=sessions[0];if(s.status!=='SCHEDULED')throw new BadRequestException('Session is not open for enrollment.');await this.staff(tx,input.staffId,s.branchId);if(s.capacity!=null){const count=await tx.$queryRawUnsafe<any[]>(`SELECT COUNT(*)::int AS count FROM training_session_enrollments WHERE session_id=$1::text AND status='ENROLLED'`,sessionId);if(Number(count[0]?.count??0)>=Number(s.capacity))throw new BadRequestException('Session capacity reached.');}const rows=await tx.$queryRawUnsafe<any[]>(`INSERT INTO training_session_enrollments(tenant_id,company_id,branch_id,session_id,staff_id,assignment_id,enrolled_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5::text,$6::text,$7::text) ON CONFLICT(tenant_id,company_id,session_id,staff_id) DO UPDATE SET assignment_id=COALESCE(training_session_enrollments.assignment_id,EXCLUDED.assignment_id) RETURNING id,status,staff_id AS "staffId"`,c.tenantId,c.companyId,s.branchId,sessionId,input.staffId,input.assignmentId??null,actor);return rows[0];},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async calendar(input:{from?:string;to?:string;branchId?:string}={}){const c=this.c(),from=input.from?new Date(input.from):new Date(),to=input.to?new Date(input.to):new Date(Date.now()+30*86400000);if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||to<from)throw new BadRequestException('Invalid calendar range.');const branch=input.branchId??c.branchId??null;return this.prisma.$queryRawUnsafe<any[]>(`SELECT s.id,s.title,s.starts_at AS "startsAt",s.ends_at AS "endsAt",s.capacity,s.location,s.status,s.branch_id AS "branchId",c.code AS "courseCode",c.title AS "courseTitle",COUNT(e.id) FILTER(WHERE e.status='ENROLLED')::int AS "enrolledCount" FROM training_sessions s JOIN training_courses c ON c.id=s.course_id LEFT JOIN training_session_enrollments e ON e.session_id=s.id WHERE s.tenant_id=$1::text AND s.company_id=$2::text AND ($3::text IS NULL OR s.branch_id=$3::text) AND s.starts_at<$5 AND s.ends_at>$4 GROUP BY s.id,c.id ORDER BY s.starts_at`,c.tenantId,c.companyId,branch,from,to);}

  async createPlan(input:{branchId:string;staffId:string;title:string;startDate?:string;targetDate?:string|null;ownerUserId?:string|null},actor:string){const c=this.c(),title=input.title?.trim();if(!title)throw new BadRequestException('Plan title is required.');return this.prisma.$transaction(async tx=>{await this.staff(tx,input.staffId,input.branchId);const rows=await tx.$queryRawUnsafe<any[]>(`INSERT INTO staff_development_plans(tenant_id,company_id,branch_id,staff_id,title,status,start_date,target_date,owner_user_id,created_by_user_id) VALUES($1::text,$2::text,$3::text,$4::text,$5,'ACTIVE',COALESCE($6::date,CURRENT_DATE),$7::date,$8::text,$9::text) RETURNING id,title,status,start_date AS "startDate",target_date AS "targetDate"`,c.tenantId,c.companyId,input.branchId,input.staffId,title,input.startDate??null,input.targetDate??null,input.ownerUserId??actor,actor);await tx.$executeRawUnsafe(`INSERT INTO staff_development_plan_events(tenant_id,company_id,branch_id,plan_id,event_type,actor_user_id) VALUES($1::text,$2::text,$3::text,$4::text,'CREATED',$5::text)`,c.tenantId,c.companyId,input.branchId,rows[0].id,actor);return rows[0];},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async addPlanItem(planId:string,input:{sequence:number;itemType:string;competencyId?:string|null;courseId?:string|null;programId?:string|null;targetLevel?:number|null;note?:string|null;dueDate?:string|null},actor:string){const c=this.c(),seq=Math.trunc(Number(input.sequence)),type=input.itemType?.trim().toUpperCase();if(seq<1||!['COMPETENCY','COURSE','PROGRAM','ACTION'].includes(type))throw new BadRequestException('Invalid plan item.');return this.prisma.$transaction(async tx=>{const p=await tx.$queryRawUnsafe<any[]>(`SELECT id,branch_id AS "branchId" FROM staff_development_plans WHERE id=$1::text AND tenant_id=$2::text AND company_id=$3::text AND status IN ('DRAFT','ACTIVE') AND ($4::text IS NULL OR branch_id=$4::text) LIMIT 1`,planId,c.tenantId,c.companyId,c.branchId);if(!p.length)throw new NotFoundException('Active development plan not found.');const rows=await tx.$queryRawUnsafe<any[]>(`INSERT INTO staff_development_plan_items(tenant_id,company_id,plan_id,sequence,item_type,competency_id,course_id,program_id,target_level,note,due_date) VALUES($1::text,$2::text,$3::text,$4,$5,$6::text,$7::text,$8::text,$9,$10,$11::date) RETURNING id,sequence,item_type AS "itemType",status`,c.tenantId,c.companyId,planId,seq,type,input.competencyId??null,input.courseId??null,input.programId??null,input.targetLevel??null,input.note?.trim()||null,input.dueDate??null);await tx.$executeRawUnsafe(`INSERT INTO staff_development_plan_events(tenant_id,company_id,branch_id,plan_id,event_type,actor_user_id,metadata) VALUES($1::text,$2::text,$3::text,$4::text,'ITEM_ADDED',$5::text,$6::jsonb)`,c.tenantId,c.companyId,p[0].branchId,planId,actor,JSON.stringify({itemId:rows[0].id,itemType:type}));return rows[0];},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

  async listPlans(staffId?:string){const c=this.c();return this.prisma.$queryRawUnsafe<any[]>(`SELECT p.id,p.staff_id AS "staffId",p.title,p.status,p.start_date AS "startDate",p.target_date AS "targetDate",p.owner_user_id AS "ownerUserId",COUNT(i.id)::int AS "itemCount",COUNT(i.id) FILTER(WHERE i.status='COMPLETED')::int AS "completedItemCount" FROM staff_development_plans p LEFT JOIN staff_development_plan_items i ON i.plan_id=p.id WHERE p.tenant_id=$1::text AND p.company_id=$2::text AND ($3::text IS NULL OR p.branch_id=$3::text) AND ($4::text IS NULL OR p.staff_id=$4::text) GROUP BY p.id ORDER BY p.created_at DESC`,c.tenantId,c.companyId,c.branchId,staffId??null);}
}
