BEGIN;
CREATE TABLE hr_approval_policies(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,name TEXT NOT NULL,entity_type TEXT NOT NULL,branch_id TEXT REFERENCES branches(id) ON DELETE CASCADE,min_amount DECIMAL(14,2),max_amount DECIMAL(14,2),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX hr_approval_policies_scope_idx ON hr_approval_policies(tenant_id,company_id,entity_type,branch_id,active);
CREATE TABLE hr_approval_policy_steps(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,policy_id TEXT NOT NULL REFERENCES hr_approval_policies(id) ON DELETE CASCADE,step_order INTEGER NOT NULL CHECK(step_order>0),approver_type TEXT NOT NULL CHECK(approver_type IN('ROLE','MANAGER','PERMISSION','USER')),approver_value TEXT,required BOOLEAN NOT NULL DEFAULT TRUE,escalation_hours INTEGER CHECK(escalation_hours IS NULL OR escalation_hours>0),UNIQUE(policy_id,step_order));
CREATE TABLE hr_approval_instances(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,branch_id TEXT REFERENCES branches(id) ON DELETE RESTRICT,policy_id TEXT NOT NULL REFERENCES hr_approval_policies(id) ON DELETE RESTRICT,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,requester_id TEXT,amount DECIMAL(14,2),status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','REJECTED','RETURNED','CANCELLED')),current_step INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at TIMESTAMP(3),UNIQUE(tenant_id,entity_type,entity_id));
CREATE INDEX hr_approval_instances_queue_idx ON hr_approval_instances(tenant_id,company_id,status,current_step,created_at);
CREATE TABLE hr_approval_actions(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,instance_id TEXT NOT NULL REFERENCES hr_approval_instances(id) ON DELETE CASCADE,step_order INTEGER NOT NULL,action TEXT NOT NULL CHECK(action IN('SUBMIT','APPROVE','REJECT','RETURN','DELEGATE','ESCALATE','CANCEL')),actor_id TEXT,delegate_to TEXT,comment TEXT,created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX hr_approval_actions_history_idx ON hr_approval_actions(instance_id,created_at);
COMMIT;
