"use client";
import Link from "next/link";
import { FormEvent,use,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { Alert,Button,Field,PageHeader,Select,Spinner,TextArea,TextInput } from "@/components/ui";
import { LeadContextFields,contextPayload,emptyLeadContext,type LeadContextForm } from "@/components/crm/lead-context-fields";
import { api,ApiError } from "@/lib/api";
import { hasActiveBranch } from "@/lib/auth";
import { leadSourceLabels,type CrmAssignee,type CrmLeadDetail } from "@/lib/crm-types";
type RichLead=CrmLeadDetail&Partial<LeadContextForm>&{alternativePhone?:string|null;preferredContactChannel?:string|null;language?:string|null;timezone?:string|null;estimatedBudget?:string|number|null;leadScore?:number|null};
const text=(v:unknown)=>v==null?"":String(v);
export default function EditCrmLeadPage({params}:{params:Promise<{id:string}>}){const {id}=use(params),router=useRouter();const [lead,setLead]=useState<RichLead|null>(null),[form,setForm]=useState({firstName:"",lastName:"",phone:"",email:"",source:"MANUAL",interestNote:"",ownerUserId:""}),[context,setContext]=useState<LeadContextForm>(emptyLeadContext),[assignees,setAssignees]=useState<CrmAssignee[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void Promise.all([api<RichLead>(`/crm/leads/${id}`),api<CrmAssignee[]>("/crm/assignees")]).then(([row,people])=>{setLead(row);setAssignees(people);setForm({firstName:row.firstName,lastName:row.lastName,phone:row.phone??"",email:row.email??"",source:row.source,interestNote:row.interestNote??"",ownerUserId:row.ownerUserId??""});setContext({alternativePhone:text(row.alternativePhone),preferredContactChannel:text(row.preferredContactChannel),language:text(row.language)||"tr",timezone:text(row.timezone)||"Europe/Istanbul",sourceDetail:text(row.sourceDetail),campaignId:text(row.campaignId),campaignName:text(row.campaignName),adSetId:text(row.adSetId),adSetName:text(row.adSetName),adId:text(row.adId),adName:text(row.adName),landingPage:text(row.landingPage),referrer:text(row.referrer),utmSource:text(row.utmSource),utmMedium:text(row.utmMedium),utmCampaign:text(row.utmCampaign),utmContent:text(row.utmContent),utmTerm:text(row.utmTerm),estimatedBudget:text(row.estimatedBudget),budgetCurrency:text(row.budgetCurrency)||"TRY",purchaseUrgency:text(row.purchaseUrgency)||"UNKNOWN",consultationNeed:text(row.consultationNeed)||"UNKNOWN",customerIntent:text(row.customerIntent),team:text(row.team),leadScore:text(row.leadScore??0),leadTemperature:text(row.leadTemperature)||"COLD"});}).catch(err=>setError(err instanceof ApiError?err.message:"Potansiyel müşteri yüklenemedi.")).finally(()=>setLoading(false));},[id]);
 async function submit(e:FormEvent){e.preventDefault();if(!lead)return;setError("");if(!hasActiveBranch()){setError("Potansiyel müşteri güncellemek için aktif bir şube seçin.");return;}if(!form.firstName.trim()||!form.lastName.trim()||(!form.phone.trim()&&!form.email.trim()&&!context.alternativePhone.trim())){setError("Ad, soyad ve en az bir iletişim bilgisi gereklidir.");return;}setSaving(true);try{await api(`/crm/leads/${id}`,{method:"PATCH",body:{version:lead.version,firstName:form.firstName.trim(),lastName:form.lastName.trim(),phone:form.phone.trim()||null,email:form.email.trim()||null,source:form.source,interestNote:form.interestNote.trim()||null,ownerUserId:form.ownerUserId||null,...contextPayload(context)}});router.push(`/crm/leads/${id}`);router.refresh();}catch(err){setError(err instanceof ApiError?err.message:"Potansiyel müşteri güncellenemedi.");}finally{setSaving(false);}}
 if(loading)return <Spinner label="Potansiyel müşteri bilgileri hazırlanıyor..."/>;if(!lead)return <div className="space-y-4">{error?<Alert>{error}</Alert>:null}<Link href="/crm/leads"><Button>Potansiyel Müşteri Havuzuna Dön</Button></Link></div>;
 return <div className="space-y-6"><Link href={`/crm/leads/${id}`} className="text-[11px] font-semibold text-[#1674BD]">← Potansiyel Müşteri Detayına Dön</Link><PageHeader title={`${lead.firstName} ${lead.lastName} · Düzenle`} description="İletişim, edinim, ticari niyet ve satış sınıflandırmasını birlikte yönetin."/><form onSubmit={submit} className="space-y-6"><section className="space-y-4 rounded-[22px] border border-[var(--line)] bg-white p-5 shadow-[var(--shadow-soft)]">{error?<Alert>{error}</Alert>:null}<h2 className="text-[13px] font-semibold">Temel Bilgiler</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Ad" required><TextInput value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></Field><Field label="Soyad" required><TextInput value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></Field><Field label="Telefon"><TextInput value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="E-Posta"><TextInput type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Kaynak"><Select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}>{Object.entries(leadSourceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field><Field label="Sorumlu"><Select value={form.ownerUserId} onChange={e=>setForm({...form,ownerUserId:e.target.value})}><option value="">Atanmamış</option>{assignees.map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</Select></Field></div><Field label="İlgi / İhtiyaç Notu"><TextArea rows={3} value={form.interestNote} onChange={e=>setForm({...form,interestNote:e.target.value})}/></Field></section><section className="rounded-[22px] border border-[var(--line)] bg-white p-5 shadow-[var(--shadow-soft)]"><LeadContextFields value={context} onChange={setContext}/></section><div className="flex justify-end gap-3"><Link href={`/crm/leads/${id}`}><Button type="button" variant="secondary">Vazgeç</Button></Link><Button type="submit" disabled={saving}>{saving?"Güncelleniyor...":"Değişiklikleri Kaydet"}</Button></div></form></div>}
