import type { CrmLeadDetail } from "@/lib/crm-types";
import type { CommercialOptions } from "./lead-context-fields";

const channelLabels:Record<string,string>={CALL:"Telefon",SMS:"SMS",EMAIL:"E-Posta",WHATSAPP:"WhatsApp",IN_PERSON:"Yüz Yüze",OTHER:"Diğer"};
const urgencyLabels:Record<string,string>={IMMEDIATE:"Hemen",THIS_WEEK:"Bu Hafta",THIS_MONTH:"Bu Ay",LATER:"Daha Sonra",UNKNOWN:"Bilinmiyor"};
const consultationLabels:Record<string,string>={REQUIRED:"Gerekli",REQUESTED:"Talep Edildi",NOT_NEEDED:"Gerekli Değil",UNKNOWN:"Bilinmiyor"};
const temperatureLabels:Record<string,string>={COLD:"Soğuk",WARM:"Ilık",HOT:"Sıcak"};
function value(v:unknown){return v===null||v===undefined||v===""?"—":String(v);}
function Row({label,children}:{label:string;children:React.ReactNode}){return <div><dt className="text-[10px] text-[var(--muted)]">{label}</dt><dd className="mt-1 break-words text-[12px] font-medium">{children}</dd></div>}
function names(ids:string[]|undefined,items:Array<{id:string;name:string}>){if(!ids?.length)return "—";const map=new Map(items.map(item=>[item.id,item.name]));return ids.map(id=>map.get(id)??id).join(", ");}
export function LeadContextSummary({lead,options}:{lead:CrmLeadDetail;options?:CommercialOptions}){
 const branch=options?.branches.find(row=>row.id===lead.preferredBranchId);
 return <section className="rounded-[22px] border border-[var(--line)] bg-white p-5 shadow-[var(--shadow-soft)]"><header className="flex items-start justify-between gap-4"><div><h2 className="text-[13px] font-semibold">CRM Bağlamı</h2><p className="mt-1 text-[10px] text-[var(--muted)]">İletişim tercihi, edinim attribution, ticari niyet ve satış sınıflandırması.</p></div></header><div className="mt-5 grid gap-6 lg:grid-cols-2">
 <div className="space-y-4"><h3 className="text-[10px] font-semibold uppercase tracking-wide text-[var(--muted)]">İletişim ve Edinim</h3><dl className="grid gap-4 sm:grid-cols-2"><Row label="Alternatif Telefon">{value(lead.alternativePhone)}</Row><Row label="Tercih Edilen Kanal">{lead.preferredContactChannel?channelLabels[lead.preferredContactChannel]??lead.preferredContactChannel:"—"}</Row><Row label="Dil / Saat Dilimi">{[lead.language,lead.timezone].filter(Boolean).join(" · ")||"—"}</Row><Row label="Kaynak Detayı">{value(lead.sourceDetail)}</Row><Row label="Kampanya">{[lead.campaignName,lead.campaignId].filter(Boolean).join(" · ")||"—"}</Row><Row label="Reklam Seti">{[lead.adSetName,lead.adSetId].filter(Boolean).join(" · ")||"—"}</Row><Row label="Reklam">{[lead.adName,lead.adId].filter(Boolean).join(" · ")||"—"}</Row><Row label="UTM">{[lead.utmSource,lead.utmMedium,lead.utmCampaign].filter(Boolean).join(" / ")||"—"}</Row></dl></div>
 <div className="space-y-4"><h3 className="text-[10px] font-semibold uppercase tracking-wide text-[var(--muted)]">Ticari ve Satış</h3><dl className="grid gap-4 sm:grid-cols-2"><Row label="Tercih Edilen Şube">{branch?.name??value(lead.preferredBranchId)}</Row><Row label="Tahmini Bütçe">{lead.estimatedBudget==null?"—":`${lead.estimatedBudget} ${lead.budgetCurrency??"TRY"}`}</Row><Row label="Satın Alma Aciliyeti">{lead.purchaseUrgency?urgencyLabels[lead.purchaseUrgency]??lead.purchaseUrgency:"—"}</Row><Row label="Danışmanlık İhtiyacı">{lead.consultationNeed?consultationLabels[lead.consultationNeed]??lead.consultationNeed:"—"}</Row><Row label="Satış Ekibi">{value(lead.team)}</Row><Row label="Lead Skoru / Sıcaklık">{`${lead.leadScore??0}/100 · ${temperatureLabels[lead.leadTemperature??"COLD"]??lead.leadTemperature??"—"}`}</Row><Row label="İlgilenilen Hizmetler">{names(lead.interestedServiceIds,options?.services??[])}</Row><Row label="İlgilenilen Paketler">{names(lead.interestedPackageIds,options?.packages??[])}</Row></dl>{lead.customerIntent?<div className="border-t border-[var(--line)] pt-4"><p className="text-[10px] text-[var(--muted)]">Müşteri Niyeti</p><p className="mt-2 whitespace-pre-wrap text-[12px] leading-6">{lead.customerIntent}</p></div>:null}</div>
 </div></section>;
}
