"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Button, Spinner } from "@/components/ui";
import { useToast } from "@/components/toast";
import { api, ApiError } from "@/lib/api";

type Health = { score:number; status:string; direction?:string; scoreDelta?:number|null; monthOverMonthDelta?:number|null };
type Cockpit = {
  asOf?: string;
  health?: Health;
  covenants?: { total:number; compliant:number; breached:number; allCompliant:boolean };
  liquidity?: { opening:number; thirteenWeekClosing:number; thirteenWeekLowest:number; risk:boolean; runwayWeeks:number|null };
  workingCapital?: { netWorkingCapital:number; dsoDays:number|null; dpoDays:number|null; overdueReceivableRatioPercent:number };
  branchPortfolio?: { activeScoredBranches:number; improvingBranches:number; deterioratingBranches:number; criticalBranches:number; weakestBranches:any[] };
  priorities?: any[];
  executiveAlerts?: any[];
  actions?: { summary:{ total:number; open:number; overdue:number; criticalOpen:number }; sla:{ open:number; overdue:number; critical:number; dueNext24Hours:number; maxEscalationLevel:number } };
};
type ActionItem = { id:string; title:string; description?:string|null; priority:string; status:string; dueAt?:string|null; sourceCode?:string|null; autoGenerated?:boolean; escalationLevel?:number; lastEscalatedAt?:string|null };
type Benchmark = { averageHealthScore:number|null; medianHealthScore:number|null; bestScore:number|null; worstScore:number|null; scoredBranchCount?:number; branches:Array<{branchId:string;branchName:string;branchCode:string;healthScore:number|null;healthStatus?:string|null;percentile:number|null;varianceFromAverage:number|null}> };
type Anomalies = { anomalyCount:number;criticalCount:number;warningCount:number;anomalies:Array<{scope:string;branchName?:string|null;snapshotDate:string;healthScore:number;scoreDelta:number;zScore:number;severity:string}> };
type HealthHistoryItem = { id:string; snapshotDate:string; healthScore:number; healthStatus:string };
type CashFlowWeek = { week:number; start:string; end:string; projectedInflows:number; projectedOutflows:number; netCashFlow:number; closingLiquidity:number };
type CashFlow = { openingLiquidity:number; projectedInflows:number; projectedOutflows:number; projectedNetCashFlow:number; forecastClosingLiquidity:number; lowestLiquidity:number; liquidityRisk:boolean; weeks:CashFlowWeek[] };

type TabKey = "overview"|"trends"|"branches"|"actions"|"risk";

const statusLabel:Record<string,string>={STRONG:"Güçlü",STABLE:"Dengeli",WEAK:"Zayıf",CRITICAL:"Kritik",IMPROVING:"İyileşiyor",DETERIORATING:"Kötüleşiyor",INSUFFICIENT_HISTORY:"Yetersiz veri",OPEN:"Açık",IN_PROGRESS:"Devam ediyor",BLOCKED:"Bloke",COMPLETED:"Tamamlandı",CANCELLED:"İptal"};

export default function CfoCockpitPage(){
  const {showToast}=useToast();
  const [cockpit,setCockpit]=useState<Cockpit|null>(null);
  const [benchmark,setBenchmark]=useState<Benchmark|null>(null);
  const [anomalies,setAnomalies]=useState<Anomalies|null>(null);
  const [actions,setActions]=useState<ActionItem[]>([]);
  const [history,setHistory]=useState<HealthHistoryItem[]>([]);
  const [cashFlow,setCashFlow]=useState<CashFlow|null>(null);
  const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const [tab,setTab]=useState<TabKey>("overview");

  const load=useCallback(async()=>{
    setLoading(true);setError("");
    try{
      const [c,b,a,acts,h,cf]=await Promise.all([
        api<Cockpit>("/profitability/cfo/management-cockpit"),
        api<Benchmark>("/profitability/cfo/branches/benchmark"),
        api<Anomalies>("/profitability/cfo/anomalies?days=60"),
        api<ActionItem[]>("/profitability/cfo/actions?limit=100"),
        api<HealthHistoryItem[]>("/profitability/cfo/health/history?limit=180"),
        api<CashFlow>("/profitability/cash-flow/13-week?scenario=BASE"),
      ]);
      setCockpit(c);setBenchmark(b);setAnomalies(a);setActions(acts);setHistory(h);setCashFlow(cf);
    }catch(e){setError(e instanceof ApiError?e.message:"CFO verileri yüklenemedi.")}
    finally{setLoading(false)}
  },[]);

  useEffect(()=>{void load()},[load]);

  const openActions=useMemo(()=>actions.filter(a=>!["COMPLETED","CANCELLED"].includes(a.status)),[actions]);

  async function syncRecommendations(){
    setBusy(true);setError("");
    try{await api("/profitability/cfo/actions/sync-recommendations",{method:"POST"});showToast("Finansal öneriler aksiyon listesiyle eşleştirildi.");await load()}
    catch(e){setError(e instanceof ApiError?e.message:"Öneriler eşitlenemedi.")}
    finally{setBusy(false)}
  }

  async function escalate(){
    setBusy(true);setError("");
    try{await api("/profitability/cfo/actions/escalate",{method:"POST"});showToast("SLA escalation kontrolü tamamlandı.");await load()}
    catch(e){setError(e instanceof ApiError?e.message:"Escalation çalıştırılamadı.")}
    finally{setBusy(false)}
  }

  async function setActionStatus(id:string,status:"IN_PROGRESS"|"COMPLETED"){
    setBusy(true);setError("");
    try{await api(`/profitability/cfo/actions/${id}`,{method:"PATCH",body:{status}});showToast(status==="COMPLETED"?"Aksiyon tamamlandı.":"Aksiyon başlatıldı.");await load()}
    catch(e){setError(e instanceof ApiError?e.message:"Aksiyon güncellenemedi.")}
    finally{setBusy(false)}
  }

  if(loading&&!cockpit)return <div className="mx-auto max-w-[1500px] py-20"><Spinner label="CFO yönetim kokpiti hazırlanıyor..."/></div>;

  const health=cockpit?.health;
  const liquidity=cockpit?.liquidity;
  const wc=cockpit?.workingCapital;
  const actionSummary=cockpit?.actions?.summary;
  const sla=cockpit?.actions?.sla;

  return <div className="mx-auto max-w-[1500px] space-y-6 pb-12">
    <header className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
      <div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.16em] text-[#9b97a7]">FİNANS & CFO</p><h1 className="text-[36px] font-semibold tracking-[-.045em] text-[#20202a]">Yönetim Kokpiti</h1><p className="mt-2 max-w-3xl text-[14px] leading-6 text-[#85828e]">Likidite, çalışma sermayesi, finansal sağlık, trendler, şube kıyaslaması ve yönetim aksiyonlarını tek ekrandan yönetin.</p></div>
      <div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void syncRecommendations()}>Önerileri Aksiyona Çevir</Button><Button disabled={busy} onClick={()=>void escalate()} className="!border-[#2f2d3a] !bg-[#2f2d3a] !text-white">SLA Kontrolü</Button></div>
    </header>
    {error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
      <Metric label="Finansal Sağlık" value={health?.score??"—"} sub={statusLabel[health?.status??""]??health?.status} tone={health?.status==="CRITICAL"?"danger":health?.status==="WEAK"?"warn":"good"}/>
      <Metric label="Nakit Runway" value={liquidity?.runwayWeeks==null?"Self-funded":`${fmt(liquidity.runwayWeeks)} hf`} sub="Likidite tabanına kadar" tone={liquidity?.risk?"danger":"good"}/>
      <Metric label="Net Çalışma Sermayesi" value={money(wc?.netWorkingCapital)} sub="Alacak + stok − borç" tone={(wc?.netWorkingCapital??0)<0?"danger":"default"}/>
      <Metric label="DSO / DPO" value={`${fmt(wc?.dsoDays)} / ${fmt(wc?.dpoDays)}`} sub="Gün"/>
      <Metric label="Açık Aksiyon" value={actionSummary?.open??openActions.length} sub={`${actionSummary?.overdue??0} gecikmiş`} tone={(actionSummary?.overdue??0)>0?"warn":"default"}/>
      <Metric label="Anomali" value={anomalies?.anomalyCount??0} sub={`${anomalies?.criticalCount??0} kritik`} tone={(anomalies?.criticalCount??0)>0?"danger":"default"}/>
    </div>

    <div className="flex gap-1 overflow-x-auto rounded-[18px] border border-[#ece9f0] bg-white/80 p-1.5 shadow-[0_8px_28px_rgba(49,38,74,.035)]">
      <Tab active={tab==="overview"} onClick={()=>setTab("overview")}>Genel Bakış</Tab><Tab active={tab==="trends"} onClick={()=>setTab("trends")}>Trend & Nakit</Tab><Tab active={tab==="branches"} onClick={()=>setTab("branches")}>Şube Kıyaslama</Tab><Tab active={tab==="actions"} onClick={()=>setTab("actions")}>Aksiyon Merkezi</Tab><Tab active={tab==="risk"} onClick={()=>setTab("risk")}>Risk & Anomali</Tab>
    </div>

    {tab==="overview"?<Overview cockpit={cockpit} benchmark={benchmark} actions={openActions}/>:null}
    {tab==="trends"?<TrendCenter history={history} cashFlow={cashFlow}/>:null}
    {tab==="branches"?<BranchComparison benchmark={benchmark}/>:null}
    {tab==="actions"?<ActionCenter actions={actions} sla={sla} busy={busy} onStatus={setActionStatus}/>:null}
    {tab==="risk"?<RiskCenter cockpit={cockpit} anomalies={anomalies}/>:null}
  </div>
}

function Overview({cockpit,benchmark,actions}:{cockpit:Cockpit|null;benchmark:Benchmark|null;actions:ActionItem[]}){
  const alerts=cockpit?.executiveAlerts??[];const priorities=cockpit?.priorities??[];
  return <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
    <section className="space-y-5">
      <Panel title="13 Haftalık Likidite" subtitle="Tahmini nakit pozisyonu ve minimum seviye"><div className="grid gap-3 sm:grid-cols-3"><Mini label="Açılış Likiditesi" value={money(cockpit?.liquidity?.opening)}/><Mini label="13. Hafta Kapanış" value={money(cockpit?.liquidity?.thirteenWeekClosing)}/><Mini label="En Düşük Likidite" value={money(cockpit?.liquidity?.thirteenWeekLowest)} danger={(cockpit?.liquidity?.thirteenWeekLowest??0)<0}/></div></Panel>
      <Panel title="Şube Sağlık Dağılımı" subtitle={`${benchmark?.scoredBranchCount??benchmark?.branches.length??0} şube skorlandı`}><div className="grid gap-3 sm:grid-cols-4"><Mini label="Ortalama" value={fmt(benchmark?.averageHealthScore)}/><Mini label="Medyan" value={fmt(benchmark?.medianHealthScore)}/><Mini label="En Güçlü" value={fmt(benchmark?.bestScore)}/><Mini label="En Zayıf" value={fmt(benchmark?.worstScore)} danger={(benchmark?.worstScore??100)<60}/></div><div className="mt-4 space-y-2">{(benchmark?.branches??[]).slice(0,6).map((b,index)=><div key={b.branchId} className="flex items-center gap-3 rounded-[14px] bg-[#faf9fc] px-4 py-3"><span className="w-6 text-[11px] font-semibold text-[#aaa6b2]">{index+1}</span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-[#302f3b]">{b.branchName}</p><p className="text-[11px] text-[#9a96a4]">Percentile {fmt(b.percentile)} · Ortalamaya göre {signed(b.varianceFromAverage)}</p></div><Score value={b.healthScore}/></div>)}</div></Panel>
    </section>
    <aside className="space-y-5">
      <Panel title="Yönetim Öncelikleri" subtitle="Finansal health engine önerileri"><div className="space-y-2">{priorities.length?priorities.slice(0,6).map((p:any,i:number)=><Notice key={`${p.code}-${i}`} severity={p.priority==="CRITICAL"?"CRITICAL":"WARNING"} title={p.action??p.code} text={p.recommendation??"Yönetim aksiyonu gerekli."}/>):<Empty text="Aktif finansal öncelik yok."/>}</div></Panel>
      <Panel title="Executive Alerts" subtitle={`${alerts.length} aktif uyarı`}><div className="space-y-2">{alerts.length?alerts.slice(0,6).map((a:any,i:number)=><Notice key={`${a.code}-${i}`} severity={a.severity} title={a.title??a.code} text={`Gerçekleşen: ${String(a.actual??"—")} · Eşik: ${String(a.threshold??"—")}`}/>):<Empty text="Aktif executive alert yok."/>}</div></Panel>
      <Panel title="Aksiyon Kuyruğu" subtitle={`${actions.length} açık aksiyon`}><div className="space-y-2">{actions.slice(0,5).map(a=><div key={a.id} className="rounded-[14px] border border-[#efedf3] p-3"><div className="flex items-start justify-between gap-3"><p className="text-[12px] font-semibold leading-5 text-[#383643]">{a.title}</p><Badge text={a.priority}/></div><p className="mt-2 text-[10px] text-[#9995a3]">{statusLabel[a.status]??a.status}{a.dueAt?` · ${date(a.dueAt)}`:""}</p></div>)}{!actions.length?<Empty text="Açık aksiyon yok."/>:null}</div></Panel>
    </aside>
  </div>
}

function TrendCenter({history,cashFlow}:{history:HealthHistoryItem[];cashFlow:CashFlow|null}){
  const healthPoints=history.slice(-90).map(item=>({label:shortDate(item.snapshotDate),value:Number(item.healthScore)}));
  const liquidityPoints=(cashFlow?.weeks??[]).map(item=>({label:`H${item.week}`,value:Number(item.closingLiquidity)}));
  const inflows=(cashFlow?.weeks??[]).map(item=>Number(item.projectedInflows));
  const outflows=(cashFlow?.weeks??[]).map(item=>Number(item.projectedOutflows));
  return <div className="space-y-5">
    <div className="grid gap-5 xl:grid-cols-2">
      <Panel title="Financial Health Trend" subtitle="Son 90 snapshot"><LineChart points={healthPoints} minFloor={0} maxCeil={100} empty="Trend için yeterli snapshot yok."/></Panel>
      <Panel title="13 Haftalık Likidite Eğrisi" subtitle="BASE senaryosu · haftalık kapanış likiditesi"><LineChart points={liquidityPoints} empty="Cash-flow projeksiyonu bulunamadı." moneyAxis/></Panel>
    </div>
    <Panel title="Haftalık Nakit Giriş / Çıkış" subtitle="Öngörülen tahsilat ve tedarikçi ödeme yükü"><CashBars weeks={cashFlow?.weeks??[]}/></Panel>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MiniCard label="Toplam Beklenen Giriş" value={money(cashFlow?.projectedInflows)}/><MiniCard label="Toplam Beklenen Çıkış" value={money(cashFlow?.projectedOutflows)}/><MiniCard label="13H Net Nakit" value={money(cashFlow?.projectedNetCashFlow)} danger={(cashFlow?.projectedNetCashFlow??0)<0}/><MiniCard label="En Düşük Likidite" value={money(cashFlow?.lowestLiquidity)} danger={(cashFlow?.lowestLiquidity??0)<0}/></div>
    <div className="hidden">{inflows.length+outflows.length}</div>
  </div>
}

function LineChart({points,minFloor,maxCeil,empty,moneyAxis=false}:{points:Array<{label:string;value:number}>;minFloor?:number;maxCeil?:number;empty:string;moneyAxis?:boolean}){
  if(points.length<2)return <Empty text={empty}/>;
  const width=720,height=230,pad=28;
  const values=points.map(p=>p.value).filter(Number.isFinite);
  const rawMin=Math.min(...values),rawMax=Math.max(...values);
  const min=minFloor!==undefined?Math.min(minFloor,rawMin):rawMin;
  const max=maxCeil!==undefined?Math.max(maxCeil,rawMax):rawMax;
  const range=Math.max(1,max-min);
  const coords=points.map((p,i)=>({x:pad+(i*(width-pad*2))/Math.max(1,points.length-1),y:height-pad-((p.value-min)/range)*(height-pad*2),...p}));
  const path=coords.map((p,i)=>`${i===0?"M":"L"} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(" ");
  return <div><div className="overflow-hidden rounded-[16px] border border-[#efedf3] bg-[#fbfafe] p-2"><svg viewBox={`0 0 ${width} ${height}`} className="h-[230px] w-full" role="img" aria-label="Finansal trend grafiği"><line x1={pad} x2={width-pad} y1={height-pad} y2={height-pad} stroke="#e8e4ef" strokeWidth="1"/><line x1={pad} x2={width-pad} y1={pad} y2={pad} stroke="#f0edf4" strokeWidth="1"/><path d={path} fill="none" stroke="#7657e8" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>{coords.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="3.5" fill="#fff" stroke="#7657e8" strokeWidth="2"/>)}</svg></div><div className="mt-2 flex items-center justify-between text-[9px] text-[#aaa6b2]"><span>{points[0]?.label}</span><span>{moneyAxis?`${money(min)} → ${money(max)}`:`${fmt(min)} → ${fmt(max)}`}</span><span>{points[points.length-1]?.label}</span></div></div>
}

function CashBars({weeks}:{weeks:CashFlowWeek[]}){
  if(!weeks.length)return <Empty text="Cash-flow haftaları bulunamadı."/>;
  const max=Math.max(1,...weeks.flatMap(w=>[Number(w.projectedInflows),Number(w.projectedOutflows)]));
  return <div className="overflow-x-auto"><div className="grid min-w-[820px] grid-cols-13 items-end gap-2">{weeks.map(w=><div key={w.week} className="flex flex-col items-center gap-2"><div className="flex h-[180px] w-full items-end justify-center gap-1 rounded-[12px] bg-[#faf9fc] px-1.5 py-2"><div title={`Giriş ${money(w.projectedInflows)}`} className="w-3 rounded-t bg-[#8a6ee9]" style={{height:`${Math.max(3,(Number(w.projectedInflows)/max)*155)}px`}}/><div title={`Çıkış ${money(w.projectedOutflows)}`} className="w-3 rounded-t bg-[#d9a858]" style={{height:`${Math.max(3,(Number(w.projectedOutflows)/max)*155)}px`}}/></div><span className="text-[9px] font-semibold text-[#9894a2]">H{w.week}</span></div>)}</div><div className="mt-3 flex gap-4 text-[10px] text-[#8f8b98]"><span>■ Tahsilat</span><span>■ Ödeme</span></div></div>
}

function BranchComparison({benchmark}:{benchmark:Benchmark|null}){return <Panel title="Şube Benchmark" subtitle="Şubeleri finansal sağlık ve şirket ortalamasına göre karşılaştırın"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-[#eeeaf2] text-[10px] uppercase tracking-[.12em] text-[#9c98a6]"><th className="px-3 py-3">Şube</th><th className="px-3 py-3">Skor</th><th className="px-3 py-3">Durum</th><th className="px-3 py-3">Percentile</th><th className="px-3 py-3">Ort. Farkı</th><th className="px-3 py-3">Konum</th></tr></thead><tbody>{benchmark?.branches.map((b,i)=><tr key={b.branchId} className="border-b border-[#f3f0f5] text-[12px]"><td className="px-3 py-4"><p className="font-semibold text-[#33313e]">{b.branchName}</p><p className="mt-1 text-[10px] text-[#aaa6b2]">{b.branchCode}</p></td><td className="px-3 py-4"><Score value={b.healthScore}/></td><td className="px-3 py-4">{statusLabel[b.healthStatus??""]??b.healthStatus??"—"}</td><td className="px-3 py-4">{fmt(b.percentile)}</td><td className="px-3 py-4">{signed(b.varianceFromAverage)}</td><td className="px-3 py-4">#{i+1}</td></tr>)}</tbody></table></div></Panel>}

function ActionCenter({actions,sla,busy,onStatus}:{actions:ActionItem[];sla:any;busy:boolean;onStatus:(id:string,status:"IN_PROGRESS"|"COMPLETED")=>Promise<void>}){return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-4"><MiniCard label="Açık" value={sla?.open??0}/><MiniCard label="Gecikmiş" value={sla?.overdue??0} danger={(sla?.overdue??0)>0}/><MiniCard label="Kritik" value={sla?.critical??0} danger={(sla?.critical??0)>0}/><MiniCard label="24 Saat İçinde" value={sla?.dueNext24Hours??0}/></div><Panel title="Executive Action Center" subtitle="Finansal risklerden doğan yönetim aksiyonları"><div className="space-y-3">{actions.map(a=><div key={a.id} className="grid gap-3 rounded-[16px] border border-[#ece9f0] bg-white p-4 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><Badge text={a.priority}/><span className="text-[10px] font-medium text-[#9692a0]">{statusLabel[a.status]??a.status}</span>{a.autoGenerated?<span className="rounded-full bg-[#f1edff] px-2 py-1 text-[9px] font-semibold text-[#7557df]">AUTO</span>:null}{(a.escalationLevel??0)>0?<span className="rounded-full bg-[#fff0ed] px-2 py-1 text-[9px] font-semibold text-[#d15d48]">ESC L{a.escalationLevel}</span>:null}</div><p className="mt-2 text-[13px] font-semibold text-[#302f3b]">{a.title}</p>{a.description?<p className="mt-1 text-[11px] leading-5 text-[#85818f]">{a.description}</p>:null}<p className="mt-2 text-[10px] text-[#aaa6b2]">Kaynak: {a.sourceCode??"MANUAL"}{a.dueAt?` · Son tarih ${date(a.dueAt)}`:""}</p></div>{!["COMPLETED","CANCELLED"].includes(a.status)?<div className="flex gap-2">{a.status==="OPEN"?<Button disabled={busy} onClick={()=>void onStatus(a.id,"IN_PROGRESS")}>Başlat</Button>:null}<Button disabled={busy} onClick={()=>void onStatus(a.id,"COMPLETED")} className="!border-[#3aa675] !bg-[#3aa675] !text-white">Tamamla</Button></div>:null}</div>)}{!actions.length?<Empty text="Henüz yönetim aksiyonu yok."/>:null}</div></Panel></div>}

function RiskCenter({cockpit,anomalies}:{cockpit:Cockpit|null;anomalies:Anomalies|null}){const alerts=cockpit?.executiveAlerts??[];return <div className="grid gap-5 xl:grid-cols-2"><Panel title="Risk Heatmap" subtitle="Executive threshold ihlalleri"><div className="grid gap-3 sm:grid-cols-2">{alerts.map((a:any,i:number)=><div key={`${a.code}-${i}`} className={`rounded-[16px] border p-4 ${a.severity==="CRITICAL"?"border-[#f4c7c1] bg-[#fff7f5]":"border-[#f0dfb2] bg-[#fffbf1]"}`}><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#9a8790]">{a.severity}</p><p className="mt-2 text-[13px] font-semibold text-[#36333e]">{a.title??a.code}</p><p className="mt-2 text-[11px] text-[#8f8993]">Gerçek: {String(a.actual??"—")} · Eşik: {String(a.threshold??"—")}</p></div>)}{!alerts.length?<Empty text="Aktif threshold ihlali yok."/>:null}</div></Panel><Panel title="Finansal Anomaliler" subtitle={`Son 60 gün · ${anomalies?.anomalyCount??0} tespit`}><div className="space-y-2">{anomalies?.anomalies.slice(0,12).map((a,i)=><Notice key={`${a.snapshotDate}-${i}`} severity={a.severity} title={a.branchName??"Şirket geneli"} text={`${date(a.snapshotDate)} · Skor ${fmt(a.healthScore)} · Δ ${signed(a.scoreDelta)} · Z ${fmt(a.zScore)}`}/>)}{!anomalies?.anomalyCount?<Empty text="İstatistiksel anomali tespit edilmedi."/>:null}</div></Panel></div>}

function Metric({label,value,sub,tone="default"}:{label:string;value:any;sub?:string;tone?:"default"|"good"|"warn"|"danger"}){const cls=tone==="danger"?"bg-[#fff5f3] border-[#f2d2cc]":tone==="warn"?"bg-[#fffaf0] border-[#f1e1bc]":tone==="good"?"bg-[#f4fbf7] border-[#d7eadf]":"bg-white/85 border-[#ece9f0]";return <div className={`rounded-[20px] border p-4 shadow-[0_8px_28px_rgba(49,38,74,.035)] ${cls}`}><p className="text-[10px] font-semibold uppercase tracking-[.11em] text-[#9b97a5]">{label}</p><p className="mt-3 text-[22px] font-semibold tracking-[-.035em] text-[#292734]">{value}</p>{sub?<p className="mt-1 text-[10px] text-[#9d99a6]">{sub}</p>:null}</div>}
function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:any}){return <section className="rounded-[22px] border border-[#ece9f0] bg-white/85 p-5 shadow-[0_12px_36px_rgba(49,38,74,.04)]"><div className="mb-4"><h2 className="text-[16px] font-semibold tracking-[-.02em] text-[#2d2b37]">{title}</h2>{subtitle?<p className="mt-1 text-[11px] text-[#9995a2]">{subtitle}</p>:null}</div>{children}</section>}
function Mini({label,value,danger=false}:{label:string;value:any;danger?:boolean}){return <div className={`rounded-[15px] border p-3 ${danger?"border-[#f3d0ca] bg-[#fff6f4]":"border-[#efedf2] bg-[#faf9fc]"}`}><p className="text-[9px] uppercase tracking-[.1em] text-[#aaa6b2]">{label}</p><p className="mt-2 text-[16px] font-semibold text-[#373540]">{value}</p></div>}
function MiniCard({label,value,danger=false}:{label:string;value:any;danger?:boolean}){return <div className={`rounded-[18px] border p-4 ${danger?"border-[#f3d0ca] bg-[#fff6f4]":"border-[#ece9f0] bg-white/85"}`}><p className="text-[10px] uppercase tracking-[.1em] text-[#aaa6b2]">{label}</p><p className="mt-2 text-[24px] font-semibold text-[#302e3a]">{value}</p></div>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:any}){return <button type="button" onClick={onClick} className={`whitespace-nowrap rounded-[13px] px-4 py-2.5 text-[11px] font-semibold transition ${active?"bg-[#eee8ff] text-[#7557df]":"text-[#878391] hover:bg-[#f8f6fb] hover:text-[#393643]"}`}>{children}</button>}
function Score({value}:{value:number|null}){if(value==null)return <span className="text-[#aaa6b2]">—</span>;const cls=value>=80?"bg-[#e8f7ef] text-[#31855d]":value>=60?"bg-[#f1edff] text-[#7255da]":value>=40?"bg-[#fff4dd] text-[#b87b20]":"bg-[#ffebe7] text-[#cb5947]";return <span className={`inline-flex min-w-12 justify-center rounded-full px-2.5 py-1 text-[11px] font-bold ${cls}`}>{fmt(value)}</span>}
function Badge({text}:{text:string}){const cls=text==="CRITICAL"?"bg-[#ffebe7] text-[#c85443]":text==="HIGH"?"bg-[#fff3dd] text-[#ad741e]":text==="LOW"?"bg-[#edf6ff] text-[#477ca6]":"bg-[#f1edff] text-[#7557df]";return <span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${cls}`}>{text}</span>}
function Notice({severity,title,text}:{severity:string;title:string;text:string}){return <div className={`rounded-[14px] border p-3 ${severity==="CRITICAL"?"border-[#f3d1cb] bg-[#fff7f5]":"border-[#efe2bf] bg-[#fffbf2]"}`}><div className="flex items-start justify-between gap-3"><p className="text-[12px] font-semibold text-[#3a3742]">{title}</p><Badge text={severity}/></div><p className="mt-1.5 text-[10px] leading-4 text-[#8f8995]">{text}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-[14px] border border-dashed border-[#e6e2ea] px-4 py-7 text-center text-[11px] text-[#aaa6b2]">{text}</div>}
function money(v:any){const n=Number(v??0);return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number.isFinite(n)?n:0)}
function fmt(v:any){if(v===null||v===undefined||!Number.isFinite(Number(v)))return "—";return new Intl.NumberFormat("tr-TR",{maximumFractionDigits:1}).format(Number(v))}
function signed(v:any){if(v===null||v===undefined||!Number.isFinite(Number(v)))return "—";const n=Number(v);return `${n>0?"+":""}${fmt(n)}`}
function date(v:string){return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v))}
function shortDate(v:string){return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short"}).format(new Date(v))}
