"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Alert, Button, Field, PageHeader, Spinner, TextInput } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
type Settings={salesVatRate:number;purchaseVatRate:number;pricesIncludeVat:boolean};
type Summary={outputVat:number;inputVat:number;goodsReceiptInputVat:number;purchaseReturnVat:number;replacementInputVat:number;netVatPayable:number;position:string};
const money=(v:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:2}).format(v||0);
export default function TaxPage(){
 const[settings,setSettings]=useState<Settings|null>(null),[summary,setSummary]=useState<Summary|null>(null),[from,setFrom]=useState(""),[to,setTo]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async(rangeFrom:string,rangeTo:string)=>{setLoading(true);setError("");try{const q=new URLSearchParams();if(rangeFrom)q.set("from",rangeFrom);if(rangeTo)q.set("to",rangeTo);const[s,m]=await Promise.all([api<Settings>("/tax/settings"),api<Summary>(`/tax/summary?${q.toString()}`)]);setSettings(s);setSummary(m)}catch(e){setError(e instanceof ApiError?e.message:"Vergi verileri yüklenemedi.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load("","")},[load]);
 async function save(e:FormEvent){e.preventDefault();if(!settings)return;setSaving(true);setError("");try{const next=await api<Settings>("/tax/settings",{method:"PUT",body:settings});setSettings(next);setNotice("Vergi ayarları güncellendi.");await load(from,to)}catch(err){setError(err instanceof ApiError?err.message:"Vergi ayarları kaydedilemedi.")}finally{setSaving(false)}}
 if(loading&&!settings)return <Spinner label="Vergi yönetimi hazırlanıyor..."/>;
 return <div className="mx-auto max-w-[1300px] space-y-6 pb-12"><PageHeader title="Vergi Yönetimi" description="Satış ve alış KDV oranlarını yönetin; dönemsel hesaplanan ve indirilecek KDV pozisyonunu izleyin."/>
 {error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}{notice?<Alert tone="success" onClose={()=>setNotice("")}>{notice}</Alert>:null}
 {settings?<form onSubmit={save} className="grid gap-4 rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5 md:grid-cols-3"><Field label="Satış KDV Oranı (%)"><TextInput type="number" min="0" max="100" step="0.01" value={settings.salesVatRate} onChange={e=>setSettings({...settings,salesVatRate:Number(e.target.value)})}/></Field><Field label="Alış KDV Oranı (%)"><TextInput type="number" min="0" max="100" step="0.01" value={settings.purchaseVatRate} onChange={e=>setSettings({...settings,purchaseVatRate:Number(e.target.value)})}/></Field><Field label="Fiyatlara KDV Dahil"><select className="min-h-10 w-full rounded-xl border border-[var(--line)] px-3" value={String(settings.pricesIncludeVat)} onChange={e=>setSettings({...settings,pricesIncludeVat:e.target.value==="true"})}><option value="true">Evet</option><option value="false">Hayır</option></select></Field><div className="md:col-span-3"><Button type="submit" disabled={saving}>{saving?"Kaydediliyor...":"Vergi Ayarlarını Kaydet"}</Button></div></form>:null}
 <section className="grid gap-3 rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5 md:grid-cols-[1fr_1fr_auto]"><Field label="Başlangıç"><TextInput type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Bitiş"><TextInput type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><div className="flex items-end"><Button variant="secondary" onClick={()=>void load(from,to)}>Dönemi Hesapla</Button></div></section>
 {summary?<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Hesaplanan KDV" value={money(summary.outputVat)}/><Metric label="İndirilecek KDV" value={money(summary.inputVat)}/><Metric label="Net KDV Pozisyonu" value={money(summary.netVatPayable)}/><Metric label="Mal Kabul KDV" value={money(summary.goodsReceiptInputVat)}/><Metric label="Alış İade KDV" value={money(summary.purchaseReturnVat)}/><Metric label="Pozisyon" value={summary.position==="PAYABLE"?"Ödenecek":summary.position==="CREDIT"?"Devreden/Alacak":"Dengede"}/></section>:null}
 </div>
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-[16px] border border-[var(--line)] bg-[var(--surface)] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[var(--muted-soft)]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
