"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { api,ApiError } from "@/lib/api";
import { hasPermission } from "@/lib/auth";

type Certification={id:string;name:string;code:string;category?:string|null;credentialNumber?:string|null;issuingOrganization?:string|null;qualification?:string|null;issuedAt?:string|null;expiresAt?:string|null;status:string;warningDays:number;serviceEligibilityRequired:boolean};
const label=(v:string)=>({PENDING:"Doğrulama Bekliyor",VERIFIED:"Doğrulandı",REJECTED:"Reddedildi",EXPIRED:"Süresi Doldu",REVOKED:"İptal Edildi"}[v]??v);
const date=(v?:string|null)=>v?new Date(`${v}T00:00:00`).toLocaleDateString("tr-TR"):"—";
const remaining=(v?:string|null)=>v?Math.ceil((new Date(`${v}T00:00:00`).getTime()-new Date().setHours(0,0,0,0))/86400000):null;

export function EmployeeCertificationCard({employeeId}:{employeeId:string}){
 const[allowed,setAllowed]=useState(false),[rows,setRows]=useState<Certification[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{setAllowed(hasPermission("hr_sensitive","read"))},[]);
 useEffect(()=>{if(!allowed){setLoading(false);return}let active=true;setLoading(true);setError("");api<Certification[]>(`/hr/employees/${employeeId}/certifications`).then(x=>{if(active)setRows(x)}).catch(e=>{if(active)setError(e instanceof ApiError?e.message:"Sertifika bilgileri yüklenemedi.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[allowed,employeeId]);
 const summary=useMemo(()=>{let valid=0,risk=0,action=0;for(const row of rows){const days=remaining(row.expiresAt);if(row.status==="VERIFIED"&&(days===null||days>row.warningDays))valid++;else if(row.status==="VERIFIED"&&days!==null&&days>=0)risk++;else action++}return{valid,risk,action}},[rows]);
 if(!allowed)return <section className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="text-sm font-semibold">Sertifikalar ve Yetkinlik</h2><p className="mt-2 text-xs text-[var(--muted)]">Sertifika ve mesleki yetkinlik bilgileri hassas İK verisi olarak korunuyor.</p></section>;
 if(loading)return <section className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><p className="text-xs text-[var(--muted)]">Sertifikalar yükleniyor…</p></section>;
 return <section className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Sertifikalar ve Yetkinlik</h2><p className="mt-1 text-[10px] text-[var(--muted)]">Mesleki credential, geçerlilik ve hizmet yetkinliği görünümü.</p></div><Link href={`/hr/employees/${employeeId}/certifications`} className="text-xs font-semibold text-[var(--accent)]">Sertifikaları yönet →</Link></div>{error?<p className="rounded-xl border border-[var(--line)] bg-[var(--surface-2)] p-3 text-xs text-[var(--danger)]">{error}</p>:<><div className="grid gap-2 sm:grid-cols-3"><Stat label="Geçerli" value={summary.valid}/><Stat label="Yaklaşan Bitiş" value={summary.risk}/><Stat label="Aksiyon Gereken" value={summary.action}/></div><div className="mt-4 grid gap-2 md:grid-cols-2">{rows.slice(0,6).map(row=>{const days=remaining(row.expiresAt),risk=row.status==="VERIFIED"&&days!==null&&days>=0&&days<=row.warningDays;return <div key={row.id} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--line)] p-3"><div className="min-w-0"><p className="truncate text-xs font-medium">{row.name}</p><p className="mt-1 truncate text-[10px] text-[var(--muted)]">{row.credentialNumber||row.qualification||row.code}{row.expiresAt?` · ${date(row.expiresAt)}`:""}</p></div><span className={`shrink-0 rounded-full border border-[var(--line)] px-2 py-1 text-[10px] font-semibold ${row.status!=="VERIFIED"?"text-[var(--danger)]":risk?"text-[var(--warning)]":"text-[var(--accent)]"}`}>{risk?`${days} gün`:label(row.status)}</span></div>})}</div>{!rows.length?<p className="mt-4 text-xs text-[var(--muted)]">Bu çalışan için henüz sertifika kaydı bulunmuyor.</p>:rows.length>6?<p className="mt-3 text-[10px] text-[var(--muted)]">İlk 6 kayıt gösteriliyor. Tüm kayıtlar yönetim ekranında görüntülenebilir.</p>:null}</>}</section>
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-[var(--line)] bg-[var(--surface-2)]/40 p-3"><p className="text-[9px] uppercase tracking-[.08em] text-[var(--muted-soft)]">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>}
