"use client";

import Link from "next/link";
import { CardInfo } from "@/components/card-info";
import { useCallback, useEffect, useState } from "react";
import { Alert, Button, Field, GlassCard, PageHeader, Select, Spinner, TextInput } from "@/components/ui";
import { useToast } from "@/components/toast";
import { api, ApiError } from "@/lib/api";
import { getCardHelp } from "@/lib/card-help";
import { hasActiveBranch, hasPermission } from "@/lib/auth";

type Summary = { totalThreads:number; unreadThreads:number; unreadMessages:number; awaitingResponse:number; breachedTarget:number; criticalBreached:number; whatsappAwaiting:number; smsAwaiting:number; emailAwaiting:number; oldestAwaitingMinutes:number; whatsappTargetMinutes:number; smsTargetMinutes:number; emailTargetMinutes:number; criticalAfterMinutes:number };
type Policy = { id:string|null; whatsappTargetMinutes:number; smsTargetMinutes:number; emailTargetMinutes:number; criticalAfterMinutes:number; version:number };
type Breach = { subjectType:"CUSTOMER"|"LEAD"|"OPPORTUNITY"; subjectId:string; subjectLabel:string; channel:"EMAIL"|"SMS"|"WHATSAPP"; lastBody:string; lastInboundAt:string; responseAgeMinutes:number; targetMinutes:number; critical:boolean; assignedUserId:string|null; assignedUserName:string|null; unreadCount:number };
type Severity = "ALL" | "BREACHED" | "CRITICAL";

const channelLabel = { EMAIL:"E-posta", SMS:"SMS", WHATSAPP:"WhatsApp" } as const;
const subjectLabel = { CUSTOMER:"Müşteri", LEAD:"Lead", OPPORTUNITY:"Fırsat" } as const;
function waitLabel(minutes:number) { if (minutes < 60) return `${minutes} dk`; if (minutes < 1440) return `${Math.floor(minutes/60)} sa`; return `${Math.floor(minutes/1440)} gün`; }
function hrefFor(row:Breach) { if (row.subjectType === "CUSTOMER") return `/customers/${row.subjectId}`; if (row.subjectType === "LEAD") return `/crm/leads/${row.subjectId}`; return `/crm/opportunities/${row.subjectId}`; }

export default function CrmConversationAnalyticsPage() {
  const canRead=hasPermission("crm","read"), canManage=hasPermission("crm","manage"), activeBranch=hasActiveBranch();
  const { showToast }=useToast(); const [summary,setSummary]=useState<Summary|null>(null); const [policy,setPolicy]=useState<Policy|null>(null);
  const [breaches,setBreaches]=useState<Breach[]>([]); const [severity,setSeverity]=useState<Severity>("BREACHED");
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false); const [error,setError]=useState("");

  const load=useCallback(async()=>{ if(!canRead||!activeBranch){setLoading(false);return;} setLoading(true);setError("");
    try { const [metrics,currentPolicy,queue]=await Promise.all([api<Summary>("/crm/conversation-analytics/summary"),api<Policy>("/crm/conversation-operations/sla-policy"),api<Breach[]>(`/crm/conversation-analytics/breaches?severity=${severity}&limit=100`)]); setSummary(metrics);setPolicy(currentPolicy);setBreaches(queue); }
    catch(requestError){setError(requestError instanceof ApiError?requestError.message:"Konuşma analitiği yüklenemedi.");} finally{setLoading(false);} },[activeBranch,canRead,severity]);
  useEffect(()=>{void load();},[load]);

  async function savePolicy(){if(!canManage||!policy||saving)return;setSaving(true);setError("");try{const saved=await api<Policy>("/crm/conversation-operations/sla-policy",{method:"PATCH",body:{version:policy.version,whatsappTargetMinutes:policy.whatsappTargetMinutes,smsTargetMinutes:policy.smsTargetMinutes,emailTargetMinutes:policy.emailTargetMinutes,criticalAfterMinutes:policy.criticalAfterMinutes}});setPolicy(saved);showToast("Conversation SLA policy kaydedildi.");await load();}catch(requestError){setError(requestError instanceof ApiError?requestError.message:"SLA policy kaydedilemedi.");}finally{setSaving(false);}}
  function updatePolicy(key:keyof Pick<Policy,"whatsappTargetMinutes"|"smsTargetMinutes"|"emailTargetMinutes"|"criticalAfterMinutes">,value:string){setPolicy(current=>current?{...current,[key]:Math.max(0,Number(value)||0)}:current);}

  return <div className="space-y-6">
    <PageHeader title="Conversation SLA Analytics" description="Şubenin WhatsApp, SMS ve e-posta konuşmalarında cevap yükünü, SLA riskini ve müdahale kuyruğunu yönetin." action={<div className="flex gap-2"><Link href="/crm/conversations"><Button variant="secondary">Inbox</Button></Link><Button variant="secondary" onClick={()=>void load()}>Yenile</Button></div>}/>
    {!activeBranch?<Alert>Conversation analytics için aktif şube seçin.</Alert>:null}{!canRead?<Alert>Bu ekran için crm.read yetkisi gerekir.</Alert>:null}{error?<Alert>{error}</Alert>:null}
    {loading?<Spinner label="Conversation SLA metrikleri yükleniyor..."/>:summary?<>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><GlassCard><p className="text-[10px] text-[var(--muted)]">Toplam Konuşma</p><strong className="mt-2 block text-[22px]">{summary.totalThreads}</strong></GlassCard><GlassCard><p className="text-[10px] text-[var(--muted)]">Okunmamış Thread</p><strong className="mt-2 block text-[22px]">{summary.unreadThreads}</strong><p className="mt-1 text-[9px] text-[var(--muted)]">{summary.unreadMessages} mesaj</p></GlassCard><GlassCard><div className="flex items-start justify-between gap-3"><p className="text-[10px] text-[var(--muted)]">Cevap Bekleyen</p><CardInfo help={getCardHelp("Cevap Bekleyen")} /></div><strong className="mt-2 block text-[22px]">{summary.awaitingResponse}</strong></GlassCard><GlassCard><div className="flex items-start justify-between gap-3"><p className="text-[10px] text-[var(--muted)]">SLA İhlali</p><CardInfo help={getCardHelp("SLA İhlali", "Tanımlı cevap süresi hedefini aşan konuşmaları gösterir.")} /></div><strong className="mt-2 block text-[22px]">{summary.breachedTarget}</strong></GlassCard><GlassCard><div className="flex items-start justify-between gap-3"><p className="text-[10px] text-[var(--muted)]">Kritik İhlal</p><CardInfo help={getCardHelp("Kritik İhlal", "Kritik cevap süresi eşiğini aşmış konuşmaları gösterir.")} /></div><strong className="mt-2 block text-[22px]">{summary.criticalBreached}</strong></GlassCard><GlassCard><div className="flex items-start justify-between gap-3"><p className="text-[10px] text-[var(--muted)]">En Eski Bekleyen</p><CardInfo help={getCardHelp("En Eski Bekleyen", "Henüz yanıtlanmamış konuşmalar içindeki en uzun bekleme süresini gösterir.")} /></div><strong className="mt-2 block text-[22px]">{waitLabel(summary.oldestAwaitingMinutes)}</strong></GlassCard></div>
      <section className="grid gap-4 lg:grid-cols-3"><GlassCard><div className="flex items-start justify-between gap-3"><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[var(--accent)]">WhatsApp</p><CardInfo help={getCardHelp("WhatsApp", "WhatsApp kanalında cevap bekleyen konuşmaları gösterir.")} /></div><strong className="mt-3 block text-[28px]">{summary.whatsappAwaiting}</strong><p className="mt-1 text-[10px] text-[var(--muted)]">cevap bekleyen · hedef {waitLabel(summary.whatsappTargetMinutes)}</p></GlassCard><GlassCard><div className="flex items-start justify-between gap-3"><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[var(--accent)]">SMS</p><CardInfo help={getCardHelp("SMS", "SMS kanalında cevap bekleyen konuşmaları gösterir.")} /></div><strong className="mt-3 block text-[28px]">{summary.smsAwaiting}</strong><p className="mt-1 text-[10px] text-[var(--muted)]">cevap bekleyen · hedef {waitLabel(summary.smsTargetMinutes)}</p></GlassCard><GlassCard><div className="flex items-start justify-between gap-3"><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[var(--accent)]">E-posta</p><CardInfo help={getCardHelp("E-posta", "E-posta kanalında cevap bekleyen konuşmaları gösterir.")} /></div><strong className="mt-3 block text-[28px]">{summary.emailAwaiting}</strong><p className="mt-1 text-[10px] text-[var(--muted)]">cevap bekleyen · hedef {waitLabel(summary.emailTargetMinutes)}</p></GlassCard></section>
      {policy?<GlassCard><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-[14px] font-semibold">Branch SLA Policy</h2><p className="mt-1 text-[10px] text-[var(--muted)]">Dakika cinsinden cevap hedefleri. Kritik eşik tüm kanallara uygulanır. Version {policy.version}.</p></div>{canManage?<Button disabled={saving} onClick={()=>void savePolicy()}>{saving?"Kaydediliyor...":"SLA Policy Kaydet"}</Button>:null}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Field label="WhatsApp hedef (dk)"><TextInput type="number" min={5} max={10080} disabled={!canManage} value={policy.whatsappTargetMinutes} onChange={e=>updatePolicy("whatsappTargetMinutes",e.target.value)}/></Field><Field label="SMS hedef (dk)"><TextInput type="number" min={5} max={10080} disabled={!canManage} value={policy.smsTargetMinutes} onChange={e=>updatePolicy("smsTargetMinutes",e.target.value)}/></Field><Field label="E-posta hedef (dk)"><TextInput type="number" min={5} max={10080} disabled={!canManage} value={policy.emailTargetMinutes} onChange={e=>updatePolicy("emailTargetMinutes",e.target.value)}/></Field><Field label="Kritik eşik (dk)"><TextInput type="number" min={30} max={43200} disabled={!canManage} value={policy.criticalAfterMinutes} onChange={e=>updatePolicy("criticalAfterMinutes",e.target.value)}/></Field></div></GlassCard>:null}
      <GlassCard className="p-0"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-[var(--line)] px-5 py-4"><div><h2 className="text-[14px] font-semibold">SLA Müdahale Kuyruğu</h2><p className="mt-1 text-[10px] text-[var(--muted)]">En kritik ve hedefi en fazla aşan konuşmalar önce gösterilir.</p></div><Select value={severity} onChange={e=>setSeverity(e.target.value as Severity)} className="max-w-[180px]"><option value="BREACHED">SLA ihlalleri</option><option value="CRITICAL">Sadece kritik</option><option value="ALL">Tüm bekleyenler</option></Select></div>{breaches.length?<div className="divide-y divide-[var(--line)]">{breaches.map(row=><div key={`${row.subjectType}:${row.subjectId}`} className="grid gap-3 px-5 py-4 lg:grid-cols-[minmax(0,1fr)_120px_130px_160px_auto] lg:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="truncate text-[11px]">{row.subjectLabel}</strong><span className="text-[9px] text-[var(--muted)]">{subjectLabel[row.subjectType]} · {channelLabel[row.channel]}</span>{row.unreadCount?<span className="rounded-full bg-[var(--accent)] px-2 py-0.5 text-[9px] font-semibold text-white">{row.unreadCount} yeni</span>:null}</div><p className="mt-1 line-clamp-1 text-[10px] text-[var(--muted)]">{row.lastBody}</p></div><span className={`w-fit rounded-full px-2 py-1 text-[9px] font-semibold ${row.critical?"bg-[#fff0eb] text-[#9c513f]":"bg-[var(--warning-soft)] text-[var(--warning)]"}`}>{row.critical?"Kritik":"İhlal"}</span><div className="text-[10px]"><strong>{waitLabel(row.responseAgeMinutes)}</strong><p className="mt-1 text-[9px] text-[var(--muted)]">hedef {waitLabel(row.targetMinutes)}</p></div><p className="truncate text-[10px] text-[var(--muted)]">{row.assignedUserName?`Sahibi: ${row.assignedUserName}`:"Atanmamış"}</p><div className="flex gap-2"><Link href={`/crm/conversations?subjectType=${row.subjectType}&subjectId=${row.subjectId}`}><Button variant="secondary">Inbox</Button></Link><Link href={hrefFor(row)}><Button variant="secondary">CRM Kaydı</Button></Link></div></div>)}</div>:<div className="p-5"><Alert tone="success">Seçili SLA filtresinde müdahale bekleyen konuşma yok.</Alert></div>}</GlassCard>
      <Alert tone={summary.criticalBreached>0?undefined:"success"}>{summary.criticalBreached>0?`${summary.criticalBreached} konuşma branch kritik SLA eşiğini aştı. Müdahale kuyruğundan öncelikli olarak ele alınmalı.`:"Kritik conversation SLA ihlali yok."}</Alert>
    </>:null}
  </div>;
}
