"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Button, Spinner } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import { hasPermission } from "@/lib/auth";

type Creator={id:string;displayName:string;category?:string|null;status:string;primaryPlatform:string;handle:string;followerCount:string|number;engagementRate?:string|number|null;rateCard:Record<string,unknown>;attributedRevenue:string|number;collaborationCount:number};
type Collaboration={id:string;status:string;feeAmount:string|number;currency:string;couponCode?:string|null;deliverables:Array<{platform:string;format:string;quantity:number}>;attributedRevenue:string|number};
const field="mt-2 h-11 w-full rounded-[13px] border border-[var(--line)] bg-white px-3 text-[12px] text-[var(--ink)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]";
const money=new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0});
const number=new Intl.NumberFormat("tr-TR");

export default function CreatorsPage(){
 const canManage=hasPermission("communications","manage");const [rows,setRows]=useState<Creator[]>([]);const [selected,setSelected]=useState<Creator|null>(null);const [collabs,setCollabs]=useState<Collaboration[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [name,setName]=useState("");const [platform,setPlatform]=useState("INSTAGRAM");const [handle,setHandle]=useState("");const [followers,setFollowers]=useState("");const [engagement,setEngagement]=useState("");const [category,setCategory]=useState("");const [reelRate,setReelRate]=useState("");const [storyRate,setStoryRate]=useState("");const [fee,setFee]=useState("");const [coupon,setCoupon]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setRows(await api<Creator[]>("/corporate-communications/creators?limit=100"));}catch(e){setError(e instanceof ApiError?e.message:"Creator kayıtları yüklenemedi.");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const stats=useMemo(()=>({active:rows.filter((r)=>r.status==="ACTIVE").length,reach:rows.reduce((s,r)=>s+Number(r.followerCount||0),0),revenue:rows.reduce((s,r)=>s+Number(r.attributedRevenue||0),0)}),[rows]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{await api("/corporate-communications/creators",{method:"POST",body:{displayName:name,category:category||null,primaryPlatform:platform,handle,followerCount:Number(followers||0),engagementRate:engagement?Number(engagement):null,audienceProfile:{},rateCard:{...(reelRate?{reel:Number(reelRate)}:{}),...(storyRate?{story:Number(storyRate)}:{})},metadata:{source:"CREATOR_CRM"}}});setName("");setHandle("");setFollowers("");setEngagement("");setCategory("");setReelRate("");setStoryRate("");await load();}catch(err){setError(err instanceof ApiError?err.message:"Creator kaydedilemedi.");}finally{setSaving(false);}}
 async function openCreator(row:Creator){setSelected(row);setError("");try{setCollabs(await api<Collaboration[]>(`/corporate-communications/creators/${row.id}/collaborations`));}catch(e){setError(e instanceof ApiError?e.message:"İşbirlikleri yüklenemedi.");}}
 async function addCollaboration(){if(!selected)return;setSaving(true);setError("");try{await api(`/corporate-communications/creators/${selected.id}/collaborations`,{method:"POST",body:{status:"CONTRACTED",feeAmount:Number(fee||0),currency:"TRY",couponCode:coupon||null,deliverables:[{platform:selected.primaryPlatform,format:"REEL",quantity:1}],performance:{},notes:null}});setFee("");setCoupon("");await openCreator(selected);}catch(e){setError(e instanceof ApiError?e.message:"İşbirliği oluşturulamadı.");}finally{setSaving(false);}}
 if(loading&&!rows.length)return <div className="py-20"><Spinner label="Creator CRM yükleniyor..."/></div>;
 return <div className="space-y-6 pb-12"><header className="rounded-[24px] border border-[var(--line)] bg-[var(--surface)] p-6"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--accent)]">Kurumsal İletişim</p><h1 className="text-[30px] font-semibold tracking-[-.04em] text-[var(--ink)]">Influencer / Creator CRM</h1><p className="mt-2 max-w-4xl text-[12px] leading-5 text-[var(--muted)]">Creator profilleri, platform metrikleri, rate card, kampanya işbirlikleri, deliverable, kupon ve attribution verilerini tek yerde yönetin.</p></header>{error?<Alert>{error}</Alert>:null}<section className="grid gap-4 sm:grid-cols-3"><Metric label="Aktif Creator" value={String(stats.active)}/><Metric label="Toplam Takipçi" value={number.format(stats.reach)}/><Metric label="Atfedilen Gelir" value={money.format(stats.revenue)}/></section>
 <div className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]">{canManage?<form onSubmit={(e)=>void create(e)} className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="text-[15px] font-semibold text-[var(--ink)]">Creator Ekle</h2><label className="mt-5 block text-[11px] font-semibold text-[var(--muted)]">Görünen ad<input required className={field} value={name} onChange={(e)=>setName(e.target.value)}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="mt-4 block text-[11px] font-semibold text-[var(--muted)]">Platform<select className={field} value={platform} onChange={(e)=>setPlatform(e.target.value)}><option>INSTAGRAM</option><option>TIKTOK</option><option>YOUTUBE</option><option>FACEBOOK</option><option>LINKEDIN</option><option>OTHER</option></select></label><label className="mt-4 block text-[11px] font-semibold text-[var(--muted)]">Handle<input required className={field} value={handle} onChange={(e)=>setHandle(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Kategori<input className={field} value={category} onChange={(e)=>setCategory(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Takipçi<input type="number" min="0" className={field} value={followers} onChange={(e)=>setFollowers(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Engagement %<input type="number" min="0" step="0.01" className={field} value={engagement} onChange={(e)=>setEngagement(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Reel rate<input type="number" min="0" className={field} value={reelRate} onChange={(e)=>setReelRate(e.target.value)}/></label><label className="block text-[11px] font-semibold text-[var(--muted)]">Story rate<input type="number" min="0" className={field} value={storyRate} onChange={(e)=>setStoryRate(e.target.value)}/></label></div><Button className="mt-5" disabled={saving} type="submit">{saving?"Kaydediliyor...":"Creator Kaydet"}</Button></form>:null}
 <section className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="text-[15px] font-semibold text-[var(--ink)]">Creator Portföyü</h2><div className="mt-4 space-y-3">{rows.map((row)=><button type="button" key={row.id} onClick={()=>void openCreator(row)} className="w-full rounded-[16px] border border-[var(--line)] p-4 text-left hover:bg-[var(--surface-2)]"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="text-[13px] font-semibold text-[var(--ink)]">{row.displayName}</p><Badge text={row.primaryPlatform}/><Badge text={row.status}/></div><p className="mt-1 text-[10px] text-[var(--muted)]">@{row.handle} · {number.format(Number(row.followerCount||0))} takipçi · {row.engagementRate??"—"}% engagement</p></div><div className="text-right"><p className="text-[11px] font-semibold text-[var(--ink)]">{row.collaborationCount} işbirliği</p><p className="mt-1 text-[10px] text-[var(--muted)]">{money.format(Number(row.attributedRevenue||0))}</p></div></div></button>)}</div></section></div>
 {selected?<section className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-[15px] font-semibold text-[var(--ink)]">{selected.displayName} · İşbirlikleri</h2><p className="mt-1 text-[10px] text-[var(--muted)]">@{selected.handle}</p></div>{canManage?<div className="flex gap-2"><input className="h-10 rounded-[11px] border border-[var(--line)] px-3 text-[11px]" placeholder="Ücret" type="number" value={fee} onChange={(e)=>setFee(e.target.value)}/><input className="h-10 rounded-[11px] border border-[var(--line)] px-3 text-[11px]" placeholder="Kupon" value={coupon} onChange={(e)=>setCoupon(e.target.value)}/><Button disabled={saving} onClick={()=>void addCollaboration()}>İşbirliği Ekle</Button></div>:null}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{collabs.map((c)=><div key={c.id} className="rounded-[15px] border border-[var(--line)] p-4"><div className="flex items-center justify-between gap-2"><Badge text={c.status}/><p className="text-[12px] font-semibold text-[var(--ink)]">{money.format(Number(c.feeAmount||0))}</p></div><p className="mt-2 text-[10px] text-[var(--muted)]">{c.couponCode?`Kupon: ${c.couponCode}`:"Kupon yok"} · {c.deliverables.reduce((s,d)=>s+d.quantity,0)} deliverable</p><p className="mt-2 text-[10px] text-[var(--muted)]">Atfedilen gelir {money.format(Number(c.attributedRevenue||0))}</p></div>)}</div></section>:null}</div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-[18px] border border-[var(--line)] bg-[var(--surface)] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[var(--muted-soft)]">{label}</p><p className="mt-2 text-[22px] font-semibold text-[var(--ink)]">{value}</p></div>}
function Badge({text}:{text:string}){return <span className="rounded-full bg-[var(--accent-soft)] px-2 py-1 text-[9px] font-semibold text-[var(--accent)]">{text.replaceAll("_"," ")}</span>}
