"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { FinanceEmpty, FinancePanel } from "@/components/finance-view";
import { Alert, Button, Field, Spinner, TextInput } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import { useParams } from "next/navigation";

type Version={id:string;version:number;status:string;requiresPractical:boolean;practicalPassScore?:number|null};
type Criterion={id?:string;code:string;label:string;description:string;weightPercent:string;minimumScore:string;isRequired:boolean};
type Rubric={id:string;title:string;instructions?:string|null;criteria:Array<{id:string;code:string;label:string;description?:string|null;weightPercent:number;minimumScore?:number|null;isRequired:boolean}>};
const blank=():Criterion=>({code:"",label:"",description:"",weightPercent:"",minimumScore:"",isRequired:true});
function msg(e:unknown){return e instanceof ApiError?e.message:e instanceof Error?e.message:"Rubric işlemi tamamlanamadı.";}

export default function PracticalRubricPage(){
 const {courseId}=useParams<{courseId:string}>();
 const [version,setVersion]=useState<Version|null>(null),[title,setTitle]=useState("Pratik Değerlendirme Rubric'i"),[instructions,setInstructions]=useState(""),[criteria,setCriteria]=useState<Criterion[]>([blank()]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const versions=await api<Version[]>(`/training/lms/courses/${courseId}/versions`);const draft=versions.find(v=>v.status==="DRAFT")??null;setVersion(draft);if(draft?.requiresPractical){try{const r=await api<Rubric>(`/training/practical/versions/${draft.id}/rubric`);setTitle(r.title);setInstructions(r.instructions??"");setCriteria(r.criteria.map(c=>({id:c.id,code:c.code,label:c.label,description:c.description??"",weightPercent:String(c.weightPercent),minimumScore:c.minimumScore==null?"":String(c.minimumScore),isRequired:c.isRequired})));}catch(e){if(!(e instanceof ApiError&&e.status===404))throw e;}}}catch(e){setError(msg(e));}finally{setLoading(false);}},[courseId]);
 useEffect(()=>{void load();},[load]);
 function patch(index:number,key:keyof Criterion,value:string|boolean){setCriteria(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row));}
 async function save(event:FormEvent){event.preventDefault();if(!version||saving)return;setSaving(true);setError("");setSuccess("");try{await api(`/training/practical/versions/${version.id}/rubric`,{method:"PUT",body:{title,instructions:instructions||null,criteria:criteria.map(c=>({code:c.code,label:c.label,description:c.description||null,weightPercent:Number(c.weightPercent),minimumScore:c.minimumScore===""?null:Number(c.minimumScore),isRequired:c.isRequired}))}});setSuccess("Pratik rubric kaydedildi. Course version publish edildiğinde rubric immutable hale gelir.");await load();}catch(e){setError(msg(e));}finally{setSaving(false);}}
 if(loading)return <div className="flex min-h-[360px] items-center justify-center"><Spinner label="Pratik Rubric Hazırlanıyor..."/></div>;
 if(!version)return <FinanceEmpty title="Taslak sürüm yok" description="Pratik değerlendirme ölçütlerini düzenlemek için önce kursun taslak sürümünü oluşturun."/>;
 if(!version.requiresPractical)return <FinanceEmpty title="Pratik değerlendirme gerekmiyor" description="Bu taslak sürüm yalnızca teori eğitimi olarak tanımlı."/>;
 const total=criteria.reduce((sum,c)=>sum+(Number(c.weightPercent)||0),0);
 return <div className="space-y-5 pb-10">{error?<Alert>{error}</Alert>:null}{success?<Alert tone="success">{success}</Alert>:null}<FinancePanel title={`Pratik değerlendirme ölçütleri · Sürüm ${version.version}`} description={`Geçme puanı: ${version.practicalPassScore??70}. Kriter ağırlıkları toplamı %100 olmalıdır.`}><form onSubmit={save} className="space-y-5"><Field label="Rubric Başlığı"><TextInput required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Assessor Talimatı"><textarea className="control min-h-[90px] w-full" value={instructions} onChange={e=>setInstructions(e.target.value)}/></Field><div className="space-y-3">{criteria.map((c,index)=><div key={index} className="rounded-[16px] border border-[var(--line)] p-4"><div className="grid gap-3 md:grid-cols-2"><Field label="Kod"><TextInput required value={c.code} onChange={e=>patch(index,"code",e.target.value)}/></Field><Field label="Kriter"><TextInput required value={c.label} onChange={e=>patch(index,"label",e.target.value)}/></Field><Field label="Ağırlık %"><TextInput required type="number" min="0.001" max="100" step="0.001" value={c.weightPercent} onChange={e=>patch(index,"weightPercent",e.target.value)}/></Field><Field label="Minimum Puan"><TextInput type="number" min="0" max="100" value={c.minimumScore} onChange={e=>patch(index,"minimumScore",e.target.value)}/></Field></div><Field label="Açıklama"><TextInput value={c.description} onChange={e=>patch(index,"description",e.target.value)}/></Field><div className="mt-3 flex items-center justify-between"><label className="flex items-center gap-2 text-[11px] text-[var(--muted)]"><input type="checkbox" checked={c.isRequired} onChange={e=>patch(index,"isRequired",e.target.checked)}/> Zorunlu kriter</label>{criteria.length>1?<Button type="button" variant="secondary" onClick={()=>setCriteria(rows=>rows.filter((_,i)=>i!==index))}>Kaldır</Button>:null}</div></div>)}</div><div className="flex flex-wrap items-center justify-between gap-3"><div><Button type="button" variant="secondary" onClick={()=>setCriteria(rows=>[...rows,blank()])}>Kriter Ekle</Button><span className={`ml-3 text-[11px] font-semibold ${Math.abs(total-100)<0.001?"text-[var(--success)]":"text-[var(--warning)]"}`}>Toplam %{total}</span></div><Button type="submit" disabled={saving||Math.abs(total-100)>=0.001}>{saving?"Kaydediliyor...":"Rubric Kaydet"}</Button></div></form></FinancePanel></div>;
}