"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { DatePicker } from "@/components/date-picker";
import { Alert, Button, Spinner } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import { hasPermission } from "@/lib/auth";
import { userLabel } from "@/lib/user-language";

type DocumentRow={id:string;documentType:string;documentNumber?:string|null;title:string;issuedAt?:string|null;expiresAt?:string|null;status:string;fileName?:string|null;version:number;restricted:boolean;verificationNote?:string|null;createdAt?:string};
type FormState={documentType:string;documentNumber:string;title:string;issuedAt:string;expiresAt:string;fileKey:string;fileName:string;mimeType:string;restricted:boolean;notes:string};
const EMPTY:FormState={documentType:"",documentNumber:"",title:"",issuedAt:"",expiresAt:"",fileKey:"",fileName:"",mimeType:"",restricted:true,notes:""};
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString("tr-TR"):"—";
const daysLeft=(v?:string|null)=>v?Math.ceil((new Date(v).getTime()-Date.now())/86400000):null;

export default function EmployeeDocumentsPage(){const{id}=useParams<{id:string}>();const[rows,setRows]=useState<DocumentRow[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[form,setForm]=useState<FormState>(EMPTY);const canSensitive=hasPermission("hr_sensitive","read"),canManage=hasPermission("hr","manage")&&canSensitive;
async function load(){setLoading(true);setError("");try{const path=canSensitive?`/hr/employees/${id}/documents/sensitive`:`/hr/employees/${id}/documents`;setRows(await api<DocumentRow[]>(path))}catch(e){setError(e instanceof ApiError?e.message:"Personel belgeleri yüklenemedi.")}finally{setLoading(false)}}useEffect(()=>{void load()},[id,canSensitive]);
async function create(e:FormEvent){e.preventDefault();if(!canManage)return;setSaving(true);setError("");try{await api(`/hr/employees/${id}/documents`,{method:"POST",body:{...form,documentNumber:form.documentNumber||undefined,issuedAt:form.issuedAt||undefined,expiresAt:form.expiresAt||undefined,fileKey:form.fileKey||undefined,fileName:form.fileName||undefined,mimeType:form.mimeType||undefined,notes:form.notes||undefined}});setForm(EMPTY);await load()}catch(x){setError(x instanceof ApiError?x.message:"Belge kaydedilemedi.")}finally{setSaving(false)}}
async function verify(row:DocumentRow,status:"VERIFIED"|"REJECTED"){let note="";if(status==="REJECTED"){note=window.prompt("Ret gerekçesi")?.trim()||"";if(!note)return}try{await api(`/hr/employees/${id}/documents/${row.id}/verify`,{method:"PATCH",body:{status,note:note||undefined}});await load()}catch(e){setError(e instanceof ApiError?e.message:"Belge doğrulanamadı.")}}
async function archive(row:DocumentRow){if(!window.confirm(`${row.title} arşivlensin mi?`))return;try{await api(`/hr/employees/${id}/documents/${row.id}/archive`,{method:"POST"});await load()}catch(e){setError(e instanceof ApiError?e.message:"Belge arşivlenemedi.")}}
return <div className="mx-auto max-w-[1280px] space-y-5 pb-12"><header><Link href={`/hr/employees/${id}`} className="text-xs font-semibold text-[var(--accent)]">← Personel 360°</Link><p className="mt-4 text-[11px] font-semibold uppercase tracking-[.15em] text-[var(--muted-soft)]">Özlük · Belge ve Uyum</p><h1 className="mt-1 text-[30px] font-semibold tracking-[-.035em]">Personel Belgeleri</h1><p className="mt-1 text-xs text-[var(--muted)]">Belge sürümlerini, doğrulama durumunu ve geçerlilik tarihlerini yönetin.</p></header>{error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}
{canManage?<form onSubmit={create} className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><div className="mb-4"><h2 className="text-sm font-semibold">Yeni belge / yeni sürüm</h2><p className="mt-1 text-[11px] text-[var(--muted)]">Aynı belge türü ve numarası yeniden kaydedildiğinde sistem yeni bir sürüm oluşturur.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input label="Belge Türü" value={form.documentType} required onChange={v=>setForm(x=>({...x,documentType:v}))}/><Input label="Belge No" value={form.documentNumber} onChange={v=>setForm(x=>({...x,documentNumber:v}))}/><Input label="Başlık" value={form.title} required onChange={v=>setForm(x=>({...x,title:v}))}/><Input label="Dosya Adı" value={form.fileName} onChange={v=>setForm(x=>({...x,fileName:v}))}/><Input label="Düzenlenme Tarihi" type="date" value={form.issuedAt} onChange={v=>setForm(x=>({...x,issuedAt:v}))}/><Input label="Son Geçerlilik" type="date" value={form.expiresAt} onChange={v=>setForm(x=>({...x,expiresAt:v}))}/><Input label="Dosya kayıt bilgisi" value={form.fileKey} onChange={v=>setForm(x=>({...x,fileKey:v}))}/><Input label="Dosya türü" value={form.mimeType} onChange={v=>setForm(x=>({...x,mimeType:v}))}/></div><label className="mt-3 flex items-center gap-2 text-xs text-[var(--muted)]"><input type="checkbox" checked={form.restricted} onChange={e=>setForm(x=>({...x,restricted:e.target.checked}))}/> Kısıtlı / hassas belge</label><label className="mt-3 block"><span className="mb-1 block text-[11px] text-[var(--muted)]">Not</span><textarea className="control min-h-20 w-full p-3" value={form.notes} onChange={e=>setForm(x=>({...x,notes:e.target.value}))}/></label><div className="mt-4 flex justify-end"><Button type="submit" disabled={saving}>{saving?"Kaydediliyor…":"Belgeyi Kaydet"}</Button></div></form>:<div className="rounded-[16px] border border-[var(--line)] bg-[var(--surface)] p-4 text-xs text-[var(--muted)]">Belge ekleme, doğrulama ve arşivleme işlemleri için personel belgelerini yönetme ve hassas personel verilerini görüntüleme yetkileri gerekir.</div>}
<section className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)]"><div className="flex items-center justify-between border-b border-[var(--line)] p-5"><h2 className="text-sm font-semibold">Belge Envanteri</h2><span className="text-xs text-[var(--muted)]">{rows.length} kayıt</span></div>{loading?<div className="flex h-48 items-center justify-center"><Spinner/></div>:rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b border-[var(--line)] text-[10px] uppercase text-[var(--muted-soft)]"><th className="p-4">Belge</th><th className="p-4">Sürüm</th><th className="p-4">Durum</th><th className="p-4">Geçerlilik</th><th className="p-4">Erişim</th><th className="p-4">İşlem</th></tr></thead><tbody>{rows.map(r=>{const left=daysLeft(r.expiresAt);return <tr key={r.id} className="border-b border-[var(--line)] last:border-0"><td className="p-4"><strong>{r.title}</strong><p className="mt-1 text-[10px] text-[var(--muted)]">{userLabel(r.documentType)}{r.documentNumber?` · ${r.documentNumber}`:""}{r.fileName?` · ${r.fileName}`:""}</p></td><td className="p-4">Sürüm {r.version}</td><td className="p-4"><span className="rounded-full border border-[var(--line)] px-2 py-1 text-[10px] font-semibold">{userLabel(r.status)}</span>{r.verificationNote?<p className="mt-2 max-w-52 text-[10px] text-[var(--muted)]">{r.verificationNote}</p>:null}</td><td className="p-4">{date(r.expiresAt)}<p className={`mt-1 text-[10px] ${left!==null&&left<=30?"text-[var(--danger)]":"text-[var(--muted)]"}`}>{left===null?"Süresiz":left<0?`${Math.abs(left)} gün önce doldu`:`${left} gün kaldı`}</p></td><td className="p-4">{r.restricted?"Kısıtlı":"Standart"}</td><td className="p-4">{canManage&&r.status!=="ARCHIVED"?<div className="flex flex-wrap gap-3"><button type="button" className="font-semibold text-[var(--accent)]" onClick={()=>void verify(r,"VERIFIED")}>Doğrula</button><button type="button" className="text-[var(--danger)]" onClick={()=>void verify(r,"REJECTED")}>Reddet</button><button type="button" className="text-[var(--muted)]" onClick={()=>void archive(r)}>Arşivle</button></div>:"—"}</td></tr>})}</tbody></table></div>:<div className="p-10 text-center text-xs text-[var(--muted)]">Henüz personel belgesi bulunmuyor.</div>}</section></div>}
function Input({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label><span className="mb-1.5 block text-[11px] font-medium text-[var(--muted)]">{label}{required?<span className="ml-1 text-[var(--accent)]" aria-hidden="true">*</span>:null}</span>{type==="date"?<DatePicker value={value} onChange={onChange} ariaLabel={label}/>:<input className="control h-11 w-full" type={type} required={required} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
