import { EnterpriseDataPage } from "@/components/enterprise-data-page";
export default function HRPlanningPage(){return <EnterpriseDataPage eyebrow="İnsan Kaynakları" title="İnsan Kaynakları Planlama" description="Kadro ihtiyacını, görevlendirmeleri ve çalışan anketlerini tek merkezden planlayın." sections={[
{title:"Kadro Planı",path:"/hr/planning/headcount?periodMonth=2026-09-01"},
{title:"Seyahat ve Görevlendirmeler",path:"/hr/planning/travel"},
{title:"İK Anketleri",path:"/hr/planning/surveys"},
]} forms={[
{title:"Kadro Planını Kaydet",path:"/hr/planning/headcount",fields:[{name:"periodMonth",label:"Dönem",type:"date",required:true},{name:"targetHeadcount",label:"Hedef Çalışan Sayısı",type:"number",required:true},{name:"plannedHires",label:"Planlanan İşe Alım",type:"number",defaultValue:"0"},{name:"plannedExits",label:"Planlanan Çıkış",type:"number",defaultValue:"0"},{name:"notes",label:"Not",type:"textarea"}]},
{title:"Görevlendirme Talebi",path:"/hr/planning/employees/{staffId}/travel",fields:[{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"],required:true},{name:"purpose",label:"Amaç",required:true},{name:"destination",label:"Görevlendirme Yeri",required:true},{name:"startsOn",label:"Başlangıç",type:"date",required:true},{name:"endsOn",label:"Bitiş",type:"date",required:true},{name:"advanceAmount",label:"Avans Tutarı",type:"number",defaultValue:"0"},{name:"currency",label:"Para Birimi",type:"select",defaultValue:"TRY",options:[{value:"TRY",label:"Türk Lirası"},{value:"USD",label:"ABD Doları"},{value:"EUR",label:"Euro"},{value:"GBP",label:"İngiliz Sterlini"}]}]},
{title:"Çalışan Anketi Oluştur",path:"/hr/planning/surveys",fields:[{name:"name",label:"Anket Adı",required:true},{name:"surveyType",label:"Anket Türü",type:"select",required:true,options:[{value:"ENGAGEMENT",label:"Çalışan Bağlılığı"},{value:"SATISFACTION",label:"Çalışan Memnuniyeti"},{value:"PULSE",label:"Kısa Nabız Anketi"},{value:"ONBOARDING",label:"İşe Başlangıç Deneyimi"},{value:"EXIT",label:"İşten Ayrılış Deneyimi"},{value:"OTHER",label:"Diğer"}]},{name:"anonymous",label:"Anonim",type:"boolean",defaultValue:"true"},{name:"startsAt",label:"Başlangıç",type:"datetime-local"},{name:"endsAt",label:"Bitiş",type:"datetime-local"},{name:"status",label:"Durum",type:"select",defaultValue:"DRAFT",options:[{value:"DRAFT",label:"Taslak"},{value:"ACTIVE",label:"Aktif"},{value:"CLOSED",label:"Kapalı"}]}]}
]} />;}
