import { EnterpriseDataPage } from "@/components/enterprise-data-page";
export default function PlatformControlPlanePage(){return <EnterpriseDataPage eyebrow="VALOO Platform Yönetimi" title="SaaS Control Plane" description="Tenant provisioning, abonelik, müşteri başarısı, destek ve entitlement katmanlarını merkezi olarak izleyin." sections={[
{title:"Provisioning Özeti",path:"/platform/provisioning/summary"},
{title:"Provisioning Çalışmaları",path:"/platform/provisioning?limit=100"},
{title:"Paketler ve Planlar",path:"/platform/plans"},
{title:"Müşteri Başarısı",path:"/platform/customer-success?limit=100"},
{title:"Tenant Sağlığı",path:"/platform/customer-success/health?limit=100"},
{title:"Destek Özeti",path:"/platform/support/summary"},
{title:"Destek Talepleri",path:"/platform/support/tickets?limit=100"},
{title:"Entitlement Kataloğu",path:"/platform/entitlements"},
]} actions={[
{label:"Bekleyen Sahip Davetlerini Gönder",path:"/platform/provisioning/owner-invitations/dispatch-due",body:{limit:10,reason:"Platform yönetim ekranı tetikledi"},success:"Bekleyen sahip davetleri işlendi."}
]} forms={[
{title:"Yeni Tenant Provisioning Başlat",path:"/platform/provisioning",fields:[{name:"tenantName",label:"Tenant Adı",required:true},{name:"tenantSlug",label:"Tenant Slug",required:true},{name:"planVersionId",label:"Plan Versiyonu ID",required:true},{name:"companyName",label:"Şirket Adı",required:true},{name:"companySlug",label:"Şirket Slug",required:true},{name:"primaryBranchName",label:"İlk Şube Adı",required:true},{name:"primaryBranchCode",label:"İlk Şube Kodu",required:true},{name:"sourceType",label:"Kaynak",type:"select",defaultValue:"MANUAL",options:[{value:"MANUAL",label:"Manuel"},{value:"OPPORTUNITY",label:"Fırsat"}]},{name:"ownerEmail",label:"Şirket Sahibi E-posta"},{name:"reason",label:"Neden",type:"textarea"}]},
{title:"Paket / Plan Versiyonu Oluştur",path:"/platform/plans/versions",fields:[{name:"code",label:"Plan Kodu",required:true},{name:"name",label:"Plan Adı",required:true},{name:"description",label:"Açıklama",type:"textarea"},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"monthlyPrice",label:"Aylık Fiyat",type:"number"},{name:"annualPrice",label:"Yıllık Fiyat",type:"number"},{name:"branchLimit",label:"Şube Limiti",type:"number"},{name:"userLimit",label:"Kullanıcı Limiti",type:"number"}]},
{title:"Tenant Aboneliği Ata",path:"/platform/customers/{tenantId}/subscription",fields:[{name:"tenantId",label:"Tenant ID",required:true},{name:"planVersionId",label:"Plan Versiyonu ID",required:true},{name:"status",label:"Durum",type:"select",defaultValue:"TRIAL",options:[{value:"TRIAL",label:"Deneme"},{value:"ACTIVE",label:"Aktif"},{value:"PAST_DUE",label:"Gecikmiş"}]},{name:"contractedMonthlyPrice",label:"Sözleşmeli Aylık Fiyat",type:"number"},{name:"contractedAnnualPrice",label:"Sözleşmeli Yıllık Fiyat",type:"number"},{name:"discountPercent",label:"İndirim %",type:"number"},{name:"startsAt",label:"Başlangıç",type:"datetime-local"},{name:"renewsAt",label:"Yenileme",type:"datetime-local"}]},
{title:"Tenant Onboarding Başlat",path:"/platform/onboarding/{tenantId}/bootstrap",fields:[{name:"tenantId",label:"Tenant ID",required:true},{name:"provisioningRunId",label:"Provisioning Run ID"},{name:"reason",label:"Neden",type:"textarea"}]},
{title:"Destek Talebi Oluştur",path:"/platform/support/tickets",fields:[{name:"tenantId",label:"Tenant ID",required:true},{name:"subject",label:"Konu",required:true},{name:"description",label:"Açıklama",type:"textarea"},{name:"priority",label:"Öncelik",defaultValue:"NORMAL"},{name:"source",label:"Kaynak",defaultValue:"PLATFORM"},{name:"requesterEmail",label:"Talep Eden E-posta"},{name:"assignedPlatformUserId",label:"Atanan Platform Kullanıcı ID"}]},
{title:"Destek SLA Politikası Oluştur",path:"/platform/support/sla/policies",fields:[{name:"priority",label:"Öncelik",required:true},{name:"name",label:"Politika Adı",required:true},{name:"initialResponseMinutes",label:"İlk Yanıt Dakika",type:"number",required:true},{name:"resolutionMinutes",label:"Çözüm Dakika",type:"number",required:true},{name:"reason",label:"Neden",type:"textarea"}]},
{title:"Müşteri Başarısı Olayı Ekle",path:"/platform/customer-success/{tenantId}/events",fields:[{name:"tenantId",label:"Tenant ID",required:true},{name:"eventType",label:"Olay Türü",required:true},{name:"severity",label:"Önem",required:true},{name:"summary",label:"Özet",required:true},{name:"happenedAt",label:"Olay Tarihi",type:"datetime-local"}]},
{title:"Tenant Sağlığını Yeniden Hesapla",path:"/platform/customer-success/{tenantId}/health/recalculate",fields:[{name:"tenantId",label:"Tenant ID",required:true},{name:"reason",label:"Neden",type:"textarea"}]},
{title:"Tenant Yetki Override Oluştur",path:"/platform/customers/{tenantId}/entitlement-overrides",fields:[{name:"tenantId",label:"Tenant ID",required:true},{name:"entitlementKey",label:"Yetki Anahtarı",required:true},{name:"value",label:"Değer",required:true},{name:"reason",label:"Neden",type:"textarea",required:true},{name:"startsAt",label:"Başlangıç",type:"datetime-local"},{name:"endsAt",label:"Bitiş",type:"datetime-local"}]}
]} />;}
