export const reportKeys = {
  staffPerformance: 'staff.performance',
  servicePerformance: 'service.performance',
  paymentSummary: 'payments.summary',
  customerPerformance: 'customers.performance',
  salesPerformance: 'sales.performance',
  appointmentPerformance: 'appointments.performance',
  financePerformance: 'finance.performance',
  inventoryPerformance: 'inventory.performance',
  procurementPerformance: 'procurement.performance',
  crmPerformance: 'crm.performance',
  hrWorkforce: 'hr.workforce',
  payrollSummary: 'payroll.summary',
} as const;

export type ReportKey = (typeof reportKeys)[keyof typeof reportKeys];
export type ReportExportFormat = 'PDF' | 'XLSX' | 'CSV';
export type ReportPermission = Readonly<{ resource: string; action: string }>;
export type ReportDefinition = Readonly<{
  key: ReportKey;
  title: string;
  description: string;
  domain: 'staff' | 'services' | 'payments' | 'customers' | 'sales' | 'appointments' | 'finance' | 'inventory' | 'procurement' | 'crm' | 'hr' | 'payroll';
  route: string;
  resultKind: 'table' | 'summary';
  requiredPermissions: readonly ReportPermission[];
  filters: readonly string[];
  availableColumns: readonly string[];
  defaultColumns: readonly string[];
  exportableColumns: readonly string[];
  sortableColumns: readonly string[];
  exportFormats: readonly ReportExportFormat[];
  drilldowns: readonly string[];
  pagination: boolean;
}>;

export const reportDefinitions: readonly ReportDefinition[] = Object.freeze([
  { key: reportKeys.staffPerformance, title: 'Personel Performansı', description: 'Personel bazında randevu, tamamlanma ve tahsilat performansı.', domain: 'staff', route: '/staff/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'staff', action: 'read' }], filters: ['from','to'], availableColumns: ['name','status','branchId','appointmentCount','completedAppointments','completionRate','collected'], defaultColumns: ['name','appointmentCount','completedAppointments','completionRate','collected'], exportableColumns: ['name','status','appointmentCount','completedAppointments','completionRate','collected'], sortableColumns: ['name','appointmentCount','completedAppointments','completionRate','collected'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: ['appointments'], pagination: true },
  { key: reportKeys.servicePerformance, title: 'Hizmet Performansı', description: 'Hizmet bazında performans görünümü.', domain: 'services', route: '/services/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'services', action: 'read' }], filters: ['from','to'], availableColumns: ['name','price','status','branchId','appointmentCount','completedAppointments','completionRate','collected'], defaultColumns: ['name','appointmentCount','completedAppointments','completionRate','collected'], exportableColumns: ['name','price','status','appointmentCount','completedAppointments','completionRate','collected'], sortableColumns: ['name','appointmentCount','completedAppointments','completionRate','collected'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: ['appointments'], pagination: true },
  { key: reportKeys.paymentSummary, title: 'Ödeme Raporu', description: 'Ödeme ve tahsilat performansı görünümü.', domain: 'payments', route: '/payments/summary', resultKind: 'summary', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'payments', action: 'read' }], filters: ['from','to'], availableColumns: ['gross','refunds','net','paymentCount','refundCount','methods'], defaultColumns: ['gross','refunds','net','paymentCount','refundCount','methods'], exportableColumns: ['gross','refunds','net','paymentCount','refundCount','methods'], sortableColumns: [], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: false },
  { key: reportKeys.customerPerformance, title: 'Müşteri Performansı', description: 'Müşteri bazında ziyaret ve tahsilat performansı.', domain: 'customers', route: '/customers/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'customers', action: 'read' }], filters: ['from','to'], availableColumns: ['name','customerSource','customerSince','visitCount','completedVisits','firstVisitAt','lastVisitAt','collected','averageCollectedPerVisit'], defaultColumns: ['name','visitCount','completedVisits','lastVisitAt','collected','averageCollectedPerVisit'], exportableColumns: ['name','customerSource','customerSince','visitCount','completedVisits','firstVisitAt','lastVisitAt','collected','averageCollectedPerVisit'], sortableColumns: ['name','customerSince','visitCount','completedVisits','firstVisitAt','lastVisitAt','collected','averageCollectedPerVisit'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
  { key: reportKeys.salesPerformance, title: 'Satış Performansı', description: 'Onaylanmış satışlarda ciro, tahsilat, iade ve açık bakiye görünümü.', domain: 'sales', route: '/sales/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'payments', action: 'read' }], filters: ['from','to'], availableColumns: ['confirmedAt','customerName','subtotal','discountTotal','revenue','collected','refunded','netCollected','outstanding','itemCount','serviceQuantity','packageQuantity'], defaultColumns: ['confirmedAt','customerName','revenue','collected','refunded','outstanding','itemCount'], exportableColumns: ['confirmedAt','customerName','subtotal','discountTotal','revenue','collected','refunded','netCollected','outstanding','itemCount','serviceQuantity','packageQuantity'], sortableColumns: ['confirmedAt','customerName','subtotal','discountTotal','revenue','collected','refunded','netCollected','outstanding','itemCount','serviceQuantity','packageQuantity'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
  { key: reportKeys.appointmentPerformance, title: 'Randevu Performansı', description: 'Gün bazında tamamlanma, iptal, no-show, müşteri davranışı ve talep yoğunluğu.', domain: 'appointments', route: '/appointments/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'appointments', action: 'read' }], filters: ['from','to'], availableColumns: ['date','appointmentCount','scheduledCount','confirmedCount','completedCount','cancelledCount','noShowCount','completionRate','cancellationRate','noShowRate','uniqueCustomerCount','newCustomerCount','repeatCustomerCount','rebookedCustomerCount','rebookingRate','collected','averageDurationMinutes','peakHour'], defaultColumns: ['date','appointmentCount','completedCount','cancelledCount','noShowCount','completionRate','newCustomerCount','repeatCustomerCount','rebookingRate','peakHour'], exportableColumns: ['date','appointmentCount','scheduledCount','confirmedCount','completedCount','cancelledCount','noShowCount','completionRate','cancellationRate','noShowRate','uniqueCustomerCount','newCustomerCount','repeatCustomerCount','rebookedCustomerCount','rebookingRate','collected','averageDurationMinutes','peakHour'], sortableColumns: ['date','appointmentCount','scheduledCount','confirmedCount','completedCount','cancelledCount','noShowCount','completionRate','cancellationRate','noShowRate','uniqueCustomerCount','newCustomerCount','repeatCustomerCount','rebookedCustomerCount','rebookingRate','collected','averageDurationMinutes','peakHour'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
  { key: reportKeys.financePerformance, title: 'Finans Operasyon Özeti', description: 'Onaylı gelir/gider kayıtları, aktif tahsilat/ödemeler ve açık bakiyelerin günlük görünümü.', domain: 'finance', route: '/finance/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'finance', action: 'read' }], filters: ['from','to'], availableColumns: ['date','incomeRecognized','expenseRecognized','operatingMargin','collected','paid','netCashMovement','receivableOutstanding','payableOutstanding','collectionRate','paymentRate','incomeRecordCount','expenseRecordCount'], defaultColumns: ['date','incomeRecognized','expenseRecognized','operatingMargin','collected','paid','netCashMovement','receivableOutstanding','payableOutstanding'], exportableColumns: ['date','incomeRecognized','expenseRecognized','operatingMargin','collected','paid','netCashMovement','receivableOutstanding','payableOutstanding','collectionRate','paymentRate','incomeRecordCount','expenseRecordCount'], sortableColumns: ['date','incomeRecognized','expenseRecognized','operatingMargin','collected','paid','netCashMovement','receivableOutstanding','payableOutstanding','collectionRate','paymentRate','incomeRecordCount','expenseRecordCount'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
  { key: reportKeys.inventoryPerformance, title: 'Stok Hareket Performansı', description: 'Stok hareket türü bazında miktar, hareket sayısı ve maliyet değeri görünümü.', domain: 'inventory', route: '/inventory/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'inventory', action: 'read' }], filters: ['from','to'], availableColumns: ['date','movementType','movementCount','quantity','movementValue'], defaultColumns: ['date','movementType','movementCount','quantity','movementValue'], exportableColumns: ['date','movementType','movementCount','quantity','movementValue'], sortableColumns: ['date','movementType','movementCount','quantity','movementValue'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
  { key: reportKeys.procurementPerformance, title: 'Satın Alma Performansı', description: 'Satın alma siparişlerinde hacim, tutar, kalem ve teslim alma performansı.', domain: 'procurement', route: '/procurement/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'inventory', action: 'read' }], filters: ['from','to'], availableColumns: ['date','status','orderCount','totalAmount','itemCount','receivedCount','receiptRate'], defaultColumns: ['date','status','orderCount','totalAmount','itemCount','receivedCount','receiptRate'], exportableColumns: ['date','status','orderCount','totalAmount','itemCount','receivedCount','receiptRate'], sortableColumns: ['date','status','orderCount','totalAmount','itemCount','receivedCount','receiptRate'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
  { key: reportKeys.crmPerformance, title: 'CRM Performansı', description: 'Lead, fırsat, dönüşüm ve pipeline performansının günlük görünümü.', domain: 'crm', route: '/crm/performance', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'crm', action: 'read' }], filters: ['from','to'], availableColumns: ['date','leadCount','contactedCount','qualifiedCount','convertedCount','lostLeadCount','opportunityCount','openOpportunityCount','wonCount','lostOpportunityCount','pipelineValue','wonValue','leadConversionRate','winRate'], defaultColumns: ['date','leadCount','convertedCount','leadConversionRate','opportunityCount','openOpportunityCount','wonCount','winRate','pipelineValue','wonValue'], exportableColumns: ['date','leadCount','contactedCount','qualifiedCount','convertedCount','lostLeadCount','opportunityCount','openOpportunityCount','wonCount','lostOpportunityCount','pipelineValue','wonValue','leadConversionRate','winRate'], sortableColumns: ['date','leadCount','contactedCount','qualifiedCount','convertedCount','lostLeadCount','opportunityCount','openOpportunityCount','wonCount','lostOpportunityCount','pipelineValue','wonValue','leadConversionRate','winRate'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
  { key: reportKeys.hrWorkforce, title: 'İK İşgücü Raporu', description: 'Devam, devamsızlık, çalışma süresi, fazla mesai ve izin hareketlerinin günlük görünümü.', domain: 'hr', route: '/hr/workforce', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'hr', action: 'read' }], filters: ['from','to'], availableColumns: ['date','attendanceRecords','presentRecords','absentRecords','absenceRate','workedMinutes','overtimeMinutes','leaveRequests','approvedLeaveRequests','approvedLeaveDays'], defaultColumns: ['date','attendanceRecords','absentRecords','absenceRate','workedMinutes','overtimeMinutes','approvedLeaveDays'], exportableColumns: ['date','attendanceRecords','presentRecords','absentRecords','absenceRate','workedMinutes','overtimeMinutes','leaveRequests','approvedLeaveRequests','approvedLeaveDays'], sortableColumns: ['date','attendanceRecords','presentRecords','absentRecords','absenceRate','workedMinutes','overtimeMinutes','leaveRequests','approvedLeaveRequests','approvedLeaveDays'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
  { key: reportKeys.payrollSummary, title: 'Bordro Özeti', description: 'Bordro dönemlerinde brüt/net ücret, işveren maliyeti ve ödeme kapanış görünümü.', domain: 'payroll', route: '/hr/payroll/summary', resultKind: 'table', requiredPermissions: [{ resource: 'reports', action: 'read' }, { resource: 'hr', action: 'read' }, { resource: 'hr_sensitive', action: 'read' }], filters: ['from','to'], availableColumns: ['periodDate','status','employeeCount','gross','net','employerCost','salaryPaid','salaryRemaining','taxLiability','socialLiability','payrollSettlementRate'], defaultColumns: ['periodDate','status','employeeCount','gross','net','employerCost','salaryPaid','salaryRemaining','payrollSettlementRate'], exportableColumns: ['periodDate','status','employeeCount','gross','net','employerCost','salaryPaid','salaryRemaining','taxLiability','socialLiability','payrollSettlementRate'], sortableColumns: ['periodDate','status','employeeCount','gross','net','employerCost','salaryPaid','salaryRemaining','taxLiability','socialLiability','payrollSettlementRate'], exportFormats: ['CSV','XLSX','PDF'], drilldowns: [], pagination: true },
]);

export function getReportDefinition(key: ReportKey) {
  return reportDefinitions.find((report) => report.key === key);
}
