"use client";

import { useCallback, useEffect, useState } from "react";
import { Alert, Button, Modal, Spinner, TextInput } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import { useToast } from "@/components/toast";

const units = ["UNIT", "ML", "LITER", "GRAM", "KG", "METER", "PAIR", "BOX"];

type Product = { id:string; name:string; sku?:string|null; brand?:string|null; unit:string; status:string; quantity:number|string; minimumQuantity:number|string; targetQuantity:number|string };
type Warehouse = { id:string; name:string; type:string; branchId?:string|null };
type Overview = { metrics:{ totalProducts:number; criticalProducts:number; inventoryValue:number|string }; critical:Product[]; warehouses:Warehouse[]; purchaseRequests:any[] };

function Icon({name}:{name:"box"|"alert"|"search"|"plus"|"arrow"|"warehouse"}) {
 const c={width:19,height:19,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.7,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};
 if(name==="box")return <svg {...c}><path d="m4 7 8-4 8 4-8 4-8-4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/></svg>;
 if(name==="alert")return <svg {...c}><path d="M12 4 3.5 19h17L12 4Z"/><path d="M12 9v5M12 17h.01"/></svg>;
 if(name==="search")return <svg {...c}><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/></svg>;
 if(name==="plus")return <svg {...c}><path d="M12 5v14M5 12h14"/></svg>;
 if(name==="warehouse")return <svg {...c}><path d="m3 10 9-6 9 6v9H3v-9Z"/><path d="M7 19v-6h10v6M9 10h.01M15 10h.01"/></svg>;
 return <svg {...c}><path d="M5 12h13M14 7l5 5-5 5"/></svg>;
}

export default function InventoryPage(){
 const {showToast}=useToast();
 const [data,setData]=useState<Overview|null>(null); const [products,setProducts]=useState<Product[]>([]); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false);
 const [form,setForm]=useState({name:"",sku:"",brand:"",unit:"UNIT",minimumQuantity:"",targetQuantity:"",initialQuantity:""});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [o,p]=await Promise.all([api<Overview>("/inventory/overview"),api<Product[]>(`/inventory/products${search.trim()?`?search=${encodeURIComponent(search.trim())}`:""}`)]);setData(o);setProducts(p)}catch(e){setError(e instanceof ApiError?e.message:"Envanter yüklenemedi.")}finally{setLoading(false)}},[search]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),160);return()=>window.clearTimeout(t)},[load]);
 async function createProduct(e:React.FormEvent){e.preventDefault();if(!form.name.trim())return;setSaving(true);try{await api("/inventory/products",{method:"POST",body:{...form,minimumQuantity:Number(form.minimumQuantity||0),targetQuantity:Number(form.targetQuantity||0),initialQuantity:Number(form.initialQuantity||0)}});setOpen(false);setForm({name:"",sku:"",brand:"",unit:"UNIT",minimumQuantity:"",targetQuantity:"",initialQuantity:""});showToast("Ürün envantere eklendi.");await load()}catch(e){setError(e instanceof ApiError?e.message:"Ürün oluşturulamadı.")}finally{setSaving(false)}}
 if(loading&&!data)return <div className="mx-auto max-w-[1440px] py-16"><Spinner label="Envanter hazırlanıyor..."/></div>;
 return <div className="mx-auto max-w-[1440px] space-y-6 pb-10">
  <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.14em] text-[#9a96a2]">ENVANTER</p><h1 className="text-[30px] font-semibold tracking-[-.035em] text-[#20202a]">Stok & Envanter</h1><p className="mt-1 text-[14px] text-[#85828e]">Ürünleri, şube stoklarını ve satın alma ihtiyaçlarını tek yerden yönetin.</p></div><Button onClick={()=>setOpen(true)}><span className="mr-2 inline-flex"><Icon name="plus"/></span>Yeni ürün</Button></header>
  {error?<Alert onClose={()=>setError("")}>{error}</Alert>:null}
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
   <Metric icon="box" label="Toplam ürün" value={data?.metrics.totalProducts??0} hint="aktif ürün"/><Metric icon="alert" label="Kritik stok" value={data?.metrics.criticalProducts??0} hint="müdahale gerekli" tone="orange"/><Metric icon="warehouse" label="Lokasyon" value={data?.warehouses.length??0} hint="ana depo + şubeler"/><Metric icon="box" label="Envanter değeri" value={money(Number(data?.metrics.inventoryValue??0))} hint="mevcut stok maliyeti" tone="purple"/>
  </div>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
   <section className="overflow-hidden rounded-[24px] border border-[var(--line)] bg-white"><div className="flex items-center gap-3 border-b border-[var(--line)] p-4"><div className="relative min-w-0 flex-1"><span className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-[#9995a0]"><Icon name="search"/></span><TextInput className="h-11 pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ürün, SKU ara..."/></div><span className="hidden text-[12px] text-[#9995a0] sm:block">{products.length} ürün</span></div>
    <div className="divide-y divide-[#f0eef2]">{products.map(p=><div key={p.id} className="flex items-center gap-4 px-5 py-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[12px] bg-[#f5f3f8] text-[#777382]"><Icon name="box"/></div><div className="min-w-0 flex-1"><div className="truncate text-[13px] font-semibold text-[#292833]">{p.name}</div><div className="mt-1 truncate text-[11px] text-[#9995a0]">{p.brand||"Markasız"}{p.sku?` · ${p.sku}`:""}</div></div><div className="hidden text-right sm:block"><div className="text-[13px] font-semibold text-[#292833]">{fmt(p.quantity)} {unitLabel(p.unit)}</div><div className="mt-1 text-[10px] text-[#9995a0]">min. {fmt(p.minimumQuantity)}</div></div><Status quantity={Number(p.quantity)} min={Number(p.minimumQuantity)}/><button className="text-[#9b97a2]" title="Detay"><Icon name="arrow"/></button></div>)}{!products.length?<div className="px-6 py-16 text-center text-[13px] text-[#9995a0]">Ürün bulunamadı.</div>:null}</div>
   </section>
   <aside className="space-y-6"><section className="overflow-hidden rounded-[24px] border border-[var(--line)] bg-white"><div className="flex items-center justify-between border-b border-[var(--line)] p-5"><div><h2 className="text-[16px] font-semibold text-[#292833]">Kritik stoklar</h2><p className="mt-1 text-[11px] text-[#9995a0]">Öncelikli müdahale gerekenler</p></div><span className="rounded-full bg-[#f7f2ed] px-2.5 py-1 text-[10px] font-semibold text-[#9a6747]">{data?.critical.length??0}</span></div><div className="divide-y divide-[#f0eef2]">{(data?.critical??[]).slice(0,6).map(p=><div key={p.id} className="px-5 py-4"><div className="flex items-center justify-between gap-3"><span className="min-w-0 truncate text-[12px] font-medium text-[#34323d]">{p.name}</span><span className="shrink-0 text-[12px] font-semibold text-[#a26442]">{fmt(p.quantity)} {unitLabel(p.unit)}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#efeeed]"><span className="block h-full rounded-full bg-[#c99170]" style={{width:`${Math.min(100,Number(p.minimumQuantity)>0?Number(p.quantity)/Number(p.minimumQuantity)*100:0)}%`}}/></div></div>)}{!(data?.critical?.length)?<div className="px-5 py-10 text-center text-[12px] text-[#9995a0]">Kritik stok yok. Harika.</div>:null}</div></section>
    <section className="overflow-hidden rounded-[24px] border border-[var(--line)] bg-white"><div className="border-b border-[var(--line)] p-5"><h2 className="text-[16px] font-semibold text-[#292833]">Lokasyonlar</h2><p className="mt-1 text-[11px] text-[#9995a0]">Ana depo ve şube stok alanları</p></div><div className="divide-y divide-[#f0eef2]">{(data?.warehouses??[]).map(w=><div key={w.id} className="flex items-center gap-3 px-5 py-3.5"><span className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-[#f5f3f8] text-[#777382]"><Icon name="warehouse"/></span><span className="min-w-0 flex-1 truncate text-[12px] font-medium text-[#34323d]">{w.name}</span><span className="text-[10px] text-[#aaa6b0]">{w.type==='MAIN_DEPOT'?"Ana depo":"Şube"}</span></div>)}</div></section>
   </aside>
  </div>
  <Modal open={open} onClose={()=>setOpen(false)} title="Yeni Ürün"><form onSubmit={createProduct} className="space-y-5"><p className="text-[12px] text-[#898591]">Envantere eklenecek ürünün temel bilgilerini ve stok eşiklerini tanımlayın.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Ürün adı"><TextInput value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Örn. Keratin Maskesi" required/></Field><Field label="SKU / Barkod"><TextInput value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} placeholder="KER-001"/></Field><Field label="Marka"><TextInput value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} placeholder="Marka"/></Field><Field label="Ölçü birimi"><select className="control h-11 w-full" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}>{units.map(u=><option key={u}>{u}</option>)}</select></Field><Field label="Minimum stok"><TextInput type="number" min="0" step="0.001" value={form.minimumQuantity} onChange={e=>setForm({...form,minimumQuantity:e.target.value})} placeholder="10"/></Field><Field label="İdeal stok"><TextInput type="number" min="0" step="0.001" value={form.targetQuantity} onChange={e=>setForm({...form,targetQuantity:e.target.value})} placeholder="30"/></Field><Field label="Başlangıç stoğu"><TextInput type="number" min="0" step="0.001" value={form.initialQuantity} onChange={e=>setForm({...form,initialQuantity:e.target.value})} placeholder="0"/></Field></div><div className="flex justify-end gap-2 border-t border-[var(--line)] pt-4"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Vazgeç</Button><Button type="submit" disabled={saving}>{saving?"Kaydediliyor...":"Ürünü oluştur"}</Button></div></form></Modal>
 </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[11px] font-medium text-[#6f6b76]">{label}</span>{children}</label>}
function Metric({icon,label,value,hint,tone}:{icon:any;label:string;value:any;hint:string;tone?:string}){return <div className="rounded-[20px] border border-[var(--line)] bg-white p-5"><div className={`mb-4 flex h-9 w-9 items-center justify-center rounded-[11px] ${tone==='orange'?"bg-[#f8f1eb] text-[#9d6b4c]":tone==='purple'?"bg-[#f1edfb] text-[#7657b5]":"bg-[#f4f3f6] text-[#777382]"}`}><Icon name={icon}/></div><div className="text-[11px] text-[#94909b]">{label}</div><div className="mt-1 text-[23px] font-semibold tracking-[-.025em] text-[#26252e]">{value}</div><div className="mt-1 text-[10px] text-[#aaa6b0]">{hint}</div></div>}
function Status({quantity,min}:{quantity:number;min:number}){const critical=min>0&&quantity<=min;return <span className={`hidden rounded-full px-2.5 py-1 text-[9px] font-semibold sm:inline-flex ${critical?"bg-[#fbf0ea] text-[#9a6244]":"bg-[#f2f5f2] text-[#6f8871]"}`}>{critical?"Kritik":"Normal"}</span>}
function fmt(v:any){return Number(v||0).toLocaleString("tr-TR",{maximumFractionDigits:3})} function money(v:number){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(v)} function unitLabel(v:string){return ({UNIT:"adet",ML:"ml",LITER:"lt",GRAM:"gr",KG:"kg",METER:"m",PAIR:"çift",BOX:"kutu"} as any)[v]||v}
