import { EnterpriseDataPage } from "@/components/enterprise-data-page";

export default function RewardsManagePage(){
  return <EnterpriseDataPage eyebrow="İnsan Kaynakları · Toplam Ödül" title="Ödül, Yan Hak ve Masraf İşlemleri" description="Ücret, yan hak, değişken kazanç, avans ve çalışan masrafı kayıtlarını yönetin." sections={[]} forms={[
    {title:"Ücret Kaydı Ekle",path:"/hr/rewards/employees/{staffId}/compensation",fields:[{name:"staffId",label:"Personel ID",required:true},{name:"baseSalary",label:"Temel Ücret",type:"number",required:true},{name:"variableTarget",label:"Değişken Hedef",type:"number",defaultValue:"0"},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"salaryType",label:"Ücret Türü",defaultValue:"GROSS"},{name:"payFrequency",label:"Ödeme Sıklığı",defaultValue:"MONTHLY"},{name:"effectiveFrom",label:"Başlangıç",type:"date",required:true},{name:"effectiveTo",label:"Bitiş",type:"date"},{name:"reason",label:"Neden",type:"textarea"}]},
    {title:"Yan Hak Ekle",path:"/hr/rewards/employees/{staffId}/benefits",fields:[{name:"staffId",label:"Personel ID",required:true},{name:"type",label:"Yan Hak Türü",required:true},{name:"name",label:"Yan Hak Adı",required:true},{name:"amount",label:"Tutar",type:"number"},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"employerCost",label:"İşveren Maliyeti",type:"number"},{name:"payrollTaxable",label:"Bordroda Vergilendirilecek",type:"boolean",defaultValue:"false"},{name:"effectiveFrom",label:"Başlangıç",type:"date",required:true},{name:"effectiveTo",label:"Bitiş",type:"date"}]},
    {title:"Prim / Bonus Ekle",path:"/hr/rewards/employees/{staffId}/variable-earnings",fields:[{name:"staffId",label:"Personel ID",required:true},{name:"type",label:"Kazanç Türü",type:"select",required:true,options:[{value:"COMMISSION",label:"Komisyon"},{value:"BONUS",label:"Bonus"},{value:"REWARD",label:"Ödül"}]},{name:"amount",label:"Tutar",type:"number",required:true},{name:"currency",label:"Para Birimi",defaultValue:"TRY"}]},
    {title:"Avans Talebi Oluştur",path:"/hr/rewards/employees/{staffId}/advances",fields:[{name:"staffId",label:"Personel ID",required:true},{name:"amount",label:"Tutar",type:"number",required:true},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"reason",label:"Neden",type:"textarea"}]},
    {title:"Çalışan Masrafı Gir",path:"/hr/rewards/employees/{staffId}/expenses",fields:[{name:"staffId",label:"Personel ID",required:true},{name:"category",label:"Masraf Kategorisi",required:true},{name:"amount",label:"Tutar",type:"number",required:true},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"expenseDate",label:"Masraf Tarihi",type:"date",required:true},{name:"receiptUrl",label:"Fiş / Belge URL"},{name:"costCenterId",label:"Masraf Merkezi ID"},{name:"description",label:"Açıklama",type:"textarea"}]}
  ]}/>;
}
