import { EnterpriseDataPage } from "@/components/enterprise-data-page";

export default function RewardsManagePage(){
  return <EnterpriseDataPage eyebrow="İnsan Kaynakları" title="Ücret, Yan Hak ve Masraf İşlemleri" description="Çalışan ücretlerini, yan haklarını, primlerini, avanslarını ve masraflarını anlaşılır şekilde yönetin." sections={[]} forms={[
    {title:"Ücret Kaydı Ekle",path:"/hr/rewards/employees/{staffId}/compensation",fields:[{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"],required:true},{name:"baseSalary",label:"Temel Ücret",type:"number",required:true},{name:"variableTarget",label:"Hedef Prim / Değişken Ücret",type:"number",defaultValue:"0"},{name:"currency",label:"Para Birimi",type:"select",defaultValue:"TRY",options:[{value:"TRY",label:"Türk Lirası"},{value:"USD",label:"ABD Doları"},{value:"EUR",label:"Euro"},{value:"GBP",label:"İngiliz Sterlini"}]},{name:"salaryType",label:"Ücret Gösterimi",type:"select",defaultValue:"GROSS",options:[{value:"GROSS",label:"Brüt"},{value:"NET",label:"Net"}]},{name:"payFrequency",label:"Ödeme Dönemi",type:"select",defaultValue:"MONTHLY",options:[{value:"MONTHLY",label:"Aylık"},{value:"WEEKLY",label:"Haftalık"},{value:"DAILY",label:"Günlük"},{value:"HOURLY",label:"Saatlik"}]},{name:"effectiveFrom",label:"Başlangıç",type:"date",required:true},{name:"effectiveTo",label:"Bitiş",type:"date"},{name:"reason",label:"Neden",type:"textarea"}]},
    {title:"Yan Hak Ekle",path:"/hr/rewards/employees/{staffId}/benefits",fields:[{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"],required:true},{name:"type",label:"Yan Hak Türü",type:"select",required:true,options:[{value:"MEAL",label:"Yemek"},{value:"TRANSPORT",label:"Ulaşım"},{value:"HEALTH",label:"Sağlık Sigortası"},{value:"PHONE",label:"Telefon"},{value:"BONUS",label:"Düzenli Prim"},{value:"OTHER",label:"Diğer"}]},{name:"name",label:"Yan Hak Adı",required:true},{name:"amount",label:"Tutar",type:"number"},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"employerCost",label:"İşveren Maliyeti",type:"number"},{name:"payrollTaxable",label:"Bordroda Vergilendirilecek",type:"boolean",defaultValue:"false"},{name:"effectiveFrom",label:"Başlangıç",type:"date",required:true},{name:"effectiveTo",label:"Bitiş",type:"date"}]},
    {title:"Prim veya Ek Kazanç Ekle",path:"/hr/rewards/employees/{staffId}/variable-earnings",fields:[{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"],required:true},{name:"type",label:"Ek Kazanç Türü",type:"select",required:true,options:[{value:"COMMISSION",label:"Komisyon"},{value:"BONUS",label:"Bonus"},{value:"REWARD",label:"Ödül"}]},{name:"amount",label:"Tutar",type:"number",required:true},{name:"currency",label:"Para Birimi",defaultValue:"TRY"}]},
    {title:"Avans Talebi Oluştur",path:"/hr/rewards/employees/{staffId}/advances",fields:[{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"],required:true},{name:"amount",label:"Tutar",type:"number",required:true},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"reason",label:"Neden",type:"textarea"}]},
    {title:"Çalışan Masrafı Gir",path:"/hr/rewards/employees/{staffId}/expenses",fields:[{name:"staffId",label:"Çalışan",type:"remote-select",optionsPath:"/hr/employees",optionLabelKeys:["firstName","lastName"],required:true},{name:"category",label:"Masraf Kategorisi",type:"select",required:true,options:[{value:"TRAVEL",label:"Seyahat"},{value:"MEAL",label:"Yemek"},{value:"TRANSPORT",label:"Ulaşım"},{value:"ACCOMMODATION",label:"Konaklama"},{value:"OFFICE",label:"Ofis / İş Gereci"},{value:"OTHER",label:"Diğer"}]},{name:"amount",label:"Tutar",type:"number",required:true},{name:"currency",label:"Para Birimi",defaultValue:"TRY"},{name:"expenseDate",label:"Masraf Tarihi",type:"date",required:true},{name:"receiptUrl",label:"Fiş veya Belge Bağlantısı"},{name:"costCenterId",label:"Masraf Merkezi"},{name:"description",label:"Açıklama",type:"textarea"}]}
  ]}/>;
}
