import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, PrismaService } from '@beauty-erp/database';
import { randomUUID } from 'node:crypto';
import { TenantContext } from '../../common/tenant/tenant-context';
import { PlatformAuditService } from '../platform-audit/platform-audit.service';

@Injectable()
export class ApprovalDelegationService {
  constructor(private readonly prisma:PrismaService,private readonly tenantContext:TenantContext,private readonly audit:PlatformAuditService){}
  list(){const c=this.tenantContext.getContext();return this.prisma.$queryRaw`
    SELECT d.*,du.email AS "delegatorEmail",eu.email AS "delegateEmail"
    FROM approval_delegations d JOIN users du ON du.id=d."delegatorUserId" JOIN users eu ON eu.id=d."delegateUserId"
    WHERE d."tenantId"=${c.tenantId} AND d."companyId"=${c.companyId} ORDER BY d."createdAt" DESC LIMIT 500`}
  async create(input:{delegatorUserId:string;delegateUserId:string;domain?:string|null;startsAt:string;endsAt:string;reason:string}){const c=this.tenantContext.getContext(),actor=await this.actor();if(input.delegatorUserId===input.delegateUserId)throw new BadRequestException('Delegator and delegate must be different');const startsAt=new Date(input.startsAt),endsAt=new Date(input.endsAt);if(Number.isNaN(startsAt.getTime())||Number.isNaN(endsAt.getTime())||endsAt<=startsAt)throw new BadRequestException('Invalid delegation period');if(endsAt.getTime()-startsAt.getTime()>90*24*60*60*1000)throw new BadRequestException('Delegation cannot exceed 90 days');const members=await this.prisma.membership.findMany({where:{tenantId:c.tenantId,companyId:c.companyId,status:'ACTIVE',userId:{in:[input.delegatorUserId,input.delegateUserId]}},select:{userId:true}});if(new Set(members.map(x=>x.userId)).size!==2)throw new BadRequestException('Both users must be active members of the company');const id=randomUUID();return this.prisma.$transaction(async tx=>{const dup=await tx.$queryRaw<Array<{id:string}>>`SELECT id FROM approval_delegations WHERE "tenantId"=${c.tenantId} AND "companyId"=${c.companyId} AND "delegatorUserId"=${input.delegatorUserId} AND "delegateUserId"=${input.delegateUserId} AND "revokedAt" IS NULL AND "startsAt"<${endsAt} AND "endsAt">${startsAt} AND domain IS NOT DISTINCT FROM ${input.domain?.trim()||null} LIMIT 1 FOR UPDATE`;if(dup.length)throw new BadRequestException('Overlapping approval delegation already exists');const rows=await tx.$queryRaw<any[]>`INSERT INTO approval_delegations(id,"tenantId","companyId","delegatorUserId","delegateUserId",domain,"startsAt","endsAt",reason,"createdByUserId","createdAt","updatedAt") VALUES(${id},${c.tenantId},${c.companyId},${input.delegatorUserId},${input.delegateUserId},${input.domain?.trim()||null},${startsAt},${endsAt},${input.reason.trim()},${actor},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING *`;await this.audit.record({actorUserId:actor,resource:'approval_delegations',action:'create',targetTenantId:c.tenantId,targetEntityType:'approval_delegation',targetEntityId:id,beforeState:null,afterState:{delegatorUserId:input.delegatorUserId,delegateUserId:input.delegateUserId,domain:input.domain??null,startsAt,endsAt,reason:input.reason.trim()},metadata:{companyId:c.companyId}},tx);return rows[0];},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
  async revoke(id:string){const c=this.tenantContext.getContext(),actor=await this.actor();return this.prisma.$transaction(async tx=>{const rows=await tx.$queryRaw<any[]>`SELECT * FROM approval_delegations WHERE id=${id} AND "tenantId"=${c.tenantId} AND "companyId"=${c.companyId} FOR UPDATE`;const d=rows[0];if(!d)throw new NotFoundException('Approval delegation not found');if(d.revokedAt)return d;const updated=await tx.$queryRaw<any[]>`UPDATE approval_delegations SET "revokedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id} RETURNING *`;await this.audit.record({actorUserId:actor,resource:'approval_delegations',action:'revoke',targetTenantId:c.tenantId,targetEntityType:'approval_delegation',targetEntityId:id,beforeState:{revokedAt:null},afterState:{revokedAt:updated[0].revokedAt},metadata:{companyId:c.companyId,delegatorUserId:d.delegatorUserId,delegateUserId:d.delegateUserId}},tx);return updated[0];},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
  private async actor(){const c=this.tenantContext.getContext();const m=await this.prisma.membership.findFirst({where:{id:c.membershipId,tenantId:c.tenantId,companyId:c.companyId,status:'ACTIVE'},select:{userId:true}});if(!m)throw new BadRequestException('Active membership is required');return m.userId;}
}
